### ISSUE TITLE
Can't log in on companies with '&' in name

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1004]

**Comment by einhverfr** [comment]
I think we have a more general encoding issue here.  I am wondering if we need a more general solution to it.

**Comment by einhverfr** [comment]
actually the problem is fairly simple.  Expect to have this fixed in 1.4.31

**Comment by einhverfr** [comment]
I have a fix for 1.4
For 1.5 I have the login issues fixed, but db creation is creating dbs named testing&amp;testing which is clearly wrong.....
