### ISSUE TITLE
default salesperson to logged in user

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1010]
Not sure if this has been resolved or not.  If it has not, it is a quick fix.

IIRC SQL-Ledger used to do this and so LSMB 1.0 used to so this may be technically a regression

https://sourceforge.net/p/ledger-smb/feature-requests/64/

**Comment by einhverfr** [comment]
On review, I don' think this could have ever worked the way i assumed it did.  Not a regression.

**Comment by ehuelsmann** [comment]
Quick test: this hasn't been done yet.

**Comment by ehuelsmann** [comment]
Actually, it has been done in 1.8.
