### ISSUE TITLE
1.4 regression: cash payments pay $0 by default

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1021]
After merging in the fixes for #961 , the default "To Pay" value for all invoices is no longer filled with the amount due for that invoice -- this field is blank.

Because these fields are hidden on vendors marked to pay "All" instead of "Some", when you go to print, you actually get $0 transactions printed instead of the balance due. (Fortunately when I went to post the batch it failed...).

**Comment by einhverfr** [comment]
To set expectations, this will be merged to my 1.4.20-fixes branch and and then merged to master and closed.  1.4.20-fixes will be merged to 1.4.20 immediately following the 1.4.19 release
