### ISSUE TITLE
budget variance reports should use accounting hierarchies

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1030]
title says it all

**Comment by ehuelsmann** [comment]
@einhverfr where can I find these variance reports? I have "Add" and "Search", but no "Reports" in the budgets menu. Never had. Clicking on "Search" and opening one of the resulting budgets simply shows the data entered through the "Add" menu.

**Comment by ehuelsmann** [comment]
There are no budget variance reports. Closing.
