### ISSUE TITLE
Add contact info to search results

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1064]
This was originally left out of 1.4 and should be added back.  See https://sourceforge.net/p/ledger-smb/feature-requests/279/

**Comment by einhverfr** [comment]
While this is a regression vs 1.3, it hasn't generated a lot of complaints, and given our changes in directory structure would be easiest to mark against 1.5

**Comment by ehuelsmann** [comment]
@einhverfr the link to sourceforge is now dead. could you include some screenshots of what you're referring to, to help me get up to speed and form an idea what I'm aiming for?

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
