### ISSUE TITLE
Remove unused top-level files

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1067]
* Reconciliation.pl
* common.pl
* custom.pl

Maybe:
* index.html

**Comment by einhverfr** [comment]
common.pl might still be used by old code.  Custom.pl is pretty rarely used and arguably there are better ways of addressing it in the current framework.  Reconciliation.pl should go.  And I would agree we should remove index.html

**Comment by ehuelsmann** [comment]
Researching your remark of possible use of 'common.pl', I'm finding that Form.pm has a "redirect" method which is used everywhere except:

* LedgerSMB/Form.pm:678 (which uses the function lsmb_legacy::redirect() from within its own redirect)
* bin/am.pl:1480 (which uses the - probably non-existent - main::redirect() )

My proposal would be to have Form->redirect() consume lsmb_legacy::redirect() and replace the call in am.pl by a call to $form->redirect(). The fact that a form has been set up at that point in am.pl is indicated by the fact that 2 lines up, the $form object is being used already.
