### ISSUE TITLE
1.4.19: Error when saving template transaction

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1071]
When trying to save an AP Transaction, I get the following error:

Error!

'42703:ERROR: column "source" of relation "journal_entry" does not exist
LINE 1: INSERT INTO journal_entry (source, description, entry_type, ...
^
QUERY: INSERT INTO journal_entry (source, description, entry_type, transaction_date,
approved, is_template)
VALUES (in_source, in_description, in_entry_type, in_transaction_date,
coalesce(in_approved, false),
coalesce(in_is_template, false))
CONTEXT: PL/pgSQL function journal__add(text,text,integer,date,boolean,boolean) line 4 at SQL statement at LedgerSMB.pm line 770.
'

dbversion: 1.4.19

**Comment by ehuelsmann** [comment]
Other problems with template transactions:

- Missing from the menu
- When manually invoking the search URL: http://localhost:5000/transtemplate.pl?action=search --> error, missing file "filter.html" (searched for in UI/transtemplate)

**Comment by ehuelsmann** [comment]
The table "journal_entry" misses these columns:

 * source (text)
 * entry_type (integer)
 * transaction_date (date)

Or, at least, journal__add tries to insert into them.

**Comment by ehuelsmann** [comment]
The journal__add() function doesn't fill these columns:

* reference
* effective_start
* effective_end

Note: gl.pl::save_temp() sets up an object for saving a GL transaction and needs to be updated to pass *at least* the "reference" column, if that's the solution chosen.

[Shouldn't the "reference" column be required for *non* template transactions??]

**Comment by einhverfr** [comment]
Due to db changes needed making this dependent on the db replacement for sqitch in 1.5
