### ISSUE TITLE
Need better performance bulk payment widget for 1.6

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1077]
Our use of Dojo is likely to have made the bulk payment interface less scalable in 1.4 and the removal of various performance optimizations compounds this in 1.5

We need to have a high performance bulk payment widget  for 1.6 because otherwise some users may be stuck on 1.3.

**Comment by ehuelsmann** [comment]
Well, I'd like to stick to Dojo, but maybe it's in idea to work up a test data set and specify some metrics that help clarify this ticket? Then it's easier to determine if a certain solution could be considered sufficient or not.

**Comment by ehuelsmann** [comment]
Wondering if somethnig that "needs-design" should hold the "blocking" class. Sounds conflicting.

**Comment by einhverfr** [comment]
Well either that or we need to stop saying we can easily handle cases where our clients pay thousands a week.  Anyway I think we have a design down:

Possibly as an external tool at first:
1.  Use web sockets
2.  Stream json messages of payments in set
3.  Display/render/manipulate
4.  Save batch over web socket.

**Comment by einhverfr** [comment]
Just to be clear, I don;t think we can stop supporting 1.3 until we have this.

**Comment by sbts** [comment]
I see no reason why dojo should prevent good performance on bulk payments.
If anything it should facilitate improved performance.

I second ehuelsmann's request for some metrics and test case

**Comment by ehuelsmann** [comment]
Marking 'waiting for user' because there's an old (but still outstanding) request for more data (test data and bottleneck identification).

**Comment by ehuelsmann** [comment]
My feeling is that not enough of this has been substantiated over the last 2.5 years to justify the `blocking` status. I'm going to remove that status; I'm hoping we'll have test data available representative for the assumed problematic use-case as described in the initial description.

**Comment by ehuelsmann** [comment]
Without specs for what we need to support (and with what timings), I'm afraid there's little we can do here.
