### ISSUE TITLE
Financial reports without input report date + time (instead of just dates)

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1089]
See the header of this income statement, run without any input at all (just click Continue immediately).

![capture](https://cloud.githubusercontent.com/assets/2326559/11454198/b2045c8c-9624-11e5-9f9f-cc24e1a2fe7b.PNG)

**Comment by einhverfr** [comment]
This looks like a more general issue with PGDate.

**Comment by einhverfr** [comment]
Worse, if you do enter dates, you get a report of the full range but no dates listed on the header.
