### ISSUE TITLE
APPLICATION ERROR in t/40-dbsetup.t, but tests not failing

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1100]
This is the log from Travis CI:

t/40-dbsetup.t .............. 2/11 Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 349.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 357, <LOADORDER> line 48.

sql/modules/Fixes.sql: No such file or directory

APPLICATION ERROR

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 364.

Use of uninitialized value in concatenation (.) or string at /home/travis/build/ehuelsmann/LedgerSMB/build_dir/blib/lib/LedgerSMB/Database.pm line 357.

t/40-dbsetup.t .............. 3/11 sql/modules/Fixes.sql: No such file or directory

APPLICATION ERROR

t/40-dbsetup.t .............. ok

**Comment by einhverfr** [comment]
because I moved it.  Will fix for beta 3.

the t/40 tests are not really intended to catch things like this though arguably they should.  There are problems in intercepting the errors.  The t/43-dbtests are intended to catch such.
