### ISSUE TITLE
Languages sorted by code rather than description

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1118]
Meaning people need to search for "Dutch" under the "n" (nl_NL)... Which is... Not so intuitive.

**Comment by einhverfr** [comment]
so we probably need to change the locale dropdowns to have full descriptions too.  Wondering if those need to be localized

**Comment by ehuelsmann** [comment]
I can't find where we have incorrectly sorted locale names. I could find where the incorrectly sorted language names come from.

Changing this issue to be only about incorrectly sorted language names -- translated language names can be an enhancement for a later date.
