### ISSUE TITLE
Important application styling information in user stylesheet

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1130]
E.g. dynatable's amount right alignment should be in application styling.

**Comment by einhverfr** [comment]
potentially breaking customizations, needs to go through full rc process

**Comment by ehuelsmann** [comment]
@ylavoie did you address this issue with your case refactoring last month?

**Comment by ehuelsmann** [comment]
with the de-duplication of CSS, I'm finding this issue isn't fully addressed, but sufficiently so.
