### ISSUE TITLE
LedgerSMB::Scripts::setup.pm untranslated strings

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1148]
While checking the results from the new translated-strings scanner, this error appears:

./LedgerSMB/Scripts/setup.pm:178: text() called with non string first argument; resetting scan (consider using maketext() directly!)

However, the strings referenced at that line ($dispatch_entry->{$field}), isn't marked for translation (it's an entry from @login_actions_dispatch_table defined on LedgerSMB/Scripts/setup.pm:93.

**Comment by einhverfr** [comment]
This is trivial to fix actually.  Will fix it now, for rc1

**Comment by einhverfr** [comment]
In the process I am removing pre-1.2 support from the dispatch table.

**Comment by einhverfr** [comment]
there's also a bug here.
translating next_action is quite definitely unsafe.

**Comment by ehuelsmann** [comment]
You mean 1.0 and 1.1? Or 1.2 as well?

**Comment by einhverfr** [comment]
sorry, I mean 1.1.x and before.  Sorry for that.

**Comment by einhverfr** [comment]
Also removed 1.3 betas from the dispatch table too.
1.2 and 1.3 still show up correctly.
