### ISSUE TITLE
1.4.21-dev on lsmb demo server / 1.4.13.1 -- cant upload html templates

### ISSUE THREAD

**Issue by amr-gh** [ledgersmb/LedgerSMB#1179]
in lsmb 1.4.13.1
System -> HTML Templates
1. choose language -> click display
2. browse for file (with correct file name) and upload. 
3. again choose language -> click display
Problem: File not uploaded to the proper location. template available under (for example) sales_quotation.html(NO LANGUAGE) Only one template can be uploaded

in lsmb 1.4.21-dev on lsmb demo server
Menu System ->HTML Templates does not exist

**Comment by einhverfr** [comment]
Fixing by adding another account dropdown by the upload widget.

**Comment by einhverfr** [comment]
fixed in 1.4, pull imminent in master
