### ISSUE TITLE
Feature idea: Less default values

### ISSUE THREAD

**Issue by mikl** [ledgersmb/LedgerSMB#1185]
A common source of mistakes for me, while working with LedgerSMB, is default values.
- Lots of drop downs for account selection default to the first item in the list, which (at least in my case) is almost never the right option.
- Some date fields default to current date, which is also almost never the right value for me.

When filling out these big forms, I often miss a field somewhere, and as things works currently, missing a field will cause LedgerSMB to use the default value, leading to having the wrong date, or the wrong account on the saved data, and once posted, there's no way to undo mistakes.

Ideally, fields that have not have a value set in them (and are required values) should give the user validation errors, instead of assuming a default value.

**Comment by ehuelsmann** [comment]
I'm wondering what to do with this request. For some, the default values are a nuisance, for others a major data-entry boost.

@ylavoie , @freelock any opinions on which way to go on this issue?

**Comment by rakool** [comment]
I agree with @ehuelsmann 's assessment; and that assessment implies value in having these selection defaults as user reference options per screen or as multiple named saved searches per user. 

But that is not Mikl's plaint.  Having the default be the first of an alphabetized list seems of negative utility if  `don't care` is a common choice.   A date defaulting  to `today` is probably more easily assessed for utility.

The most important point raised is the being 'locked in' to a search; in many applications useless defaults force the user to correct them and thereby prevent the silent default `all` which could be worse.

**Comment by ehuelsmann** [comment]
In c10e6fa5cc3678c53398d77aaf92ddf698280de2, code was added to present an empty value on all optional input values.
