### ISSUE TITLE
Translation of front page login.pl and setup.pl pages

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1187]
From http://archive.ledgersmb.org/ledger-smb-devel/msg06108.html :

```
At the moment I'm evaluating our translation experience and one thing I'm finding
is that we've marked all strings for translation in setup.pl and dependent code
(notably Upgrade_Tests.pm).

However, there's no possibility to select another language than the default language
in setup.pl, unless we start parsing the HTTP Accept-Language heading. [The same
could be said for the front-page -- login.pl.]

What's the next step? Do we remove the translations from the lexicon, or do we parse
the Accept-Language header and fall back to that when there's no user detected?
```

In IRC (irc://chat.freenode.net/ledgersmb), we went over the various options here, leading to the creation of an issue to record the outcome in order to help anyone picking up this task.

We came to the conclusion we want the language to be determined in this order (first to last):
1. Take the language value from a query string "lang" parameter
2. Use the user's configured language preference when logged in _and_ the user saved a language pref
3. Use a LedgerSMB server-wide configured language, if one is configured (default: no config)
4. Use the request's "Accept-Language" header, if present
5. Fall back to the built-in language ('en')

**Comment by einhverfr** [comment]
I think item 3 is aready supported btw.  However, I am not really sure how #2 would work.  A cookie?

**Comment by ehuelsmann** [comment]
As a system wide default can be configured in LedgerSMB.conf, I don't think  there is anything of impact to be achieved here...
