### ISSUE TITLE
Translate language and country names

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1189]
Currently language names are shown in English. We should use http://search.cpan.org/~dmuey/Locales-0.33/ to look up the language and country (territory??) names in the language we're using for the current user.

As it stands, we're not translating those at all

**Comment by einhverfr** [comment]
major because of added dependency

**Comment by ehuelsmann** [comment]
Note that https://metacpan.org/release/Bundle-Locale-CLDR-World seems more maintained than Locales-*

**Comment by ehuelsmann** [comment]
@ylavoie didn't you achieve this with your recent CLDR changes?

**Comment by ehuelsmann** [comment]
@ylavoie ping. Didn't you realise this?

**Comment by ylavoie** [comment]
Fixed by #4880.
