### ISSUE TITLE
Default length of Project Dropdown too short or missing

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1195]
Looking at this link on the demo for 1.4.22
https://demo.cloud.efficito.com/erp/1.4/login.pl?action=login&company=demo14
It can be seen that the "Project" Dropdown box is defaulting to auto width which is aesthetically unpleasing.
We should have a minimum width set for all controls.

![screenshot from 2016-01-04 05 52 21](https://cloud.githubusercontent.com/assets/11002795/12081006/cf342158-b2a7-11e5-8a4d-93e5bbcb248a.png)

**Comment by ehuelsmann** [comment]
*all* dropdowns are missing width declaration...

**Comment by einhverfr** [comment]
how would we set the width without knowing the contents?

**Comment by ehuelsmann** [comment]
Hmm. but once the admin created the projects, the contents is known, right?

OTOH, I'm also feeling for a simple "min-width" CSS declaration...

**Comment by ehuelsmann** [comment]
there are 2 possible solutions here: tag-specific `style` attributes for which we generate the content dynamically. I'm not sure that works really well with i18n though. The other is to dynamically select a class based on the maximum length of the content which is available from the user-defined style sheet.

**Comment by sbts** [comment]
While I agree that setting the width based on content length is preferable and our end goal.
In the immediate sense ( and it can be retained as a default for when there is no data yet) all fields should have a rational min-width defined. 
The minimum should be something that fits with the purpose of the field, and visual layout intent.

**Comment by ehuelsmann** [comment]
> The minimum should be something that fits with the purpose of the field, and visual layout intent.

If I may ask, then why do you pick this detail? There's *a lot* of layout work to be done. Almost all of the filter pages are completely unstyled or if they are, still look crap. Why then pick on the drop-down?
