### ISSUE TITLE
Add 'selected item' indication to the main menu

### ISSUE THREAD

**Issue by pbolger** [ledgersmb/LedgerSMB#1196]
Normally this would be done by adding a class to the list item in the menu on page load.
Suggestion by ehuelsmann: 
"make use of dojo's publish/subscribe model and allow the menu items to subscribe to page loading events with names"

**Comment by einhverfr** [comment]
major due to testing/build requirements

**Comment by einhverfr** [comment]
This could be done in 1.5 using a class.  For later versions the pubsub model is probably better but don't want to break things in a stable version.

**Comment by ehuelsmann** [comment]
In 1.6, we switched to a Dojo Tree widget which has exactly this property. Closing as dealt with in 1.6.
