### ISSUE TITLE
setup.pl needs an overhaul to improve user experience

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1198]
There are a number of user experience issues with the current implementation of setup.pl

The first one is we need some help information on the login screen. at the moment it is expected that users just know that the Database field will either 
    \* create a new db if the text is not a valid db name
    \* allow changes to and/or backup of an existing db if the text is a valid  db name
~~There is another ticket #1197 dealing with the hardcoded default 'postgres' for the login name.~~ (this is solved)

Really the Database field is probably not needed here these days.
Instead
    \* simple login screen
    \* once logged in present a list or dropdown list of available DB's
    \* make the list filterable (dojo can filter select elements)
    \* add a button "Create New Company Database"
    \* add text that makes it clear that the company name is the database name
    ~~\* add a system level (ledgersmb.conf) blacklist regex that hides db's from the list.
        this would be used to hide things like postgres, template0, template1~~ (a hard coded list exists now)
    ~~\* add a configurable (in databse) blacklist regex that hides db's from the list.
        this would allow site specific hiding~~ (site specific hiding works through LedgerSMB.conf)

Once you have opened a config page for a specific DB there are a couple of other issues.
    \* If the db is not a recognised ledgersmb db the cancel button should not be labeled "Yes"
        but either "cancel" or "back".
    \* The backup buttons should not be active, or not visible at all.
    \* when the cancel or back button is clicked it should return to the list, rather than the login screen

**Comment by sbts** [comment]
we should also return result confirmation dialogs for otherwise silent actions.
A good example here is the "password change" button for changing a user password.
When clicked it silently completes with the only outward change to the UI being any entered password is cleared

**Comment by ylavoie** [comment]
Switch order of 'Date of birth' and 'Country' on user creation page so that date format can be localized.

**Comment by einhverfr** [comment]
I think a couple key improvements are possible here:

1.  App::LedgerSMB::Admin::Web should be able to handle the web-service backend calls here, but we need to add user handling etc to that.
2.  Supply a dojo-based admin widget here.  The above merely does a form and jquery interface for html (functional but minimalistic).
3.  After logging in, the screen should pop up either a db creation wizard (if no db) or a db console with functions with no confirmation portion, just a title, list of actions, and db statistics.

**Comment by ehuelsmann** [comment]
First we need to define what setup.pl means to be/contribute.

**Comment by ehuelsmann** [comment]
Consolidated into #3746
