### ISSUE TITLE
Top of main menu crowded

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1203]
The area under the logo, and above the menu contains some status info.
    \* add some white space above and below.
    \* center the text
    \* remove the bold attribute
    \* consider adding a dynamically updated session count after the username
      eg: Logged in as user (6)
where the session count is the number of currently logged in sessions for that user.
It would be expected that a session would include all windows open in a single browser
so 10 open tabs or windows would count as 1 session.
A login from 2 different browsers would be 2 sessions (on the same or different machines)

**Comment by ehuelsmann** [comment]
What about this:

![screenshot from 2016-05-25 10 28 06](https://cloud.githubusercontent.com/assets/2326559/15533153/9890f686-2263-11e6-8333-fe15004a45a8.png)

?

**Comment by ehuelsmann** [comment]
Storing the HTML (with embedded CSS) required to do that here for a moment:

<div style="text-align: center"><a target="_blank" href="http://ledgersmb.org/">
		<img class="cornderlogo" src="images/ledgersmb_small.png" alt="LedgerSMB" height="50" width="100" border="1">
  </a><br>
<div id="version_info">1.4.26</div></div>
<div style="text-align: center; margin-top: 1em; margin-bottom: 1em;">
  <span id="login_info">ehuelsmann</span> / 
  <span id="company_info">efficito</span>
</div>

**Comment by sbts** [comment]
As discussed on IRC the proposed change looks good.
However the session count should be moved to a separate issue for future implementaion

**Comment by ehuelsmann** [comment]
This has been resolved when we replaced the menu for 1.6.
