### ISSUE TITLE
Income statement period dropdowns throwing error when Year is set

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1210]
Hi,

Testing 1.5-beta3, and finding a few things not working.

Reports -> Income Statement. Set a period for the 1st comparison to "January 2015", "Year" and click Continue.

Get the following error:

Can't locate object method "new" via package "2015-01-01T00:00:00" (perhaps you forgot to load "2015-01-01T00:00:00"?) at /usr/local/lib/perl5/site_perl/5.22.1/PGObject/Type/DateTime.pm line 108.
PGObject::Type::DateTime::from_db(LedgerSMB::PGDate=HASH(0xb130178), "2015-01-01") called at LedgerSMB/Report/Dates.pm line 100
LedgerSMB::Report::Dates::_get_to_date(LedgerSMB::Report::PNL::Income_Statement=HASH(0xb12f868)) called at reader LedgerSMB::Report::PNL::to_date (defined at LedgerSMB/Report/Dates.pm line 35) line 8
LedgerSMB::Report::PNL::to_date(LedgerSMB::Report::PNL::Income_Statement=HASH(0xb12f868)) called at LedgerSMB/Report/Dates.pm line 116
LedgerSMB::Report::Dates::_set_lazy_dates(LedgerSMB::Report::PNL::Income_Statement=HASH(0xb12f868)) called at LedgerSMB/Report/Dates.pm line 129
Class::MOP::Class:::before(LedgerSMB::Report::PNL::Income_Statement=HASH(0xb12f868)) called at /usr/lib/x86_64-linux-gnu/perl5/5.20/Class/MOP/Method/Wrapped.pm line 41
Class::MOP::Method::Wrapped::__ANON__(LedgerSMB::Report::PNL::Income_Statement=HASH(0xb12f868)) called at /usr/lib/x86_64-linux-gnu/perl5/5.20/Class/MOP/Method/Wrapped.pm line 86
LedgerSMB::Report::PNL::run_report(LedgerSMB::Report::PNL::Income_Statement=HASH(0xb12f868)) called at LedgerSMB/Scripts/pnl.pm line 53
LedgerSMB::Scripts::pnl::generate_income_statement(LedgerSMB=HASH(0xaf51f48)) called at bin/lsmb-request.pl line 102
LedgerSMB::PSGI::try {...} () called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try(CODE(0x9a359b0), Try::Tiny::Catch=REF(0xb05f558)) called at bin/lsmb-request.pl line 114
LedgerSMB::PSGI::call_script("pnl.pl", LedgerSMB=HASH(0xaf51f48), LedgerSMB::Locale::en=HASH(0xaf84878)) called at bin/lsmb-request.pl line 140
require bin/lsmb-request.pl called at LedgerSMB/PSGI.pm line 82
LedgerSMB::PSGI::try {...} () called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try(CODE(0x99d4530), Try::Tiny::Catch=REF(0xaf83458)) called at LedgerSMB/PSGI.pm line 90
LedgerSMB::PSGI::_run_new("pnl.pl") called at LedgerSMB/PSGI.pm line 46
LedgerSMB::PSGI::__ANON__() called at /usr/share/perl5/CGI/Emulate/PSGI.pm line 29
CGI::Emulate::PSGI::__ANON__(HASH(0xafad998)) called at /usr/share/perl5/Plack/Middleware/Static.pm line 18
Plack::Middleware::Static::call(Plack::Middleware::Static=HASH(0x9a34e28), HASH(0xafad998)) called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0xafad998)) called at /usr/share/perl5/Plack/Util.pm line 142
eval {...} called at /usr/share/perl5/Plack/Util.pm line 142
Plack::Util::run_app(CODE(0x9a34d80), HASH(0xafad998)) called at /usr/share/perl5/Starman/Server.pm line 281
Starman::Server::process_request(Starman::Server=HASH(0x1e50358), Net::Server::Proto::TCP=GLOB(0x9a353f8)) called at /usr/share/perl5/Net/Server.pm line 74
Net::Server::run_client_connection(Starman::Server=HASH(0x1e50358)) called at /usr/share/perl5/Net/Server/PreFork.pm line 229
eval {...} called at /usr/share/perl5/Net/Server/PreFork.pm line 229
Net::Server::PreFork::run_child(Starman::Server=HASH(0x1e50358)) called at /usr/share/perl5/Net/Server/PreFork.pm line 187
Net::Server::PreFork::run_n_children(Starman::Server=HASH(0x1e50358), 5) called at /usr/share/perl5/Net/Server/PreFork.pm line 111
Net::Server::PreFork::loop(Starman::Server=HASH(0x1e50358)) called at /usr/share/perl5/Net/Server.pm line 60
Net::Server::run(Starman::Server=HASH(0x1e50358), "port", ARRAY(0x222e398), "host", "*", "proto", "tcp", "serialize", "none", ...) called at /usr/share/perl5/Starman/Server.pm line 89
Starman::Server::run(Starman::Server=HASH(0x1e50358), CODE(0x1e502b0), HASH(0x1e50550)) called at /usr/share/perl5/Plack/Handler/Starman.pm line 18
Plack::Handler::Starman::run(Plack::Handler::Starman=HASH(0x1e50298), CODE(0x1e502b0)) called at /usr/share/perl5/Plack/Loader/Delayed.pm line 20
Plack::Loader::Delayed::run(Plack::Loader::Delayed=HASH(0x1d64420), Plack::Handler::Starman=HASH(0x1e50298)) called at /usr/share/perl5/Plack/Runner.pm line 277
Plack::Runner::run(Plack::Runner=HASH(0x1d6bff0)) called at /usr/bin/starman line 38

**Comment by freelock** [comment]
Note that I'm not getting an error if I select "Current" instead of "Year" or select dates in the date selectors.

**Comment by einhverfr** [comment]
Unable to reproduce.

**Comment by einhverfr** [comment]
Reproduced.  Year and month must be set.
