### ISSUE TITLE
Cannot load/edit templates

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1213]
When testing 1.5-beta3, cannot view or edit html or latex templates.

* System -> (HTML Templates|LaTeX Templates) -> (.*)

Text area is blank.

* Click Edit.

Error message: 

Template Not Found at LedgerSMB/Scripts/template.pm line 84.
LedgerSMB::Scripts::template::edit(LedgerSMB=HASH(0x83eb3a0)) called at bin/lsmb-request.pl line 102
LedgerSMB::PSGI::try {...} () called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try(CODE(0x8bf25d8), Try::Tiny::Catch=REF(0x92ceba8)) called at bin/lsmb-request.pl line 114
LedgerSMB::PSGI::call_script("template.pl", LedgerSMB=HASH(0x83eb3a0), LedgerSMB::Locale::en=HASH(0x92d7cf8)) called at bin/lsmb-request.pl line 140
require bin/lsmb-request.pl called at LedgerSMB/PSGI.pm line 82
LedgerSMB::PSGI::try {...} () called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try(CODE(0x7c720b8), Try::Tiny::Catch=REF(0x8555b10)) called at LedgerSMB/PSGI.pm line 90
LedgerSMB::PSGI::_run_new("template.pl") called at LedgerSMB/PSGI.pm line 46
LedgerSMB::PSGI::__ANON__() called at /usr/share/perl5/CGI/Emulate/PSGI.pm line 29
CGI::Emulate::PSGI::__ANON__(HASH(0x7cf6aa8)) called at /usr/share/perl5/Plack/Middleware/Static.pm line 18
Plack::Middleware::Static::call(Plack::Middleware::Static=HASH(0x7bfb850), HASH(0x7cf6aa8)) called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x7cf6aa8)) called at /usr/share/perl5/Plack/Util.pm line 142
eval {...} called at /usr/share/perl5/Plack/Util.pm line 142
Plack::Util::run_app(CODE(0x7bfb7d8), HASH(0x7cf6aa8)) called at /usr/share/perl5/Starman/Server.pm line 281
Starman::Server::process_request(Starman::Server=HASH(0x1d6b348), Net::Server::Proto::TCP=GLOB(0x52611e0)) called at /usr/share/perl5/Net/Server.pm line 74
Net::Server::run_client_connection(Starman::Server=HASH(0x1d6b348)) called at /usr/share/perl5/Net/Server/PreFork.pm line 229
eval {...} called at /usr/share/perl5/Net/Server/PreFork.pm line 229
Net::Server::PreFork::run_child(Starman::Server=HASH(0x1d6b348)) called at /usr/share/perl5/Net/Server/PreFork.pm line 187
Net::Server::PreFork::run_n_children(Starman::Server=HASH(0x1d6b348), 5) called at /usr/share/perl5/Net/Server/PreFork.pm line 111
Net::Server::PreFork::loop(Starman::Server=HASH(0x1d6b348)) called at /usr/share/perl5/Net/Server.pm line 60
Net::Server::run(Starman::Server=HASH(0x1d6b348), "port", ARRAY(0x2149838), "host", "*", "proto", "tcp", "serialize", "none", ...) called at /usr/share/perl5/Starman/Server.pm line 89
Starman::Server::run(Starman::Server=HASH(0x1d6b348), CODE(0x1d6b2a0), HASH(0x1d6b540)) called at /usr/share/perl5/Plack/Handler/Starman.pm line 18
Plack::Handler::Starman::run(Plack::Handler::Starman=HASH(0x1d6b288), CODE(0x1d6b2a0)) called at /usr/share/perl5/Plack/Loader/Delayed.pm line 20
Plack::Loader::Delayed::run(Plack::Loader::Delayed=HASH(0x1c7f410), Plack::Handler::Starman=HASH(0x1d6b288)) called at /usr/share/perl5/Plack/Runner.pm line 277
Plack::Runner::run(Plack::Runner=HASH(0x1c86fe0)) called at /usr/bin/starman line 38

**Comment by ehuelsmann** [comment]
Definitely a bug. My templates are all empty in the UI.

**Comment by einhverfr** [comment]
editing the templates now works. moving to rc1 since it should be fairly quick to finish the llast part.

**Comment by einhverfr** [comment]
The issue of loading templates is still there.  It looks like we are not able to pass in the expected template name with the current structure.  Will need to discuss the changes in the file upload area before going further.

**Comment by einhverfr** [comment]
(basically the previous hidden parameters are no longer passed.  I think this has to do with the switch to the file submission approach we are now using)

**Comment by einhverfr** [comment]
or maybe the hiddens are empty.... fixing that first.
