### ISSUE TITLE
User with "Contact All" permissions cannot create Vendor

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1219]
In 1.4.20 (can't verify on demo site b/c can't control perms)

User permissions bug:

If user has "contact all" permissions but no other contact or contact class related permissions are checked, and attempts to add new Vendor from AP screen (possibly other workflows as well), then "Vendor" will not show under "Class", and saving throws the following error:

<code>
*Attribute (entity_class) is required at constructor                                                                                        
LedgerSMB::Entity::Company::new (defined at LedgerSMB/Entity/Company.pm                                                                     
line 149) line 50                                                                                                                           
LedgerSMB::Entity::Company::new('LedgerSMB::Entity::Company',                                                                               
'_role_prefix', undef, '_roles', 'ARRAY(0x55960f8)', 'stylesheet',                                                                          
'ledgersmb.css', 'company', 'cedar_moon_2', 'form_id', 148, 'control_code',                                                                 
'A-00014', 'have_latex', 1, '_locale',                                                                                                      
'LedgerSMB::Locale::en=HASH(0x5672ce8)', 'legal_name', 'Hoodland                                                                            
Thriftway', 'login', 'ian', 'VERSION', 1.4.20, '_user',                                                                                     
'LedgerSMB::User=HASH(0x559bc90)', 'dbh', 'DBI::db=HASH(0x5595de0)',                                                                        
'session_id', 31, 'target_div', 'company_div', 'version', 1.4.20,                                                                           
'_request', 'CGI::Simple=HASH(0x52cf340)', '_script_handle',                                                                                
'LedgerSMB::Scripts::contact', 'name', 'Hoodland Thriftway', 'path',                                                                        
'bin/mozilla', 'warn_expire', 0, 'script', 'contact.pl                                                                                      
<http://contact.pl>', 'action', 'save_company', 'dbversion', 1.4.20,                                                                        
'country_id', 232, 'custom_db_fields', 'HASH(0x5596170)') called at                                                                         
LedgerSMB/Scripts/contact.pm <http://contact.pm> line 559                                                                                   
LedgerSMB::Scripts::contact::save_company('LedgerSMB=HASH(0x52c9620)')                                                                      
called at lsmb-request.pl <http://lsmb-request.pl> line 113                                                                                 
LedgerSMB::Handler::try {...} at /usr/local/share/perl/5.18.2/Try/Tiny.pm                                                                   
line 92 eval {...} at /usr/local/share/perl/5.18.2/Try/Tiny.pm line 83                                                                      
Try::Tiny::try('CODE(0x5673bf8)', 'Try::Tiny::Catch=REF(0x5596158)') called                                                                 
at lsmb-request.pl <http://lsmb-request.pl> line 125                                                                                        
LedgerSMB::Handler::call_script('contact.pl <http://contact.pl>',                                                                           
'LedgerSMB=HASH(0x52c9620)') called at lsmb-request.pl                                                                                      
<http://lsmb-request.pl> line 88 require lsmb-request.pl                                                                                    
<http://lsmb-request.pl> at /usr/share/ledgersmb/contact.pl                                                                                 
<http://contact.pl> line 8 *  
</code>

Workaround: select all contact and contact class-related permissions.

**Comment by einhverfr** [comment]
fixed for 1.4.31
