### ISSUE TITLE
Recurring transactions are broken

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1222]
1.4.22

Reproduce on demo:

* Recurring Transactions
* Click "Next Number" on one of them
* Type "10" times, and click "Schedule"
* Throws error:
Error!

'DELETE FROM recurring
WHERE id = ?
ERROR: update or delete on table "recurring" violates foreign key constraint "recurringprint_id_fkey" on table "recurringprint"
DETAIL: Key (id)=(11143) is still referenced from table "recurringprint". at bin/arap.pl line 708
' 

This is a different error than I was getting in 1.4.20 -- where saving would sometimes fail silently by simply erasing the schedule, other times fail silently and do nothing, and other times throw different errors than the above, depending on the date and number of repeats.

**Comment by ehuelsmann** [comment]
Started https://github.com/ehuelsmann/LedgerSMB/tree/1.4-recurrence-fixes

**Comment by ehuelsmann** [comment]
Fixed in https://github.com/ledgersmb/LedgerSMB/commit/3ea6f2abb1da71132eb60eb8dd4a604142ee3393 on master; Fixed in 1.4 using #1227
