### ISSUE TITLE
Broken Workflow while entering GIFI's

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1223]
When entering GIFI's in System GIFI the workflow is broken.

   * Click List gifi, get a list. [good]
   * Click Add GIFI
   * Complete the form, save, get a list. [good]
   * click add GIFI again to add the next one and nothing happens.
   * click List GIFI, then Add GIFI and you can fill out the form again

   * on click of add gifi URL is
     http://lsmb-dev.local:8080/login.pl?action=login&company=test#am.pl?login=dcg&action=add_gifi&module=am.pl&

   * after clicking save the URLl is 
    http://lsmb-dev.local:8080/login.pl?action=login&company=test#am.pl?login=dcg&action=add_gifi&module=am.pl&
    but a list is displayed.

   * after click of list gifi URL is
    http://lsmb-dev.local:8080/login.pl?action=login&company=test#reports.pl?login=dcg&action=list_gifi&module=reports.pl&

even resending the URL request by hitting enter in the address bar doesn't work
Reload Button does

This makes for a frustrating workflow

As a side note, perhaps we should have a button "Add New" on the list page, doing away with the main menu "Add GIFI" link

**Comment by ehuelsmann** [comment]
This isn't a workflow problem for GIFI alone: it's a problem that the 'window.location' value doesn't change when the same menu item is clicked twice in a row, even if the underlying page has changed e.g. due to clicking on a POST button.
