### ISSUE TITLE
HTML needs rationalising

### ISSUE THREAD

**Issue by pbolger** [ledgersmb/LedgerSMB#1225]
Many pages in the UI use tables for visual organisation and have deprecated tags such as 

`<th align="right" nowrap="">`

The appearance of the UI could be improved by reformatting the pages to html5, which would allow easy writing of themes for the application.

The first step in this would probably be to draw up a 'map' of the UI and to decide which elements should be grouped or nested to make the most semantic sense. A good example would be 'date ranges', which should be grouped wherever they occur.

**Comment by einhverfr** [comment]
Moving to 2.0.  We are in the process of entirely rewriting the UI and so this will be a many-stage process

**Comment by lkraav** [comment]
Three recommendations:

1. go with flexbox grid, structure HTML accordingly
2. use a wrapper inside grid units for maximum styling flexbility and consistency, avoids `box-model: border-box` kludge as a positive side-effect
3. use full page width container(s) with wrapper(s) inside

I'll post an example minimal general skeleton structure if needed.

**Comment by einhverfr** [comment]
would be appreciated.  Also we are happy to accept patches to this effect, just are not promising to fix it fully before 2.0

**Comment by ehuelsmann** [comment]
Is this a must or a nice to have in light of the fact that the UI will need to be redone anyway to switch to Vue/whatever
