### ISSUE TITLE
scripts in /utils missing documentation

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1228]
We need to document all scripts and other files in /tools and /utils

The suggestion is to follow roughly this....
    \* All executables must use a command line option --help that displays a Usage Summary followed by more detail if required.

```
* All executables must use a command line option --readme that displays a markdown formatted chunck containing script description an usage summary

* All executables must use a command line option --version that reports the script version in "scriptname v1.0.0" format
```

There is a mailing list discussion about this, I'll add a link later.

**Comment by ehuelsmann** [comment]
The scripts which are relevant for users have been moved to /bin. All scripts in /utils should be relevant strictly to developers (or are remnants which haven't been tested for a long time -- meaning I didn't feel comfortable moving them to /bin).
