### ISSUE TITLE
System configuration parameter 'return_accno' used but not declared/documented

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1229]
https://github.com/ledgersmb/LedgerSMB/blob/master/LedgerSMB/IS.pm#L892 references the configuration parameter $LedgerSMB::Sysconfig::return_accno. This parameter isn't defined in the configuration file "ledgersmb.conf", nor is it documented in Sysconfig.pm.

This parameter should probably be moved from 'ledgersmb.conf' to the database, because this is 100% company related configuration: it's the account used to post the (negative) income on which is caused by parts returns.

**Comment by einhverfr** [comment]
IIRC the one user of this feature eventually moved to other systems.

Returns are fairly hard and we need to think about them carefully.  My vote is to remove the use of this variable entirely.

**Comment by einhverfr** [comment]
Actually on further review, any use fo this code should be removed.  I am ok bumping that to 1.6

**Comment by einhverfr** [comment]
in my remove-chart branch, I remove this.
