### ISSUE TITLE
Add BDD/Selenium tests

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1251]
In IRC, we've been discussing options for adding browser-based tests, especially in 1.5 where so much is driven by Javascript.

Erik mentioned using Test::BDD::Cucumber for this, based on my enthusiasm for Behavior Driven Design tests based on what we're doing in Drupal. He was asking me to help get this framework in place.

After spending some time evaluating options, it looks like what is available for us to use in Perl is far less mature than what's available for Drupal.

TL;DR - check out Test::Selenium::Remote::Driver (part of Selenium::Remote::Driver). That's what we need in place first.

### Layers/components needed for BDD

The huge head start Drupal has with BDD is a bunch of driver/support modules that provide > 120 step definitions right out of the gate, along with all of the integration of the various layers of tools.

#### Test runner - pherkin, cucumber, behat

The top level is there for Perl -- at least at a basic level. Test::BDD::Cucumber provides "pherkin" to run tests, and supports integration with Test::Builder for running them in an automated way.

Cucumber is sort of the gold standard here. A Ruby tool, Cucumber seems to have the most robust functionality available, and supports running tests in several languages -- though I did not see exactly how you would hook this up to step definitions written in Perl, and the code templates it outputs are in Ruby (though I did find references online suggesting it could create step definition stubs in other languages, but I did not find exactly how to do this).

Behat is PHP.

Really, we could potentially use any of these tools -- if we're doing browser-side testing, the only reason we would need Perl is for the scaffolding around more easily inserting test data (e.g. by calling our own internal functions).

I actually tried setting up a simple feature to test the login.pl screen, and all 3 executed this file, with slightly different output:

* All three used the same color-coding to indicate incomplete steps
* Pherkin provided little data about the test run -- only the steps themselves.
* Cucumber and Behat provided more info about line numbers of sources, and output step definition templates (in Ruby or PHP).
* Behat provided the line number of the beginning of each scenario. Cucumber provided the line number of each individual step.
* Behat provides a "behat -dl" option that lists all available, pre-defined step definitions from all loaded sources (including your project's Feature Context, where you define your own).

#### Test framework

The next layer is where Perl seems to fall short.

Behat ships with a driver called "mink" which essentially drives the web browser, and supports a bunch of actual drivers -- Selenium, Goutte, Zombie, BrowserKit, Sahi, and a couple others. Mink handles starting up the browser, providing an abstraction layer across the various web drivers and integrating right into Behat.

It sounds like the main solution for Cucumber here is "Capybara", which mainly uses Selenium or PhantomJS (via "Poltergeist"), and provides a similar role as Mink.

For Perl, I didn't find anything on CPAN that looks quite equivalent -- it looks like much of this is done project-by-project. The closest thing I found is here: https://github.com/motemen/Wight, which connects to PhantomJS.

This layer provides most of the convenience for writing tests that drive the web browser, but not supporting Gherkin directly -- rather, Cucumber/Behat sits on top of this layer to drive a variety of actual browser engines.

#### Browser drivers

Here Perl has plenty to choose from, in the Mech:: namespace, and Selenium::Remote::Driver. At this level you're writing tests for a specific browser driver, no abstraction layer (other than Selenium itself offers some cross-browser testing, grid testing, etc).

Here the main decision might be headless or not -- Selenium drives fully functional browsers, and that makes it slow -- although it also makes it visible, something you can watch in action.

We've started using a new screen-comparison tool that uses PhantomJS, and it's so much faster -- tests that used to take 15 minutes to run now finish up in < 1 minute.

#### Step definitions

This is where Drupal is so far ahead. The DrupalExtension provides a bunch of step definitions already available for immediate use, for finding text on a page, filling out forms, finding text in particular rows of a table, generating user accounts, auto-logging a user in, creating content, users, taxonomy terms, and more.

You can start writing a feature file in Gherkin and immediately execute it with much of it passing, not needing any step definitions written.

### What do we really need?

BDD and Gherkin is very useful for defining the user experience, mainly as a communication tool that can be tested very quickly -- if you already have an extensive library of step definitions.

Since we don't have that library, there's quite a gap here in implementing all the pieces necessary to get this working.

And given that the main goal here is testing the functionality of the web side of our application, and most of us (at least for the moment) are capable of creating these tests in code (especially with some examples to start with) I think we should start out with tests written using the Test::Selenium::Remote::Driver module directly, and not attempt to engineer a whole BDD testing stack to drive those Selenium tests...

The alternatives:

* Build out Wight or equivalent, and get it integrated with Test::BDD::Cucumber to a sufficient point -- probably quite a bit of effort to do this

* Use Cucumber/Capybara/Ruby -- need to set up data manipulation using Ruby, or figure out how to get Cucumber to run Perl steps for when we want to enter data. Introduces test dependency on Ruby (though if we're considering Sass, we may end up with that anyway -- Compass seems to be the de-facto Sass compiler...)

* Use Behat, and write steps in PHP -- we would be able to use many of the pre-defined steps from DrupalExtension, because they are simply targeting the DOM in the browser. But now we have a PHP/Composer dependency, and any data population we want to do would need to go through a PHP binding (or escape to a shell...)

* Possibly try Cucumber.js -- I did not dig deep, but it does look like there are a ton of tools built on node.js for this kind of processing, and it seems like the other vast ecosystem used across languages -- Ruby and Node.js seem to be on par for processing tools for testing, CSS/Sass processing, etc. And the dojo build step does introduce a dependency on node.js for doing the Javascript build.

None of these seem like the right option for a Perl project... I've been scouring the web, and I'm finding very little on actually doing any tests driving browsers for testing using Perl. Just a handful of modules that don't really talk to each other, relying on a lot of code from the project (us) to actually get working...

**Comment by ehuelsmann** [comment]
@freelock thanks a bunch for all the work for this great review!

Sent a response to the development mailing list (archived here: http://archive.ledgersmb.org/ledger-smb-devel/msg06133.html). Used the mailing list because I'm thinking discussion gets sparked somewhat easier there than here.

**Comment by ehuelsmann** [comment]
Following up on the thread referred to above, I've been working on getting some basic infrastructure up and running for BDD testing. The result is a working setup with 2 scenarios on my "master-bdd-basics" branch.

**Comment by ehuelsmann** [comment]
On my master-bdd-basics branch, I have a significant amount of bed framework implemented. This work can be worked on when that branch is merged. However, in having issues with that branch: for some unknown (to me) reason the last step in the first real scenario fails on traffic, but not locally.

The first real scenario is the first one beyond the two initial ones mentioned above: it creates an initial user and a chomping administration (database) using the standard setup.pl l route

**Comment by ehuelsmann** [comment]
Just a minute ago, I merged #1271 (the bdd basics branch). Over the weeks/months/years, we'll need to collect much, *much* more tests. However, this issue should be considered "fixed" as the initial infrastructure is there now.

Thanks for your contribution and discussion!
