### ISSUE TITLE
Tax accounts with long descriptions don't fit layout on ECA screen

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1253]
When the user defines tax accounts with descriptions longer than 25 characters, the layout of the ECA screen looks weird: the account descriptions get wrapped, but there's lots of space left in the screen to show 1 description per line.

**Comment by einhverfr** [comment]
minor enough to bump to 1.4

**Comment by ehuelsmann** [comment]
This isn't a problem on the lastest master; so at the latest in 1.8, this is fixed (but it could be fixed in 1.7 or even earlier already -- haven't checked).
