### ISSUE TITLE
1.4.22: User needs "Contact Edit" permission to create new contacts (in addition to create permissions)

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1255]
The subject says it all. The error is the following:

PL/pgSQL function company__save(integer,text,integer,text,text,integer,text,integer,text,text) line 16 at SQL statement at LedgerSMB.pm line 577.
2016/01/10 14:40:34 - ERROR - LedgerSMB::dberror LedgerSMB.pm (761) -- Logging SQL State 42501, error 7, string ERROR:  permission denied for relation entity
CONTEXT:  SQL statement "UPDATE entity
        SET name = in_legal_name,
                entity_class = in_entity_class,
                control_code = t_control_code,
                country_id   = in_country_id
        WHERE id = in_entity_id"

**Comment by einhverfr** [comment]
Given our upsert logic, seems like a good idea to make create a role which also has update permission.  easy enough.
