### ISSUE TITLE
Using thousands separator as decimal separator multiplies amounts by 1000

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1260]
Proposed solution: we might just want to strip the thousands separator from input, or verify that the separator isn't used in appropriate positions and report a warning/error?

(Could Dojo numeric entry/ validating textboxes help here?)

**Comment by einhverfr** [comment]
what happens if one has a multiple of three in precision?

**Comment by einhverfr** [comment]
thousands separator is currently stripped out.  If that is sufficient, we can close this.
However you still have the issue that if your number format is 1,000.00 and you enter a number in 1.000,00 format it will be divided by 1000.  Similarly if you enter a number a number the other way, you get an error.  Also some formats don't have thousand separators.

**Comment by ehuelsmann** [comment]
I'm thinking this item will or should be resolved when the front-end gets rewritten into a service-based spa
