### ISSUE TITLE
1.5 master does not currently upgrade from 1.4

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1262]
On a dev machine previously running 1.5 on the same database, I dropped the database, recreated, and restored a more recent copy of my production database. Then I attempted to run setup.pl to update it.

Got this error:

Error!
 
psql:sql/modules/Roles.sql:383: ERROR: relation "warehouse_inventory" does not exist at /usr/local/lib/perl5/site_perl/5.22.1/PGObject/Util/DBAdmin.pm line 257.
PGObject::Util::DBAdmin::run_file(LedgerSMB::Database=HASH(0x71e9608), "file", "sql/modules/Roles.sql", "log_stdout", "/tmp/ledgersmb/dblog_2016-01-15T191237_9_stdout", "log_stderr", "/tmp/ledgersmb/dblog_2016-01-15T191237_9_stderr") called at LedgerSMB/Database.pm line 359
LedgerSMB::Database::load_modules(LedgerSMB::Database=HASH(0x71e9608), "LOADORDER", HASH(0xa15a2b8)) called at LedgerSMB/Database.pm line 425
LedgerSMB::Database::upgrade_modules(LedgerSMB::Database=HASH(0x71e9608), "LOADORDER", "1.5.0-dev") called at LedgerSMB/Scripts/setup.pm line 1233
LedgerSMB::Scripts::setup::rebuild_modules(LedgerSMB=HASH(0x71e6d38)) called at bin/lsmb-request.pl line 102
LedgerSMB::PSGI::try {...} () called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try(CODE(0x71e8530), Try::Tiny::Catch=REF(0x89e2bb8)) called at bin/lsmb-request.pl line 114
LedgerSMB::PSGI::call_script("setup.pl", LedgerSMB=HASH(0x71e6d38), LedgerSMB::Locale::en=HASH(0x71e85d8)) called at bin/lsmb-request.pl line 140
require bin/lsmb-request.pl called at LedgerSMB/PSGI.pm line 82
LedgerSMB::PSGI::try {...} () called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} called at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try(CODE(0x8a1a6b8), Try::Tiny::Catch=REF(0x8b12a98)) called at LedgerSMB/PSGI.pm line 90
LedgerSMB::PSGI::_run_new("setup.pl") called at LedgerSMB/PSGI.pm line 46
LedgerSMB::PSGI::__ANON__() called at /usr/share/perl5/CGI/Emulate/PSGI.pm line 29
CGI::Emulate::PSGI::__ANON__(HASH(0x8a724a8)) called at /usr/share/perl5/Plack/Middleware/Static.pm line 18
Plack::Middleware::Static::call(Plack::Middleware::Static=HASH(0x8bd3718), HASH(0x8a724a8)) called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x8a724a8)) called at /usr/share/perl5/Plack/Util.pm line 142
eval {...} called at /usr/share/perl5/Plack/Util.pm line 142
Plack::Util::run_app(CODE(0x8bd36a0), HASH(0x8a724a8)) called at /usr/share/perl5/Starman/Server.pm line 281
Starman::Server::process_request(Starman::Server=HASH(0x184d3d8), Net::Server::Proto::TCP=GLOB(0x8bd3448)) called at /usr/share/perl5/Net/Server.pm line 74
Net::Server::run_client_connection(Starman::Server=HASH(0x184d3d8)) called at /usr/share/perl5/Net/Server/PreFork.pm line 229
eval {...} called at /usr/share/perl5/Net/Server/PreFork.pm line 229
Net::Server::PreFork::run_child(Starman::Server=HASH(0x184d3d8)) called at /usr/share/perl5/Net/Server/PreFork.pm line 187
Net::Server::PreFork::run_n_children(Starman::Server=HASH(0x184d3d8), 5) called at /usr/share/perl5/Net/Server/PreFork.pm line 111
Net::Server::PreFork::loop(Starman::Server=HASH(0x184d3d8)) called at /usr/share/perl5/Net/Server.pm line 60
Net::Server::run(Starman::Server=HASH(0x184d3d8), "port", ARRAY(0x1c2b448), "host", "*", "proto", "tcp", "serialize", "none", ...) called at /usr/share/perl5/Starman/Server.pm line 89
Starman::Server::run(Starman::Server=HASH(0x184d3d8), CODE(0x184d330), HASH(0x184d5d0)) called at /usr/share/perl5/Plack/Handler/Starman.pm line 18
Plack::Handler::Starman::run(Plack::Handler::Starman=HASH(0x184d318), CODE(0x184d330)) called at /usr/share/perl5/Plack/Loader/Delayed.pm line 20
Plack::Loader::Delayed::run(Plack::Loader::Delayed=HASH(0x1761448), Plack::Handler::Starman=HASH(0x184d318)) called at /usr/share/perl5/Plack/Runner.pm line 277
Plack::Runner::run(Plack::Runner=HASH(0x1769020)) called at /usr/bin/starman line 38
 
dbversion: 1.5.0-dev, company:

**Comment by freelock** [comment]
... I get this result in 1.5.0-beta3, and Master @ fb5da9d1.

1.5-beta2 does upgrade cleanly. However, when I then attempt to upgrade from there to master, setup.pl shows me "Unsupported version detected."

**Comment by einhverfr** [comment]
Actully with the db change framework working now, putting this o next beta

**Comment by einhverfr** [comment]
This appears to have been fixed in the process of the db change framework.
