### ISSUE TITLE
1.4.23 [UI]: Clicking on the account number in the CoA screen confusing

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1268]
Feedback I'm receiving indicates (and I'm making this mistake regularly too) that users expect to click on an account in the CoA screen and be taken to the account settings screen. However, currently this link takes the user to a search screen, while clicking on "[Show]" leads to the account settings screen.

Proposed resolution:

* Change the text "[Show]" to "[Report]"
* Change the link on the account number to the link that was on [Show]
* Set the link on [Report] to what was on the account number
* Add "alt" text / title text to indicate where the link is going to lead

**Comment by einhverfr** [comment]
for 1.5 want to make this consistent with the rest of the UI:
clicking on the accno and description takes you to the edit screen
clicking on the amounts takes you to the report screen.   Will submit a pr for review.
