### ISSUE TITLE
1.4.23 [UI]: Replace Open/Closed checkmarks with radio Open/Closed/All

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1269]
From the feedback I'm getting, users don't understand the dual checkboxes Open/Closed to be a combination which can be meaningless: i.e. when both are unchecked.

Proposed solution: Replace the Open/Closed checkmarks with a "tri-state" radiobutton: Open/Closed/All to eliminate the fourth state and make the choices clear in the UI.

**Comment by einhverfr** [comment]
this is for ar/ap search routines?

**Comment by ehuelsmann** [comment]
Yes.

**Comment by einhverfr** [comment]
sufficient user experience change to save for a major release.

**Comment by ehuelsmann** [comment]
Could probably take the same approach as the "Approval_Option" on some reports.
