### ISSUE TITLE
GL Description not escaping/encoding correctly (1.4)

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1270]
I'm doing some reconciling, and have found an escaping issue in GL items, the description field:

1. Create a GL transaction, with an '&' in the description field -- e.g. "Owl & Thistle"
2. Save.

Result: description gets changed to "Owl &amp; Thistle", and this is what gets saved. If you do another operation, it gets escaped again, to "Owl &amp;amp; Thistle".

**Comment by einhverfr** [comment]
we've had a few issues with Dojo having trouble here.

**Comment by einhverfr** [comment]
This is fixed in 1.5 and it hasn\t generated many complaints, so closing it as rc2 for now.
