### ISSUE TITLE
forms won't submit after UI functions moved

### ISSUE THREAD

**Issue by maikkeli** [ledgersmb/LedgerSMB#1277]
A lot of the forms don't seem to work any more in ledgersmb/master. (Eg; search for customer).

Looking at errors thrown in the javascript console, dojo can't find some functions (load_form, load_links, +others?) after they were split out into their own file in commit# ceb23009cf504e447815b208b532ace8583cffe6

**Comment by ehuelsmann** [comment]
@maikkeli thanks for the report! This is definitely a high-priority issue to be resolved on my list.
