### ISSUE TITLE
Upgrade_Tests.pm: gifi account no. test returns null result -- incorrectly?  Odd behaviour.

### ISSUE THREAD

**Issue by m455873** [ledgersmb/LedgerSMB#1278]
This is a usability enhancement for upgrades.  I'm trying to do an upgrade from 1.3.46 to 1.4.23.  Running the upgrade.pl page,  I get caught at the gifi account numbers page.  Error is: 

> GIFI accounts not in "gifi" table
Please use the 1.3/1.4 UI to add the GIFI accounts
gifi_accno 

There are no "gifi_accno" values, just the heading.  Thats all I get.

In 1.4 tree, LedgerSMB/Upgrade_Tests.pm, around line: 324-327.  I'm using 1.4.23, but the latest milestone is unchanged.  SQL query in question:

```
324 select distinct gifi_accno from account
325                    where not exists (select 1
326                                        from gifi
327                                       where gifi.accno = account.gifi_accno)
```

Using pgAdminIII query, on my system returns 1 null result.  This seems odd, as the intent is to provide a list of account numbers that are used in the account table, but not present in the gifi text description table.  A null result here is not really useful.

Maybe answer would be to provide a list of account numbers along with gifi account number (distinct tuples) that need to be updated, if more than one account has a null gifi value.

Like so:

```
324 select distinct accno,gifi_accno from account
325                    where not exists (select 1
326                                        from gifi
327                                       where gifi.accno = account.gifi_accno)
```

**Comment by ehuelsmann** [comment]
Fixed in 1.4.28
