### ISSUE TITLE
Item Not On File page needs Cancel Button

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#1284]
- Sales->Sales Invoice
- Mis-type a product/service code in the Number Column
- Click Update
- An "Item Not On File" page appears

This page has only a "Continue" button, taking you to the "Add Part" or "Add Service" pages.

There is no "Cancel" button to take you back to the invoice so that the invalid product/service code can be corrected. There should be.

**Comment by einhverfr** [comment]
important enough ux improvement to get in during a stable branch

**Comment by nick-prater** [comment]
Confirmed - bug can be closed. Many thanks.
