### ISSUE TITLE
Sales Invoice Item Notes Field blank after Update

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#1285]
Tested in 1.4.23:

* Sales->Sales Invoice
* On a blank line, enter an existing Product Number
* Click Update - note the description has now been populated
* Enter something in the item's Notes field (beneath the description)
* Click Update

The text entered in the Item Notes field should be kept, instead the field is blank after clicking 'Update'

**Comment by einhverfr** [comment]
Works for me in 1.5, now testing on 1.4

**Comment by einhverfr** [comment]
Works on 1.4 except when new item is populated.  IOW, this happens on current 1.4 only when updating the first.  We may have fixed this along with other things.
