### ISSUE TITLE
AR/AP->Aging doesn't take date into account

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1286]
Verified on 1.4 demo.

Go to AR or AP Aging, change date, results don't change.

**Comment by ehuelsmann** [comment]
Initial diagnosis: the UI element has a name of "todate", while the Perl side expects it to be 'date_ref' (see LedgerSMB/Report/Aging.pm:238) -- the documentation talks about 'to_date'. It seems all these need is being aligned.

**Comment by craigwebster** [comment]
Great! That works, and it really helps to get details like this is learning the codebase. Patch files attached, should I also git push?
[aging.html.diff.txt](https://github.com/ledgersmb/LedgerSMB/files/114776/aging.html.diff.txt)
[Aging.pm.diff.txt](https://github.com/ledgersmb/LedgerSMB/files/114777/Aging.pm.diff.txt)

**Comment by ehuelsmann** [comment]
If you're able to provide a git push+pull request, that would be a great
time-saver on my part, yes. Please give it a try if it doesn't work, we can
try the diff files.

Regards,

Erik.

**Comment by craigwebster** [comment]
Will try.

**Comment by ehuelsmann** [comment]
Fixed in PR #1292
