### ISSUE TITLE
GJ->Search doesn't take amount into account

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1287]
This already reported on IRC, may have been worked on?

Change in "amount" max and/or min makes no difference to search.

**Comment by ehuelsmann** [comment]
There seems to be a mismatch between the UI element (called 'amountfrom' and 'amountto') where the code seems to expect 'amount_from' and 'amount_to' (see LedgerSMB/Report/GL.pm). All that needs to happen is that the UI elements get renamed to 'amount_from' and 'amount_to', as defined in UI/Reports/filters/gl.html

**Comment by craigwebster** [comment]
Great, that works -- and it's really helpful to get details like this in learning the code structure.  Patch files attached -- should I try to git push as well?

[aging.html.diff.txt](https://github.com/ledgersmb/LedgerSMB/files/114772/aging.html.diff.txt)
[Aging.pm.diff.txt](https://github.com/ledgersmb/LedgerSMB/files/114773/Aging.pm.diff.txt)

**Comment by craigwebster** [comment]
Hmmm, this one doesn't appear to solve the problem. I make the change and the HTML sourcecode refers to amount_to & amount_from, but no change in behavior. I'm wanting to trace run_report further from GL.pm, and as a shortcut, I'll ask:  where is the file that takes the variables and turns it into SQL?

**Comment by ehuelsmann** [comment]
The actual code generating the SQL is in PGObject and PGObject::Simple::Role (the inheritance is: LedgerSMB::Report::GL -> LedgerSMB::Report -> LedgerSMB::PGObject -> PGObject::Simple::Role).

However, it's probably easier to turn on statement logging in PostgreSQL and see what query is fired at the database.

But I can see the problem already: the names of the amount arguments in the function 'report__gl' is:
 * in_to_amount
 * in_from_amount

While the fields in the object with the same purpose are called:
 * amount_from
 * amount_to

Please make sure the naming is in line with the argument names in in the SQL in the entire call chain. Then it should start to work. Let me know if it works!

**Comment by craigwebster** [comment]
Found that earlier, and tried swapping the names, no luck. Been exploring further through the call chain, will report further. Appears that it's a more widespread problem, as other reports using LSMB::Report also have the problem, eg. Reconciliation.

**Comment by ehuelsmann** [comment]
Based on the above, I'd say that this issue is no longer bite-sized. Please continue to work on it though, if you have the time and feel like it.

**Comment by einhverfr** [comment]
Having looked into this, the larger issues are:

1)  The stored procedure doesn't support the functionality.
2)  Adding that will have an adverse impact on db performance.

I am going to go ahead and take this one.  I think what we have to do is to decide if we need a search on amount and if so, then do the more expensive query.

**Comment by einhverfr** [comment]
This is definitely not bite-sized

**Comment by einhverfr** [comment]
On further review, this is the per line amount, not the per transaction amount so we can fix it.

The problems were differences in field names.  Got these fixed.  I also changed the stored procedure to return debits or credits matching the range.

**Comment by craigwebster** [comment]
Yes! This works ... I had the changes except the absolute value in the sql -- which is a great place to look for issues. Thanks for helping on this, very helpful in learning the code.
