### ISSUE TITLE
Cash->Voucher->Reverse payment fails -- silently, or with error

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1291]
The "reverse payment" structure is a major improvement from previous workflows requiring exactly reproducing transactions.

{Major revision of comment on Mar 17}

On demo 1.4

Cash->Voucher->Reverse Payment 
Select batch
Select period/account, select payment
Returns to search screen as if reversal occurred
Search again, payment remains
Go to "Approve transactions"
Find batch -- it will be "0", no contents
Approve batch
Search again, payment remains

This is the "silent fail".

My current best guess: since many people do not report this problem, perhaps it only happens when "Separation of Duties" is on? Ie. when it's off, code creates an empty batch to be approved that can't be approved, thus never posts?

On our 1.4.25, apparently only for the main Cash account, also have an error thrown on "Reverse", may or may not be related: 

```
2016-03-16 10:33:06 PDT ERROR:  null value in column "chart_id" violates not-null constraint
2016-03-16 10:33:06 PDT DETAIL:  Failing row contains (27042, null, 0.00000000000000000000, 2016-03-16, cash TEST, f, f, Reversing cash TEST, null, f, null, null, 35, 76133).
2016-03-16 10:33:06 PDT CONTEXT:  SQL statement "INSERT INTO acc_trans
                        (trans_id, chart_id, amount, transdate, source, memo, approved,
                                voucher_id)
                        VALUES
                        (pay_row.trans_id, pay_row.chart_id,
                                pay_row.amount / t_paid_fx * -1 * t_rev_fx,
                                in_date_reversed, in_source, 'Reversing ' ||
                                COALESCE(in_source, ''),
                                case when in_batch_id is not null then false
                                else true end, t_voucher_id),
                         (pay_row.trans_id, pay_row.ar_ap_account_id,
                                pay_row.amount / t_paid_fx * pay_row.fxrate,
                                in_date_reversed, in_source, 'Reversing ' ||
                                COALESCE(in_source, ''),
                                case when in_batch_id is not null then false
                                else true end, t_voucher_id),
                         (pay_row.trans_id,
                          case when pay_row.fxrate > t_rev_fx
                               THEN t_fxloss_id ELSE t_fxgain_id END,
                          pay_row.amount / t_paid_fx * (t_rev_fx - pay_row.fxrate),
                          in_date_reversed, in_source, 'Reversing ' ||
                                                        COALESCE(in_source, ''),
                           case when in_batch_id is not null then false
                                else true end, t_voucher_id)"
        PL/pgSQL function payment__reverse(text,date,integer,text,date,integer,integer,integer,numeric,character) line 90 at SQL statement
2016-03-16 10:33:06 PDT STATEMENT:  SELECT * FROM "public"."payment__reverse"('cash TEST', '2016-03-16', '93', '1060', '2016-03-16', '1', '30', NULL, NULL, 'USD')
```

**Comment by einhverfr** [comment]
We need better handling of what happens if no cash account is set on the eca.  the cash account sets the account that the cash payment portion of the payment is returned to.

**Comment by ehuelsmann** [comment]
Well, the functionality says "Reverse Payment" in which case I think we should actually reverse the *orginal* payment, with all its details, meaning including its cash account.

**Comment by ehuelsmann** [comment]
Setting to 1.6: too invasive to make the proposed change in any released branch.

**Comment by ehuelsmann** [comment]
Just tested this with e78eef7 (master/1.8) and works perfectly, even when no cash account is set up on the eca. (Not setting up an arap account on an eca is prevented by a constraint on the eca.)
