### ISSUE TITLE
Trying to "Ship to" throws error

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1293]
Customer has no shipping address,

In Sales Invoice, after created, go to "Ship to"

Put "NA" in all string fields, select arbitrary radio buttons.

Throws: 

'select \* from eca__location_save(?,?,?,?,?,?,?,?,?,?, null);
ERROR: duplicate key value violates unique constraint "eca_to_location_pkey"
DETAIL: Key (location_id, credit_id, location_class)=(800, 822, 3) already exists.
CONTEXT: SQL statement "INSERT INTO eca_to_location 
(credit_id, location_class, location_id)
VALUES (in_credit_id, in_location_class, l_id)"
PL/pgSQL function eca__location_save(integer,integer,integer,text,text,text,text,text,text,integer,integer) line 39 at SQL statement at LedgerSMB/IS.pm line 2255.
'

**Comment by einhverfr** [comment]
This initial problem appears to no longer happen at least in 1.5.
However, when the user does have a shipto, then the shipto button breaks and one cannot get there to see it.

I am opening a new issue for 1.5, but need to test this again on 1.4

**Comment by ehuelsmann** [comment]
As 1.4 is now EOL (and I'm not seeing this behaviour here), closing as works for me.

I know what the 1.5 problem is too. A reference from here to there would be helpful next time.
