### ISSUE TITLE
Can't Post AP Transaction 1.4.24-rc1

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#1297]
* Purchases->Add Transaction
* Enter details
* Click Save
* Post button should be displayed but isn't

Without the post button... you cannot post the transaction!

**Comment by nick-prater** [comment]
Turns out this was broken some time ago.
Reverting commit fe817c7b7e0ef884e54b6158104985d2084825fb fixes this issue for me.

**Comment by ehuelsmann** [comment]
Hi Nick,

Thanks for finding the offending commit! What happens if you click "Save" twice? I think it simply didn't save the first time, because if I "Save" twice, the Post button *does* appear.

Regards,

Erik.

**Comment by ehuelsmann** [comment]
Looking at https://github.com/ledgersmb/LedgerSMB/blob/master/bin/aa.pl#L1348 I would say the code path you're talking about *is* intentional (although possibly not desirable). Wondering what to do here...

**Comment by nick-prater** [comment]
If I click Save twice (or more) I don't see a change in the buttons. The post button *doesn't* appear.

This old code is a minefield of side-effects and unintended consequences, so the solution is not yet clear in my head I'm afraid.

**Comment by ehuelsmann** [comment]
Ok. Since it fails for you, but works for me - *and* since it's been broken since 1.4.20 - I'm going to go through with the 1.4.24 release tonight. This needs more research.

**Comment by ehuelsmann** [comment]
Could you check the submitted parameters for the value of 'oldvendor' on both "Save" calls? (Do you know how to track network requests in Chrome/FireFox?)

**Comment by nick-prater** [comment]
Agree with releasing 1.4.24. I'll check the submitted parameters shortly. Thanks for looking at this.

**Comment by nick-prater** [comment]
On first save, oldvendor=""
On second and subsequent saves, oldvendor="4Children--155--155", (4Children being the name of the vendor)

Mashing together the vendor name and id into the same parameter like this seems like a recipe for trouble. I'm wondering if there is a reason why we don't just pass the numeric id and how tricky that change is to make.

**Comment by nick-prater** [comment]
Does this fix the issue without breaking anything else? Always hard to tell with this old code.
```
--- aa.orig	2016-02-09 13:26:13.000000000 +0000
+++ aa.pl	2016-02-09 13:37:45.000000000 +0000
@@ -227,7 +227,7 @@
     $form->{duedate}     = $duedate     if $duedate;
     $form->{crdate}      = $crdate      if $crdate;
 
-    if ($form->{"old$form->{vc}"} =~ /--/){
+    if ($form->{"old$form->{vc}"} =~ /--/ && $form->{$form->{vc}} !~ /--/){
         $form->{"old$form->{vc}"} = $form->{$form->{vc}} . '--' . $form->{"$form->{vc}_id"};
     } else {
         $form->{"old$form->{vc}"} = $form->{$form->{vc}};
```

Earlier versions didn't have this conditional expression at all and I'm not sure why it was added.

**Comment by ehuelsmann** [comment]
Lumping text and IDs together like that absolutely is a recipe for trouble and clearly we have been through a lot of that with SL code. Lumping together these values like that happens *everywhere* in the SL code.

This issue has had me wondering all this time how you were seeing a vendor value "<vendor-name>--<vendor-id>". I think I figured it out:

**Are you selecting your vendors through a dropdown in the transaction entry screen?**

**Comment by ehuelsmann** [comment]
Assuming the answer is "yes", could you try if this patch works for you:

```
--- aa.orig 2016-02-09 13:26:13.000000000 +0000
+++ aa.pl   2016-02-09 13:37:45.000000000 +0000
@@ -227,7 +227,7 @@
     $form->{duedate}     = $duedate     if $duedate;
     $form->{crdate}      = $crdate      if $crdate;

-    if ($form->{"old$form->{vc}"} =~ /--/){
+    if ($form->{$form->{vc}} !~ /--/){
         $form->{"old$form->{vc}"} = $form->{$form->{vc}} . '--' . $form->{"$form->{vc}_id"};
     } else {
         $form->{"old$form->{vc}"} = $form->{$form->{vc}};
````

**Comment by nick-prater** [comment]
> Are you selecting your vendors through a dropdown in the transaction entry screen?

Yes I am. In fact I'd forgotten there was another way!

Your patch does indeed work for me. Thank you!
