### ISSUE TITLE
Cash->Receipt shows entries with fractions of pennies outstanding

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#1298]
Tested in 1.4.24-rc1

I have a number of invoices and credit notes for which there are fractions of pennies outstanding. In my case, these are all rounding errors resulting from foreign exchange transactions.

In discussion on irc, it was established that:
<ehuelsmann> the code should consider sub-penny differences as fully paid, actually.

For context, the following screenshot should therefore display no entries:

![screenshot from 2016-02-06 18 20 28](https://cloud.githubusercontent.com/assets/1817335/12868433/913867da-ccfe-11e5-8989-613eac822f6a.png)

**Comment by JigmeDatse** [comment]
I am currently seeing this on Master.

**Comment by nick-prater** [comment]
Confirmed as fixed in 1.7 and 1.8.
