### ISSUE TITLE
GJ>Searching by Department fails

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1358]
1.4.23

GJ -> Search
Enter a dep't with known entries
Result is some, but not all, of known entries.

Reports->Income statement
Enter a dep't
Result is everything, not restricted by Dep't.

Likely affects all reporting units

**Comment by craigwebster** [comment]
Note: I think this also fixes Income Statement report not filtered by Dep't/reporting unit.

**Comment by craigwebster** [comment]
Do mcr's Malay language fixes really address this issue??

**Comment by craigwebster** [comment]
Brief check with 1.4.37 seems not to find this GJ->Search problem anymore.

**Comment by ehuelsmann** [comment]
Thanks for verifying. Closing.
