### ISSUE TITLE
CoA Account & Account Heading page layout borked

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1364]
The account heading tab needs a vertical scrollbar

The account page has its layout completely mixed up -- missing CSS?

The account page needs a vertical scrollbar too.

**Comment by einhverfr** [comment]
Propose we break the translation bit off into a new tab visible only after the account or heading is saved.

**Comment by einhverfr** [comment]
The account page also lost the handling of groupings of accounts, so we may need a new solution for that.
