### ISSUE TITLE
Duplicate entries in language selector

### ISSUE THREAD

**Issue by mikl** [ledgersmb/LedgerSMB#1371]
With LedgerSMB 1.4.25 via Docker, I'm experiencing duplicate entries in the language selector on the `user.pl` page.

As can be seen here:
![screen shot 2016-02-27 at 03 53 49](https://cloud.githubusercontent.com/assets/10263/13370379/c963c2fa-dd05-11e5-8d45-7a8cda1bf762.png)
each language has duplicate entries. Danish has both “Danish” and “Danish/”.

For languages with country variations the root language is only present once (eg. “English”) but the sub-languages are doubled (eg. “English/Canada” appears twice).

**Comment by sbts** [comment]
@mikl
We are trying to investigate this further but are having trouble reproducing it.
Are you still having this issue?
If you are, are you still running the same version?

**Comment by ehuelsmann** [comment]
Moving to 1.4.38 pending user feedback.

**Comment by mikl** [comment]
@sbts I just tried with 1.4.36, I can no longer reproduce. I assume it has been fixed somewhere in between.

**Comment by ehuelsmann** [comment]
@mikl, thanks for the feedback! Closing.
