### ISSUE TITLE
Purchase unit conversion

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1388]
It would be nice to be able to specify a purchase unit
conversion and have this tracked in the database rather
than having this managed via assemblies (which is a
very complex hack, IMO).

From https://sourceforge.net/p/ledger-smb/feature-requests/39/

**Comment by ehuelsmann** [comment]
@einhverfr with the original request gone, could you add a description of how this would work on this issue? Maybe you have a specific user in mind? We could add their use-case too.
