### ISSUE TITLE
1.5 schema mismatch: journal table has 'memo' column on 1.4, but not in 1.5

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1396]

**Comment by einhverfr** [comment]
moving here due to interdependence with upgrade testing

**Comment by einhverfr** [comment]
I cannot seem to find this.  Closing as worksforme for now.  If yu see it, please let me know which table specifically.

**Comment by ehuelsmann** [comment]
Can't find it myself either; this report stems from porting changes from the master and 1.4 branches to the master-mc and 1.4-mc branches.
