### ISSUE TITLE
[1.4.26] Attribute validation error when entering a sales order

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1408]
Error!'Attribute (description) does not pass the type constraint because: Validation failed for 'Maybe[Str]' with value [ "Hours - Non Profit Charity rate" ] at constructor LedgerSMB::File::new (defined at LedgerSMB/File.pm line 348) line 52LedgerSMB::File::new('LedgerSMB::File', 'reqdate_2', '', 'meta_number', 423, 'PRINTERS', 'ARRAY(0x754a930)', 'oldtotalpaid', '', 'onhand_1',...

The above tries to fit an array (```[ "Hours - Non Profit Charity rate" ]```) into the "description" slot which is of type "Maybe[Str]"... (EDOESNTFIT)

**Comment by ehuelsmann** [comment]
User remark: "I don't  think we're adding a file here"

**Comment by freelock** [comment]
I think this is happening when emailing a PDF sales order, not when saving the invoice.

**Comment by ehuelsmann** [comment]
Ok. still seeing this at 1.4.28; the problem shows *after* the mail has been sent.

**Comment by ehuelsmann** [comment]
Merged (but not closed by the merge??). Closing.
