### ISSUE TITLE
Master: Search for recon reports shows blank page

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1423]
Scenario:  Trying to approve a reconciliation report
When I go to the menu And select Cash/Reports/Reconcoliations
And click continue
Then I see a list of reconciliation reports

------------

Instead I just see a blank screen.

**Comment by ehuelsmann** [comment]
Issue resolved, BDD test to be implemented, leaving bug open for handling during 1.5 release cycle.
