### ISSUE TITLE
Broken Print/Email to PDF and Postscript due to LaTeX::driver bug

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1426]
LaTeX::driver has a bug that forces the use of xelatex to render all pdf or postscript source material.
It also has a bug that causes data to be dumped to stdout.

These cause the following issues

 ~~1. a "normal" install of LedgerSMB to fail when trying to generate PDF or Postscript output if running under Apache (due to leaking data to stdout) 
Running under Starman succeeds so this issue can be worked around~~

 2. All installations will fail if xelatex packages are not installed

 3. You can't generate postscript output, it always generates PDF output instead

 4. You can't currently use TeX templates that are not valid XeLaTeX
 Instead you get errors like "Package inputenc Error: inputenc is not designed for xetex or luatex"

 5. You probably can't print to a printer on any system that requires postscript instead of PDF to be sent to lpr

#### To work around 1.
Run LedgerSMB under Starman (see the included README.md) and reverse proxy with Apache (ask on mailing lists or IRC

#### To work around 2.
install system packages for xelatex

#### To work around 3.
Unfortunately no work around is available, you can't generate postscript output for the moment

#### To work around 4.
Unfortunately the only work around available it to
You can convert your templates to XeLaTeX.
Or
patch /usr/share/perl5/LaTeX/Driver.pm line 78 to read
pdf => [ 'pdflatex' ]

#### To work around 5.
It may be possible to use different printer drivers, or a different printer until LaTeX is fixed
Otherwise there is no workaround for now

**Comment by jame** [comment]
This was from LaTeX::Driver  version 0.200.4-1 ?
Does it affect the 1.3.x series as well?

**Comment by ehuelsmann** [comment]
Yes, it applies to all LedgerSMB versions. It's specific to the
Latex::Driver module in current Jessie (which I think is the one you refer
to?).

**Comment by jame** [comment]
Yes; v0.200.4-1 is the version of LaTeX::Driver that made it into Debian v8 ('Jessie').   (Note that there are no bugs currently open in Debian or Ubuntu related to this issue that I've been able to find.)

**Comment by einhverfr** [comment]
Upstream bug, reported with a short-term fix applied.  Closing as fixed by https://github.com/Template-Toolkit-Latex/LaTeX-Driver/pull/5

**Comment by ehuelsmann** [comment]
@einhverfr re-opening, if you don't mind. Your merge upstream fixed the first item of 5. I'd say that the third item (can't generate PostScript output) is another upstream bug, possibly in the latex filter, which still needs to be addressed.

**Comment by ehuelsmann** [comment]
@einhverfr thanks for merging quickly though! (Moving to next milestone.)

**Comment by einhverfr** [comment]
Given that this is an upstream bug though, I don't want to tie it to any milestones for the following reason:

1.  Upgrading LedgerSMB won't fix the problem (therefore fixes shouldn't be in our cangelog), and
2.  It can be fixed by upgrading the other component.

an we then close as duplicate?  If nothing else, removing the milestone.

**Comment by einhverfr** [comment]
Will leave open until upstream change released.
However, it is orthogonal to lsmb releases I think since the problematic dependency can be updated with or without updating lsmb.

**Comment by ehuelsmann** [comment]
Ok. Agreed.

Having this issue logged helps to point users who experience this problem to the correct solution, so I see value there.

Regards,

Erik.

**Comment by sbts** [comment]
When combined with LaTeX::Driver >= 0.300.1
Pull Request #1441 resolves most of these issues.
It introduces the ability to specify a processor and output type directly in the template and updates the default templates in the repository.

At this time any templates stored in the database or modified templates on disk will need to be manually updated to include these directives.
Check the new default templates for correct entries (they will be in the top few lines of each template)

**Comment by ehuelsmann** [comment]
Closing, based on the fact that PR #1441 was released and 0.300.2 is too.
