### ISSUE TITLE
Improve Setup screens for reports, especially Income Statement

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1429]
Currently the setup screens for reports like Income Statement are cluttered and difficult to understand for new/casual users.

Improvements need to be made, some possible methods are listed in this issue and it's comments....

only offer one period, then an "add comparison" button that adds a second set of date range buttons, then a 3rd, 4th etc
when the next comparison is displayed on screen it should default to 12months prior to the previously entered dates. (not necessarily a 12 month window, but both dates 12 months earlier)

**Comment by freelock** [comment]
I'm using a single date-range, with sub-totals broken out by period. I've developed this in another PHP app, and it's actually pulliing this data live from the LSMB database -- I think it would be at least a useful option here.

Conversation starts here: https://vector.im/staging/#/room/!qyoLumPqusaXqFJNyK:matrix.org/$145928782651xVdcb:matrix.freelock.com

Hi, regarding the PNL report periods, I had proposed something quite a while back that Chris didn't seem keen on
I've actually implemented it on another dashboard, running queries against the lsmb database
with my PNL report there, I select start date, end date, type (cash or accrual) and "period" -- month, quarter, year
it then uses a native pg function to slice into those time periods, easy peasy
great for doing quarter on quarter comparisons, for say the last 8 quarters -- set to 2014-04-01 - 2016-03-31, quarter
![selection_368](https://cloud.githubusercontent.com/assets/46937/14125033/e9da7bde-f5bd-11e5-874a-94a95205432f.png)

**Comment by ylavoie** [comment]
Most users should have year beginnings and ends that do not change over time.
We could then keep the first From/To/Period and have 2 options.

1. Default to only ask for the number of periods to compare to and let the code handle the details
2. For others, present a detailed view where each comparison would default to one period before the previous one.

It would keep simplicity and flexibility

**Comment by einhverfr** [comment]
This is potentially workflow breaking and needs to go through full beta/rc

**Comment by einhverfr** [comment]
However, I think in keeping with the "close to the paper" philosophy, I think we need to make sure our vocabulary is consistent and that it is correct vocabulary from an accounting perspective.

Some of the concepts are genuinely difficult to understand (what is the difference between a "debit" and a "credit?")

**Comment by ehuelsmann** [comment]
Total refactoring has taken place with respect to the "setup" screens (parameter selection) for both Income statement *and* Balance sheet after it was originally filed and has been part of 1.6+.
