### ISSUE TITLE
Overhaul Sysconfig.pm to solve code complexity test failure, fix defaults and other issues

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1446]
The current Sysconfig.pm is missing various settings that are present in ledgersmb.conf and in the code
Conversely there are settings in Sysconfig.pm that don't exist elsewhere.
To make it worse not all settings have a sane default (or any default at all)

**Comment by ehuelsmann** [comment]
This has been resolved in 1.5. Closing.
