### ISSUE TITLE
Balance sheet report can't ignore year-ends

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1460]
Found on 1.4 and 1.5/master

**Comment by einhverfr** [comment]
Hot sure what this would mean since we only write to the retained earnings account during the year end.

**Comment by ehuelsmann** [comment]
Well, the way I see it, the "year end" transaction is preparing the books for the new year. The current earnings are still there at the last report for the year; then, for the next year, the current earnings have moved to retained earnings.
Being able to present the last balance of the year would mean ignoring the year-end of that year, when you look at it this way.

**Comment by einhverfr** [comment]
Ah so basically it is all about the retained earnings bit.  Agreed that this would be a good thing to do.

**Comment by ehuelsmann** [comment]
After having to explain this change, I found the right wording: the ending balance (ultimo) of a period is all the transactions excluding the year-end transaction. The starting balance of the next period (primo) is all the transactions up to that date, including the year-end transaction.
So, the ending balance should exclude the year-end transaction.
