### ISSUE TITLE
GL/search can't exclude year-ends

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1461]
But should it?

**Comment by einhverfr** [comment]
I cannot think of any reason it should except possibly when drilling down through the income statement.  Do we have a user complaint on it?  I think this should be addressed if we need to.

Note that ignoring year-ends is mostly important for people doing their own financial statements after they close their books, so it is a fairly narrow application.

**Comment by craigwebster** [comment]
FWIW, I think that many potential users of this system do or should do their own financials. Certainly we do ... and having a more robust system is invaluable. Ignoring year-ends on income statements is absolutely necessary -- the generic GJ/search is less of an issue, but I gather they use the same code?

**Comment by ehuelsmann** [comment]
@craigwebster no, the code which drills down on the PnL numbers doesn't use the same code as the code which produces the PnL itself.

**Comment by ehuelsmann** [comment]
I've given this some thought and I think year-ends are about producing opening balances which differ from the closing balance of the day before (due to year-end). As such, I think they're most important on drill-down on PNLs. Indeed, I don't think this issue is important enough to keep open (in summary: I concur with @einhverfr ).
