### ISSUE TITLE
editing COA account doesn't allow scrolling of the Translations

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1463]
As tested on 
https://demo.cloud.efficito.com/erp/1.4/
(version 1.4.27)
When editing an account in the COA we now have more languages presented for translation of the account description than can be viewed.

We need to wrap the translations table in a scrollable div or similar
Also the table probably should be given an ID as well

**Comment by ehuelsmann** [comment]
Apparently fixed, because on demo (1.4.28) it works for me.
