### ISSUE TITLE
1.5: AR/AP Transaction -> Print errors on HTML and CSV formats

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1472]
The code behind the AR/AP transaction Print button doesn't support other formats than PDF and Postscript, even though the dropdown also shows HTML and CSV...

**Comment by einhverfr** [comment]
We have templates for these.

**Comment by einhverfr** [comment]
the problem is actually that the media dropdown entry is not getting passed through.

**Comment by einhverfr** [comment]
from the console in chrome, the following works so I am puzzled:
```
require(['dijit/registry'], function(r) {
    console.log(r.byId('media'));
    console.log(r.byId('media').get('value'));
});
VM468:2 Object {_attachPoints: Array[8], _attachEvents: Array[0], _oValue: null, _notifyConnections: Array[0], _inherited: Object…}
VM468:3 screen

```

**Comment by einhverfr** [comment]
apparently the code problem is in 1.4, but it doesnt show up in behavior until 1.5
