### ISSUE TITLE
1.6: Need forking intra-code dispatch

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1484]
Currently the following "new-code" modules dispatch to "old-code" by loading and invoking those modules. Since the new code handlers are PSGI workers, which get re-used, this type of intra-code dispatch isn't supported.

We need a way to invoke the old code - best through a centralized bridge of some sort - which makes sure that after the child has completed, the Perl interpreter in which it ran gets cleaned up. [Note that this is the purpose of the forking behaviour in the PSGI handler in the first place.]

**Comment by ylavoie** [comment]
I started working on this a few weeks ago. PSGI allows for separation of applications so the first easy step was to separate new code and old code into 2 different applications that are called based on path criterias. Currently, old code is essentialy confined to /bin.

This enables us to let new code evolve more freely and make sure old code is handled properly and cleaned up after invocation.

My next step will be to complete removing pre-psgi remnants in the new code.

**Comment by ehuelsmann** [comment]
Collecting call sites and references here:

https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/contact.pm#L482
https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/order.pm#L155
https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/vouchers.pm#L121
*https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/vouchers.pm#L406
*https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/vouchers.pm#L434
*https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/vouchers.pm#L456
https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/transtemplate.pm#L35

Note that the three references marked with a '*' are already using fork() so, while bad form, aren't destabilizing the interpreter. I'm listing them here, because if we're going for a solution which allows complete separation of old and new code, those need to be addressed too.

**Comment by ehuelsmann** [comment]
With ```ab72e97``` integrated, this item is no longer blocking, but in dire need of an internal dispatch design which separates old code and new code.
Marking as such and deferring to 1.6.

**Comment by ehuelsmann** [comment]
Resolved through 1f9b77d457ac0d05592388a1728963f5ef308380
