### ISSUE TITLE
Javascript check missing on 1.4.28

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1507]
Code should check that JS can run properly on startup.
Current version report login failures instead.

**Comment by ehuelsmann** [comment]
Agreed, but I think we should implement this on 1.6: it's a major change to the login screen.

**Comment by ehuelsmann** [comment]
This has been resolved by an error indicating that Dojo (and JS) didn't load correctly -- in case they didn't; if I remember correctly, it's even backported to 1.5.
