### ISSUE TITLE
1.5 - AR Invoice - print to PDF broken

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1519]
On a db upgraded from 1.4:

AR -> Search
Click on an existing invoice
Select "PDF", "Screen", and click "Print"

Result:
![selection_152](https://cloud.githubusercontent.com/assets/46937/15272029/201aee0a-1a1b-11e6-8c77-8b1962e0e4ac.png)

**Comment by freelock** [comment]
Same error when attempting to print HTML... Customer is visible on invoice:
![selection_153](https://cloud.githubusercontent.com/assets/46937/15272037/5fe8570c-1a1b-11e6-8008-69bd0f5f0bea.png)

**Comment by ehuelsmann** [comment]
@freelock I can't see from the pictures, but are you using the dropdown function for selecting a counter party?

**Comment by freelock** [comment]
No, no dropdown -- have several hundred contacts, so it's a text box/search...
