### ISSUE TITLE
1.5 Reconciliation -- Can't change result order of transactions when doing a reconciliation

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1532]
Cash -> Reconciliation
Add a new reconciliation
Near the bottom, set "Order By" to "Post Date" and click "Update"

Result:
![selection_162](https://cloud.githubusercontent.com/assets/46937/15275621/65c153e4-1a85-11e6-8161-5412808c2581.png)

**Comment by freelock** [comment]
... this error happens even if I set the order back to the default "Source", and with any of the buttons.

**Comment by freelock** [comment]
All buttons on Reconciliation screen still broken...

![selection_205](https://cloud.githubusercontent.com/assets/46937/15640135/39904518-25e9-11e6-95a4-822f440a76ae.png)
![selection_206](https://cloud.githubusercontent.com/assets/46937/15640139/4ab622b8-25e9-11e6-9492-719feb687ab1.png)
![selection_207](https://cloud.githubusercontent.com/assets/46937/15640150/6b1b0b40-25e9-11e6-865e-8aa3fa0ba566.png)

**Comment by ehuelsmann** [comment]
Same workflow, different issue (caused by the 'file upload fix'); Fixing in this issue, because I see just bureaucracy in creating a new ticket.
