### ISSUE TITLE
1.5 - Cannot upload files

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1534]
Contacts -> Search
Open a contact
Click Files
Click "Attach to Credit Account"
Attempt to upload a file.

Result:
![selection_165](https://cloud.githubusercontent.com/assets/46937/15275717/23070d3e-1a88-11e6-851b-e6060da57df2.png)

**Comment by ehuelsmann** [comment]
This is  a problem that needs more time/thinking: our current form submission JS doesn't include 'file' support. That needs to be developed.

**Comment by ehuelsmann** [comment]
This requires forking dojox/form/Uploader, I think.
