### ISSUE TITLE
1.5 - cannot add contact info to a credit account

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1535]
Open a contact
On the "Contact info" tab, select "Credit account" in the "Attach To" drop-down
Add a description, and contact info, and click "Save Contact"

Result:
![selection_166](https://cloud.githubusercontent.com/assets/46937/15275730/9b27ca56-1a88-11e6-8cba-ad97480b1205.png)

**Comment by ehuelsmann** [comment]
1d6f780 fixes the issue, but returns an empty screen... I need to look into that, but we have enough to remove the 'blocking' flag from the issue, when we need to proceed.
