### ISSUE TITLE
1.5: Invoice parts drop-down contains overhead/labor

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1548]
While the parts drop-down should probably contain overhead/labor on the assembly page, the invoice, order and quotations pages should only allow selection of parts and services.

**Comment by einhverfr** [comment]
My thinking is to break ths into two different widgets, one for purchases and one for sales.

**Comment by ehuelsmann** [comment]
Agreed; although technically, I'd use the same widget with different configurations.

The current widget is on these 5 pages (from memory):
* invoice (sales + vendor)
* assembly + parts entry
* customer price matrix

The assembly one probably does need the overhead/labor parts in the drop-down for the BOM (bill-of-materials).

**Comment by einhverfr** [comment]
Also order entry.
