### ISSUE TITLE
Can't remove part from Sales Invoice, or make it zero

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1564]
Sales->Invoice
(Probly also for Purchase)
Add a part number with amount

Click the "x", page refreshes but item is still there with minimum amount of 1.

I think it's an error in this line:
bin/is.pl
1209 delete $form->{"partnumber_$form->{delete_line}"} if $form->{delete_line};

Is $form->{delete_line) really the part number? How does this work, really?

**Comment by craigwebster** [comment]
Issue is that description_ and partsgroup_ are also checked, so have to also be deleted along with partnumber_.

**Comment by ehuelsmann** [comment]
PR merged --> Fixed (closing)

This is a 1.4 problem only; no need to forward/backport: 1.5 uses a dojo-ized button for the same process.

**Comment by craigwebster** [comment]
This problem appears to still (or newly again) affect 1.4.34.

On demo: Do as above -- 

The "X", which is now inside the partnumber area, removes only the partnumber. Maybe this is a change, where it used to be that the "X" was only acted upon "Updated"?  Anyway, the line is now not removed.
