### ISSUE TITLE
Improve workflow for editing saved and/or posted transactions/invoices

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1577]
This is a major, nigh blocking problem.

Currently, "Void" buttons are mostly absent.

Without Void buttons, the only way to make any edits after clicking "Save", to reporting unit or account or date or amount or customer/vendor, etc., is to:

1) Save as New
2) Edit Inv. Number to be "$original - VOID"
3) Edit Amounts to be *= -1
3') If there are payments, manually enter them again with reversing amounts
4) Save/Post reversing transaction
5) Save as New again
6) Edit Inv. Number again
7) Edit Amounts again to be *= -1
7') If there are payments, manually enter them again with original amounts
8) Make edit originally intended.

This is completely onerous.  

Even with Void buttons, only the first half of the process is simplified -- esp. if payments are not included in the Voiding.

In my opinion, we need the following bugfixes/improvements:

~~A) Saved transactions not yet posted can be viewed in reports (perhaps with an editable flag at report-time)~~ (duplicate of #833)
~~B) Unposted/Saved transactions can be freely edited without constraint.~~ (duplicate of #975)
~~C) Create a flag that allows Void and Copy-as-new to include payments (very easy)~~ (duplicate of #2745)
~~D) Create a new all-in-one button that Voids a transaction (with Inv. # adding a -VOID), then copies the  original transaction to a new one (with Inv. # adding a /2 or some other revision notice), with both the reversing transaction and the new one copying payments (perhaps controlled by a flag)~~ (duplicate of #2307)
E) In my opinion, we should also add a system-level flag to allow editing of posted but unclosed transactions.

(Should I break these out into separate issues?)

**Comment by craigwebster** [comment]
Note: in improvement D, I actually think that the original transaction should have it's Inv # changed to be "$orig - VOIDED", the reversing transaction should have "$orig - VOIDING" and the new transaction should have "$orig" -- this clarifies by Inv. # the status of the transaction, minimizing confusion.

**Comment by einhverfr** [comment]
I think breaking these out into separate issues would be good and would allow better tracking of what gets done in which version.

**Comment by einhverfr** [comment]
I don't think we should change invoice numbers of posted transactions however.

**Comment by craigwebster** [comment]
Sorry, I've been focused on other things for a while, but this remains the #1 challenge interfering with day-to-day use of the system, and starting new companies on it.

I'll look and see if/how recent releases address any of this, and try to break out into pieces.

An alternativr to changing the original Inv. # is to create a "voided" flag, which is a DB change I suppose. I think it's important to be able to clearly know whether a transaction has been voided by another later one, just by looking at it. Doesn't need to affect data integrity in any way.  Could be a separate table that tracks voided transactions (though I generally don't like table bloat too much.)

**Comment by ehuelsmann** [comment]
Very much related to #1000.

**Comment by ehuelsmann** [comment]
I've edited the description to point issues separating out the items A through D. I'm not yet ready to accept E (especially when D is in place). Thereby, as all parts are separately tracked elsewhere, I think we can close this issue as concluded.
