### ISSUE TITLE
1.5 Parts selector does not populate unit, price

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1580]
The current parts selector populates the Description when used, but not unit or price.

After updating, unit (sometimes) appears to get populated, but not price.

**Comment by ehuelsmann** [comment]
Hmm. There's a bit of a problem here: I overlooked the fact that the price won't be looked up after the initial lookup of the part is entered in the UI on update (the current parts selector simulates that the page has been updated). However, the price to be assigned to the sellprice field is a function of three factors: the customer, the invoice date and the part. The data sent to the parts dropdown doesn't take the customer and invoice date into account, meaning that the store only has the generic sell price. Not good enough. Thinking of a better part selector or sell price indicator.

**Comment by ehuelsmann** [comment]
Now I remember: I didn't actually *intend* to have those parts of the item filled out. However, from the description, I do appreciate how this is very confusing.

**Comment by JigmeDatse** [comment]
I seem to (last look) be running into this.  I've been trying to figure out what a solution would be for me to work around this.  As I currently only have one service listed, and no other classes of "goods and services" it's not an issue.  In short order I expect that I will be adding a couple of "goods" which got purchased to help a with hopefully fixing the internet connection.  They haven't been put into use as of yet, but will hopefully be soon.  And I really should stock the parts in the database anyway.

**Comment by ehuelsmann** [comment]
In the current implementation, this behaviour is expected: it's possible to set the pricing per customer/vendor (price matrix). The functionality behind the current implementation doesn't query the price matrix; it queries just the part listing with the general price instead. By consequence, if we would fill the other properties, the price might be incorrect.

The solution in the current application is to hit the update button.

**Comment by einhverfr** [comment]
However there are some other bugs in this area, closing this and opening them.  Will reference this ticket.

**Comment by JigmeDatse** [comment]
It seems to be "working as expected".
