### ISSUE TITLE
1.5 data on sales invoice is lost when using the back button

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1582]
When entering data on a sales invoice (and likely other screens as well), if you add a customer and part, update, and then end up on any different screen, you cannot resume entering data where you left off.

If you end up on the "Item not found" screen and use the back button, you get taken to a screen before creating the sales invoice.

If you follow a link in the menu, you can back up to the "Create new sales invoice" screen but all fields are now blank.

Would be nice to capture field data  in the history so it may be restored when using the back button.

**Comment by JigmeDatse** [comment]
I was looking at the [new] customer link, and as it opens in a new tab, without the "main" menu or some key component of it, it doesn't end up working correctly.  It is a related, but similar problem.  I think that there are certain things we would like to be able to pop up the form (in some form) and be able to enter the data needed, without the need for supporting the "back" button functionality.  I'm not quite sure how well the back button really works for any system, unless content "partially entered" ends up getting stored either in cookies or sessions or maybe local data.

**Comment by einhverfr** [comment]
This was last supported in 1.4
