### ISSUE TITLE
Make "admin database" and "auth database" configurable

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1597]
Currently, the "auth" database (database name used setup.pl's authentication process) is hardcoded to 'postgres' and the database that LedgerSMB::Database.pm (could have moved to App::LedgerSMB::DBAdmin::Database) uses for some actions is hard-coded to 'template1'.

Both should be configurable in ledgersmb.conf

**Comment by einhverfr** [comment]
should standardize on postgres, this is a bug with App::LedgerSMB::DBAdmin

**Comment by ehuelsmann** [comment]
but a cluster that runs as me uses ehuelsmann as the admin database. I
think we should default to postgres, but not hard-code it.

**Comment by ehuelsmann** [comment]
Based on my last remark: Not an upstream issue, but something to build a config option for on our part.
