### ISSUE TITLE
1.5 - cannot edit contact method

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1609]
Contacts -> Search
Pull up an existing contact
Go to Contact Info tab
On an existing contact, click "Edit"

Result: Error
![selection_200](https://cloud.githubusercontent.com/assets/46937/15639571/2f20f0fc-25e2-11e6-84cb-ff55b8fda614.png)

**Comment by freelock** [comment]
Adding a new contact method works, but there is no feedback that it worked -- blank screen. The new contact method appears when you re-open the contact.

Adding a file to a credit account also errors out:

![selection_201](https://cloud.githubusercontent.com/assets/46937/15639604/b7d43c24-25e2-11e6-9867-164da839b7ae.png)

**Comment by freelock** [comment]
Same error occurs when editing an address.

**Comment by einhverfr** [comment]
Was duplicated by #1844 and fixed
