### ISSUE TITLE
Voucher screens clipped on left column

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1610]

**Comment by freelock** [comment]
(Premature save...) This is purely a CSS issue, part of the left-most characters are clipped, at least in Chrome. For example, Cash -> Vouchers -> Receipts:

![selection_202](https://cloud.githubusercontent.com/assets/46937/15639817/5568f464-25e5-11e6-93ed-5bf16f10eba9.png)

**Comment by ehuelsmann** [comment]
This probably is a rendering issue in Chrome: the problem disappears when you drag the vertical separator bar and put it back in the same location.  It seems to have to do with the scroll bar of the overflowing menu.

**Comment by ehuelsmann** [comment]
Not seeing this problem on 1.6 with either Chrome or Firefox. Closing.
