### ISSUE TITLE
1.5 - Cash Voucher screens cannot update

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1611]
This is on our primary workflow... cannot yet receive payments.

Cash -> Vouchers -> Receipts
Create batch, select account
Select one or more accounts to receive, some or all receipts.

Result:
![selection_203](https://cloud.githubusercontent.com/assets/46937/15639876/4f2f29e6-25e6-11e6-9302-d0de466da2ee.png)

Also in the logs:

Use of uninitialized value in pattern match (m//) at lib/LedgerSMB/DBObject/Payment.pm line 551.
Use of uninitialized value in string ne at lib/LedgerSMB/Scripts/payment.pm line 483.

**Comment by freelock** [comment]
Same issue on the Cash -> Vouchers -> Payments screen.

**Comment by ehuelsmann** [comment]
Almost done fixing this
