### ISSUE TITLE
Add Mountebank based tests

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1658]
Add tests using Mountebank to validate things like sending emails
refer to 
[Mountebank Homepage](http://www.mbtest.org/)
[ssmtp example (F#)](http://blog.nikosbaxevanis.com/2014/04/22/mountebank-mocks-with-fsharp/)
[Test::Mountebank](http://prepan.org/module/nY8EjAnEFbC)

Mountebank allows a remote protocol element to exist within a test infrastructure.
eg: 
- Test configures a Mountebank smtp Imposter
- Test tells LedgerSMB to send an invoice via email to the Imposter.
- Imposter Receives the email
- Test checks the Imposter for the email to arrive
- Test validates the email has expected contents

**Comment by ehuelsmann** [comment]
For mail, our docker-compose setup now uses MailHog. Roughly the same. No need to keep this open any longer.
