### ISSUE TITLE
Multiple Company Tax IDs

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1663]
Some countries have separated TAX IDs, depending on jurisdictions. For example, in Canada Federal and Provincial are separated and must be reported distinctly. Tax numbers must be shown on invoices too.

Currently, 1.5 only provides for a single Company Tax ID. We should provision for multiple IDs.

**Comment by ehuelsmann** [comment]
@ylavoie , our schema allows association of a tax ID per tax account. That should address this requirement, I think.
