### ISSUE TITLE
1.5:  upload templates via setup.pl broken

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1665]
Reported by Kaare in person:

Besides the issues in beta 6 of being able to load templates directly there is an issue where the bulk load by setup,pm fails.   To repro:

1.  Go to setup.pl, log in
2.  Select load templates
3.  Select demo
4.  Select Start Using LedgerSMB
5.  Log in and check, no templates available

Starman logs contain no issues other than uninitialized string warning.

**Comment by ehuelsmann** [comment]
\What you're seeing is general failure of the Document Templates functionality; it's not specific to templates uploaded through setup.pl -- instead, this screen *never* works (never has, afaik).

Yes, we'll want to fix that. (Just in case you were about to ask...)

**Comment by einhverfr** [comment]
Actually, it turns out that worked but the templates did not show up in the UI.  This has been fixed now.
