### ISSUE TITLE
1.3.x to 1.4.x DB upgrades being marked as version 1.4.0

### ISSUE THREAD

**Issue by jame** [ledgersmb/LedgerSMB#1671]
While testing the upgrade of the 1.3.47 Debian package to a preliminary version of the 1.4.29 package I thought I was then able to upgrade the 1.3.47 DB but instead ended up with the following when I tried the normal login:

> Error!
> 
> Database is not the expected version. Was 1.4.0, expected 1.4.29. Please re-run setup.pl against this database to correct.setup.pl at LedgerSMB/DBH.pm line 106.
> 
> dbversion: 1.4.29, company: testinc
> 

Going back to setup with the same company DB did result in then being able to log in normally to it.

**Comment by ehuelsmann** [comment]
Fixed when merging the branch to 1.4; however GitHub doesn't close issues not merged to the default branch.
