### ISSUE TITLE
bad defaults for "HR=>Employees=>Add Employee" screen

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1672]
using the "HR=>Employees=>Add Employee" screen to add a person.
I notice (considering the menu options used to get there) that the defaults (eg: class=vendor) are not rational.
Heck, it defaults to the "company" tab not the "person" tab, which feels weird

**Comment by ehuelsmann** [comment]
Hmm. Should we even allow a "Company" tab? Isn't an employee a person by definition?

**Comment by hasorli** [comment]
Yes.  What about: External hired consultant    
Person from a different company
In Norway a company has to report payments to some external consultants (depending on type of company the person is hired from).

**Comment by ehuelsmann** [comment]
Ah. But isn't that consultant a person too? (With a link to secondary company)?

**Comment by ehuelsmann** [comment]
This is as simple as changing the URL on the 'Add employee' menu item to `contact.pl?action=add&target_div=person_div&entity_class=3`
