### ISSUE TITLE
"HR=>Employees=>Add Employee" screen should have default employee number rather than empty field

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1674]

**Comment by ehuelsmann** [comment]
Actually, since we likely won't be the source system for employees (as we don't have sufficient wages & salary "tools"), it's more likely we should remove the employee number field instead: it's privacy sensitive information that doesn't have to be in our system.

**Comment by ehuelsmann** [comment]
Still agreeing with my comment from January.
