### ISSUE TITLE
Creating a user via setup.pl doesn't present an error if it fails

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1676]

**Comment by einhverfr** [comment]
Could you please present some information as to what sort of case you are seeing?  There really isn't much to go on here...

**Comment by einhverfr** [comment]
I checked..  The only error we trap is the duplicate user error, which suggests the db user already existed.  In this case we do provide a notice, set the import button, and allow you to try again.

This is there in order to allow you to have the same user on multiple companies.
