### ISSUE TITLE
creation of a user should be a single db transaction

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1682]
Currently it's possible to create a ghost user in the db.
If a creation fails for some reason, but the role is created you can't re-try the user creation as it fails with "Duplicate User"

Setting the "import" flag may be a work-around, depending if the role is correctly created

**Comment by einhverfr** [comment]
Can you please supply steps for how this happens?  Each page load is its own db transaction so I am not sure how the user would be created but the user record would not.

**Comment by einhverfr** [comment]
I think this is likely a misunderstanding -- if the user exists before we return you to the page with the ability to import the user, i.e. share the same user account(and password) across multiple dbs.

I checked and I cannot find any opportnity for this to happen in multiple transactions.
