### ISSUE TITLE
Emplyee termination (set end date) should also expire the password

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1684]
Rules
- the minimum of employee expiry date or password expiry date should be used to set password expiry at all times (both when changing the employee expiry date and the password etc)
- if using employee expiry date it should be that date + 1 day (assuming the employee expiry date is the last day of employment
- the password expiry date can **_never_** be set beyond the employee expiry date (+1 day)

**Comment by einhverfr** [comment]
I think this has a bit of a difficulty here.  One aspect to this is that the temporary password change by an admin would always allow the user to get back in.  A second problem is that I think we eventually want to be able to attach users to entity reccords that don't have an employee.  These could range from external contractors (vendors) to automated systems.  Tying the logic here to employee dates could have unexpected events.

Moreover what do you do if you have two dbs with a shared employee and you end the employment on one of those dbs?  Suddenly you have a case where the user is locked out but then gets an admin password reset for the other db, changes his password there, and suddenly can log into both again.

I don't see how at present we can safely do this as described.  One needs a different approach and I doubt that we can do this other than marking an employee for removal and then removing appropriate roles etc..  There are however some nasty corner cases even with that one.

**Comment by ehuelsmann** [comment]
The proposal does not work, because the password and account may be in use for other databases, which may not need to be blocked.
