### ISSUE TITLE
Add Management of statutary withholding for Vendor Invoices

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1690]
In Australia, and possibly other countries it is mandatory to withhold (currently) 47% of the value of a vendor invoice for tax if the Vendor Invoice does not display a valid ABN number (Australian Business Number)

The ABN is essentially a business's tax Identification number issued by the government

Other accounting systems will prompt the person entering the invoice about this withholding if the vendor doesn't have an ABN configured.
If the user selects "withhold" then a tax amount is added (as a reduction of the amount payable) to the invoice and posted in an appropriate account .

Now that we have a good dojo infrastructure we should be able to handle the UI portion of this fairly easily.
It probably requires a company wide config option "Mandatory Tax Number/SSN"

**Comment by ehuelsmann** [comment]
With workflows on the server, this could be an AU specific step in the workflow ("check withholding required").

**Comment by ehuelsmann** [comment]
@sbts, @tonka128, this behaviour - although not with the question as described above - can be implemented in 1.10using custom tax modules

**Comment by ehuelsmann** [comment]
Since the required functionality can be added with a custom tax module, I think this issue classifies as "implemented"/"available" or whatever classification that can consider it to be sufficiently done.
