### ISSUE TITLE
COA "Import Chart" feature needs improvements

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1691]
General Journal => Import Chart
- The file picker should have a default filter of *.csv set as we can only upload csv files here.
- Reference field needs some explanation. at a minimum as a tooltip 
- Description field needs some explanation. at a minimum as a tooltip
  Is it really a Description, or a Comment?
- Transaction Date field should probably default to today's date
- "Save" button should probably be renamed to either "Import" or "Upload"

**Comment by ehuelsmann** [comment]
@sbts can I ask why you specifically took this page to file a ticket on? I'm thinking it's a good idea to submit changes for these things, but if we are going to file tickets for each screen that needs it, currently we should add *every* screen in the system...

Now, if there was *just one* screen... Then, yes, **that** should be a ticket.
