### ISSUE TITLE
Need to translate password_expires for preferences.html

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1699]
This is a generated string straight out of the DB and can't trivially be translated within the templates.
We either need to get Postgres to supply it pretranslated, or 
pass the string into the template as multiple elements,
hours, days, months, years. (just containing numbers) then have a fixed string that shows

> expire in $years years and $months months  and $days days

This is non trivial, as the string may contain varying contents depending on locale settings etc

**Comment by ehuelsmann** [comment]
Maybe we can parse the 'interval' database type into a DateTime::Interval class and use that to generate the numbers to be inserted into the translatable string (days, weeks, months, hours, seconds)?
