### ISSUE TITLE
Period closing before the first transaction doesn't close the period

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1704]
What happens is:

There are no transactions to consolidate into the account_checkpoint table, meaning no entries show up and thereby the closed-period trigger finds an empty "max()", which in turn makes the trigger believe the period hasn't been closed.

**Comment by ehuelsmann** [comment]
Discussed with Chris: make sure there's at least 1 record in account_checkpoint for the given date; this could be done by inserting a record with a balance total of 0.00 (zero).

**Comment by einhverfr** [comment]
This is specific to when books are just closed, not where the the end of year is run, correct?

**Comment by ehuelsmann** [comment]
Correct
