### ISSUE TITLE
COA load tests should fail on coa/chart/au/General-00000.sql, but don't

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1709]
The headings have 5 digits, but are being referenced by 3-digit numbers in the account save statements (e.g. the '120' in https://github.com/ledgersmb/LedgerSMB/blob/master/sql/coa/au/chart/General-00000.sql#L14 while the heading being saved one line above is '12000')

**Comment by einhverfr** [comment]
There is nothing wrong here with the tests.  When we tighten up the logic, they will fail.  So I am closing this currently.  The current behavior is as expected though probably not as desired.
