### ISSUE TITLE
au coa General-00000.sql headings references incorrect, shows need to tighten heading logic

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1710]
Please fix #1709 before this one, because we should have a failing test for that case as long as this one isn't fixed.

https://github.com/ledgersmb/LedgerSMB/blob/master/sql/coa/au/chart/General-00000.sql#L14 references the heading as '120' which should be '12000', as saved in the line above.

**Comment by einhverfr** [comment]
Initial suspicion is that this is a question of not very tight integrity controls.  I think this needs to be subject to triage first, and then if it loads sanely, ten we need to reschedule this and the failing test for 1.6.  If it doesn't load then we have a different problem.

**Comment by einhverfr** [comment]
The actual problem is that we don't detect invalid requested items.  In that case we fall back to nearest heading.  Which is probably wrong, but would be a bad change to do in a stable branch.

**Comment by einhverfr** [comment]
And a note on the tests.

The tests ensure tat when you load a coa we provide, that you get a usable coa in your system.  In this case we actually do load it "correctly" even though we specify it incorrectly.

So the tests will fail when we tighten this up if we don't fix this issue first.

**Comment by ehuelsmann** [comment]
Assigning to me so it appears in my list of assigned issues across projects.

The solution here is to create a format which doesn't allow circular heading definition. I'm doing that now through an XML to be accompanied by an XSD which allows pre-verification before uploading (through xmllint).
