### ISSUE TITLE
extend database version checks to use a checksum

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1713]
add a checksum of the "db upgrade scripts" to be stored in the db when upgrades are applied.
We can then (at login) check that checksum against the current content of the upgrade scripts dir and raise an error if the two don't match.

We probably should only do the extra tests if .git/ exists or an override is enabled in ledgersmb.conf
we could additionally add some heuristics to run the extra tests once per day, or if the timestamp of the dir has changed. Although the last may not be worthwhile.

**Comment by einhverfr** [comment]
We store an sha hash of the upgrade script in a normalized format (comments and empty lines removed) for 1.5 and we simply re-apply if it changes, actually.
