### ISSUE TITLE
add "upgrade" target to makefile

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1714]
this target should do the following
- `git pull` (Assuming you have a clean master checked out) or a `git merge` and manual resolution
- `make dependencies` or `make cpan`
- tell the user to login to setup.pl and "upgrade" your database

It should probably start out with a simple block of text explaining what needs to be done, then prompt the user with "Would you like us to attempt to do this automatically"
before trying to auto apply the first two items.

It's possible to do the third item as well using `sql/modules/reload_modules.sh`
Although that will need to be extended as follows
- add `--user=` commandline argument
- if no `--user` is supplied fallback to old behaviour
- if `--user` is supplied get psql to ask for a password and use tcp transport to localhost

**Comment by einhverfr** [comment]
Pulling from master strikes me as dangerous since this is usually the tip of development. Upgrading from one tag to another would be safer, I would think.

**Comment by ehuelsmann** [comment]
We have a perfect system for having people on recent releases quite flawlessly: our Docker images. I don't think we should try to mimic something as controlled as Docker in our Makefile which will run on a large variety of systems meaning the task is **much** more complex than anything we need to support through Docker.
