### ISSUE TITLE
[new] link on Sales Invoice Page opens new tab, breaking calling of load_form on element id maindiv

### ISSUE THREAD

**Issue by JigmeDatse** [ledgersmb/LedgerSMB#1732]
When opening a sales invoice for a new customer (this was with an entirely new database) the [new] link beside the customer field opens a new tab.  This will break the "load_form" action on:

``registry.byId('maindiv').load_form(url, options);``

as `id maindiv` does not exist.

I also noticed that other links seem to open a new tab, I think the 'logout' does.  

I noticed this with pulling latest code in.

**Comment by einhverfr** [comment]
Wondering if we should remove the new link for now since it poses issues in a single page app.

**Comment by JigmeDatse** [comment]
It would be a quick answer, though I wonder if we can find a solution which allows it to work as it has been (or some other way which doesn't "harm" the existing information in the form).

**Comment by einhverfr** [comment]
actually as I think about it, this should be fairly easy to fix in place.  I expect to get to this tomorrow.

**Comment by einhverfr** [comment]
testing a fix
