### ISSUE TITLE
Submit to approval for reconciliation

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1739]
Should the flow pass directly from submit to approve when separation of roles isn't in effect?

**Comment by einhverfr** [comment]
yeah, probably good to check the setting and do it that way.

**Comment by ehuelsmann** [comment]
@ylavoie didn't you already change this?

**Comment by ehuelsmann** [comment]
I'm convinced this has been long realised. If it's not, please reopen and provide steps how to reproduce.
