### ISSUE TITLE
Password change widget needs to be rewritten as a full dojo widget

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1740]
This requires getting to know the following:

1.  Dojo 18n
2.  Full form widget designs
3.  Generalizing event handers

It would also likely serve as a basis for login widgets and the like.

**Comment by ehuelsmann** [comment]
Don't forget to implement feedback on failure and clearing the input form for improved UX.

**Comment by ehuelsmann** [comment]
there is a DojoX password widget which verifies that the original and the verify *new* passwords match.

Probably, this widget can be expanded to indicate "password strength" to the user too (which is probably helpful, with a dictionary lookup web service to prevent dictionary words as strong indication)

**Comment by einhverfr** [comment]
https://dojotoolkit.org/reference-guide/1.10/dojox/form/PasswordValidator.html is the link to the control.

But it is not quite a complete solution.  So will have to build one myself which should not be too hard.

**Comment by ehuelsmann** [comment]
Would be nice to include a password strength hint with it.

**Comment by einhverfr** [comment]
http://stackoverflow.com/questions/948172/password-strength-meter looks like nice code for this.

**Comment by einhverfr** [comment]
My thinking is a set of "rows" of:

1.  Form title ("Change Password")
2.  Feedback row (hidden by default)
3.  Old password (not validated until sent!)
4.  New password field
5.  Password strength
6.  Verification field
7.  Change password button.

For i18n purposes, thinking of having this as a template on the server, pre-processed via TT for now.

**Comment by einhverfr** [comment]
without this rewrite, we suddenly have the regression that you have to supply a password to change preferences (again)

**Comment by ehuelsmann** [comment]
Rewriting the page to use CSS table layout with divs instead of real
tables, works.

**Comment by ehuelsmann** [comment]
Well, except that the headings which used to be in a colspan TH, are now
restricted to the first column... and that seems to be a conscious
limitation to CSS table layouts.

**Comment by einhverfr** [comment]
Erik, I think Dojo will rewrite the divs into a table. which will make sure the labels and inputs go together, but I have resizing support already in the lsmb/TabularForm widget so.....

**Comment by ehuelsmann** [comment]
The thing that I have now doesn't use TabularForm. We could solve the
entire "problem" by making the password reset and the settings into
separate tables each surrounded by a FORM tag. However, when we do that,
the layout of the two sections on the page isn't aligned any more. That's
why I'm going to lengths to come up with different solutions to create
something which "looks like a single table", but can have separate form
tags in it...

**Comment by einhverfr** [comment]
the simple solution would be to add a menu item and move it to a separate page :-D

**Comment by ehuelsmann** [comment]
Works for me...

**Comment by einhverfr** [comment]
Expect to work on this one tonight and tomorrow.

**Comment by einhverfr** [comment]
working on this now.  There is a fairly serious workflow regression here in that in the past at least in theory you were supposed to be able to change your password independent of your settings while now this doesn't work so well.  It is for that reason I think this is release-blocking (also this is a common thing people do).
