### ISSUE TITLE
Shipping report

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1748]
https://sourceforge.net/p/ledger-smb/feature-requests/68/
A report of shipping/receiving activity would be very
helpful. Not sure what is required to make this happen
though.

**Comment by ehuelsmann** [comment]
@einhverfr , could you -with the link being dead - help with what would be required to complete this request?

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
