### ISSUE TITLE
Complete drop shipping solution

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1755]
Previous discussion at https://sourceforge.net/p/ledger-smb/feature-requests/214/

and 

https://sourceforge.net/p/ledger-smb/feature-requests/256/

Basically we need to be able to be able to invoice party A and ship to party B

**Comment by ehuelsmann** [comment]
Invoicing is one aspect. Another has to do with shipping addresses.

I can imagine that packlists are also part of this, requiring white labelling or even rebranding.

**Comment by ehuelsmann** [comment]
@einhverfr is this just niceness, or do you know of anybody with a direct need?
