### ISSUE TITLE
arrayrefs preventing recon approval

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1762]
@ylavoie notified of this:

We still have issues with arrayrefs. They are preventing reconciliation approvals at https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/DBObject/Reconciliation.pm#L165

**Comment by ehuelsmann** [comment]
@einhverfr the that's being referred to used to be a `call_dbmethod`, with an arrayref arg. It's not supported and - afaics - that will never be supported, because: how are we going to map those values to actual argument-overrides?

**Comment by ehuelsmann** [comment]
Hmm. I think the `call_procedure` that's there now, means that this issue is basically resolved. @ylavoie is that true?

**Comment by einhverfr** [comment]
I intend to triage tonight as well.

**Comment by einhverfr** [comment]
Triage indicates this is no longer a problem.  However there is another far more minor issue so closing this and opening a new one with current problems.
