### ISSUE TITLE
MC: 'amount' parameter in payment_post paradigm change

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1771]
We need to adapt the Perl code calling the `payment_post()` SQL function on MC: the amount changed from being the functional currency to the transaction currency.

**Comment by nick-prater** [comment]
For both master and MC, in_amount appears to be in the transaction currency, so in that respect I say they work the same.

**Comment by ehuelsmann** [comment]
Then there's no remaining work in this issue. Thanks for the review!
