### ISSUE TITLE
Reconciliation screen goes blank in two places

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1773]
This is showing signs of a crash that is not being reported to us.

It happens at two points:

1  Submit a recon report.  Screen goes blank.  Checking the db and reports show that the report has been submitted
2.  Approve a recon report.  Screen goes blank.  Chekcking the db and reports shows that the report has been approved.

Either we aren't redirecting to a next step or we are dying after the transaction has been committed.

**Comment by ehuelsmann** [comment]
The problem is much simpler:
The response document simply misses a <body> opening tag, meaning that the regex doesn't match and the code simply breaks down when trying to set the page content based on the matched fragment.
