### ISSUE TITLE
Displayed variance wrong on reconciliation reports

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1775]
Variance should display the correct difference between ending and beginning balance.
It should either take our or their values into account but not both.

**Comment by einhverfr** [comment]
Variance I think is correct.

It displays the correct difference between our ending balance based on the reconciled set and the statement balance.

**Comment by einhverfr** [comment]
I.e. variance should be 0 when the reconciliation is correct.
