### ISSUE TITLE
GL Search not working

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1788]
The account list is empty and prevents all functionaly.

**Comment by einhverfr** [comment]
Triaging this one, trying a couple things before I conclude it doesn't work:

1.  clearing caches (Erik changed the account dropdown)  -- no effect
2.  Rebuilding db and dojo --  no effect.

Large number of warnings:

Use of uninitialized value $label in quotemeta at lib/LedgerSMB/Scripts/journal.pm line 47.

My guess is that the label parameter is not being passed in.  So I am looking into this

**Comment by einhverfr** [comment]
After troubleshooting with Erik, the issue is that you have to make sure you really clear your browser cache.  This will of course affect all of us.
