### ISSUE TITLE
Sales Invoices with Multiple Lines double prints all but last line item

### ISSUE THREAD

**Issue by JigmeDatse** [ledgersmb/LedgerSMB#1796]
When printing the invoice for a sales invoice, I get an error in printing with multiple line items.  

This is what the Sales Invoice looks like:

![multi-line invoice interface](https://cloud.githubusercontent.com/assets/66363/17012698/5197643a-4ece-11e6-8476-5d2f2a6d5808.png)

The result print as HTML looks like:

![multi-line invoice print](https://cloud.githubusercontent.com/assets/66363/17012704/672a1234-4ece-11e6-847a-2e1b406b6d4b.png)

The PDF also produces the same multiple prints.  

[invoice-6 (1).pdf](https://github.com/ledgersmb/LedgerSMB/files/375235/invoice-6.1.pdf)

Of note the HTML invoice is not providing an "item description".  I have modified my templates (in a different template directory) and I might have done something which is causing this.

**Comment by kaare** [comment]
I can add my experience. It's almost the same when I print a Sales Order (to HTML, I haven't gotten PDF to work yet), except I don't get duplicate lines, just the last one missing.

And the description is blank here too, with standard templates.

**Comment by ehuelsmann** [comment]
The missing descriptions visible in the screen shots have been fixed in 58bcfcfd290b8e878904a2a746969890f81bbc4e
