### ISSUE TITLE
1.5: Workflows with button-goes-to-next-screen badly interacts with back button

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1798]
Many workflows proceed to the next screen on a button-click (e.g. 'Email' on the invoice or 'List' on the business unit screen); because buttons don't add to history (because for "Update", "Save" and "Post" we don't want them to [and others?]), these workflows fail; i.e., there's no button on the screen to go back to the "previous" page.

**Comment by einhverfr** [comment]
We could add something to the fragment so they do add to the history?

**Comment by einhverfr** [comment]
maybe a counter?

**Comment by ehuelsmann** [comment]
the counter isn't the issue: we already use that trick with the links in the menu.
The issue is that instead of one class of buttons (which never add history), we suddenly have two classes: one with and one without impact on history. How do we find all buttons and especially: in which category does each one belong?
(Also, impact on history is different than what currently gets historized: links get added by clicking the link *causing the page load*. POSTs get added but can't trigger the page loading process. Also note that johb would like to save form state so the backbutton gets to restore state. in our context, these problems have not been solved yet..
