### ISSUE TITLE
1.5: Business units "Save" button lacks feedback

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1799]
When clicking "Save" on a business unit class on the Business Unit classes listing page, the only way to know that the data got saved is by looking at the developer panel seeing the request round-trip with a 200 OK response.
This all happens so quickly that there's no indication to the user that the change did indeed happen.

**Comment by JigmeDatse** [comment]
When saving a Project I am not getting them saved.  Maybe I am looking in the wrong place to see the response.  When I go to list, I don't see anything.

**Comment by einhverfr** [comment]
Prelimnary observation is that I cannot see the request being submitted from the web browser.

**Comment by einhverfr** [comment]
Nothing in console, nothing in network tab either after I clear it and try to save.

**Comment by einhverfr** [comment]
ok I have the lack of submission fixed but the parent list is not showing up, nor is there enough feedback.
