### ISSUE TITLE
Reporting units class listing unusable

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1800]
The buttons don't work.

We should replace buttons with links.

**Comment by ehuelsmann** [comment]
@einhverfr, just checked your repo and you seem to be missing my fix commit: https://github.com/ledgersmb/LedgerSMB/commit/245bbb67806956412eb10ae0bbf3b40cc2703387

With that commit, the class listing absolutely worked.

However, I think there's great ux improvement to be had from rewriting the screen.

**Comment by einhverfr** [comment]
Moving to get requests is fast.  getting that in now.

**Comment by einhverfr** [comment]
see #1803
