### ISSUE TITLE
Parts/Assembly  modifiers

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1808]
Needed for food service and configure to order systems

Previous discussion at https://sourceforge.net/p/ledger-smb/feature-requests/94/

Probably requires cogs to follow serial number in these cases too.

**Comment by ehuelsmann** [comment]
With the prior discussion missing, it's hard to understand what the requirements are here, let alone how to address them. Without that information, I'm afraid this isn't a specific enough ticket.
