### ISSUE TITLE
Add ability to upload logo for inclusion on invoices and other documents

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1816]
With all templates in the database and all parts images too, we are now missi g the ability to upload arbitrary images for inclusion in html and tex or ods templates, such as logos.

**Comment by einhverfr** [comment]
might not be cross-platform but wondering if there are fuse fs drivers that give you the ability to mount this sort of thing from a relational db

**Comment by einhverfr** [comment]
Moving to "minor" since this doesn't block other workflows, and we already have the code in place largely, so it is mostly a matter of expanding it slightly.  We can do this in a stable branch I think.
