### ISSUE TITLE
Update source start when printing checks

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1817]
Previous discussion at https://sourceforge.net/p/ledger-smb/feature-requests/195/

Should involve treating this as a setting and updating.

**Comment by ehuelsmann** [comment]
@einhverfr with the link to the original feature request now dead, can you provide an overview of what's involved in delivering this functionality? Preferably a workflow description of some kind.

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
