### ISSUE TITLE
Determine which tests should be required for local test runs (by end users)

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1823]
Currently to run a full local test run, one needs, in addition to our standard dependencies a fairly large number of other ones (Test::Dependencies, Cucumber, Phantom, etc).

We should look at how many of these we should skip when the dependency is not met.

This is fairly small in terms of work but I think needs a little discussion.

**Comment by einhverfr** [comment]
With my current setup and no additional installed dependencies, the following tests fail for me when perhaps we should be skipping them when users run `make test`

```
Test Summary Report
-------------------
t/01.2-deps.t             (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/65-phantom.t            (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/66-cucumber.t           (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/98-pod-coverage.t       (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
```

These are all caused by missing dependencies.

**Comment by einhverfr** [comment]
Proposal:  we set a DEV_TEST environment variable and skip integration, coding standard, and any potentially destructive test if not set.
```
test script                     | run by normal end user
======================================
01.1-critic.t                     No
01.2-deps.t                     No
01-html-checks.t             No
01-js-checks.t                 No
01-load.t                         Yes
01-sql-checks.t               No
02-number-handling.t     Yes
03-date-handling.t          Yes
04-template-handling.t    Yes
05-po-checks.t                No
10-form.t                         Yes
11-ledgersmb.t                Yes
12-sysconfig.t                  Yes
13-auth-parsing.t             Yes
14-report-axis.t                Yes
14-report-hierarchical.t    Yes
15-loadorder.t                  Yes
16-dbchange.t                 Yes
40-dbsetup.t                    On request
41-coaload.t                    On request
43-dbtest.t                       On request (production-safe)
44-templates.t                 On request
62-api.t                            On request (production-safe)
64-x12.t                           If deps installed
65-phantom.t                   No
65-sauce.t                       No
66-cucumber                   No
66-cucumber.t                 No
89-dropdb.t                     No change
97-pod.t                          No
98-pod-coverage.t          No
99-versioning.t                No
```

Any feedback?

**Comment by einhverfr** [comment]
ok I will implement based on that list then

**Comment by ehuelsmann** [comment]
The list looks right, yes. Also prevents needing the endless list of test
dependencies required for author tests. The dependencies are already in
cpanfile to support this idea.

Regards,

Erik

**Comment by ehuelsmann** [comment]
Seems there is a growing acceptance of the "author tests" directory 'xt'.
Should we move them there?

**Comment by einhverfr** [comment]
that would work.

**Comment by einhverfr** [comment]
Ok I am putting "simple" tests in t (those that should always run to unit test the program)
I am putting extended tests (author and db tests) in xt.  Reason being there are dependencies there, ad some of these tests are safe in production environment but some are not.
