### ISSUE TITLE
Support cpan toolchain

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1826]
The move to our hand-done cpanfile and Makefile has broken any use of the cpan toolchain for management.  While this has some advantages, it has some problems associated with it as well particularly when people transition from environments which have been set up with the cpan toolchains..

Recommend:

1.  move our makefile into a new location (we could include it then as a preamble or postamble)
2.  support cpanfile ->Makefile.PL toolchains.

A separate option would be to do as follows:

1.  Only support a cpanfile -> Build.PL toolchain.

**Comment by ehuelsmann** [comment]
You are aware that the ability to "make install" has been removed deliberately? It's one of the most-often encountered installation problems by our users to be mixing versions of the libraries.

Is that what you're referring to?

**Comment by einhverfr** [comment]
Per discussion, will close this and open two more narrower issues.
