### ISSUE TITLE
Man pages no longer generated from POD

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1829]
At some point we will certainly want these back.  It is hot terribly urgent at present.  But it would be nice to have a target which creates man pages and another one which installs them in the system man directories.  This was last supported in 1.4, though installing into the system man directories required a make install.

**Comment by einhverfr** [comment]
Since this affects 1.5, we should probably fix there, esp. since it is a part of the build process and therefore doesn't impact the rest of the system.

**Comment by ehuelsmann** [comment]
The man pages have been replaced by HTML-ized, browseable POD documentation: https://docs.ledgersmb.org/perl-api/1.5.14/
