### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1835]
https://sourceforge.net/p/ledger-smb/feature-requests/121/

In my view this would probably require a global catalog with a field that is inherited by every other searcheable table on the system.  That would require quite a bit of design.

Plus given the advancements currently going on in Pg FTS, we need think about this a lot more.

don't expect before 2.0

**Comment by ehuelsmann** [comment]
With the original link now dead, I have no idea what's being requested here...
