### ISSUE TITLE
Business units migration from SQL-Ledger 3.0

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1837]
Business units in the SQL-Ledger 3.0 migration are not enabled.

**Comment by ehuelsmann** [comment]
@ylavoie then the class needs to be set to 'active' if a non-zero number of elements is being migrated; setting to active should be done in the `business_unit_class` table.

**Comment by einhverfr** [comment]
bumping to rc2 for now, but will bump back if we get a pr.
