### ISSUE TITLE
Sales name for part, separate from part description

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1839]
Previous discussion at https://sourceforge.net/p/ledger-smb/feature-requests/167/

It would be nice to be able to show parts on a receipt by a sales description that is stored in the db

**Comment by hasorli** [comment]
My customer need this.  The "wholesale part description", is different from the "shop part description"
The "shop part description"  are exported to the customers cash registers.

**Comment by ehuelsmann** [comment]
@hasorli do you mean you need purchase and sales descriptions? Or counterparty specific descriptions? Or another variant?

**Comment by hasorli** [comment]
Try to answer:  which description would be used when?  and 
How does the software know which one to use if both are available?

The "wholesale part description",  is the current description field.  (No changes needed)
 
 "shop part description" is the new field. Just a place to store a description that are used when the wholesale company export price information to the cash register. The "cash register" export should use the "shop part description".

**Comment by ehuelsmann** [comment]
@hasorli I'm wondering if this could be solved using the same functionality that kaare needs for his ingredients: if you were able to add custom characteristics to a part, you could add a "shop part description" characteristic. Would this solve your use-case?
