### ISSUE TITLE
cannot email sales order

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1845]
Kaare reported this to me in person.

Gets error "No such directory"
followed by a db error.

Hypothesis: db-template related.

**Comment by ehuelsmann** [comment]
@einhverfr I'm sorry, I can't reproduce. On my VM, I was able to mail a sales order (and a purchase order and both types of quotations) to myself on localhost. Both in HTML as well as in PDF format.

Maybe this is a PDF generation / LaTeX installation issue?

**Comment by einhverfr** [comment]
It was happening with html, but will do more digging tomorrow.....

**Comment by einhverfr** [comment]
Unable to reproduce as well  closing pending more info.

**Comment by einhverfr** [comment]
Apparently happens when the from email address is not set.
We should probably give a helpful error when that happens.

**Comment by einhverfr** [comment]
given the configuration fix, moving to rc2

**Comment by einhverfr** [comment]
removing blocking label for now
