### ISSUE TITLE
error adding contact info/address/bank account

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1846]
by email from Kaare to the list:

Btw, I created the email address for the customer from the Contact Info 
tab, selecting Email from the dropdown. When saving I get this nice screen:

---->
Error!

Attribute (class_id) is required at constructor 
LedgerSMB::Entity::Contact::new (defined at 
lib/LedgerSMB/Entity/Contact.pm line 214) line 46 
LedgerSMB::Entity::Contact::new('LedgerSMB::Entity::Contact', 
'HASH(0xa168320)') called at lib/LedgerSMB/Entity/Contact.pm line 166 
LedgerSMB::Entity::Contact::save('LedgerSMB::Entity::Contact=HASH(0xa161348)') 
called at lib/LedgerSMB/Scripts/contact.pm line 747 
LedgerSMB::Scripts::contact::save_contact('LedgerSMB=HASH(0x57f6348)') 
called at bin/lsmb-request.pl line 101 LedgerSMB::PSGI::try {...} at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Try/Tiny.pm 
line 81 eval {...} at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Try/Tiny.pm 
line 72 Try::Tiny::try('CODE(0x9661b58)', 
'Try::Tiny::Catch=REF(0x97c4b40)') called at bin/lsmb-request.pl line 
113 LedgerSMB::PSGI::call_script('contact.pl', 
'LedgerSMB=HASH(0x57f6348)', 'LedgerSMB::Locale::en=HASH(0x57fbd18)') 
called at bin/lsmb-request.pl line 136 require bin/lsmb-request.pl at 
lib/LedgerSMB/PSGI.pm line 105 LedgerSMB::PSGI::try {...} at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Try/Tiny.pm 
line 81 eval {...} at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Try/Tiny.pm 
line 72 Try::Tiny::try('CODE(0x920ebe0)', 
'Try::Tiny::Catch=REF(0x97c5980)') called at lib/LedgerSMB/PSGI.pm line 
113 LedgerSMB::PSGI::_run_new('contact.pl') called at 
lib/LedgerSMB/PSGI.pm line 88 LedgerSMB::PSGI::__ANON__ at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/CGI/Emulate/PSGI.pm 
line 30 CGI::Emulate::PSGI::__ANON__('HASH(0x57fcb58)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/App/URLMap.pm 
line 71 Plack::App::URLMap::call('Plack::App::URLMap=HASH(0x92c1fc0)', 
'HASH(0x57fcb58)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Component.pm 
line 50 Plack::Component::__ANON__('HASH(0x57fcb58)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Middleware/Conditional.pm 
line 16 
Plack::Middleware::Conditional::call('Plack::Middleware::Conditional=HASH(0x93b6c80)', 
'HASH(0x57fcb58)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Component.pm 
line 50 Plack::Component::__ANON__('HASH(0x57fcb58)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Util.pm 
line 142 eval {...} at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Util.pm 
line 142 Plack::Util::run_app('CODE(0x93b6c08)', 'HASH(0x57fcb58)') 
called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Starman/Server.pm 
line 279 
Starman::Server::process_request('Starman::Server=HASH(0x21f8690)', 
'Net::Server::Proto::TCP=GLOB(0x96617b0)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Net/Server.pm 
line 74 
Net::Server::run_client_connection('Starman::Server=HASH(0x21f8690)') 
called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Net/Server/PreFork.pm 
line 229 eval {...} at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Net/Server/PreFork.pm 
line 229 
Net::Server::PreFork::run_child('Starman::Server=HASH(0x21f8690)') 
called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Net/Server/PreFork.pm 
line 187 
Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x21f8690)', 
5) called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Net/Server/PreFork.pm 
line 111 Net::Server::PreFork::loop('Starman::Server=HASH(0x21f8690)') 
called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Net/Server.pm 
line 60 Net::Server::run('Starman::Server=HASH(0x21f8690)', 'port', 
'ARRAY(0x95128d8)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 
'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 
'max_servers', 5, 'max_requests', 1000, 'user', 1000, 'group', '1000 
1000', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1) 
called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Starman/Server.pm 
line 87 Starman::Server::run('Starman::Server=HASH(0x21f8690)', 
'CODE(0x93b6c08)', 'HASH(0x92c1900)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Handler/Starman.pm 
line 18 
Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x21a8fc8)', 
'CODE(0x93b6c08)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Loader.pm 
line 84 Plack::Loader::run('Plack::Loader=HASH(0x2104840)', 
'Plack::Handler::Starman=HASH(0x21a8fc8)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Plack/Runner.pm 
line 277 Plack::Runner::run('Plack::Runner=HASH(0x20b3120)') called at 
/home/jasonic/perl5/perlbrew/perls/perl-5.20.0/bin/starman line 38

dbversion: 1.5.0-dev, company: jasonic
<----

but the email was saved. I noticed that I made a mistake and wanted to 
edit it, but was met with

**Comment by ehuelsmann** [comment]
@einhverfr This happens both for contact info and addresses: both SQL functions return an INT (the database entity created), while the consumer expects the entire record to be returned.

Can we have a write-up of what SQL/sproc API you were aiming at? It seems we're not very consistent, which makes coding to the api harder than necessary. (At the moment, I have to look up every call to a db method...)

**Comment by einhverfr** [comment]
it would be better to return the entire record.  Lets standardize on that.

**Comment by einhverfr** [comment]
if you want i can take a look at this tonight.

**Comment by einhverfr** [comment]
Not bite-sized but hope to have a fix for this tonight.
