### ISSUE TITLE
Not printing any lines on  sales order

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1847]
Reported by Kaare

using the templates from the xedemo directory

Steps:
1.  Create sales order
2.  Add lines
3.  Save
4.  Print

Lines omitted.

**Comment by einhverfr** [comment]
print settings were:
html, screen, Danish

**Comment by einhverfr** [comment]
confirmed fixed but line descriptions missing

**Comment by ehuelsmann** [comment]
When did you last load your templates?

All templates refer to item_description.${<loop counter>}, which is what I
think is the correct template variable...
