### ISSUE TITLE
Add COA upload from SQL snippet

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1851]
Currently during company creation you can load a COA by pointing at one of the chart/*.sql files
Once you have the company created you can also load additional chart entries from file, however this must be done from a CSV file instead.

This is not explained in the UI, and the file picker allows any file to be selected, not just csv files.

I'd propose that we add a preprocessor that devolves an sql file into the required CSV before trying to apply it.

We should 
- limit the mask for the file picker to only filetypes we are actually able to load.
- sanity check the file before attempting to load it.
- generate useful error messages if a load fails or a file is rejected
- generate a nice "success" message

**Comment by sbts** [comment]
I've tagged this bite-sized for 3 reasons.
- the immediate UX issue can be solved by fixing the file picker mask
- the preprocessor to devolve the sql should be fairly trivial to write
- once the first two items are resolved, The remaining feedback messages and sanitycheck should probably be moved to their own issues. I'm including them here for clarity and because they may be easy enough to implement on the spot while writing the preprocessor

**Comment by einhverfr** [comment]
"sanity check" sounds like "needs design" to me.

At any rate running arbitrary sql files against the db should, if anything, be limited to the db admin interface.  Otherwise you have sql injection by design.....

**Comment by ehuelsmann** [comment]
Taking a step back, I think I can see that the question is to have a single
definition format for COA data that we load during setup.pl and possibly
later after the application has been set up.

The standard CSV upload (with a single table in it) doesn't satisfy the
requirement, because we want to insert/update records in the `defaults` and
`tax` tables too. Maybe we can have a different format which addresses
these concerns yet prevents the 'insecure by default' concerns @einhverfr
is raising.

**Comment by sbts** [comment]
Yep, completely agree that direct SQL isn't a good thing. 
I also agree that the core issue is that we have differing formats for "initial creation" and "later upload"

instead of sanity check, I probably should have said "sanitize" ie: strip all sql that doesn't match expected patterns for setting up a COA

It would of course be significantly better to have a safe, unified format that allows import __AND__ export of COA with ease

**Comment by sbts** [comment]
The main focus of this issue was to improve the flexibility "right now" and leave it open for future improvement.
I personally ran afoul of using the normal UI to attempt to load SQL (simply didn't think about what I was doing at the time and there was no hint's at all from the UI. Coupled with completely silent failure), and others have recently as well.

**Comment by einhverfr** [comment]
As soon as you try to sanitize, you run into the fact that someone can fairly easily pass off malicious code inside a file which basic checks will fail to notice.  Again, a reason why loading an SQL file to the user interface should never be user-facing functionality (could be admin-facing).

DBA;s should be the ones who get to control what sql files are loaded.

However, iirc, you can already load sql in the database with https://github.com/ledgersmb/App-LedgerSMB-Admin-Web though that does not support 1.5 yet (and needs to).  I would like that project to become the web services backend for what is now in the setup.pm.

**Comment by ehuelsmann** [comment]
Consensus seems to be that it's a bad idea to allow SQL uploading. Closing.
