### ISSUE TITLE
1.5: Bank accounts not listed

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1853]
I can add bank accounts to the database, but they won't be listed.

The cause is that the `entity__list_bank_account()` sproc is called with a `NULL` argument for the `entity_id`. I'm not completely sure why; this problem is located in `PGObject::Util::DBMethod`. Installing a newer version of that dependency doesn't resolve the problem.

I was unable to resolve this problem, no matter the amount of tinkering with the arguments to either the `dbmethod` mapping declaration or the actual declared `list()` method call.

**Comment by einhverfr** [comment]
Found a typo in the docs!
