### ISSUE TITLE
switch to LaTeX::Encode for 1.6

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1855]
With the recent escaping issue, we now know how to fix these things for TeX::Encoe.

However the module is not well maintained, but we can maintain LaTeX::Encode so we should switch to that.

**Comment by ehuelsmann** [comment]
Does LaTeX::Encode have the same coverage as TeX::Encode? If so, I think switching will be easy.

**Comment by ehuelsmann** [comment]
TeX::Encode has a new maintainer (since the creation of this issue) and the referenced encoding bug was fixed within a day, so I don't think there's a need to make a switch.
