### ISSUE TITLE
Cannot print sales invoice

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1862]
Reported by Kaare in person:

Now printing sales invoice shows undefined subroutine order_links

**Comment by ehuelsmann** [comment]
Confirmed. Although I was sure to have tested it. I'll check it out.

**Comment by ehuelsmann** [comment]
It's a browser caching issue. On Chromium "Empty cache and hard reload"
fixes it.

**Comment by einhverfr** [comment]
closing pending feedback (thinking we need a solution to browser caching problems)

**Comment by ehuelsmann** [comment]
Yes, we do. There are multiple solutions: rails solves it by "building" assets, with sha hashes in the built assets and in the referring html. That solves any number of caching issues. The other option could be `Plack::Middleware::Etag` (?).

**Comment by ehuelsmann** [comment]
Although this is more of a problem when tracking a development branch than when running in production with upgrades every now and then: in that situation files aren't changing all the time.

**Comment by einhverfr** [comment]
Right but I am worried about the amout of support we are going to have to do following upgrades :-P

**Comment by einhverfr** [comment]
Two problems here:

1.  Clear cache, update, print after converting sales order to invoice, it prints a sales order, not an invoice.
2.  Go to ar/search locate item, print.  Error.  Clearing cache does not resolve

**Comment by einhverfr** [comment]
In my testing, the type field is added for updates but not for prints.  This happens on multiple browsers, and clearing the cache has not proved effective.  Still need to figure out how this is happening.

**Comment by einhverfr** [comment]
The problem in this case was that in the system I could reproduce on, dojo had not been rebuilt.  On Kaare's system, dojo will not build.

Strongly recommend warning against using built dojo on development branches and adding cache protection of some sort.
