### ISSUE TITLE
bad VAT calculation when setting number format to 1.000,00 format

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1870]
Reported by Kaare.

This needs to be fixed asap, for rc1

**Comment by ehuelsmann** [comment]
What's the exact problem? Is this strictly related to VAT?? (which seems highly unlikely...)

**Comment by einhverfr** [comment]
I will get him to demo the problem for me tomorrow :-)

**Comment by einhverfr** [comment]
(but it was reported over email today)

**Comment by kaare** [comment]
The problem is when setting the format to the Danish 1.000,00 , lsmb is using the thousands separator as a decimal point, leading to a VAT amount 1e3 times too big.

**Comment by kaare** [comment]
![lsmb-20160728](https://cloud.githubusercontent.com/assets/54674/17201633/86d1b688-5490-11e6-840b-576cbb68834c.png)

I'm sure Danish "SKAT" would be thrilled. Customers not so much.

**Comment by einhverfr** [comment]
Steps to reproduce:
1. Set your number format: 1000.00
2.  Create and save a sales order
3.  Set your number format 1.000,00
4.  View sales order

VAT 100x too big.

**Comment by ehuelsmann** [comment]
The problem is this:

When you set the format in the current session, the format doesn't change
until the page is reloaded.


Which means that the first and third action have no impact on the current
session.

**Comment by einhverfr** [comment]
Not sure that is it, since this is an issue solely with the VAT field on retrieving the invoice.  What is interesting here is that there are no numbers actually entered and no client-side checks going on.

I expect to dig into this immediately after the invoice printing issue and the ability to save addresses and contact info without errors.

**Comment by einhverfr** [comment]
Ok, I have dug into this and now know what the problem is:  the vat calculations don't properly differentiate between user input numbers and numbers from the database.  They pass that responsibility on to LedgerSMB::Form->round_amount() which assumes all numbers are in 1000.00 format.  I believe this is related somehow to the change to PGObject.

**Comment by einhverfr** [comment]
There may be other cases where this happens but I haven't found any.  Entering an invoice with 1.000,00 format results in correct item prices and subtotals but incorrect vat prices.

**Comment by einhverfr** [comment]
hmm more debugging shows that is not it.  Rounding is correct before taxes are generated but incorrect after.  Maybe an issue actually with the tax modules
