### ISSUE TITLE
No status div "last action" feedback on some workflows

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1879]
There are a number of workflows where a simple page - e.g. "Draft Posted" - is shown. Pages like these are missing the "status div" with "last action" user feedback.

In order to implement the user feedback that I'm thinking about, _all_ pages which save, post, or otherwise follow a page which allows to click on a button to cause document state transition, need this status div.

**Comment by einhverfr** [comment]
No objection to going through and adding this everywhere (though not holding my breath).

I think it should be a standard part of our dojo widgets as we move in that direction.

**Comment by ehuelsmann** [comment]
Agreed, but with that div we will be able to offer a simular experience
earlier

**Comment by ehuelsmann** [comment]
![88638367-6c373d80-d0e1-11ea-9599-c87ec25f0328](https://user-images.githubusercontent.com/2326559/102184914-83b86c80-3eb0-11eb-8fb5-4224d49b58c4.png)

**Comment by ehuelsmann** [comment]
Closed by #6657 .
