### ISSUE TITLE
Improve user feedback on saving, posting, etc of documents

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1881]
The type of feedback I'm thinking about is depicted in the screenshot below.

![screenshot from 2016-07-28 09 55 37](https://cloud.githubusercontent.com/assets/2326559/17205105/916970a4-54a9-11e6-8962-2e80933541e7.png)

The point here is that the invoice number is a link to the invoice. On some screens which present a clean form after posting (e.g. the GL/AR/AP _transactions_ this allows going back to the transaction just posted). This feedback will allow users to understand that the transaction is supposed to be saved/posted, even though they are looking at a clean data entry.

Same applies to invoices posted while a 'callback' URL is in place.

**Comment by ehuelsmann** [comment]
The idea is to have the div fade after 5seconds.

The HTML for the div shown above is:
```html
<div id="history" style="
    opacity: 0.95;
    left: 40%;
    position: absolute;
    display: block;
    float: right;
    margin-right: 20%;
    height: 5em;
    vertical-align: middle;
    text-align: center;
    width: 40%;
    background-color: limegreen;
    border-radius: 5px;
    /* margin-bottom: -5em; */
"><span style="
    height: 1em;
    /* vertical-align: middle; */
    display: block;
    padding-top: 2em;
             ">Posted invoice <a href="" style="color:black"><b>17</b>
 </a></span></div>
```

**Comment by einhverfr** [comment]
wondering if it would be easiest to think about discussing/implementing first in a dojo form or two and then see what can be done to port elsewhere.  (expect to have the password reset widget for rc2, so may be a good place to start)

**Comment by ehuelsmann** [comment]
We have this with the Toasts. All we need is a way to pop up the correct message instead of the standard ”Loaded...”
