### ISSUE TITLE
need a .po to dojo i18n converter.

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1902]
Currently we are passing in translated strings as parameters but this is not going to scale well.  We need something to be able to build dojo translation objects from our .po files for translation.

**Comment by einhverfr** [comment]
Purely technical, easily tested, wont break other things

**Comment by einhverfr** [comment]
And probably required for a lot of 1.6 work

**Comment by ehuelsmann** [comment]
In all honesty, I'm not sure which problem this issue wants to address: we're our translation is still in working order and we're now going for a 1.8 release coming summer. Surely moving some translation to the client side is an option. At the moment there's little benefit. I'm also not seeing a need in the immediate future. When there is a benefit, we'll create a new issue and add it to a specific theme/project.
