### ISSUE TITLE
Add possibility to globally enable/disable tooltips

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1904]
Tooltips are great for training purposes. There should be a way to turn them on or off for experimented users

**Comment by ehuelsmann** [comment]
Hmm. why do we want the tooltips to go away? I mean, they won't be in
anybody's way, will they?

**Comment by JigmeDatse** [comment]
I find at times that tooltips are distracting, or as you suggest "in the way".  I do like that they exist, but without some way of changing behaviour with them, they can be annoying enough to make working with a system really frustrating.

**Comment by einhverfr** [comment]
it is a good idea.  It allows us to have larger tooltips that might otherwise get in the way of reading what is on the screen.

**Comment by ehuelsmann** [comment]
As we currently don't *have* any tooltips, I really wonder what this is about...

**Comment by ylavoie** [comment]
But we do on payments and reconciliations

**Comment by sbts** [comment]
I'm going to reopen this as I agree, we do have some tooltips already, and the ability to disable them is important for usability, especially from a tablet/phone with a stylus where tooltips can completely break websites by consuming most of the screen.

**Comment by sbts** [comment]
Also, I think the mechanism to hide/show tooltips should have
- a system default
- a user setting
- a "per session" toggle icon somewhere easily found  on EVERY screen, so probably in either the header or footer of the screens.
- There should be 2 classes of tooltips,
  - Always Visible (eg: for the tooltip toggle button)
  - Hidable

**Comment by ehuelsmann** [comment]
I'm not sure why this is relevant as we only have 5 tooltips in our code base so far.
