### ISSUE TITLE
Use Absolute Path instead of Relative '.'

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1911]
From various discussions in a matrix room, and two PR's
[#ledgersmb-security](https://vector.im/develop/#/room/!fbDhnxnlASGdwPNIxG:matrix.org/$1469895146714623hTdDM:matrix.org)   (This room is invite only. Contact dcg_mx, John, ehuelsmann in [#ledgersmb](https://vector.im/develop/#/room/#ledgersmb:matrix.org) for access)
https://github.com/ledgersmb/LedgerSMB/pull/1905/files
https://github.com/ledgersmb/LedgerSMB/pull/1906/files

In July 2016 Debian (and presumably other distros) applied a security patch to Perl that broke code relying on modules being included from the implied current working directory.
To resolve this quickly we have added 
```perl
use '.';
```
to a number of files.

In the future rather than adding '.' as a relative path, can we explicitly add the Current Working Directory?

I'd propose something equivalent to this block of code (which as einhverfr pointed out won't work as you can't use variables in a `use` clause)

```perl
use Cwd 'abs_path';
use File::Basename;
my $dirname = abs_path(dirname(__FILE__));
use $dirname;
```
Or something similar

einhverfr
> I don't have a problem with a block of code similar to that. However there are a couple costs to think about:

> That block won't work as such. You can't really use variables with use because use is compile time. while your path operations are run-time
Working around 1 above means significant effort, a begin block, and is something far more brittle.
I guess the question is given that this is only going in the http request handlers, what would be gained by that complexity. I do agree it would not be a great idea to put in command line tools but then you would not run a command line tool in that way from just anywhere, so presumably we'd make findbin work (and for some reason on Debian it is not working so this is a workaround).

sbts
>Actually, that exact solution won't quite work if the file isn't in the TL dir of LedgerSMB, rather we would want to strip off the trailing portion of the path, so we end up with the correct parent.

einhverfr
> http://search.cpan.org/~nwclark/perl-5.8.7/lib/FindBin.pm has some docs for FindBin, but again, it is not working for Debian at present, so my guess is they broke something more significant.....

sbts
>Ok, thanks for the corrections and valid points.
As discussed with ehuelsmann it seems releasing with use '.'; is the first step, then we can consider going further down the track.

einhverfr
>After some further testing, it looks like FindBin actually works but lib->import() doesn't which is why we saw the breakage. I think for 1.4.32 we should replace the above with:
```perl
use FindBin;
use lib $FindBin::Bin;
```

**Comment by einhverfr** [comment]
After some more testing on debian it looks like FindBin still works but the use of import in a begin block for some reason is not.  Will get this changed for 1.4.32.

**Comment by einhverfr** [comment]
also apparently does not affect master
