### ISSUE TITLE
Remove access to global state of Sysconfig

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1914]
It should be possible to load LedgerSMB.pm, for example, without a config file.  The config file startup logic should be the responsibility of PSGI.pm since that handles initializatio generally.

**Comment by ehuelsmann** [comment]
Started working on this partly yesterday. See my PR.

**Comment by einhverfr** [comment]
Nice.  Bumping the tag target up since the immediate issues are solved and now we probably need some design.

**Comment by ehuelsmann** [comment]
Renaming issue to better reflect the remaining work.

**Comment by ehuelsmann** [comment]
#5029 removes variable accesses (replacing them with function calls), which I guess satisfies the conditions of removing direct access to global state...
