### ISSUE TITLE
1.4+1.5: 'Update' in the single payment screen resets payment amount back to 0

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1916]

**Comment by einhverfr** [comment]
This is the sort fo thing we'd want to backport a fix to 1.4 as well, I think (though if you want to come up with the fix, I am happy to backport)

**Comment by ehuelsmann** [comment]
ok. so, I've worked on this and after several attempts, I came to the conclusion which @ylavoie was trying to tell me (I think), which is: the format_amount() function in the template doesn't work.

Even more: In our source tree (within the scope of 'lib/LedgerSMB/Template*') I can't find any reference to that function. I'm thinking it doesn't exist.

**Comment by einhverfr** [comment]
format_amount() in a template needs an additional format parameter iirc.  it is not intended to be used for user info but for specific info aimed at clients, so you can print checks in a certain number format.

Yeah, don't use it in the templates unless you are *printing*

**Comment by einhverfr** [comment]
I think it might be added during the print checks work flow to the template....

**Comment by ehuelsmann** [comment]
oh. I mean UI template: `UI/payment/payment2.html`

**Comment by ehuelsmann** [comment]
16144d98fee seems to be the commit which fixes this. All we now need is verification and backport.

**Comment by einhverfr** [comment]
fix confirmed
