### ISSUE TITLE
1.5 Cash -> Vouchers -> Receipts totals not updated

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1928]
When receiving checks, in 1.4 you can select customers, do partial payments, and click update, and at the bottom the Grand Total updates to the total selected. Also the customers not selected for receipts get their invoice total set to zero on update.

In 1.5, the invoice total does get properly updated for partial payments. ThIs changes the grand total to the grand total of all the visible customer payments -- but because the unselected customer payments are all non-zero, this grand total is not accurate.

![selection_241](https://cloud.githubusercontent.com/assets/46937/17277859/864fdc16-5702-11e6-8d72-ef6a5b367b37.png)

This is not a showstopper.

**Comment by ehuelsmann** [comment]
Not entirely sure what fixed it, but I worked on the bulk payments screen for check printing and that fixed the subtotal too.
