### ISSUE TITLE
1.5 Transaction Approval -> Batch, no voucher details

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1929]
On 1.4, when you open an AR or AP batch in the transaction approval screen, you get description columns so you can tell which customer/vendor each voucher is for, and can thus individually delete a voucher easily.

On 1.5, this appears to be all there, but the description and name fields are blank so you cannot easily determine which voucher to delete.

**Comment by einhverfr** [comment]
description is there for me.  Just verified.  However there are some other problems I just solved.....
