### ISSUE TITLE
1.5 Contact screens -- cannot attach file to entity or ECA

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1930]
When you attempt to attach a file to an entity or ECA on the contact management screen, you get these errors:

![selection_237](https://cloud.githubusercontent.com/assets/46937/17277959/8f85ba42-5704-11e6-9391-b6d9b0ac1828.png)

![selection_238](https://cloud.githubusercontent.com/assets/46937/17277960/92e8f870-5704-11e6-9435-c4753fbc2cb4.png)

When you attempt to download a file previously attached to an ECA, you get this error:
![selection_239](https://cloud.githubusercontent.com/assets/46937/17277967/a5adaf50-5704-11e6-8cee-f2fccc397329.png)

**Comment by ehuelsmann** [comment]
I split out the downloading of the file to #1937

**Comment by ehuelsmann** [comment]
Fixed through #1950
