### ISSUE TITLE
Add template tarball download

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1931]

**Comment by einhverfr** [comment]
tarball download via our release process?  Something else?

**Comment by ehuelsmann** [comment]
Insufficiently specified since Aug 1, 2016. Closing.

**Comment by sbts** [comment]
Sorry for the lack of detail I didnt realise it wasn't self explanatory ;-)

As we now have all templates contained within the db it's difficult for an administrator to get an on-disk copy of all the templates to either transfer to another db or edit (our built in editor is unfortunately junk and will eventually need to be replaced)

The idea is to provide a means of downloading a tarball containing all templates to facilitate the above.

Even better ifnthe templates can be reloaded from tarball as well rather than per file

**Comment by ehuelsmann** [comment]
Now that we already depend on `Archive::Zip` for downloading of multiple PDFs at once, this probably isn't too difficult to implement anymore.
