### ISSUE TITLE
1.5 Template editing -> cannot retrieve existing template

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1932]
Template editing appears to show existing templates, and allow uploading new ones. There is a button to edit a template, and that pulls up a blank editor with a "retrieve" screen.

However, clicking Retrieve generates this error:
![selection_242](https://cloud.githubusercontent.com/assets/46937/17278072/20e7ac7c-5708-11e6-80d3-af8fc255c9d7.png)

**Comment by einhverfr** [comment]
There are two obvious issues:

1.  What is that button supposed to do anyway?  I say we remove it.
2.  The parameters are not being passed in properly to the form.

**Comment by einhverfr** [comment]
(the filename.extension is showing up as "." instead, say, "index.html")

**Comment by einhverfr** [comment]
heh, problem is that 'template' is a reserved word :-P
