### ISSUE TITLE
Feature request: Make logo (and other images) available to templates

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1934]
From https://vector.im/develop/#/room/!qyoLumPqusaXqFJNyK:matrix.org/$14699851611738zqvmo:matrix.freelock.com

... provide the ability to have a "company logo" available to insert into invoice/other templates. Possibly a mechanism/practice for loading images from products, personnel, arbitrary image asset library in template system?

**Comment by einhverfr** [comment]
duplicate of #1816
