### ISSUE TITLE
1.5 Cannot print checks

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1935]
We use the multi-payment screen from Cash -> Vouchers -> Payments to print checks in 1.4.

This screen in 1.4 allows you to select invoices to print, include partial payments, select the check template, and print to screen or a configured printer.

In 1.5 the only actions on this screen are Update and Post.

This is also be affected by #1929 (and more of a problem here, because it's very useful to see the total being paid when printing the checks).

**Comment by ehuelsmann** [comment]
While #1957 fixes all issues mentioned here, it doesn't fix cheque printing, so not closing yet. The remaining error is:

`No DB handle provided at /home/ehuelsmann/LedgerSMB/tools/../lib/LedgerSMB/Scripts/payment.pm line 452.`

I've asked @einhverfr to have a look at that as I think he'll be quick to diagnose.
