### ISSUE TITLE
1.5 regression: Voucher Receipts cannot receive payments on invoices migrated from 1.4

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1936]
My initial tests succeeded when I created an invoice and used the bulk receipts screen to receive payment on it.

However, when I attempted to receive payment on a sales invoice migrated from 1.4, it failed with this error:
![selection_243](https://cloud.githubusercontent.com/assets/46937/17278246/577edc38-570d-11e6-9d8f-d818a3de73a5.png)

**Comment by freelock** [comment]
... this happened on the final screen in the process:

Cash -> Vouchers -> Receipts, create batch
Select account for receipts, next
Select customer to receive payment for, enter a source, click update and then save
Review summary, and click Post. Error appears.

**Comment by freelock** [comment]
Hmm. This is not consistent -- many transactions can be successfully received.

Not really identifying a pattern on what triggers it.

The first one that failed was for an account that has an "on hold" invoice.

Then I received several invoices without issue, until I reached an account that had two payments on a single invoice. In 1.4, I generally post these to the same batch -- enter a partial payment with the source id, save and post that, then immediately apply the remaining balance on the invoice with the second source id.

When I did this in 1.5, the first payment applied/posted successfully, but the second generated the same error as before.

I tried posting the batch and creating a new batch to receive the remainder, and this failed, even after approving the previous batch.

I tried receiving payments on other customers who have invoices on hold, and these all failed.

I then tried receiving more payments on regular invoices with nothing unusual, and some (but not all) of these failed as well.

**Comment by freelock** [comment]
After updating to master from yesterday, payments can sometimes be received that failed before. It seems to fail more often if a customer is selected with "All" outstanding invoices to be paid -- if you then click "Some" and attempt again, the payment sometimes posts successfully.

**Comment by einhverfr** [comment]
I don't think anything material in this corner changed that I know of that would cause this to be different between migrated and new invoices.  My first thought is that if "some" works, we must be missing invoice ID's when we go back to post.  This will be a fun one to track down

**Comment by einhverfr** [comment]
ok so some initial observations.

The NULL value it is complaining about is passed in as the array and comes from the first invoice in the list (by ECA).  Maybe we have a bug in display_payments?

**Comment by einhverfr** [comment]
Current review is that payment_get_all_contact_invoices can never return a null value for the invoice id.  So the problem has to be in passing it back.

**Comment by einhverfr** [comment]
I am reviewing the code and I cannot see anything that could possibly caus this.  We've had several major fixes in this area in the last week or so.  Could you try updating and see if the problem persists?

If it does ;et's see if we can see why the first id is not being passed back.

**Comment by einhverfr** [comment]
I cannot reproduce

**Comment by einhverfr** [comment]
Confirmed working
