### ISSUE TITLE
1.5: Can't download file attached to <anything>

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1937]
The error shows "Invalid server response: document contains no BODY tag"; which is probably not just restricted to the Entity/ECA screens.

The issue is that the form handler tries to load the content into the `#maindiv` instead of actually downloading it.

## Proposed solution

We need to special-case the downloads, just as we do for the printed documents with the "Print" button. One way to special case links in the new system is to provide an explicit `target` attribute on the A tag.

**Comment by ehuelsmann** [comment]
Just found that attachments to transactions don't work either.

**Comment by kaare** [comment]
I can confirm that this error exists for attachments to parts.
