### ISSUE TITLE
Merge of #1899 causes problems loading existing invoices

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1954]
@einhverfr As of the merge of #1899, I can't load existing invoices anymore. I'm getting:

![screenshot from 2016-08-01 23 09 08](https://cloud.githubusercontent.com/assets/2326559/17309030/06a55ae0-583d-11e6-9b71-effe1b45a485.png)

Note that this is with the simple case of loading a single-line invoice (where the customer doesn't have customer-specific prices, but I think that doesn't matter).

The cause as I have been able to identify it, is that `$form->{rowcount}` is still `''` or `undef` during the loading of the invoice, which means that the `qtycache` in the form doesn't get initialized for the specific part -- not even set to `0`.

Now, my first reaction was to use `// 0`; however, when I do that, I ignore the fact that (as per my comment on the code in #1899) that will lead to incorrect calculation of the qty discount (calculation based on zero items) for invoices that should have qty discounts applied.

Is this a relatively easy fix? Or should we back out for the sake of stabilizing 1.5.0?

**Comment by einhverfr** [comment]
should be an easy fix.  assigning to me.

**Comment by einhverfr** [comment]
Actually as I think about this, it is a symptom of a much more serious and deep problem only exposed by my patch.

If price matrix calculations are being applied to invoices when they are loaded from the database, that is bad.  We need to make sure that doesnt happen.

**Comment by einhverfr** [comment]
Might be worth making sure that changes to price matrix don't chance invoice prices on saved invoices in 1.4 too......
