### ISSUE TITLE
Wrong link, and information in Outstanding A/R Report

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#1973]
AR, -> Reports -> Outstanding. There's a Date column, but it's empty. The Invoices column shows how many invoices are unpaid (I guess), but the link on that column points to just a number, relative to the root. E.g. https://<servername>/5 or https://<servername>/10.

**Comment by einhverfr** [comment]
This is the summary or detail report?  not sure we should have the date column on the summary report, but the link breakage does seem new.

The link is supposed to go to the supposed to go to the detail report

**Comment by einhverfr** [comment]
Wonder how many other report features are broken.
