### ISSUE TITLE
Add Transaction total doesn't include manual tax

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#1977]
In 1.5.0-rc1

Purchases->Add Transaction
Fill in an amount and description
Click Update - Tax fields display
Manually enter a tax amount (calculate automatically is unchecked)
Click Update
Total line does not incorporate tax amount

**Comment by ehuelsmann** [comment]
@nick-prater I'm torn here. From what I understood the SL way to be is that when the checkmark gets unchecked, the amount doesn't get included in the calculation (with it checked, it gets automatically calculated, yes).

Your version is different though.

I'm proposing the following: We *always* include the amount in the calculation, but when the checkmark gets unchecked, we pre-fill the amount with `0.00`. I think that works for everybody expecting the SL behaviour and works for your use-case too.

**Comment by ehuelsmann** [comment]
(by being torn, I mean that I think that recent 1.4 versions work the same way, actually)

**Comment by ehuelsmann** [comment]
Closing: talked through this with @nick-prater on IRC. The desired behaviour is available on a workflow which is slightly different than the one used by nick: Nick enters the customer/vendor *and* the first amount without an update in between.

When one uses an "Update" between selecting the counter party and filling in the transaction amounts, it works as desired.

**Comment by nick-prater** [comment]
Broken in current 1.5 branch from github.

I am unable to enter manual tax on a purchase transaction:

* Purchases->Add Transaction
* Select creditor, click Update
* Enter amount on first item line, click Update
* Enter manual tax amount, click Update
* Manual tax amount is ignored in total

Ticking the "calculate automatically" box automatically calculates tax and includes it in the total, but overrides any manually entered amount.
