### ISSUE TITLE
Add search for vendor/uncleared checks to be reversed

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1981]
previous discussion at https://sourceforge.net/p/ledger-smb/feature-requests/226/ [2019-01-02: unfortunately the link is dead now...]

Main use case:  most small business payment reversals will be errors of entry.

**Comment by ehuelsmann** [comment]
@einhverfr with the link being dead now, could you provide a bit more clarity on what's expected in terms of workflow?

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
