### ISSUE TITLE
The Canada authorities have obsoleted some GIFI codes; would be nice to be able to obsolete them too

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1987]
... and while we're at it, maybe we want to have a "date-versioned" assignment of accounts to gifi codes, so we can have a current and a previous assignment?

**Comment by ehuelsmann** [comment]
@ylavoie what would be involved in decommissioning old gifi codes?

**Comment by ylavoie** [comment]
From what I gathered from the Canadian authorities, GIFI codes may have a beginning date and an ending date. New entries can be used in the current fiscal year and after and expired codes cannot be used after the current fiscal year.
I'd say we need to keep them available after expiry but limit their usage to their validity period.

**Comment by ehuelsmann** [comment]
@ylavoie if gifi codes have begin- and end dates, that also means that their assignment to accounts have begin- and enddates. That now means that we have a lot of additional complexity to support. What about creating a new account and marking the current one - with its gifi code - obsolete? That doesn't require full temporal control over the association between accounts and gifi codes.

**Comment by ylavoie** [comment]
GIFI numbers change *maybe* once a year, for very few accounts. I think that this issue should have a very low priority. Changing the COA to allow for GIFI validity would surely be viewed by most users as a big problem in terms of continuity, documentation, training...

**Comment by ehuelsmann** [comment]
@ylavoie I'm not sure what your response means. I'm proposing one of two things happen as resolutions to this issue:

1. We simply state that people need to create a new account which they can then assign a new GIFI number. We decide this isn't a big issue because GIFI numbers don't change often.
2. We support different GIFI codes being assigned to a single account over time (with one "active" at any single point in time). This doesn't require new accounts, but does require a functionality like the tax percentages for tax accounts where each percentage has a specified validity period.

I was saying that we may need (2); which were you saying?
