### ISSUE TITLE
Proposal, move to CUBE() views for reports for 1.6, drop support for Pg 9.4 and lower

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1997]
PostgreSQL 9.5 supports a number of advanced analytics and our data structure has already been built to some extent to use them.

I suppose we define a number of VIEWs using CUBE on date and other criteria, so that we can push slicing the data (by project unit, customer/vendor, department, date, etc) into the database more easily.

**Comment by ehuelsmann** [comment]
Precision of numbers in a cube is said to be 64 bit (float). If that's thw xase, we'll loose quite a but of precision...

**Comment by einhverfr** [comment]
@ehuelsmann ok this gets confusing.  I really should have been more specific.

PostgreSQL has two things, confusingly called cube().

Spacial cubes store coordinates in 64-bit floats.

Analytic cubes use native aggregates and data types.  Think of them as glorified, multi-dimensional pivot tables.

**Comment by einhverfr** [comment]
In other words I mean https://www.postgresql.org/docs/devel/static/queries-table-expressions.html
not
https://www.postgresql.org/docs/9.5/static/cube.html

**Comment by einhverfr** [comment]
Great question though.  Hopefully avoids lots of other confusion :-)

**Comment by einhverfr** [comment]
Having a bit of time to work with analytic cubes in another setting, there is a significant tradeoff here.

On one hand cubes are very flexible and powerful.  On the other.....  cubing largish datasets  across more than a few dimensions explodes the working set rather badly so we;d have to think about that.

**Comment by einhverfr** [comment]
Postgresql only supports up to 12 dimensions on analytic cubes and if you do this, you get 5040 different combinations of grouping your data......

**Comment by ehuelsmann** [comment]
I'm not sure this solves a problem in our software to the extent that we really need to do this...
