### ISSUE TITLE
Error when selecting a customer AFTER trying to add an order item

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2004]
Order Entry -> Sales Order -> 

1. find a product and try to update, giving  "Error! 'Customer not on file! at bin/arap.pl line 151. '" in a new frame.
2. Type in part of a customer name and update. Now it's "'ERROR: current transaction is aborted, commands ignored until end of transaction block: SELECT * FROM "public"."sequence__list_by_key"(?) at /home/jasonic/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/PGObject.pm line 361. '"

**Comment by einhverfr** [comment]
We should probably mark that field required.  At least if we aren't going to support full listings anymore.

**Comment by ehuelsmann** [comment]
The error before the one reported in (2) extracted from my logs:

```plain
2016-08-06 22:43:23 CEST [19417-40] postgres@master LOG:  statement: 
                    SELECT * FROM pricematrix__for_customer('4', '2', '2016-08-0
6', '1', 'USD') 
                
2016-08-06 22:43:23 CEST [19417-41] postgres@master ERROR:  function pricematrix
__for_customer(unknown, unknown, unknown, unknown, unknown) does not exist at ch
aracter 28
2016-08-06 22:43:23 CEST [19417-42] postgres@master HINT:  No function matches t
he given name and argument types. You might need to add explicit type casts.
```

**Comment by ehuelsmann** [comment]
@kaare the error that's being reported isn't very clear, which I've resolved (as good as I can at this point) in my PR. However, the underlying error is that the database schema needs to be rebuilt after Chris's addition of quantity discounts to the price matrix.
I had the same problem in my local VM, but reloading the modules solved it.
