### ISSUE TITLE
Batch check printing contains incorrect amounts

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2027]
When using Cash -> Vouchers -> Payments, the amount printed on checks is incorrect.

Using the "Demo with images" templates, all check printing fails with:

```
<html>
<body><h2 class="error">Error!</h2> <p><b>file error - check_basek: not found</b></p>
<p>dbversion: 1.5.0-dev, company: freelockco</p>
</body>
</html>
```

Using the "Demo" templates, checks print successfully, and the stub part of the checks appear to be correct. However, the actual check part prints incorrect amounts, varying based on the outstanding amounts.

When paying "All" outstanding invoices, the amount is printed as "Zero....".

On a vendor with $500 outstanding, the check prints $5, when paying amounts $500, $50, or $5.

On a vendor with multiple outstanding invoices totalling $6692.56, the check printed as $6006.56.

Number format is set to 1000.00.

**Comment by einhverfr** [comment]
added the commit t the wrong branch but that first one addresses the missing template (evidently when the file extensions were stripped, a typo was introduced).

Could you provide a list of vendor amounts (don't need names, just invoice amounts) to use to reproduce?

**Comment by einhverfr** [comment]
I have reproduced this

**Comment by einhverfr** [comment]
the fix for the funny numbers is in, this time with test cases.  And this time the fix we have attempted once a decade is fixed correctly.

**Comment by einhverfr** [comment]
so down to one of three issues (trying to print "all" prints zero for the amount.
