### ISSUE TITLE
Join projection issue in Chart of Accounts data

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2030]
Reported by Kaare in person (so may have to go back for more info)

For the VAT account only (which has 4 entries in account_link), the amount reported on the chart of accounts report is 8x what it is in the trial balance.

No immediate understanding of why this is happening.  Other accounts have multiple account links.

**Comment by einhverfr** [comment]
Once we figure this out, we should verify vs 1.4 as well.

**Comment by ehuelsmann** [comment]
Just a thought: what if we remove the numbers so there is space to report
gifi and account category (maybe more, like contra?)
