### ISSUE TITLE
Add note and selection for bank accounts

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2038]
https://sourceforge.net/p/ledger-smb/feature-requests/245/

"If a customer/vendor has more than one bank accounts, it would be nice to be able to add a note for each records.
Example:
A company should have USD, EUR bank accounts. One can write the note for each accounts, which one is EUR and which one is USD and make one default.
Check the example screenshot (mockup)."

Significant further discussion on the SF ticket.

**Comment by ehuelsmann** [comment]
As of 2617ad18254dab983c4e3a0a977bd2ff0c4d70ae (over 7 years ago), remarks are available in the bank account UI. With the referenced SF issue lost, I'll have to conclude this is done.
