### ISSUE TITLE
Makefile Targets required to be implemented

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2065]
### The following targets should be implemented as soon as possible but before 1.5 is released
- add "clean" which should be a superset of "clean-installed-libs" and other targets
- There should be support for HG vs GIT vs foo for the few targets that use repo commands
  This support should not break
  - for an unknown or ambiguous VCS detection
  - if the user has already performed the required VCS commands before calling the make target
  - all external operations (eg: calls to git) should have their return codes checked and handled
    - `git status` has a return code of 128 if not a repo
    - `hg status` has a return code of 255 if not a repo
    - `svn status` has a return code of 0 and merely prints a warning if not a repo
    - `svn info` returns 1 if not a repo
- add a "VCS-Detection" include file

**NOTE**: SVN VCS works, but has some strange caveats and corner cases, and can pose some real problems when you get the wrong revision.
Based on this we should (if a target requiring VCS is invoked)....
- (for now) simply error out with a request that the user contact us at [matrix:#ledgersmb](https://vector.im/beta/#/room/#ledgersmb:matrix.org)
- for now, just have the error message detail the manual steps.
- provide a variable override to continue if SVN is detected
- have the override trigger a BIG WARNING that has to be acknowledged followed by a list of manuals steps that are required
### The following targets should be implemented as soon as possible but before 1.6 is released
- add "upgrade" target to makefile #1714
- add "clean-installed-libs" target
  NOTE: App/LedgerSMB is a legitimate spot for cpan-installed libraries to be
- Support for other distros should be added (at least for dependency listing and preferably installation)

**Comment by sbts** [comment]
@ehuelsmann says it would be nice if travis failed if make dojo fails

There are two ways we can do this, capture the build log and parse it for errors, or implement dojo version reporting "in app" and have some tests that run on startup to validate the dojo install

**Comment by ehuelsmann** [comment]
@sbts last modified in august, is this really `started` (as in: work in progress, with someone working on it)?

**Comment by sbts** [comment]
At the time it certainly was.
Right now nope, I haven't touched it in a while.
Give me a month to get setup in the new premises and we should discuss what we want from the makefile going forward considering we now have a solid option in docker and good packaging for Fabian.

**Comment by ehuelsmann** [comment]
I cleaned out a lot of out-dated content from the Makefile. I'm thinking this no longer fits the scope of the Makefile...
