### ISSUE TITLE
make dojo sometimes fails to find new/changed files to be rebuilt

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2067]
In fixing #2052, I had a lot of difficulty getting files to be rebuilt.

I had to:
1.  rm -rf UI/js
2.  rm ~/dojo_archive/*
3.  make dojo

**Comment by ehuelsmann** [comment]
Development annoyance we can address sometime during 1.5

**Comment by einhverfr** [comment]
I saw something that might have addressed this in a recent pr.  We should verify before we close the rc milestone.  Testing now.

**Comment by einhverfr** [comment]
verified fixed in recent pr by @ehuelsmann
