### ISSUE TITLE
when menu resizes, it overlays main div

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2076]
When the menu resizes, we should probably resize the main div as well

**Comment by ehuelsmann** [comment]
Not seeing this; in my system, the main div gets smaller when the menu gets wider...

**Comment by einhverfr** [comment]
I am still reproducing it, at least with the second resize.

Here is my repro case with the menu in English:

1.  Open up a form of some sort  Sales invoice works.
2.  Click Cash, menu and main div seem to resize
3.  Click Vouchers.  Menu resizes but main div does not seem to.

**Comment by ehuelsmann** [comment]
Fixed for 1.5.18, duplicates #3421.
