### ISSUE TITLE
Product printing

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2091]
Goods and Services -> Search
  Search something so there is a list
Push the [PDF] at the bottom of the page.

I get this error:
Error!

undef error - Can't use string ("") as an ARRAY ref while "strict refs" in use at /home/jasonic/ledgersmb/tools/../lib/LedgerSMB/Report.pm line 350.

dbversion: 1.5.0-dev, company: jasonic

**Comment by einhverfr** [comment]
wondering if this affects other listings to pdf as well.  I suspect this whole thing may require a separate fix (i.e. if not html, download in a new window or something).

**Comment by kaare** [comment]
I guess now is a good time to tell that the error was in a new window. And that CSV d/l on the same page works.

**Comment by ehuelsmann** [comment]
Thanks for confirming that. If the download wasn't in a different window
and the PDF *was* succesfully generated, then the error you'd see was
"Response is missing BODY tag" (or something alike mentioning the body tag).
