### ISSUE TITLE
Invoice unable to post

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2095]
This has been reported in another form in the past against 1.5 only.  However I can now reproduce so expect to have a resolution in today.

The following results in a db error:

1. I have a customer.  The customer has a sales account set.
2. I open an invoice
3.  Set the customer
4.  AR entry box goes blank
5.  When I try to save the invoice I get an error about null chart_id.

The following works :

1. Create a sales order
2. save
3. create an invoice from the sales order
4. save and post

**Comment by einhverfr** [comment]
Immediate proximal cause is removing the invoice_links from update().  However, this is not on 1.4 and the problem doesn't exist there.  So when you update, the select input for ar/ap goes away.  This is because something else apparently went away from 1.5 but having trouble identifying it (esp. with the whitespace cleanup).

Proposed solution: add API to form that builds a select box based on a link description and use that.

**Comment by ehuelsmann** [comment]
There is such an api. Searc for "GENERATE_selects"
