### ISSUE TITLE
1.5-rc2 Cannot create bank reconcilation

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2107]
Using 1.5-rc2

* Go to Cash->Reconciliation
* Select an Account
* Fill in Statement Balance and To Date
* Click Create New Report

Gives an error:
Not a HASH reference at /usr/share/perl5/PGObject.pm line 302.

**Comment by nick-prater** [comment]
I get the same error message trying to view an existing reconciliation.

**Comment by nick-prater** [comment]
I had PGObject 1.402.6 installed.
Upgrading to 1.402.9 fixes this problem.
Perhaps we need to enforce, or at least advise, a minimum version of PGObject?

**Comment by einhverfr** [comment]
will bump the required version
