### ISSUE TITLE
1.5-rc2 Add Transaction Creditor changes after Save

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2108]
- Purchases->Add Transaction
- Select creditor from middle of drop-down list
- Click Update
- Fill In Amount, Invoice Number, Invoice Date, Description
- Click Save
- Creditor now shows first entry in the drop-down, rather than the previously selected creditor

**Comment by nick-prater** [comment]
I have just tested 1.5 branch from github and confirmed problem still exists

**Comment by ehuelsmann** [comment]
The problem exists on master too.

Even more, after updating with accounts and numbers filled out , the drop down isn't showing. Instead, a generic text box with the name and number of the customer is presented.

Wondering if the best course of action here is to simply phase out old code much like we did with the parts selector. A change like that would be 1.5.1 scope though.

**Comment by ehuelsmann** [comment]
It looks like Dojo wants an OPTION tag to have `selected="selected"` instead of the - for general HTML acceptable - `selected` attribute without a value.
