### ISSUE TITLE
Cash Receipt doesn't work in 1.5

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2111]
Cash -> Receipt, find a customer. Btw, the list of customer names would reaally benefit from being left justified.

On the receipt page, enter a date, choose deposit, and accept the default payment for the one invoice the customer has.

Nothing happens on the page. On the plack server console, this is seen:
Use of uninitialized value $unhandled_overpayment in string at /home/jasonic/ledgersmb/tools/../lib/LedgerSMB/Scripts/payment.pm line 996.
Use of uninitialized value in concatenation (.) or string at /home/jasonic/ledgersmb/tools/../lib/LedgerSMB/Scripts/payment.pm line 1171.

**Comment by einhverfr** [comment]
what do you click?  Post?  Update?  Something else?

**Comment by kaare** [comment]
Post

**Comment by einhverfr** [comment]
Ok so on further review what happens here is that the number is displayed non-localized but localized on entry, so if your number format is 1.000,00 you get a number displayed like 1256.35, which then is parsed on return as 125635,00 which is too high, triggering the update instead.
