### ISSUE TITLE
Can't send aging reports

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2114]
A/R -> Reports -> Aging Report. Pick a customer, try to generate after having chosen PDF and Email.
Result: 'Invalid server response: document lacks BODY tag'

**Comment by ehuelsmann** [comment]
@einhverfr could this issue be related to https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/report_aging.pm#L128 ?

**Comment by einhverfr** [comment]
yeah, looks like nothing gets done in that case.

**Comment by ehuelsmann** [comment]
Ok. after talking to Chris, I'm pretty sure this is more than trivial effort. Moving this to 1.5.1.

**Comment by ehuelsmann** [comment]
Ok. Is there a specific "new code" way to deal with sending mail?

**Comment by einhverfr** [comment]
Same as the old code, the Mailer object.

**Comment by ehuelsmann** [comment]
@einhverfr actually, my point was not the mailing of the document, my point was providing the user with an interface to mail the document from, with a mail body/text to explain to the recipient what they are receiving.

**Comment by ehuelsmann** [comment]
This being a non-trivial amount of effort, I'm putting it in 1.6. When this happens, lets see how much effort (and how invasive) it is to backport to 1.5.

**Comment by ehuelsmann** [comment]
for reference, this is where mailing used to be handled in 1.3: https://github.com/ledgersmb/LedgerSMB/blob/1.3/bin/rp.pl#L1412

**Comment by ehuelsmann** [comment]
The code has shifted by a few lines: https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/report_aging.pm#L135
