### ISSUE TITLE
1.4 regression: Multi-payment receipts screen does not show accounts with balance < 0

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2115]
I'm struggling with what seems like a necessary use case, and am hitting at least 1 regression (and possibly something not implemented).

For a rental customer, we received a "last month" rent payment at the beginning, and issued a credit invoice for the last month service not delivered. We then put the credit invoice on hold and all went fine until now -- when we go to apply it. We've done this several times. However, this time around the credit note exceeds the final invoice, so we need to issue a refund check for the remainder.

Using Cash -> Vouchers -> Receipts, this customer does not show up at all (because the balance is less than 0). So I cannot apply part of the credit invoice to the final invoice (the way I can if the amounts match).

Using Cash -> Receipts, I can pull up the customer and the two invoices. However, it is not letting me change the amount in the credit invoice to match the final invoice, to do a partial payment -- it keeps resetting to the original amount.

What should happen:

Cash -> Receipts should allow editing the amount to be received on each invoice.

Cash -> Vouchers -> Receipts should show all customers and open invoices, and not hide customers with  balances < 0.

Then comes the next part of this:

How do I print a check, with the balance to refund? Not seeing any screens that allow this...

**Comment by freelock** [comment]
Splitting this issue into multiple issues... I've solved the immediate issue of printing a check (by adding a vendor account and AP transaction, and then doing a check print on the payment screen).

However, I cannot currently resolve the payment issue, because I cannot apply part of the original credit invoice to the open sales invoice.

On the Multi-payment screen, this is because the total balance is < 0, and so the account is hidden. This has been a problem for several releases (probably for the past 8 - 9 months, if not longer).

**Comment by freelock** [comment]
I just tested 1.5, and 1.5 works correctly -- this is only an issue in 1.4.

**Comment by ehuelsmann** [comment]
As this is a 1.4-only issue *and* 1.4 is EOL at this time, I'm going to close as WONTFIX.
