### ISSUE TITLE
1.4 regression: Cash -> Receipts cannot handle partial receipts

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2120]
Related to #2115 - this issue is for the single-payment receipt screen.

When a credit invoice is available in the Cash -> Receipts screen, you cannot apply a partial receipt. If you enter a partial amount in the row with the invoice, and click update, it resets to the original balance.

**Comment by ehuelsmann** [comment]
Closing "Works for me" in 1.4.41; tested in the demo installation with "abc Widget Company" which (today) has a series of invoices and a credit invoice. The described procedure doesn't reset and thus does what it should.
