### ISSUE TITLE
1.5 regression: Cannot open GL transaction

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2122]
On current 1.5:

![selection_272](https://cloud.githubusercontent.com/assets/46937/18226436/b05bebf4-71be-11e6-9081-efab9b684317.png)

... this happens when going to a report for an account and attempting to view/edit a GL transaction. AP transactions open up fine.

**Comment by ehuelsmann** [comment]
This is fixed on master through 3ed9db1 and on 1.5 through 7fdc251. Closing as soon as this lands on 1.5.

**Comment by ehuelsmann** [comment]
Merged into 1.5 now
