### ISSUE TITLE
Ability to remove timecards (or reverse)

### ISSUE THREAD

**Issue by JigmeDatse** [ledgersmb/LedgerSMB#2163]
Currently in 1.6 I am seeing no means to reverse, or edit a timecard.  

I have a couple of timecards which ended up getting entered incorrectly.  Issues I have run into are:

1) Incorrect project selected...
2) Failing to record correct time...

I think one thing which would keep me from doing this would be rather than only being able to save, that I could update (and presumably doing so confirms I haven't entered something in incorrectly in terms of the database), or save.

**Comment by ehuelsmann** [comment]
@JigmeDatse Hi, what if we don't add this feature? I mean, what goes wrong?
