### ISSUE TITLE
User name set to "logout" on login screen after a session timeout

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2206]
The session timeout shouldn't prevent the browser to remember user previous values if the user so desires.

**Comment by sbts** [comment]
Hmm, I'm not so sure here.
It's somewhat of a security risk to retain the username after a session timeout.
While I can see that it's annoying to have to re-enter the username, it is likely a better choice, especially for "non-local" systems.

I'd think we probably should canvas the userbase before making a change here.
Or at least make it configurable on a per user level with a company wide admin setting to enable the per user setting.

I think the defaults for both settings should remain as they currently are.

**Comment by ylavoie** [comment]
It should keep the current behaviour, which is allow the user to decide if the browser can keep login parameters and feed them back to the application, or set all parameters to empty, but I fail to see why "logout" should suddenly become the username.
My only say at this moment is make sure we do not impose "logout" as username as we do now.

**Comment by ehuelsmann** [comment]
While I can see your point about not setting the user name to 'Logout', I don't think we should stop resetting the user name, because it exposes the name of the last-logged-in user on less restricted computer environments.

**Comment by ehuelsmann** [comment]
By design and due to security...
