### ISSUE TITLE
Make tests use globally unique DB name

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2225]
Currently we use the same DB name for all tests run.
This can (and does) result in failures due to collisions if multiple tests runs are active against the same posgresql instance.

We need to implement a "per test instance" unique DB name.
This could be by
- appending a true UUID to the DBname
- appending a unixtime timestamp to the DBname

@ylavoie  has definitely had issues with this while porting pgTAP to MC and I've stumbled over it when running tests locally as well.

There is certainly potential for it to be a problem even within the travis infrastructure.

**Comment by ylavoie** [comment]
The database use must be unique by branch but should remain constant within a branch.
This allows reruns of some tests instead of the whole serie to speed up develoment.
Switching to another branch should use a different database to prevent conflicts.

**Comment by sbts** [comment]
When running on travis we can probably derive something from the travis build number, which nicely identifies the scope of a DB.

When running locally this becomes somewhat more difficult as we need to both uniquely identify the branch and the top level runner for that series of tests. (equivalent to the travis build number)

Failing to do this correctly for local tests with either
- still allow conflicts to occure
- prevent tests from being re-run without fully rebuilding the DB env

**Comment by ehuelsmann** [comment]
Testing infrastructure improvements can hardly be blocking, how much I'd like them to be "in".

**Comment by ehuelsmann** [comment]
Can happen any day; no real problem if not in 1.5.1 -- probably not backported to 1.5 at all.

**Comment by ehuelsmann** [comment]
actually, this has been realized recently in an attempt to run tests in parallel.
