### ISSUE TITLE
Missing links on SL 3.0 migration

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2242]
Accounts migrated from SL 3.0, and probably earlier, do not always get their link field transferred.
Links are optional for many accounts but failure to have them set on accounts where payments are made prevent those from showing up on paid invoices.

**Comment by ehuelsmann** [comment]
@ylavoie, is this still a problem? I don't understand the "do not always": it's either always or never, right? this is a single (and simple?) SQL statement implementing the migration...
