### ISSUE TITLE
CSV PNL report has columns out of order

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2244]
I did 3 periods, quarterly, with the date field set to 
first column in the csv is 2016-07-01, 2nd is 2015-10-01, 3rd is 2016-04-01, 4th is 2016-01-01
report on the web page makes sense, CSV does not...

**Comment by ehuelsmann** [comment]
this problem occurs with both CSV and PDF output for both PNL and Balance Sheet.
