### ISSUE TITLE
Missing chart of accounts

### ISSUE THREAD

**Issue by notorand-it** [ledgersmb/LedgerSMB#2245]
After having completed a fully successful installation from the Ubuntu PPA repo and having logged in as a "power user", the item General Journal-->Chart of Accounts gave an error:

Error!

Unable to open script: LedgerSMB::Scripts::journal : No such file or directory: Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /usr/share/ledgersmb /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/ledgersmb/LedgerSMB/REST_Format/json.pm line 23.
BEGIN failed--compilation aborted at /usr/share/ledgersmb/LedgerSMB/REST_Format/json.pm line 23. Compilation failed in require at /usr/share/ledgersmb/LedgerSMB/Scripts/journal.pm line 24. BEGIN failed--compilation aborted at /usr/share/ledgersmb/LedgerSMB/Scripts/journal.pm line 24. Compilation failed in require at (eval 423) line 1. 

I chose "it" as country code and "General" for the chart of accounts.
The web UI says "dbversion: 1.4.34-dev" but the version installed from the PPA is "1.4.33+ds-1~ubuntu16.04.1"

**Comment by ylavoie** [comment]
Seems that libjson-perl is missing. We have to put it in the requirements, meanwhile, apt install libjson-perl will fix it.

**Comment by notorand-it** [comment]
Yup! That worked, indeed.
I manually installed libjson-perl and now it works.
Thanks.

**Comment by ylavoie** [comment]
Let's keep it opened until we post a fixed version so others find the solution too.

**Comment by ehuelsmann** [comment]
1.4 is EOL now. So, closing.
