### ISSUE TITLE
Reconciliation report variance miscalculation

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2246]
There is a sign problem in the variance calculation on the reconciliation reports.
It is either 0 or twice the difference between debits and credits.

**Comment by ylavoie** [comment]
Aimed to be fixed by PR#2280

**Comment by ehuelsmann** [comment]
hasn't this been long fixed? @ylavoie @nick-prater

**Comment by nick-prater** [comment]
Confirmed fixed in 1.5, 1.6 and master.
