### ISSUE TITLE
Right panel url

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2247]
Right panel url shouldn't need the server prefix only the relative part when displaying a page from the menu.
Current implementation adds the prefix needlessly and doesn't work then the right pane url isn't ours.

**Comment by ylavoie** [comment]
For example, this:
`http://ubuntu-vm:5000/login.pl?action=login&company=lsmb_company#http://ubuntu-vm:5000/recon.pl?action=display_report&report_id=622#s2`
should be simplified to:
`http://ubuntu-vm:5000/login.pl?action=login&company=lsmb_company#/recon.pl?action=display_report&report_id=622#s2`

**Comment by ehuelsmann** [comment]
It looks ugly, agreed, but there is nothing wrong with that url... where is the problem case here?

**Comment by ylavoie** [comment]
Simplification and misleading. It suggests that a different address *could* be used.

**Comment by ehuelsmann** [comment]
This has been implemented at least for 1.6 (And possibly some later 1.5 versions)
