### ISSUE TITLE
Reconcilition routing

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2248]
Submitting a reconciliation report should route to approval when separation of duties is not in effect.

**Comment by ylavoie** [comment]
Hold until routing is implemented.

**Comment by ehuelsmann** [comment]
Enhancements don't need to be held as a PR :-) Also, they'll be addressed when the time is right; for this one, when routing is implemented.

**Comment by ehuelsmann** [comment]
@ylavoie could you detail what you mean by "routing needs to be implemented"? I'd like to assert what prerequisites need to be met in order for this item to complete.

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.

**Comment by ylavoie** [comment]
Submitting a reconciliation currently routes to approval.
If separation of duties if not in effect, the user who submitted them will be the approver so why imposing that route
