### ISSUE TITLE
Template caching doesn't support multiple running LedgerSMB instances

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2250]
Due to the fact that cached templates are by default stored in <temp_dir>/templates, the default configuration doesn't support running multiple instances of LedgerSMB on a single system, as you'd want to when upgrading from one version to another.

**Comment by sbts** [comment]
I'd propose that the starting point to resolve this would be to use a uuid suffix on the tempdir.
This does mean we end up with a fresh cache dir for every instance.
An alternative would be to require an instance name to be passed in as an env-var or in the config file.
In the event that the env-var isn't provided then we fallback to an autogenerated uuid

**Comment by ehuelsmann** [comment]
As a result of the temp dir handling cleanup done by @nick-prater, the templates are now stored in a temp dir which is cleaned up on exit (exept when explicitly configured differently )
