### ISSUE TITLE
Need dynamic update for  invoice price

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2269]
Currently  changing the quantity or price on an invoice lin requires you to either press enter or click on update.
Failing to do so doesn't show correct extended price or totals.

Now we have dojo we should be able to dynamically update these totals on cell exit

**Comment by sbts** [comment]
As per #ledgersmb discussion ehuehuelsmann says
> Changing quantity could have price matrix impact

Ok. So for changing qty we probably need to have a copy of the price matrix in the ui
Either that or we simply shadow the qty value and if it's changed on cell exit trigger an update

**Comment by ehuelsmann** [comment]
This is just one of the many requirements when redesigning the invoice screen. We'll cross that bridge when we get to it.
