### ISSUE TITLE
Losing Vendor/Customer on update and/or save (Starman issue?)

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#2276]
This intermittently occurs on my local Starman system, reloading Starman solves it.

Appears currently to be happening all the time on the 1.4.34 demo.

Eg:

AR->Add Trans

Put in Vendor, sometimes get error.

If able to get through this, then add amount, account, etc., then currently attempts to save always result in :
'Vendor missing! at /usr/local/lsmb1.4/tools/../bin/aa.pl line 1395
'

**Comment by ehuelsmann** [comment]
Not seeing this issue on demo today (on AR transactions). Closing.
