### ISSUE TITLE
Income Statement - "bad date" failure

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#2277]
On demo for 1.5:

Reports->Income Statement,

Enter "Years" for period type and any date, you get:

"
Error!

Bad date at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/PGDate.pm line 150.

dbversion: 1.5.0-dev, company: demo15
"

**Comment by ehuelsmann** [comment]
@ylavoie would be great if you could have a look at this one, please.
