### ISSUE TITLE
Not showing negative amounts in Voided transactions

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#2280]
Demo 1.5:

On posted Sales Invoice, click void, and post.

In GJ->Search, shows as balancing (ie. negative), however when looking at the transaction all values seem positive.

**Comment by ehuelsmann** [comment]
@einhverfr Is this by design? And if so, shouldn't there be a large sign about it being a reversal?

**Comment by ehuelsmann** [comment]
@einhverfr ping?

**Comment by ehuelsmann** [comment]
This is by design. I think the issue #4668 makes a better case: we need visual distinction. (Which can include negative numbers.)
