### ISSUE TITLE
Login returns auth fail when no db connection 

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2297]
Currently if the db connection fails we incorrectly return an auth fail to the client.
This is confirmed for setup.pl and likely for login.pl 

This results in much confusion if the db hasn't started for some reason as it appears to be a password fault instead

**Comment by ehuelsmann** [comment]
The reason it works this way is due to the limited number of available
error numbers in the HTTP status codes.

**Comment by sbts** [comment]
I'd propose we find a way to redirect to a more useful error page if the db can't be contacted. 
Perhaps this can be done __*before*__ displaying the login page instead.

**Comment by ehuelsmann** [comment]
hmm. in what sense is this issue blocking anything? Isn't it "just" an improvement?

**Comment by sbts** [comment]
ehuelsmann I felt it was blocking as "fixing" it after we release a 1.5 deb package into the debian distros means we will probably be stuck with it pretty much forever.
As it's a fairly trivial fix it probably should be in any official package.

**Comment by ehuelsmann** [comment]
Fair enough. I'm thinking we know Jane well enough to end up with a package that runs sanely.   But it will be fixed anyway.

**Comment by ehuelsmann** [comment]
Ok. I think we want to change the way errors are being reported to the user: we have the ability now to show Dojo dialogs. In the past we didn't use to show the content of the error return (because we only had the "alert()" call); I think we can switch to showing the content of the response in the dialog.

**Comment by ehuelsmann** [comment]
Noting here that we want to change the way our authentication works - completely. So, this request is likely to run out of relevance soonish. (I'm looking at changing the auth code to use the same method Graphile uses: setting the current user, instead of having each user be a login.)

**Comment by ehuelsmann** [comment]
There's no way to know that we can't connect due to the server being unavailable or due to password mismatch, as far as I know...
