### ISSUE TITLE
Product image view on invoice and order screens etc

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2305]
From #ledgersmb
Have we provisioned image view of product on order / invoice screens before?
I'm thinking small thumbnail to the right of the description / notes lines (spanning both lines) that is clickable for a larger view
Probably need to add same to the parts selector screen too
Also parts screen I guess but a larger thumbnail there

**Comment by hasorli** [comment]
It should be possible to disable the image view. (Global setting / user setting / adhoc in each screen) 
Cause: Photos taking large screen space and reduces the overview on order / invoice with many lines

**Comment by sbts** [comment]
Agreed, although I'd make it a simple per screen disable, preferably with the default state chosen by the viewport width, and if it's been manually toggled, stored in a local cookie store (once we have that available).

**Comment by sbts** [comment]
Oh, and the per screen disable should be either a link or toggle button/checkbox on the screen it's self

**Comment by ehuelsmann** [comment]
From the discussion, it's clear that we need to work out how this is going to work before actual coding can be done.

**Comment by ehuelsmann** [comment]
There is no parts selector screen anymore. Given the limited screen estate on the invoice, I really doubt this is a good idea.

**Comment by ehuelsmann** [comment]
Do we have an actual use-case depending on this ?
