### ISSUE TITLE
Remove the (confusing) cash/check/deposit/other drop-down from the payment screens

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2320]
In reference to http://archive.ledgersmb.org/ledger-smb-devel/msg06519.html
it's considered too confusing.

**Comment by sbts** [comment]
I'd actually vote for retaining it, but allowing a per-company and per-user default.
For most businesses I've dealt with, including my own, the type of payment is relevant during end of day actions and any activity related to out of balance amounts held locally.

Lets say at the end of day (or any other time) we do a cash count, or an EFTPOS Totals printout and the figures don't match what's on the system.
If we don't have a record of how a payment was taken (cash vs EFTPOS vs Cheque etc) we have to go through ALL received amounts and Recorded amounts to isolate the discrepancy.

However, if we have the payment type recorded, various cases are expedited.
If the cash amount and the recorded cash payments have a simple pair of digits swapped, it's likely a simple data entry error that's easily resolved.
Using this method, it's often easy to tell if an incorrect amount has been taken or given as change.

It's also fairly easy to then match up payments that have been incorrectly attributed as cash vs EFTPOS for example.

I do believe that if we are going to retain this capability, then we should ensure it's available EVERYWHERE payments can be entered.

Also, even if it's removed from the UI, the storage facility should be retained in the DB for use with any POS system that may be connected.

**Comment by ehuelsmann** [comment]
> I do believe that if we are going to retain this capability, then we should ensure it's available EVERYWHERE payments can be entered.
I'm assuming that by EVERYWHERE you mean that it shows on the invoice screen too and that the drop down on that screen retains it's value between views. 

>Also, even if it's removed from the UI, the storage facility should be retained in the DB for use with any POS system that may be connected.
Ah. But that's impossible: what I'm trying to tell you all along is that there *is* **no** storage behind the drop-down.
