### ISSUE TITLE
VOID transaction does not reverse actual invoice

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2321]
When using the VOID button in 1.4, I expect to have the original transaction reversed. However, tax lines are not reversed but calculated fresh. For an invoice that did not have sales tax applied (because the customer did not have the tax box checked) I set the tax, then used Copy To New to get the sales tax, then voided the original transaction. The VOID transaction subtracted the tax amount in addition to the base amount, even though the original invoice did not have sales tax.

**Comment by ehuelsmann** [comment]
There are multiple issues going on here. The one you saw is the one where tax gets recalculated. The other issue (you didn't see) is when things are reversed on a different date than the posting date and foreign currencies are involved; in that case, anything before 1.7 will use the wrong currency to reverse the transaction (unless currencies happen to be the same).

**Comment by freelock** [comment]
Another issue here is that when you void a transaction, the voided acc_trans line for the sales tax picks up the current date instead of the invoice post date -- e.g. for one I just did now, I get these dates:
![Selection_692](https://user-images.githubusercontent.com/46937/62269178-0db08400-b3e7-11e9-9435-db0d2fde8a30.png)
... the line for chart_id 30 should also be 2019-04-29, not 2019-08-01.

**Comment by freelock** [comment]
Ugh, something got worse in 1.8 now -- I just voided 5 invoices cleaning up our books, each of which had two line items. In the voided invoices, the first line item reversed (correctly) but the second line item did not reverse -- it had a positive qty instead of negative. 

So for an invoice that originally had:
* $150
* $125
Total: $325

... the void invoice had:
* -$150
* $125
Total: -$25

... but even stranger, on the AR -> Search screen, that -$25 invoice is showing as +$25, and appears to be adding to the overall AR balance (I did not verify the actual total to be sure this is happening -- other voids with a single line item look correct).

**Comment by freelock** [comment]
Bump

**Comment by freelock** [comment]
More info: Just did a void on an invoice with 5 line items. The 2nd line item had a negative qty when it should have been positive. The rest were all correct. When I removed the - from the qty in the second line item, updated, saved, and posted, the void was correct!

So the current state of this issue is when an invoice has multiple line items, and then gets posted, if you use the "Void" button it generates a new invoice with the sign of the second line item incorrectly set to a negative number.

**Comment by ehuelsmann** [comment]
Closed by PRs #6717, #6718, #6719 and #6720.
