### ISSUE TITLE
Sales tax on posted invoice shows incorrectly if taxable status for customer is changed

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2322]
Related to #2321, if you have a customer with a sales tax checkbox unchecked, create and post an invoice for that customer, the invoice does not show any tax. If you then check the sales tax box for that customer and go back and view the invoice, you see tax listed, even though the tax is not actually posted in the invoice. It does appear correctly (as posted) on reports.

**Comment by freelock** [comment]
More details, after correcting the database after a series of mishaps:

AR -> Search correctly shows the amounts in the AR table.

Individual invoice screens (and printed/PDF invoices) always show tax if the eca is marked taxable, and never shows taxes if the eca is not marked taxable -- regardless of the underlying data in acc_trans or ar.

This suggests that the tax is calculated/shown when the invoice is rendered -- if a tax rate changes, does it show the tax rate at the time of display, or the value posted in the invoice? This seems like a pretty critical issue, as it can lead to different amounts invoiced to a customer compared to tracked in the books.

**Comment by ehuelsmann** [comment]
The data isn't really lost insofar that the original data simply isn't really visible.
