### ISSUE TITLE
Can't remove part from Sales Invoice

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#2323]
See #1564 

This problem appears to still (or newly again) affect 1.4.34.

On demo: Do as above in #1564  --

The "X", which is now inside the partnumber area, removes only the partnumber. Maybe this is a change, where it used to be that the "X" was only acted upon "Updated"? Anyway, the line is now not removed.

**Comment by ehuelsmann** [comment]
1.4 is EOL and 1.5 will be EOL as of Monday. This works for me with 1.8/master and since there's no change in this area, so should it with 1.7 (our current stable). Closing.
