### ISSUE TITLE
URGENT: Use Overpayments creates accounting errors

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#2346]
I believe this to be a regression.  I don't know of any workaround.  See #2101 for a related issue, but I think it's different.

My workflow (on 1.4.35 demo):

Cash->Use AR OverPayment

Select customer with multiple overpayments available (trying to reproduce old issue with these getting confused -- but current regression means can't even get there).

Enter partial payment of Invoice with partial use of OP, all on one page, then post.

Going back, all the overpayments are still available in original amounts, but amount on Invoice is reduced by the "posted" amount.

This is URGENT for any of us with outstanding overpayments in our live clientbase!

**Comment by ehuelsmann** [comment]
With some help of @craigwebster, I've identified the problem to be here: https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/payment.pm#L1867

The function there posts with a payment_link value of 1(hard-coded) instead of 0 - in the sql function payment_post().

**Comment by ehuelsmann** [comment]
@craigwebster talking to @einhverfr, we are on the right track here. Continuing investigation.

**Comment by ehuelsmann** [comment]
@craigwebster, @freelock, if you have overpayments to fix, one thing you could search for is:

Are there any payment_link records with a type of 0 (zero) which point to an acc_trans record for which the `fx_transaction` field is true? If so, is there a payment_link record for the preceding line (same account, same transaction, *not* `fx_transaction`)? If not, add that line. Then, your overpayments should be fine again.

**Comment by freelock** [comment]
Added fix description to http://ledgersmb.org/faq/how-do-i-fix-out-balance-overpayments.
