### ISSUE TITLE
1.4.35: Explicitly setting 'Password duration' to '1 year' fails

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2348]
Due to a syntax error, setting the password fails (apparently '1 year' is invalid syntax?).

However, there's no user feedback of the fact that the password change failed.

**Comment by ehuelsmann** [comment]
Seems important enough to want to have in 1.5.13, as the password change failure is *silent*.

**Comment by nick-prater** [comment]
In 1.5 and above, a message is displayed after a user changes their password to report an error or confirm success.

In 1.6, a database constraint for the password duration (which is specified in days) has been added to address the root cause of the failure reported here.
