### ISSUE TITLE
Monthly based reconciliations

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2358]
Our current code seems to consider monthly periods for reconciliations.
While this is probably usual for most bank statements, we should add the possibility for user defined periods.

**Comment by ehuelsmann** [comment]
@ylavoie could you point to where in our code we make this assumption? Now is a good time to get this fixed for 1.8. (Yet, I have no idea where to start looking...)

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
