### ISSUE TITLE
Bulk payment posting

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2375]
Current code still uses leftover code from 1.3 to queue payments.
Proper migration should be finished, as documented in https://github.com/ledgersmb/LedgerSMB/blob/master/old/lib/LedgerSMB/DBObject/Payment.pm#L599

**Comment by ehuelsmann** [comment]
@ylavoie could you comment a bit more what the "Current code" is? maybe function names and files where you found it? maybe even better to annotate a reference in the code to this issue?

**Comment by ehuelsmann** [comment]
90 days without user feedback. Feel free to reopen, with feedback.
