### ISSUE TITLE
1.5 Missing hard dependency on XML::Simple

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2378]
I'm testing 1.5.0-rc3
Reports->Reconciliation fails because module XML::Simple is missing
cpanfile lists this as a dependency only if the rest feature is enabled

If XML::Simple is manually installed, or ledgersmb's rest feature is enabled, there is no problem.

XML::Simple should be listed as a hard requirement. Apart from the rest functionality, It is depended on by:
lib/LedgerSMB/Reconciliation/ISO20022.pm
lib/LedgerSMB/FileFormats/ISO20022/CAMT053.pm

I had installed dependencies, following instructions in README.md,  by running:
cpanm --with-feature=starman --with-feature=openoffice --with-feature=latex-pdf-ps --installdeps .

As a result, XML::Simple had not been installed

Error message is:
Unable to open script: LedgerSMB::Scripts::recon : No such file or directory: Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /home/nick/ledgersmb-1.5.0-rc3/tools/../lib /home/nick/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/x86_64-linux /home/nick/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0 /home/nick/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0/x86_64-linux /home/nick/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0 .) at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/FileFormats/ISO20022/CAMT053.pm line 5. BEGIN failed--compilation aborted at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/FileFormats/ISO20022/CAMT053.pm line 5. Compilation failed in require at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/Reconciliation/ISO20022.pm line 2. BEGIN failed--compilation aborted at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/Reconciliation/ISO20022.pm line 2. Compilation failed in require at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/Reconciliation/CSV.pm line 16. BEGIN failed--compilation aborted at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/Reconciliation/CSV.pm line 16. Compilation failed in require at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/DBObject/Reconciliation.pm line 53. BEGIN failed--compilation aborted at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/DBObject/Reconciliation.pm line 53. Compilation failed in require at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/Scripts/recon.pm line 22. BEGIN failed--compilation aborted at /home/nick/ledgersmb-1.5.0-rc3/tools/../lib/LedgerSMB/Scripts/recon.pm line 22. Compilation failed in require at (eval 817) line 1.

**Comment by ehuelsmann** [comment]
As discussed on IRC/Matrix, this problem has been resolved after rc3.
