### ISSUE TITLE
Date entry problem in TimeCards

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2379]
Entering date for a daily TimeCard results in bad date 2016-12-11 00:00:00-05

**Comment by ehuelsmann** [comment]
@einhverfr, it seems we need 2 more types to map data from the database into Perl in order for some tables and queries to work: timecards want to use `timestamptz`, but searching Pg-database.sql, other tables use `timestamp` (no-tz-variant).

The lack of support for `timestamptz` causes the following error to be thrown:
`
Bad date (2016-12-12 00:00:00-07) at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/PGDate.pm line 270 LedgerSMB::PGDate::from_input('LedgerSMB::PGDate', '2016-12-12 00:00:00-07') called at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/MooseTypes.pm line 59 LedgerSMB::MooseTypes::__ANON__('2016-12-12 00:00:00-07') called at /usr/lib/perl5/Moose/Meta/TypeCoercion.pm line 68 Moose::Meta::TypeCoercion::__ANON__('2016-12-12 00:00:00-07') called at constructor LedgerSMB::Timecard::new (defined at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/Timecard.pm line 278) line 68 LedgerSMB::Timecard::new('LedgerSMB::Timecard', 'business_unit_id', 10486, 'curr', 'IDR', 'jctype', 1, 'bu_class_id', 1, ...) called at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/Timecard.pm line 211 LedgerSMB::Timecard::get('LedgerSMB::Timecard=HASH(0xcaba9d0)', 4) called at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/Scripts/timecard.pm line 159 LedgerSMB::Scripts::timecard::save('LedgerSMB=HASH(0xb029a14)') called at bin/lsmb-request.pl line 103 LedgerSMB::PSGI::__ANON__() called at /usr/share/perl5/Try/Tiny.pm line 76 eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67 Try::Tiny::try('CODE(0xb02a158)', 'Try::Tiny::Catch=REF(0xc9825d8)') called at bin/lsmb-request.pl line 115 LedgerSMB::PSGI::call_script('timecard.pl', 'LedgerSMB=HASH(0xb029a14)', 'LedgerSMB::Locale::en=HASH(0xb044d80)') called at bin/lsmb-request.pl line 138 require bin/lsmb-request.pl called at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/PSGI.pm line 105 LedgerSMB::PSGI::__ANON__() called at /usr/share/perl5/Try/Tiny.pm line 76 eval {...} called at /usr/share/perl5/Try/Tiny.pm line 67 Try::Tiny::try('CODE(0xc852204)', 'Try::Tiny::Catch=REF(0x9a18cc8)') called at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/PSGI.pm line 113 LedgerSMB::PSGI::_run_new('timecard.pl') called at /usr/local/lsmb1.5/tools/../lib/LedgerSMB/PSGI.pm line 88 LedgerSMB::PSGI::__ANON__() called at /usr/share/perl5/CGI/Emulate/PSGI.pm line 29 CGI::Emulate::PSGI::__ANON__('HASH(0xc961d10)') called at /usr/share/perl5/Plack/App/URLMap.pm line 71 Plack::App::URLMap::call('Plack::App::URLMap=HASH(0x9a19470)', 'HASH(0xc961d10)') called at /usr/share/perl5/Plack/Component.pm line 39 Plack::Component::__ANON__('HASH(0xc961d10)') called at /usr/share/perl5/Plack/Middleware/Conditional.pm line 19 Plack::Middleware::Conditional::call('Plack::Middleware::Conditional=HASH(0x8afa440)', 'HASH(0xc961d10)') called at /usr/share/perl5/Plack/Component.pm line 39 Plack::Component::__ANON__('HASH(0xc961d10)') called at /usr/share/perl5/Plack/Middleware/AccessLog.pm line 21 Plack::Middleware::AccessLog::call('Plack::Middleware::AccessLog=HASH(0x8aaaed4)', 'HASH(0xc961d10)') called at /usr/share/perl5/Plack/Component.pm line 39 Plack::Component::__ANON__('HASH(0xc961d10)') called at /usr/share/perl5/Plack/Util.pm line 165 eval {...} called at /usr/share/perl5/Plack/Util.pm line 165 Plack::Util::run_app('CODE(0x8aaae20)', 'HASH(0xc961d10)') called at /usr/share/perl5/Starman/Server.pm line 255 Starman::Server::process_request('Starman::Server=HASH(0x8aaaf74)', 'Net::Server::Proto::TCP=GLOB(0xc9610a4)') called at /usr/share/perl5/Net/Server.pm line 75 Net::Server::run_client_connection('Starman::Server=HASH(0x8aaaf74)') called at /usr/share/perl5/Net/Server/PreFork.pm line 228 eval {...} called at /usr/share/perl5/Net/Server/PreFork.pm line 228 Net::Server::PreFork::run_child('Starman::Server=HASH(0x8aaaf74)') called at /usr/share/perl5/Net/Server/PreFork.pm line 186 Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x8aaaf74)', 2) called at /usr/share/perl5/Net/Server/PreFork.pm line 111 Net::Server::PreFork::loop('Starman::Server=HASH(0x8aaaf74)') called at /usr/share/perl5/Net/Server.pm line 61 Net::Server::run('Starman::Server=HASH(0x8aaaf74)', 'port', 'ARRAY(0x9a18c14)', 'host', 'ARRAY(0x9a18a70)', 'proto', 'ARRAY(0x9a1887c)', 'serialize', 'flock', ...) called at /usr/share/perl5/Starman/Server.pm line 67 Starman::Server::run('Starman::Server=HASH(0x8aaaf74)', 'CODE(0x8aaae20)', 'HASH(0x9a18868)') called at /usr/share/perl5/Plack/Handler/Starman.pm line 18 Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x9a19448)', 'CODE(0x8aaae20)') called at /usr/share/perl5/Plack/Loader.pm line 88 Plack::Loader::run('Plack::Loader=HASH(0x8a86308)', 'Plack::Handler::Starman=HASH(0x9a19448)') called at /usr/share/perl5/Plack/Runner.pm line 263 Plack::Runner::run('Plack::Runner=HASH(0x8959624)') called at /usr/bin/starman line 31 
`

**Comment by ehuelsmann** [comment]
blocking what? 1.5 as a milestone can't really be blocked...

**Comment by ehuelsmann** [comment]
I consider this part of solving the entire timecards business. No need to have issues on that until it's all been merged to master and still faulty.
