### ISSUE TITLE
1.5 Error deleting Draft Sales Invoice with Manual Tax

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2380]
Testing 1.5.0-rc3 and replicated on the Efficito 1.5 demo site:
* Create and save a draft sales invoice with manually applied tax.
* Go to Transaction Approval->Drafts
* Locate the sales invoice, tick it and click 'Delete'

Note an error appears:
ERROR: update or delete on table "acc_trans" violates foreign key constraint "tax_extended_entry_id_fkey" on table "tax_extended" DETAIL: Key (entry_id)=(5466) is still referenced from table "tax_extended". CONTEXT: SQL statement "DELETE FROM acc_trans WHERE trans_id = in_id" PL/pgSQL function draft_delete(integer) line 9 at SQL statement: SELECT * FROM "public"."draft_delete"(?) at /usr/local/share/perl/5.14.2/PGObject.pm line 359.

**Comment by ehuelsmann** [comment]
Solution is that the draft__delete() function runs as security definer, so the perm is handed out implicitly.
