### ISSUE TITLE
Output Template processors

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2383]
- Trying to export a report as ODS errors with Not a HASH reference at /lib/LedgerSMB/Template/ODS.pm line 834.
- The CSV works fine but send file named according to the Perl calling module.

The HTML processor seems to have evolved nicely, but other seems to need adjustments. The preprocessing routines should probably be general and common to all Template processors.

**Comment by ehuelsmann** [comment]
Full refactoring of the output processors has been done for 1.6. Closing.
