### ISSUE TITLE
1.5.0-rc3 Bank Reconciliation shows wrong currency amount

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2393]
My bank account currency is GBP.

I have received a payment of EUR 600.00 into this account with an exchange rate of 0.8802555.

Cash->Reports->Receipts correctly shows the amount received as GBP 528.15.

But the bank reconciliation report, which should show the GBP value, instead shows the EUR value of 600.00.

This makes it impossible to reconcile the account.

**Comment by ehuelsmann** [comment]
@nick-prater this too is fixed in the head 1.5 :-) Seems we'll need to release soon.

**Comment by nick-prater** [comment]
Still seems broken in the 1.5 branch head I tested just now. I'm struggling to find a commit for this issue. Do you have a pointer to where it was fixed?

**Comment by ehuelsmann** [comment]
Hmm. You're correct. I discussed the issue last week with @ylavoie; however, apparently that didn't lead to a fix. I'll be committing a fix shortly.
