### ISSUE TITLE
1.5 Cannot Submit Bank Reconciliation

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2419]
* Create a reconciliation report with a number of credit and debit transactions
* Ensure the reconciliation is balanced - Variance should show zero
* Note that to the right of Ending Statement Balace is a number highlighted in red
* Note that the Submit button is greyed-out

As the Submit button remains greyed-out even when there the variance is 0 and there are no unapproved transactions, it is impossible to Submit a bank reconciliation.

Proposed one-liner fix for 1.5 to follow shortly.

For 1.6 Yves says the recon dialog has been revamped:
https://riot.im/app/#/room/!qyoLumPqusaXqFJNyK:matrix.org/$1482272597227758hvaQf:matrix.org

**Comment by ehuelsmann** [comment]
The suggested fix has been merged to 1.5; closing this bug.
