### ISSUE TITLE
README.md 1.5 issues

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2424]
ehuelsmann: Yves: John: Ok, so I'm going through the "quickstart" and the following are either problems with the document or places we make assumptions that we probably shouldn't.
- System (library) dependencies
  - as Yves found, if cpan want's to compile anything, we probably need build-essentials packages installed, not just gcc and make
  - there is no suggestion to use distro versions of cpanm, it points you to a cpan page that shows use of cpan to install cpanm. This may clash with distro customisations.
  - ~~what to do about DBD::Pg is not clear enough~~
  - ~~for DBD::Pg to be compiled you need (on debian) both of~~
    - ~~libpq-dev~~
    - ~~libexpat1-dev~~
  - ~~redhat etc will have similar requirements.~~
  - ~~we call for "PostgreSQL client libraries" but don't indicate that postgres server side is required~~
  - ~~we don't suggest local::lib be installed. This will almost certainly result in collisions with system perl (At least on deb based systems.) as the default with no local::lib is a suggestion (by cpanm) to run as root. (installing from a .deb should pull local::lib as well, this may not be the case for a cpan install of cpanm)~~
  - ~~Yves experience confirms that a cpan install  of cpanm doesn't pull local::lib~~
  -  ~~Actually we do mention local::lib, but only after the user will have run the cpanm command~~
  - ~~following the quickstart basically installs all deps as cpan deps regardless if there are system packages available.~~
- PostgreSQL configuration
  - `sudo su - postgres -c 'createuser --no-superuser --createdb --login  --createrole --pwprompt lsmb_dbadmin'`
should probably be
  `sudo -u postgres createuser --no-superuser --createdb --login  --createrole --pwprompt --createrole --pwprompt lsmb_dbadmin`
  - both of the above commands fail until the user works out they need to install postgres server as well.
  - we possibly should show an example path for where to find pg_hba.conf, 
  - there should be a note that the order of entries in pg_hba.conf matters
  -  do we need a warning about our shown pg_hba.conf possibly breaking other users of postgres?
    I ask as we explicitly reject access to all db's from user postgres at localhost, if other programs only use tcp (instead of unix sockets) this will prevent them from working.
  - we also prevent access to postgres,template0,template1 from all users except lsmb_dbadmin if accessed via localhost
- Configure LedgerSMB
  - why are we suggesting a ledgersmb.conf file in the quickstart? it's not supposed to be required anymore.
  - we certainly shouldn't be muddying the waters with talk about LSMB_CONFIG_FILE variable here.
- Build optimized JavaScript widgets
  - simply installing nodejs isn't enough. (debian stable)
    this is due to nodejs installing on debian as `nodejs`, 
    while `UI/js-src/util/buildscripts/build.sh` only tests for and uses `node`
    A symlink needs to be created with
    `ln -s /usr/bin/nodejs /usr/bin/node`
  - It also appears that some elements of the build require java to be installed as well as nodejs.
This can be satisfied on debian by installing `default-jre-headless`
- Running Starman
  - ~~`cpanm --quiet --notest --with-feature=starman --installdeps .`
previously completed successfully but running 
`starman -I lib --port 5762 tools/starman.psgi` returns
`starman: command not found`
This is caused by installing with local::lib, but not having any entries added to $PATH or $PERL* variables
The correct solution here is to move "Environment Variables" to above "Running Starman" and either~~
  - ~~show both PATH and PERL5LIB entries and a suggestion of where they can be added.~~
~~or~~
  - ~~have a wrapper script that starts starman with the correct env-vars set~~
- Environment Variables
  - ~~`PERL5LIB='/home/foo/perl5/lib/perl5:/home/foo/perl5/lib/perl5:/usr/local/ledgersmb/'`
should probably be shown as
`export PERL5LIB="$HOME/perl5/lib/perl5:$HOME/perl5/lib/perl5:/usr/local/ledgersmb/"`
This makes it copy/paste friendly~~
  - ~~PATH can probably be set with the following (although it will need to be tested for corner cases)~~
```bash
[[ "$PATH" =~ (^|:)$HOME/perl5/bin(:|$) ]] || PATH="$HOME/perl5/bin${PATH:+":$PATH"}";
```
~~The complexity is needed to ensure duplicates aren't added to the path.
Although that still doesn't ensure $HOME/perl5/bin is at the beginning of the path which it probably should.~~

- Running Starman
  - ~~`starman -I lib --port 5762 tools/starman.psgi`
should probably be
`starman -I lib --listen :5762 tools/starman.psgi`
as according to the manpage --port is a compatibility option and --listen is recommended~~

  - ~~`starman -I lib --port 5762 tools/starman.psgi` returns
`Can't locate Plack/Runner.pm in @INC (you may need to install the Plack::Runner module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/dcg/perl5/bin/starman line 3.
BEGIN failed--compilation aborted at /home/dcg/perl5/bin/starman line 3.`
This was due to no export for PERL5LIB~~
- Next steps
  - we need to linkify
    - http://localhost:5762/setup.pl
    - http://localhost:5762/login.pl

**Comment by ylavoie** [comment]
1- System: With the above additions, I was able to run cpanm without --force or problems.
2- Postgresql: A cut & paste of the createuser fails on createrole.

**Comment by ehuelsmann** [comment]
Personally, I think it's overkill to point out that these changes may cause problems for other uses. After all, almost every edit in the system's config area can have that effect.

**Comment by sbts** [comment]
True, however we are introducing a change to the postgres config that will almost certainly break other software that tries to do basic things with postgres on that system.
In particular I'm fairly certain it will break use of pgAdmin via ssh (which is the way I normally use it) as I believe that depends on access via localhost

**Comment by sbts** [comment]
the line....
> Those who don't want to install the dependencies globally should investigate local::lib to create an "overlay" over the system packages in a separate directory.

probably should be removed.

**Comment by ehuelsmann** [comment]
We suggest using a ledgersmb.conf, because it allows us to simplify the remainder of the instructions.

**Comment by ylavoie** [comment]
I think that we should suggest ledgersmb.conf only if your need local config, then copy the default and edit. The Readme is supposed to be a quick start and defaults should work well

**Comment by sbts** [comment]
@ehuelsmann in what way does using a ledgersmb.conf simplify the instructions?

**Comment by ehuelsmann** [comment]
@sbts because the config defines the use of unbuilt dojo, thus removing the need to describe the process of building.

**Comment by sbts** [comment]
Ah, Of course, we now only use unbuilt dojo (dojo src) for the Quickstart instructions, hence the need for a ledgersmb.conf

**Comment by ylavoie** [comment]
I forgot that. I was looking for a way to not have to copy a default ledgersmb.conf for quickstart
