### ISSUE TITLE
fallback to dojo src

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2427]
if we are configured (explicitly or by default) to use built dojo, but it doesn't exist, fall back to dojo src.
When this is implemented 
- drop conf/ledgersmb.conf.unbuilt-dojo
- correct README.md
- correct website docs

**Comment by ehuelsmann** [comment]
Great idea, definitely not for 1.5.1. Maybe another 1.5 version.

**Comment by ehuelsmann** [comment]
To be done some other day.

**Comment by ehuelsmann** [comment]
Built dojo is included in the distribution archive; this isn't a problem our users actually have.
