### ISSUE TITLE
Refresh detailed installation instruction

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2428]
The current instructions a slightly outdated and should be refreshed.
For example, we talk about Debian/Ubuntu distribution dependencies and available packages to not have to rely only on cpanm, but give examples only for Debian/Jessie. Ubuntu/Xenial should be detailed to for it is the current LTS release.

**Comment by ehuelsmann** [comment]
I'm afraid we're all too busy doing other stuff. it'll get done when it gets done.

**Comment by ehuelsmann** [comment]
To which documentation does this issue refer? Could you add a link?
