### ISSUE TITLE
Expired TODO item for 1.4 in "recon.pl"

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2434]
https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/recon.pm#L319 says "# Not sure I like it but won't refactor until 1.4..... --CT" which has expired by a few years as we just released 1.5.0.

**Comment by ylavoie** [comment]
Let's review this after #2288

**Comment by ehuelsmann** [comment]
Resolved in e8f4df4f0c1fd5be9bdc31a5bcac8340edccc226
