### ISSUE TITLE
Timecards CSV import

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2462]
Trying to import Timecards gives Action Not Defined: run_import.
Moreover, we have lots of duplicated code for CSV imports in many modules. We should aim to standardize that and find ways to cope with the vast types of CSV formats (tabs, comma, semi-columns...)

**Comment by sbts** [comment]
perhaps the first step is to 
- get a standard "csv" import functional
- add a single preprocessor script that does nothing, allowing local override (this script would eventually become a sample to show how to implement local variations
- add a preprocessor selector
- add XML import backend with CSV/XML auto select based on preprocessor output
- extend to other import locations than timecards

The preprocessor scripts would be held in a directory per import origin.
ie: one dir for timecards, one for reconcilliation, etc

I'm thinking each of the above is a discrete step that while needing to be done in order, can each occur over a longer period of time

**Comment by ehuelsmann** [comment]
Separated out the "we have lots of duplicated code for CSV imports in many modules. We should aim to standardize that" to #2465, which would be code cleanup.

Separated out the "find ways to cope with the vast types of CSV formats (tabs, comma, semi-columns...)" to #2466, which would be an enhancement.

**Comment by ylavoie** [comment]
Agreed. Better. Closing.

**Comment by ylavoie** [comment]
Let's fix the bug before closing

**Comment by ehuelsmann** [comment]
What remains is the bug that we can't import a timecard.
