### ISSUE TITLE
All Template Export

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2478]
I can't remember if we have a working "template export" feature at the moment.
It's something we probably need so templates can be edited system side instead of in the UI, then reloaded.

- The export should be for all files as a set.
- The import function should be per file.

Some of this may be present, but not fully functional or sufficiently accesible

**Comment by ehuelsmann** [comment]
The "template import" functionality has been added in a more friendly way to our in-app UI.

Remaining item in this issue is the "all template export".

**Comment by ehuelsmann** [comment]
Duplicate of #1931
