### ISSUE TITLE
Contact Search by City, State does not work

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2490]
When using Contact -> Search, searching by company name does pull up results, but searches containing only City or State values does not pull up any customers or vendors in those cities or states. Other search fields not tested, and may also need attention. Should either fix these filter boxes or remove if they don't work.

**Comment by einhverfr** [comment]
On the demo this seems to work in 1.5, but seems broken in 1.4 and 1.3.

**Comment by nick-prater** [comment]
commit b2ac0a70494c1ba7bd0052842248f94d6523e30a fixed this in 1.5. I have a fix for master, held back until tests are in place. I don't run 1.4 or 1.3 so cannot easily backport.

**Comment by einhverfr** [comment]
I am actually backporting :-)

**Comment by nick-prater** [comment]
Thank you :)
There are some other issues with the contact search - hence why I am writing tests, then fixing.
Started to write some documentation on contacts here: https://github.com/ledgersmb/LedgerSMB/wiki/Contacts-in-LedgerSMB

**Comment by einhverfr** [comment]
I actually got a complaint from an Efficito customer on 1.3 so getting this backported all the way to there at least locally.  Have a fix for 1.4 ready for testing.
