### ISSUE TITLE
Add "current version:latest version" banner to login page

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2505]
by adding the equivalent to the following code to the generated HTML for our login pages we can notify the user what the current (installed) and latest versions are.
```bash
# https://developer.github.com/v3/git/tags/

# If you pass in no arguments it will return the latest tag starting with a number.
# otherwise pass in a regex that will partially match a version string
CurrentVersion="${1:-[0-9]}"

curl -s "https://api.github.com/repos/ledgersmb/LedgerSMB/tags" | awk '/name": "'"$CurrentVersion"'/ {gsub("[\",]",""); print $2; exit}'
```

If we first retrieve the results and filter just for the name key where the tag name matches /^[0-9]/ then the first entry in the list will be the latest tagged version of any series.
we can then filter further to get the latest version of the installed series.

If the two results don't match, we can flag both latest version (in the installed series) and that there is a series upgrade availabe (eg: 1.4 to 1.5)

The banner should be worded something like....
> Installed Version 1.5.0 Latest Version 1.5.1 released on 9th January 2017

The work for this should be done server side, not client side.

**Comment by ehuelsmann** [comment]
Note that GitLab when they switched to doing something like this,
explicitly notified the userbase of a change like it and how to disable
that. I think that we in our position should be even more careful about it.

Also, I think packagers should be able to get notifications in place
specifically for the distro, because notifying users of packages of new
software which isn't packaged doesn't seem useful.

**Comment by sbts** [comment]
Agreed that it needs to be easy to disable, perhaps a tooltip pointing to website article on adding a config file option to disable it?
Packagers can (to start with) simply pre-set the disable config option

When we can, I'd think we should also add a "installed from package" flag file (ledgersmb/installedfrom containing a description of the install method and source)
I'm thinking that file could also contain a key pointing to a package::function that returns a string to display in the version check banner instead of our default.

**Comment by nick-prater** [comment]
We should consider that this might be running on a server without internet access. The banner should then report only the currently installed version number.

**Comment by ehuelsmann** [comment]
having this in 1.5.1 is simply unrealistic. I think here applies "It's done when it's done". Shifting to 1.6 and I may even remove a milestone.

**Comment by ehuelsmann** [comment]
This is taking too many cycles from other important stuff, most notably because it requires the definition of a centralized infrastructure listing "latest".
