### ISSUE TITLE
"Need" a developer test for DB schema updates applied

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2506]
Yves: I actually had a discussion with ehuelsmann about that recently (as I'd also forgotten to do it more than once despite knowing full well it's needed)
In that discussion I proposed a mechanism where for 'dev versions' we validate the schema updates on startup and provide a prompt in the UI
To prevent it blocking the idea was to do the validation in a forked process and use a callback or similar to report

**Comment by ehuelsmann** [comment]
With the infrastructure to upgrade databases by default, it's actually too simple to move from one schema to another. That, combined with the fact that there actually are hardly any database changes over the course of a stable release and only few over the course of a minor release cycle on master, I don't think this is worth our cycles at the moment.
