### ISSUE TITLE
Tax applicability rules

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2531]
Many Canadian provincial regulations requires that tax applicability varies with the number of items in a transaction for specific categories.

For example, pastries in Québec are taxable when bought/sold by less than 6 items at the same time.

We could support that by adding tax applicability rules in the item definition.
Currently, one has to define similar products and different taxes and let the user decide about the proper grouping to handle that.

**Comment by ehuelsmann** [comment]
I think this idea leads to too complex configuration for the standard release, but I'll gladly support any vendor to develop a Quebec tax module
