### ISSUE TITLE
Auto drop superuser for admin user

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2537]
Security wise it's undesirable for lsmb_dbadmin to have superuser.
To that end, during login to setup.pl let's. ...
- have a test to see if lsmb_dbadmin (or the admin user that is currently authenticated) has superuser
- if it does prompt the user "we don't need postgres superuser anymore. Can we drop it?"

If that prompt has 
- yes
- not now
- never

As buttons we should have it covered

**Comment by ehuelsmann** [comment]
How do we implement the "never" choice? After all, we have no global
storage...

**Comment by sbts** [comment]
As I raised recently we probably do need some global storage to facilitate various things such as display of available db's and users on login ad well as possibly a db -> user and reverse map so we can behave more like a desktop app for local installs but still ave the ability to disable those features for web based installs and sites where the admin wants to reduce information provided pre authentication at the expense of convenience for their users.

**Comment by ehuelsmann** [comment]
Deemed too complex. Can be worked around by not using setup.pl
