### ISSUE TITLE
Incorrect reversal of payments for transactions with non-ECA-default AR/AP-accounts

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#2558]
This has been an ongoing issue in 1.4 -- 1.4.25 through 1.4.37.  Also in 1.5.1, in different way.

In 1.4, the symptom is that some invoices that have payments on them (usually positive and negative payments?) show two lines in the invoice section of the payment screen, both of them with the little arrow "open" and details shown. Whenever attempt to pay on these, get error: Only one decimal separator permitted at /usr/share/ledgersmb/tools/../LedgerSMB/PGNumber.pm line 164.

In 1.5, simply can't display screen of affected customer/vendor at all. Visible error is 
An error occurred!
Server return value invalid
Starman displays another error: Use of uninitialized value $unhandled_overpayment in addition (+) at /usr/share/ledgersmb-1.5.1/tools/../lib/LedgerSMB/Scripts/payment.pm line 880.

Looking at this section of code seems to indicate in the comments that there are some known problems??

**Comment by ylavoie** [comment]
Display problems only? What kind of data damage?

**Comment by ylavoie** [comment]
Uninitialized variable is an annoyance at most, It shouldn't be producing payment failure.

**Comment by ehuelsmann** [comment]
Do you have a reproduction recipe for me? If not, could you provide me with access to a copy of the database that exhibits the problem? Contact me privately so we can force progress on the issue, if there is no way to create a repro recipe.

**Comment by ehuelsmann** [comment]
In Chrome, can you check the 'Console' tab of the developers tools? This would show you what went wrong with the server response. This might be key to understanding what's going on here.

**Comment by craigwebster** [comment]
ylavoie: I should have been more precise: my suspicion is that data "damage" (or simply unexpected behavior) may have been introduced at some point (I think around 1.4.25 or so), and then the code can't handle it, resulting (in 1.4.*) in multiple lines with display errors that can't be paid on. Screenshot on request.

Secondly: yes, I know uninitializable variable probably isn't the problem, but it does point to executed code, and there is something potentially relevant in the comments there.

ehuelsmann: I've not yet been able to manufacture a reliable recipe, working on it. May no longer create the data confusion in current versions, will PM you to send you access to a DB... 

Re: console -- the error that comes up in 1.5.1 is a dojo window, not sure it would show more in console?? Will look next time I start the 1.5.1 server...

**Comment by ehuelsmann** [comment]
Investigating the actual data, the problem turns out to be that postings were made to two AP accounts, which leads to problems in the aggregation at payments_get_open_invoices().

**Comment by ehuelsmann** [comment]
Actually, my thinking is that the output is correctly aggregated, but incorrectly not taking into account that the payment is to be split over 2 AP accounts, which means that the payments_get_open_invoices() should include an AP account `id`, but that the posting interface should consume an account id to post the payment to.

**Comment by craigwebster** [comment]
This is interesting. As I understand, what's causing issues in a new Cash->Pmt screen is historical payments on a single invoice. That invoice only has a single AP account -- I believe that is necessarily true of all invoices? But are you saying that somehow in the past payments were applied to two different AP accounts?

**Comment by craigwebster** [comment]
Based on conversation with Erik, likely cause is reversing Payments that post to a different AR or AP account than the original transaction. Workaround would be to change the AR or AP for that reversing transaction (in the DB?). Fix would be for the code to ensure that any reversal (or other) payment posting to an AR or AP transaction hits the original AR or AP account.

**Comment by ehuelsmann** [comment]
Posting my analysis here so I don't forget.

The problem stems from the fact that `payment__reverse` doesn't use the transaction's AR/AP account, but the vendor's, as can be seen from the following:

The transaction is posted here: https://github.com/ledgersmb/LedgerSMB/blob/master/sql/modules/Payment.sql#L1234 which uses the `pay_row.ar_ap_account_id`, which is retrieved here https://github.com/ledgersmb/LedgerSMB/blob/master/sql/modules/Payment.sql#L1181 from the credit_account instead of from the payment transaction itself.

**Comment by ehuelsmann** [comment]
This fix is in 1.4.41 too.
