### ISSUE TITLE
Invoice generated from Send Email uses values in form post and not posted data

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2606]
When posting an invoice via an external tool, when the external tool triggers the Send_Email action the values of the description_1, description_2, taxincluded fields override those values in the posted invoice, leading to PDF copies of the invoice that do not match what's in the database. Printing/Emailng the invoice through the UI generates the correct values.

**Comment by ehuelsmann** [comment]
For printing to screen, we're now using the data retrieved from the database. We should do the same for the e-mails.
