### ISSUE TITLE
Cannot edit LaTeX quotation.tex

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2617]
In 1.5.2, System -> LaTeX Templates -> Ordering -> Quotation pulls up an empty file. When you click edit, you get the error message 'Template Not Found at /srv/ledgersmb/tools/../lib/LedgerSMB/Scripts/template.pm line 85.'

When going to print a PDF quotation, the print button fails silently with either PDF or HTML. Console log reports a 500 error, 'undef error - Can't locate object method _include via package LedgerSMB::Template at /srv/ledgersmb/tools/../lib/LedgerSMB/Template.pm line 296.

**Comment by ehuelsmann** [comment]
The problem here is that the menu thinks the templates are called "rfq" and "quotation" while in the database they're actually called request_quotation and sales_quotation respectively.
