### ISSUE TITLE
Add proper handling of manual price overrides on invoices

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2627]
Copied from #ledgersmb
dcg => ehuelsmann: so can I propose we make a slight change to how we handle pricing.

- use the existing field (price) on an invoice/order/quote/etc to represent the final price for the item
- add a new field "auto_price"
- add a new field "manual_price"
- if "manual_price" is null price=auto_price
- if manual_price != null price=manual_price
- discount field is only applied to "price"

I think that change should be fairly easy to implement. And can be implemented piecemeal. One UI screen at a time.
In fact, if we implement it in the API first, then it comes almost for free if we switch the UI over to consume the api

ehuelsmann  => dcg: sounds like a good improvement

We probably should also
- have a new permission to enable/disable price overrides.
- provide a "privilege escalation" mechanism for price overrides (although that could be handled by saving the invoice etc then another user logging in to apply the override)
- store the authorised user info with any manual override so the invoice can be altered by a user with lower privileges in all aspects except that line item

**Comment by ehuelsmann** [comment]
@sbts I can't remember which problem this solves. We already look up prices and allow overriding of said prices in the invoice screen.

**Comment by sbts** [comment]
This ties in with a more recent request I've received (I think I raised an issue for it recently)
where tracking of system sell price vs actual sell price is needed to allow handling of things like
- sales person discount limits
- sales person bonus' (may be reduced if more discounts are offered to customers)

**Comment by ehuelsmann** [comment]
But then, what is the definition of "proper" here?

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
