### ISSUE TITLE
Makefile "all_dependencies" missing Test :: Trap, Excel :: Writer :: XLSX, Spreadsheet :: Write Excel

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2628]
If I understand the doc in the Makefile right "all_dependencies " should install all I need to run the test ?

cpanm --notest --with-feature=all_dependencies --installdeps .

If the Makefile doc is correct, this modules are not being installed to run the 
"prove -Ilib xt/*.t" test :

cpanm Test::Trap
cpanm Excel::Writer::XLSX
cpanm Spreadsheet::WriteExcel

I can find the modules in the cpanfile under feature 'xls' and on 'develop'

The "prove -Ilib xt/*.t" tests need:
cpanm HTML::Lint::Pluggable
cpanm Perl::Critic
cpanm Module::CPANfile
cpanm File::Util
cpanm Test::ParallelSubtest
cpanm YAML::Syck
cpanm --force Test::ParallelSubtest           [1] Note below 
cpanm Selenium::Remote::Driver
cpanm File::Find::Rule
cpanm Test::Dependencies Test::Pod::Coverage X12::Parser

[1] Test::ParallelSubtest
! Installing Test::ParallelSubtest failed.  Retry with --force to force install it.
Moved to: 
[#2639] Test::ParallelSubtest is known to be broken in version 0.05 and below

From build log: 
* Module \'Test::ParallelSubtest\' is known to be broken in version 0.05 and below, newer versions have not been tested. You have: 0.05 
----

**Part of solution:** 

Add --with-develop to the cpanm command line to include all the modules in the "on 'develop' => sub {" section in "cpanfile".

cpanm --notest --with-feature=all_dependencies --with-develop --installdeps . 

--with-develop
    EXPERIMENTAL: Installs develop phase dependencies in META files or cpanfile when used with --installdeps. Defaults to false.
(Tested by @hasorli on osx, with cpanm from macports. Seems to work)

More info in cpanm doc:
http://search.cpan.org/~miyagawa/Menlo-1.9003/script/cpanm-menlo

**Todo Mac OSX**  
Building Linux-Inotify2-1.22 ... FAIL    :  moved to new case :
[Linux::Inotify2: replace with a cross-platform alternative #2637](https://github.com/ledgersmb/LedgerSMB/issues/2637)

**Comment by ehuelsmann** [comment]
@sbts could you look at this?

**Comment by sbts** [comment]
@hasorli @ehuelsmann 
Ok, so the make target "all_dependencies" is intended for use with a "normal" install, not a development one

Infact, there isn't a make target for installing development modules as yet.

You are correct that --with-develop is needed on the cpanm commandline for installing development deps, but that's only part of the story, we also need to add per OS lists of packages that should be installed before attempting to run cpanm

I'll keep this issue open, but set with a Milestone of 1.6, we'll either deal with it by then, or review when we are getting close.

@hasorli as for the issue with Test:ParallelSubtest, can you move that to it's own issue please.
We will want to assign that to @ylavoie I believe

**Comment by ehuelsmann** [comment]
Sufficiently handled, I'd say.
