### ISSUE TITLE
 Test::ParallelSubtest is known to be broken in version 0.05 and below

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2639]
From build log:  (attached in file)
Module \'Test::ParallelSubtest\' is known to be broken in version 0.05 and below, newer versions have not been tested. You have: 0.05 

cpanm Test::ParallelSubtest           [1] Note below 

[1] Test::ParallelSubtest
! Installing Test::ParallelSubtest failed. See .cpanm/work/1487240319.6645/build.log for details. Retry with --force to force install it.

Workaround
cpanm --force Test::ParallelSubtest         
[build_log.txt](https://github.com/ledgersmb/LedgerSMB/files/785961/build_log.txt)

Relates to: 
#2628 Makefile "all_dependencies" missing

**Comment by sbts** [comment]
@ylavoie can you please have a look at this one. From memory you added it not all that long ago

**Comment by ylavoie** [comment]
This is reported to have been fixed 3 years ago. See https://rt.cpan.org/Public/Bug/Display.html?id=92119

**Comment by ylavoie** [comment]
Even though it is reported fixed, this still miscompile. Moving to another soution, like Fennec or Test::Class::Moose
