### ISSUE TITLE
'Inventory Entity' is confusing: it's not a real customer or vendor

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2642]
Also, it doesn't have a complete customer/vendor setup, but is only used to account for inventory differences due to adjustments.

Instead of requiring AR/AP items (and thus a fictitious counterparty) to be created for inventory adjustments, we could be using GL items -- same way manufacturing/stocking of parts is currently implemented.

**Comment by ehuelsmann** [comment]
Due to the lack of a complete setup at database creation time (i.e. lacking a currency), the sql/changes/mc/ changes can't be succesfully executed. As there is no way to add a currency to an empty database, the only solution here is to declare this issue as blocking MC and eliminate the need for AR/AP transactions.

**Comment by einhverfr** [comment]
I think we should remove this for 1.6 and if necessary supply an upgrade path for anyone using it manually.  This need not be in 1.6.0 and we can work with people directly.

**Comment by einhverfr** [comment]
(the upgrade path need not be in 1.6.0)

**Comment by ehuelsmann** [comment]
I'm working on eliminating the inventory entity. The plan consists of a few steps:

* [ ] Fix #2648 (as this is a precondition to resolving this one)
* [ ] Add "inventory change types" (or some other indication to differentiate GL transactions for inventory adjustment and assembly stocking)
* [ ] Rewrite inventory adjustment routines to insert GL transactions instead of AR+AP transactions
* [ ] Write tests (xt/42-*) for the new inventory adjustment
