### ISSUE TITLE
Improve default selection for setup.pl

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2644]
When adding a new DB we should better handle selection of defaults. including the COA.
The Non-COA questions I'm thinking about are things like

- default decimal separator
- default thousands grouping character
- default date/time formats
- preferred currency set (list of currency codes)

Perhaps we can come up with a generic COA that is generated based on some questions the user answers

**Comment by ehuelsmann** [comment]
Other items I'm thinking that could be prefilled in the newly created company include:

* Weight unit
* Company details
  * Name
  * Address
  * Tel
  * Fax
  * etc

Basically, anything that's on the System > Defaults page

**Comment by ehuelsmann** [comment]
Nice to have. Moving to 1.7.

**Comment by ehuelsmann** [comment]
The new xml configuration supports adding these parameters to the coa file. Which leaves the question: do we really need this functionality, or does the setup format sufficiently address this requirement?
