### ISSUE TITLE
Inventory movements due to stocking assemblies don't appear in the movement report

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2648]
Due to the fact that inventory movements associated with stocking assemblies are linked to `acc_trans` lines with a `trans_id` in the `gl` table (in contrast with the "regular" ones which have a `trans_id` in either `ar` or `ap`), these movements don't appear in the inventory movements report.

**Comment by sbts** [comment]
This will impact me sooner than 1.6.
I'll lend a hand to resolve it within the near future.
It would be good to milestone this as 1.5.5
