### ISSUE TITLE
SQL-Ledger.README is out of date

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2653]
@ylavoie can you please have a look at
- `sql/upgrade/SQL-Ledger.README`

It's not been edited since I wrote the rough draft back in March 2016 and needs a bit of work.

Also, while you are looking at it, can you please discuss it's location with @ehuelsmann.
It is in the correct location, however, as it's not easily discoverable, perhaps it needs a symlink (or at least a same name file that refers people to the real file) in the normal docs dir

**Comment by sbts** [comment]
@ylavoie as you are currently revisiting SL migration can you please check on this one

**Comment by ehuelsmann** [comment]
Can you please move the document to `docs/` and add a reference to the general README in the repository root?

Thanks!

**Comment by ehuelsmann** [comment]
@ylavoie another option is to replace it with a notice that the content needs updating and where the original content can be found... (No idea if this is one of the most important issues, although it *looks* important, but it's also 5 years old..)
