### ISSUE TITLE
1.3->1.5 migration fails on "not the latest" 1.3 schemas. Same for 1.2->1.5

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2657]
Which is only logical, but: I suggest we "teach" 1.5 to upgrade the old schemas, so people don't run into migration problems due to the schema mismatch. (There are plenty other reasons to run into problems on the migration.)

**Comment by sbts** [comment]
# For LedgerSMB 1.2, 1.3 and SQL-Ledger
- Currently the workaround is to run `/sql/upgrade/foo.sql
where foo is the appropriate file for the origin version
This __MUST__ be done __BEFORE__ attempting to update via setup.pl

It may help to grab the latest version of the appropriate foo.sql from
  - [github master branch](https://github.com/ledgersmb/LedgerSMB/tree/master/sql/upgrade)
or
  - [github master branch](https://github.com/ledgersmb/LedgerSMB/tree/1.5/sql/upgrade)

as they will have the latest fixes incorporated

**Comment by sbts** [comment]
#2658  is related

**Comment by einhverfr** [comment]
for 1.3, we need to know what the fixes.sql is before we install so maybe we should just copy that file in and run it first?  For 1.2, we had a different approach and I think documenting this is fine.

**Comment by einhverfr** [comment]
I really don't want to recreate the 1.2 upgrade logic going forward :-) but 1.3 could use running the Fixes.sql first if we keep that current.

**Comment by ehuelsmann** [comment]
I think it's a good idea to "prepend" the 1.3 fixes to running the 1.3->1.5 upgrade script indeed. Nice solution.

**Comment by ehuelsmann** [comment]
@einhverfr, I've looked at the 1.2 sql directories. There are only 5 schema upgrade files there *most* of which change stored procedures. Didn't 1.2 have schema upgrades? Or am I looking in the wrong place?
