### ISSUE TITLE
1.3->1.5 migrations: Need a fixed "end-point" schema to run the migration "to"

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2658]
With a single data migration script *from* 1.3, we do not only need a single point of departure (latest 1.3 schema), we also need a single point of arrival (point to migrate *to*). From that point, the standard `sql/changes/` scripts will handle the migration as they do for "everybody else".

**Comment by ehuelsmann** [comment]
Currently, the 1.3 -> 1.5 migration doesn't work due to an added REFERENCES constraint on the `acc_trans.invoice_id` column while the migration script populates the acc_trans table before the invoice table (which thus leads to the referential integrity constraint being triggered).

This needs to be fixed in order to fix migrations.

**Comment by sbts** [comment]
The same issue applies to 1.2->1.5 as well

**Comment by sbts** [comment]
#2657 is related to this bug
