### ISSUE TITLE
sql/changes/ needs pre-checks and offer corrective actions

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2667]
In order to allow users to take corrective action when their schema contains data that won't fit the schema changes which are about to be applied, we need to add infra structure to do pre migration checks and define corrective action.

Actions that should be supported:
* Delete records with problem data (after exporting it)
* Modify existing data to until it complies
* ~Add new data to make existing data comply with the schema constraints (separated into #3544)~

**Comment by ehuelsmann** [comment]
after the schema-change-checks branch merges, support for modifying and deleting data is in place.

Separating "add data" into a new issue, as that's a scenario that is'n't required to complete the "Inventory adjustments" project.

**Comment by einhverfr** [comment]
Big step forward
