### ISSUE TITLE
1.3 to 1.5 Migration Issue

### ISSUE THREAD

**Issue by billott323** [ledgersmb/LedgerSMB#2675]
After migrating from 1.3 to 1.5, cash->receipts->continue->Choose a Company  appears to show the info from the "Pay To:" field instead of the "Company" field.

**Comment by billott323** [comment]
I found a work around. if you go to Company->credit account and erase any entry in the "Pay_to" field and save the results, then cash-receipts-continue-Choose a Company will show the Company instead of the Pay To field.
  
You can do a wholesale change in sql with

```
update entity_credit_account set pay_to_name = null where entity_class = 2;
```

**Comment by billott323** [comment]
I have verified that this error occurs on 1.5.8, as well.

**Comment by ehuelsmann** [comment]
@einhverfr is this intended change? It looks like a change in functionality rather than a migration problem, becaues otherwise clearing "Pay To" would not result in the old behaviour.

**Comment by ehuelsmann** [comment]
Without a reaction from @einhverfr and combined with the fact that new users will be used to the current way of working and there being a work-around, I'm going to close this as WONTFIX: there's no way that I can make an obviously correct decision here.
