### ISSUE TITLE
Fix license on files in utils/release/ 

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2676]
I am not happy with :

"Exclusively Licensed for use in the LedgerSMB Project
Use in whole or part outside of the LedgerSMB Project is Not Permitted"

Proposes to remove the two lines above. 

Reason: 
I do not think this is inline with LedgerSMB openness. We use code from other projects and have to give back to the community. If we stop giving back, the hole open source concept is dead..

https://github.com/ledgersmb/LedgerSMB/search?utf8=%E2%9C%93&q=%22is+Not+Permitted%22&type=Code

utils/release/notification-helpers/README.md
Showing the top three matches. Last indexed on 17 Sep 2016.
    Exclusively Licensed for use in the LedgerSMB Project
    Use in whole or part outside of the LedgerSMB Project is Not Permitted

utils/release/README.md
    Use in whole or part outside of the LedgerSMB Project is Not Permitted

utils/lib/bash-functions.sh
    Exclusively Licensed for use in the LedgerSMB Project
    Use in whole or part outside of the LedgerSMB Project is Not Permitted

utils/release/notification-helpers/release-irc.sh
Showing the top three matches. Last indexed on 18 Jan.
   Exclusively Licensed for use in the LedgerSMB Project
   Use in whole or part outside of the LedgerSMB Project is Not Permitted

**Comment by ehuelsmann** [comment]
@sbts has this been resolved?

**Comment by ehuelsmann** [comment]
@sbts I'm still seeing this phrasing in the `bash-functions` helper.
