### ISSUE TITLE
Release; update : https://en.wikipedia.org/wiki/List_of_ERP_software_packages

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2681]
Release script

Update LedgerSMB,  "Last stable relase date" : 
https://en.wikipedia.org/wiki/List_of_ERP_software_packages

**Comment by ehuelsmann** [comment]
@sbts could you implement this in the "update wikipedia" script?

**Comment by ehuelsmann** [comment]
(both english and russian version have the same table)

**Comment by ehuelsmann** [comment]
Wikipedia won't allow the IP address of my server to edit their pages...
