### ISSUE TITLE
Backup database button in setup.pl does not work

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2686]
In 1.5.5, the database backup button on the setup.pl screen looks successful but sends a 0-byte file to download.

**Comment by hasorli** [comment]
Solved by adding temp dir and install correct pg_dump version

**Comment by nicefiddler** [comment]
Am getting a 0byte file in the docker version.  1.5.19

**Comment by sbts** [comment]
@nicefiddler that's a surprise. We thought that was resolved recently via a change to the pgutils version  in the docker image.

Could you please check the version of pgdump installed in both the ledgersmb container and in the postgres container.

`docker inspect` should allow that.
Check the man page and if you need further pointers please ask.

Also could you please open a new issue to track this as it's most likely a different issue to the old one.
Just reference this issue by mentioning `#2686` in the new issue

**Comment by nicefiddler** [comment]
I confess that I wasn't able to create the image by docker-compose as it
was getting stuck at Auto-vacuum, owing to which I used docker pull for the
latest images of postgresql and ledgersmb. Does that cause different
versions of postgresql (within the postgresql container) and pg_dump
(within the ledgersmb container)? Instead of using docker pull, will it be
better to use docker build with a docker file? Am a noobie; please excuse
my queries.

**Comment by nick-prater** [comment]
I am seeing the issue on my test 1.5.19 install. Shame, as I previously
checked this was fixed. I'm looking at it now... I'll let you know what 
I find.

Thanks for reporting.

Nick

**Comment by nicefiddler** [comment]
I checked the info in pgdg.list in both containers. They are

In the Postgres container:
deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main 10

While in the ledgersmb container:
deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main

Is that the consequence of using docker pull for the images of ledgersmb
and postgresql? Will my problem be resolved if I use docker build instead?
Or is it a problem which has cropped up for which there may be a
workaround. Please guide.

**Comment by nicefiddler** [comment]
Using docker exec -it bash, when I enter into the containers and give [
echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg
main"],

the results are:

In the Postgres container:
deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main 10

While in the ledgersmb container:
deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main

**Comment by nick-prater** [comment]
In my tests, this is a new issue. The backup is working, but not being captured and delivered to the browser - the backup is ending up in log files instead. Not an issue on master - only 1.5.

PGObject::Util::DBAdmin now uses Capture::Tiny to capture the pgdump output.

From the Capture::Tiny documentation:
```If code localizes any of Perl's standard filehandles before capturing, the capture will affect the localized filehandles and not the original ones. External system calls are not affected by localizing a filehandle in Perl and will continue to send output to the original filehandles (which will thus not be captured)```

**Comment by nicefiddler** [comment]
Is there a workaround? Do we need to register a new issue for this?
