### ISSUE TITLE
Backup database button in setup.pl, better error handling

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2687]
Relates to 
#2686 Backup database button in setup.pl does not work 

* Get exit status from pg_dump  - > inform user on error.
* Check for missing Ledgersmb temp dir (or not writeable)
* Full disk ?

**Comment by einhverfr** [comment]
we should be able to send the backup directly to the server without buffering on disk I would hope.

**Comment by ehuelsmann** [comment]
@nick-prater I think all of the above are now correctly handled, right?

**Comment by sbts** [comment]
@einhverfr you suggest we don't need to buffer to disk.
How would that work when a db contains at lease one file blob per invoice and order (both ar and ap)

In this case the db could easily be hundreds of MB in size. Potentially GB over time.

**Comment by nick-prater** [comment]
As it stands, we use a file to buffer the backup on disk and you're right that the db could be very large. I have tested that an error is raised if there is insufficient disk space.

With the new PGObject::Util::DBAdmin module, which we now require, the exit status of pg_dump is checked and an error reported to the user on failure.

We no longer use specific Ledgersmb temp dir - this is delegated to File::Temp and an error is raised if the tempfile cannot be written.
