### ISSUE TITLE
Diff 1.3 vs 1.5 -  Transition from reports to accounts

### ISSUE THREAD

**Issue by billott323** [ledgersmb/LedgerSMB#2689]
In 1.5, under Reports->Trial Balance/Inventory, clicking on the account number or account description takes you to the GL account. Under Balance sheet/Income statement, clicking on the amount takes you to the GL account. Seems like, when you want to go to an account you should click on the account and not the amount. 
In 1.3, the account number or the description takes you to the GL account, not the amount.

**Comment by ehuelsmann** [comment]
I don't understand this issue: on the 1.5 demo, in the Reports/Balance sheet, accounts don't link anywhere. In the Reports/Trial balance menu the accounts and their descriptions link to transactions. In Reports/Inventory, there *are* no accounts...

In General Journal/Chart of Accounts, the accounts and descriptions link to the account setup; the amounts link to transaction search.

**Comment by ehuelsmann** [comment]
Given the above, *and* the fact that this has been how it currently is for at least 3 (maybe 4) minor releases, I think we should leave it as it is, unless I'm missing an inconsistency.
