### ISSUE TITLE
LedgerSMB .rpm package build for 1.5 ->

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2694]
### Target:  Complete install with yum
`$ yum install ledgersmb`

for 
`Centos 7.x, Redhat 7.x, xyz` please add your target in the comments 

 - Package the missing perl modules
 - Install code
 - Setup production ready default database access rules
 - Add commits from #2691 rename conf/systemd/%run%-ledgersmb as a patch   
 - Create ledgersmb user and group
 - LedgerSMB running with Starman 
 - Setup and configure proxie
 - SELinux
 - Setup and configure SSL ( options: https://letsencrypt.org/ )
 - LedgerSMB GPG Key

### Call for testers and code.  
Please add a comment to this issue and subscribe to "Notifications" if you can help with code or testing. 

### Progress so far:
- the missing Perl .rpm packages are identified and manual packaged (needs more "polish" and automation)
- Working on `ledgersmb.spec` - (Current version does not work) 

### Current package resources
[Build & rpm .spec ](https://github.com/ledgersmb/LedgerSMB/tree/master/dists/rpm)
[Config files for systemd ](https://github.com/ledgersmb/LedgerSMB/tree/master/conf/systemd) to start LedgerSMB on boot

[Debian](https://packages.debian.org/search?searchon=sourcenames&keywords=ledgersmb) does not have a 1.5 .deb package.. yet.. (20. mars 2017) [Debian status](https://tracker.debian.org/pkg/ledgersmb)

#2691 Rename conf/systemd/%run%-ledgersmb to ledgersmb_%run%.service

**Comment by ehuelsmann** [comment]
While I agree that it'd be nice to have this, I'd like to defer it to packaging volunteers. We have packaging repositories in the `ledgersmb` organization here on GitHub, so feel free to request one.
