### ISSUE TITLE
CII Best Practices - check all boxes

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2700]
ehuelsmann: (or others)  It would be nice to get a review of the missing answers to "Bestpractices."
https://bestpractices.coreinfrastructure.org/projects/795#analysis
and in some of the other sections.

ehuelsmann: static analysis is something we do: Perl::Critic ( Added) 

https://matrix.to/#/!qyoLumPqusaXqFJNyK:matrix.org/$149037242487261nJXhk:matrix.org

dcg_mx: There's a "Getting started (Developing)" page, but it doesn't explain anything about our processes.
instead it explains about GitHub.
Can you maybe refer to the github pages for beginning developers and instead put our processes (overview) on that page?
hasorli: I think we may need to write down a few things before we can check all boxes

**Comment by ehuelsmann** [comment]
We're currently at 97%; we can knock the last 3% by either upgrading our test framework to 80% coverage or using a dynamic fuzzing tool to test our code.

**Comment by ehuelsmann** [comment]
We're actually at full compliance now!
