### ISSUE TITLE
Regression: Cannot update Vendor Address

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2709]
When attempting to edit a Credit Account address, you cannot update a contact's address. Contacts -> Search, find a contact, go to Address tab, click Edit. Page reloads and goes back to Company tab. Click Addresses, address is present in input form. Make an update, change Attach To back to Credit Account. There is no Save button, so click Save New Location. Result: Duplicate Key value violates unique constraint.

Also, Delete link next to address does not do anything.

**Comment by nick-prater** [comment]
Confirmed in 1.5.6 and master
