### ISSUE TITLE
LedgerSMB 1.5.5: Apparently after saving "Part" It has not been saved in the system.

### ISSUE THREAD

**Issue by star39** [ledgersmb/LedgerSMB#2714]
Dear All,

I try to be as short and clear as possible. I just say what I did. I created some vendors and parts with the intentions to create orders and start with the usual cycle.
The first part in the purchase order the "vendor"-part all went smoothly.
but second part I noticed "Part" , although the drop-down worked well the costprice was not mentioned. When I "updated" it then the system came with pop-up that products was not "known" and I came in the screen in which you have to indicate it is whether a service or a part. I clicked on "part" and then all was gone (meaning the initial purchase order.
In this respect I would like to say if I went to report "Parts" the relevant part was mentioned in the report list.
So i did again the purchase order not using "update" and keyed in manually "costprice" and saved it immediately (no update) of course.
When I go reports "purchase order" the order did not appear in there.

So in some way the "Parts" are "vanishing" in some way in the system.

For your info I am testing LedgerSMB 5 on its cycles Purchase and Sale.

Thank you in advance
Frans

**Comment by hasorli** [comment]
Frans ( @Star39 )  Are you testing on  LedgerSMB 1.5.5 ? 
Installed from https://sourceforge.net/projects/ledger-smb/files/ ?

**Comment by star39** [comment]
Yes indeed I am testing on LedgerSMB 1.5.5. You are experiencing the same as I do?

**Comment by einhverfr** [comment]
I wonder if the problem here is a caching problem.  Something to try would be refreshing your screen.  If that fixes the issue, we may need to look at what else we need to do to expire cached data from the parts dropdown.

**Comment by ehuelsmann** [comment]
@star39 there were problems with parts with capitals which were resolved in 1.5.7. They exhibit exactly the problem you're describing. Closing under that assumption. Could you re-open if the problem still exists on 1.5.7+ ? Please also provide some data about the parts you've created so we can simulate your situation, or (even better) create a failing part on demo.cloud.efficito.com/erp/1.5 and point us there.
