### ISSUE TITLE
admin user password change

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2717]
we should implement a password change function for the db admin user within setup.pl

**Comment by ehuelsmann** [comment]
Why?

**Comment by sbts** [comment]
Well, currently the admin has no way to change password other than knowing how to do so from a commandline SQL statement.
As we move more towards containerised distribution administrators have even more hoops to jump through to manage this.
ie: you either need to have knowledge on how to `docker inspect` as well as how to run the required sql, or you need to expose the pg container's port in some way to direct connect to the db.

**Comment by ehuelsmann** [comment]
Correct. But they need that knowledge in the first place to get to the
initial password. Also, when you loose the admin password, there is no way
to recover. So I would definitely favor making it a bit hard to change
admin passwords.

**Comment by sbts** [comment]
Hmm.
Setting the initial password in the docker containers is a simple edit of the config file.

Loss of admin password does require fixing from a command line, so it's not unrecoverable, just harder

**Comment by ehuelsmann** [comment]
I guess I was trying to say: if we stick with the design that the admin is a super user (and as far as I'm concerned we are), then this is by design and not something we can or I will fix.
