### ISSUE TITLE
Kernel or minimal version?

### ISSUE THREAD

**Issue by ppKrauss** [ledgersmb/LedgerSMB#2721]
Hi, sorry if here is not the place to questions... I am new here.

There are a "minimal version", a "kernel system" or a way to "clean" tables, etc. to get a minimal set of tables and functions to obtain a basic Accounting System?

PS: it will be a starting point to adapt to portuguese (lang=pt) and Brazilian law.

**Comment by sbts** [comment]
@ppKraus. Welcome.
If you look at the README.md file it contains information on a simple install. 
If you follow that you should end up with a simple system with a sample Chart Of Accounts configured for your company. 

If you have any questions or problems please either join our mailing list or chat room.
[Mailing Lists](https://sourceforge.net/p/ledger-smb/mailman/)
[Chat: #ledgersmb:matrix.org](https://riot.im/app/#/room/#ledgersmb:matrix.org)

We use [transifex.com](https://www.transifex.com/ledgersmb/ledgersmb/) for localisation (translation) with a partial Portuguese translation available already. 
We encourage everyone familiar with a language to contribute to the translation as much as possible.

**Comment by ehuelsmann** [comment]
Welcome to the community!

The application as it's being installed is basically "it". It's possible to grant people fewer rights in the system, resulting in fewer functionalities being available. It's possible to remove roles until the only remaining functionality is to enter and search for GL transactions and run the trial balance, balance sheet and income statement reports. (For that to work, you'll also need some System menus, like setting up some defaults and creation of GL accounts, but that's really it.)

Basically, that's the absolute minimum we can do. However, I'm assuming you want accounts receivable, accounts payable and payments too. This all can be managed with roles. On the database level, all the tables and functions remain though. I hope that's good for you?

Taking @sbts's response a bit further: we really want to be compliant with as many locales as we can be. To that extent, we're looking for people to contribute to the project who can keep an eye out for changing regulations in their jurisdiction and can inform the project about the upcoming changes. Then - as a project - we can adjust to the changes and release new software.

You indicate you want to make chances for Brazilian law. Do you have an assessment of our current level of (non-)compliance? I'd be eager to learn about it.

Regards,

Erik.

**Comment by ppKrauss** [comment]
Thanks @sbts and @ehuelsmann. Hum... many points to align... Introducing myself and my goals here.

I am a [member of the Open Knowledge Network at Brazil Chapter](http://br.okfn.org/membros) and my aim is in that context, but interest is still personal, we are just probing possibilities: the ultimate goal is to use the LedgerSMB tables as operational and fine-grained data-interchange standard. The main (direct and indirect) LedgerSMB users will be transparent [condominium](https://en.wikipedia.org/wiki/Condominium) and transparent  [cooperative](https://en.wikipedia.org/wiki/Cooperative).

Big picture of the context of use of LedgerSMB, with other [*open contracting* technologies](http://www.open-contracting.org/):

* use of [CKAN](https://ckan.org/) and [LexML](http://projeto.lexml.gov.br/documentacao/resumo-em-ingles): public documents and public IDs ([URN LEX](https://en.wikipedia.org/wiki/Lex_(URN)) are like [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier)) of the normative documents.

* use of [Data Packaged Core Datasets](https://github.com/datasets): for public datasets,  example [state-codes](https://github.com/datasets-br/state-codes) or [Brazilian Standard Classification of Occupations](https://github.com/datasets-br/cbo).

* use of PostgreSQL 9.6+ to maintain online services (official backup) for fine-grained data, and to generate standard reports using LedgerSMB or similar one...  We are studing the use of [JWT tokens](https://jwt.io/) and services at  [API Gateway complemented by PostgREST](https://github.com/ppKrauss/PostgREST-writeAPI).

-----

Answering each point... A final decision will be in 2 or 3 weeks.

## Translation

[transifex.com is "not so open"](https://www.transifex.com/pricing/)... It is a problem, but we can translate when confirm that all translation [**licences** and formats are open](http://opendefinition.org/licenses/).

Other strategy is to add **semantic reference** in each table and each column, using [SchemaOrg](http://schema.org/docs/schemas.html) and [Wikidata](https://www.wikidata.org) vocabularies. Examples:

* the concept of [*current asset*](https://en.wikipedia.org/wiki/Current_asset) has the [Wikidata ID Q730884](https://www.wikidata.org/wiki/Q730884);

* the main *bank account* are properties of the [SchemaOrg *BankAccount* class](https://schema.org/BankAccount) &mdash;  and other more specific financial product types, as *[BrokerageAccount](https://pending.schema.org/BrokerageAccount), [CurrencyConversionService](https://pending.schema.org/CurrencyConversionService), [InvestmentOrDeposit](https://pending.schema.org/InvestmentOrDeposit), [LoanOrCredit](https://pending.schema.org/LoanOrCredit)*, etc.

* the main *monetary amounts* are properties of the [SchemaOrg *MonetaryAmount* class](https://schema.org/MonetaryAmount).

Semantic is a core issue, when using SQL tables as foundation for open data-interchange.
  
##  Fewer functionalities

I can help to write a README ("for dummies" installing at UBUNTU 16 LTS)  with all instructions to obtain the "Fewer functionalities LedgerSMB" version.  Will will try to install in few weeks, them we can start to talk, I think I will have many doubts.

**Comment by hasorli** [comment]
@ppKrauss Transifex is just a tool we use to get more people involved. You can get the (standard and open) .po files to translate from https://github.com/ledgersmb/LedgerSMB/tree/master/locale/po
The licence on the translation is GPLv2 (same as the LedgerSMB application).

**Comment by einhverfr** [comment]
One other thing worth noting here is that we have been spinning off a lot of general functionality into other libraries.  I don't expect that will stop.  In fact if we could cpanize the application and have pieces on CPAN, that might actually be ideal, but we are so far from being able to really do this that it isn't worth discussing as anything more than a pie-in-the-sky ideal.

**Comment by einhverfr** [comment]
Closing this for now.  If further discussion is necessary, feel free to re-open.
