### ISSUE TITLE
Add templates and print button etc for all reports

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2781]
On the dev list Michael has asked about ways of printing various reports. He suggested having a 'print' css which is not ideal as it's difficult to customise. As we already have a print subsystem for invoices etc we should leverage that for reports also.

**Comment by ehuelsmann** [comment]
I'm not sure what's being asked. Reports have PDF links. You want the reports to be sent to a remote (server based) printer? Or download the thing by "print to screen" and send the PDF to the printer???

**Comment by ehuelsmann** [comment]
I'm not sure what's being asked, but if the question is to have customizable templates report (balance sheet, income statement & generic reports), then that is indeed what we have added for 1.8. I think that fulfills this enhancement request.
