### ISSUE TITLE
permalink button mangles links the 2nd time around

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2783]
Michael reported this in [this email](https://sourceforge.net/p/ledger-smb/mailman/message/35818601/)
Using a permalink results in the displayed permalink button presenting a link that invalidates the session.

I've just had a play on https://efficito.com/demo and reproduced this.

The steps are....

- General Jornal => Search and GL
- Select an Account  (1000--CURRENT ASSETS)
- Continue
- Click on [permalink]
You are now at the first link you shown below
- Click on [permalink] again
Your session is force expired as you have tried to visit the second link.

[LINK 1](https://demo.cloud.efficito.com/erp/1.5/login.pl?action=login&company=demo15#https://demo.cloud.efficito.com/erp/1.5/journal.pl?action=search&sort=transdate&reference=&accno=1000&source=&memo=&description=&notes=&business_unit_1=&business_unit_2=&business_unit_3=&business_unit_4=&business_unit_5=&bc_count=5&from_date=&to_date=&from_month=&from_year=&interval=none&from_amount=&to_amount=&category=X&is_approved=Y&col_transdate=Y&col_reference=Y&col_description=Y&col_debits=Y&col_credits=Y&col_source=Y&col_accno=Y&path=bin%2Fmozilla&login=demo_en&company=demo15#s2)
[LINK 2](https://demo.cloud.efficito.com/erp/1.5/login.pl?action=login&company=demo15#https://demo.cloud.efficito.com/erp/1.5/journal.pl?action=search&sort=transdate&reference=&accno=1000&source=&memo=&description=&notes=&business_unit_1=&business_unit_2=&business_unit_3=&business_unit_4=&business_unit_5=&bc_count=5&from_date=&to_date=&from_month=&from_year=&interval=none&from_amount=&to_amount=&category=X&is_approved=Y&col_transdate=Y&col_reference=Y&col_description=Y&col_debits=Y&col_credits=Y&col_source=Y&col_accno=Y&path=bin%2Fmozilla&login=demo_en&company=demo15&company=demo15#s1)
The only difference between the two links the end of the link
    &company=demo15#s2
vs
    &company=demo15&company=demo15#s1

**Comment by einhverfr** [comment]
ah.... so what is happening here is that company is being appended each time you click it.  We need to fix that.  This is a bug that I would expect probably happens in 1.4 and later.

**Comment by einhverfr** [comment]
verified that this happens with 1.4 and higher.  I think the solution is to to check the URL before we append.  That should be nicely contained, robust, and clear.  I could have a PR on that fairly soon.

This sort of thing will affect clients and is pretty clearly a bug.  I think we need to fix it on all supported versions.

**Comment by einhverfr** [comment]
Testing a fix now for 1.4, 1.5, and master.
