### ISSUE TITLE
Add print css

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2785]
On the Mailing list Michael has asked for some print CSS to be added.
While for his original request #2781 makes more sense (printing reports) he makes a valid point in a later email where he suggests a print css would facilitate printing "any page" including partially completed forms.

@ehuelsmann do you have any objection to this capability?

Priority for the dev team on this will be low, but if anyone would like to contribute a user style (using stylish browser plugin) we are happy to add it for the next release.

**Comment by ehuelsmann** [comment]
I experimented with this a bit, but it seems Dojo does some heavy calculations with absolute values. No longer marking as `bite-sized`, because those absolute width settings complicate matters.

**Comment by ehuelsmann** [comment]
Based on the fact that we will soon be having separate printable html templates (separated from UI components) which may include their own css combined with my prior testing that our dojo UI does lots of unprintable things: I'm thinking we should no longer want this change.
