### ISSUE TITLE
installation documentation improvement in regards to perl modules & apache

### ISSUE THREAD

**Issue by redgrapetech** [ledgersmb/LedgerSMB#2791]
(1) 

We need to indicate the need of installation of  following perl modules
libhttp-exception-perl
cpanm PGObject::Type::BigFloat
cpanm PGObject::Type::DateTime
cpanm PGObject::Type::ByteString
cpanm Plack::Builder::Conditionals
cpanm App::LedgerSMB::Admin::Database

(2) We need to indicate the activation of following in case apache is used

a2enmod rewrite
a2enmod proxy
a2enmod proxy_http

(3) The example vhost setup should also include a non-ssl config 
As at times the SSL enabled front end is on a separate server
than the one on which PSGI app is running , as the PSGI app
runs on  127.0.0.1:5762 ,  2 apache's are involved  , enabling
SSL on both proxy leads to other complications.

Eg: In my setup I have a common(shared)  frontend (SSL-enabled) for many apps 
and ledgersmb being one of them. Most of my apps run as sub-domains of 
my corporate domain 

mentioning @sbts

**Comment by redgrapetech** [comment]
It would be better to make the redirect for /login.pl in vhost example 
http schema aware.

```
###########################################
  RewriteCond %{HTTP:X-Forwarded-Proto} =https
  RewriteRule .* - [E=proto:https]
  RewriteCond %{HTTP:X-Forwarded-Proto} =http
  RewriteRule .* - [E=proto:http]
  # Rewrite '/' URL to /login.pl script
  RewriteRule "^/$"  %{ENV:proto}://%{HTTP_HOST}/login.pl [R=301,L]
```
the frontend also needs to include below for setting the  X-Forwarded-Proto
header appropriately.

```
 RequestHeader set X-Forwarded-Proto  https env=HTTPS
 RequestHeader set X-Forwarded-Proto  http env=!HTTPS

```

**Comment by redgrapetech** [comment]
the following tip for auto-redirection of http to https may also be included.

```
 RewriteEngine On
 RewriteCond %{HTTPS} off
 RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

```

**Comment by sbts** [comment]
@redgrapetech I'd disagree with adding straight http handling as that becomes a risk.
I do agree about redirecting http to https.

There is no need to run 2 httpd's in series, 
Starman it's self can be set up to listen on a local network port (see the --listen argument).
And if you want an internal httpd for the speed gains (as well as the external one) you should be able to point both httpd at the same starman instance.

From my local tests (with nginx) things run slightly faster once starman is reverse proxied due to static asset caching so even for a local install it's desirable.

While you don't *__have__* to run https for a local network it is highly recommended especially if you may have untrusted clients on the network. (Smart TV's etc are untrusted clients).
For access from a remote network however it's essential that you run reverse proxies and under https for security reasons.

**Comment by redgrapetech** [comment]
Dear David , 

Of course  one size does not fits all and my suggestion is of keeping maximum no of sizes.

In my case I have a public facing SSL enabled frontend that proxies to many apps
based on the virtual host being used , ledgersmb being one of the apps. I do agree
running 2 httpd in series is awkward , but how do we offload the application
server (starman) from serving the static assets , in  case the frontend and backend
are on separate hosts. moreover if starman is configured to  listen on a local network port ( ie NOT localhost or 127.0.0.1 )  then it poses the same risk as running a straight http server.

we would definitely NOT want starman to do SSL processing  and leave that with the 
reverse proxies I guess.

kind regards
Rajesh Kumar Mallah ( rmallah )

**Comment by redgrapetech** [comment]
I also had to add below to `/etc/systemd/system/starman-ledgersmb.service` 

```
Environment=LSMB_CONFIG_FILE=/usr/local/ledgersmb/conf/ledgersmb.conf 
```
in the `[Service]`  section otherwise below warnings were coming in syslog

```
May  7 12:21:31 ledgersmb starman[1999]: No configuration file; running with default settings
May  7 12:21:31 ledgersmb starman[1999]: No configuration file; running with default settings
May  7 12:21:31 ledgersmb starman[1999]: No configuration file; running with default settings
```

**Comment by ehuelsmann** [comment]
Thank you for the documentation additions. I've got them implemented. I'm afraid that the setup you're running and the additional config examples you're suggesting because of that, is beyond the scope of the example documentation we mean to provide.

Hope you're still enjoying LedgerSMB!

**Comment by rmallah** [comment]
Thanks Eric for incorporating whatever points were applicable.
