### ISSUE TITLE
Update website "Areas to Contribute"

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2793]
Rmallah said (in #ledgersmb
> Hi I was having a look at Areas to Contribute  ( https://ledgersmb.org/topic/areas-contribute )  to and I am interested to work on "Windows Installer"  , is there anyone already working on it so that i could collaborate.

dcg_mx 
> rmallah: hmm. There are issues with running the server on windows these days.
> Rather than running it directly it would be better to work on testing and documenting how to run our docker container on windows

**Comment by ehuelsmann** [comment]
Feel free to remove the bullet next time. No need to have it sitting 1+ months in the tracker. When you do put in the tracker, please mark with "bite-sized" and "task".

**Comment by ehuelsmann** [comment]
Page updated: bullet removed.
