### ISSUE TITLE
new test to confirm code and pod versions match

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2812]
in many files (see https://github.com/ehuelsmann/perl-Test-Dependencies/pull/8/files for an example or 3) we have both a module version and POD version.
Currently there is no way to ensure these versions stay in sync, or are both present (where required)

To the best of @ehuelsmann and my knowledge there is no better way to handle this as POD requires the version entry and so does the module code, but there is no mechanism to share the data from a single declaration

I'll write a test script for that as early as possible.

**Comment by ehuelsmann** [comment]
Dist::Zilla can take care of this (i.e. sync the numbers)

**Comment by ehuelsmann** [comment]
@sbts is this still a priority? Dist::Zilla van take care of it and even generate both code and pod versions

**Comment by sbts** [comment]
If Dist::Zilla can take care of this and it's been implemented then I thinknthats the best solution. 
Nothing extra for us to maintain then.

**Comment by ehuelsmann** [comment]
I'm not really sure what the issue is here. Should all our modules have a single version, being the same version as the version having been released? Or...?

Anyway, we're not a library and we're not publishing to CPAN, so Dist::Zilla isn't on my agenda for the moment...
