### ISSUE TITLE
Database Schema Upgrade interlock improvements

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2813]
Looking at [Database schema upgrades - data migrations](https://github.com/ledgersmb/LedgerSMB/wiki/Database-schema-upgrades----data-migrations)
We currently say.....
> Under this scheme, it's of vital importance that the change files do not get edited once they have been published in a release.

That needs to change to....
> Under this scheme, it's of vital importance that the change files do not get edited once they have been published.

Also as we already have code to md5sum that file (when storing the md5sum in the schema) why don't we append the md5sum to the filename (via a "tool" script that processes all files in the `changes` dir that DON'T have an md5sum in the filename already) and also in a file "changes.md5" file that only gets appended to.
We can then have a test that verifies that all changes have been processed, and no file has had it's md5 changed

In [this discussion](https://matrix.to/#/!qyoLumPqusaXqFJNyK:matrix.org/$14951248816130iNeqc:matrix.org) in #ledgersmb @ehuelsmann said....
> agreed
I think that's a good improvement indeed

I'll look to implement that in the near future.

**Comment by ehuelsmann** [comment]
These days we have means to create new versions of schema update files, so there's no issue changing the files. Just that it should happen in a specific way.
