### ISSUE TITLE
Contact Info not escaped properly

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#2820]
Tested in 1.5.6 and 1.6

* Open an existing contact
* Click Contact Info tab
* Enter a new contact containing a '+' character
* Click Save Contact
* Note that details have been correctly saved
* Click Edit on the saved contact
* Note that displayed form fields have translated '+' into a space.

This problem was found trying to edit an international telephone number prefixed with '+353'.

**Comment by ehuelsmann** [comment]
As it turns out, this *could* apply to bank account data too (in case that contains non-alphanumeric characters).
