### ISSUE TITLE
Paramaterise port number in Is_LSMB_running.sh

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2842]
To support dev in docker containers we shouldn't hardcode the port to 5001.
Instead use a variable that defaults to 5001, but can be overridden by ENV VARs that the docker containers set

**Comment by sbts** [comment]
@ehuelsmann tagging you

**Comment by nick-prater** [comment]
Resolved by #3325 - can be closed.

**Comment by ehuelsmann** [comment]
Closed by #3325 as indicated by @nick-prater
