### ISSUE TITLE
Description search is sensitive to timing

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2846]
1.5.6

In Sales / Purchase orders, searching for products via their desciption renders a list of products. Choosing one, and then immediately hitting Update will result in lsmb finding the first product in it's system, probably not the one you're looking for.

**Comment by ehuelsmann** [comment]
How long do you need to pause for the selected product to "hold"? (and how fast is "immediately"?) Do you have any idea what the timings to your server are? I mean, is there a significant lag between client and server?

**Comment by kaare** [comment]
The product dropdown is virtually appearing immediately. After choosing one product, there is a delay of approximate 1 second before the part number appears in the number field.

**Comment by ehuelsmann** [comment]
I'm sure it was this way before, but today, I'm not seeing this behaviour. The update of the part code is immediate.
