### ISSUE TITLE
Attaching a file to a product doesn't work

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2859]
Searching a product, pushing "attach" and a new page where you can browse for a file. Finding a odt (LibreOffice) file, and pushing "Upload" returns this box: 

--

Error!

Cannot bind a reference

dbversion: 1.5.6, company: jasonic

--

Nothing immediately visible on the server, or in the pg logs.

**Comment by ehuelsmann** [comment]
Traced this error back to https://github.com/ledgersmb/PGObject-Simple/commit/704b974cc00da04c72bfee037cd5f9dc67c45b0e#commitcomment-22476384 ; added review comments.

**Comment by ehuelsmann** [comment]
@kaare the short term solution is to remove [line 259](https://github.com/ledgersmb/PGObject-Simple/commit/704b974cc00da04c72bfee037cd5f9dc67c45b0e#diff-0e5939d54708aa0214300a125e102c8aR259) from PGObject::Simple.
