### ISSUE TITLE
investigate better temp file handling

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2861]
http://search.cpan.org/~dagolden/File-Temp-0.2304/lib/File/Temp.pm looks like it may be a good choice and it likely deletes files once they are closed. Do some tests across platforms to confirm before we switch to it.

**Comment by nick-prater** [comment]
We're now using File::Temp in a number of places. I think this issue can now be closed. Is there anything else you feel needs addressing, or are you happy to close this issue?

**Comment by ehuelsmann** [comment]
Closing: done.
