### ISSUE TITLE
Recurring transaction failure v1.5.7 

### ISSUE THREAD

**Issue by billott323** [ledgersmb/LedgerSMB#2888]
Upon logging into v1.5.7, performing one recurring transaction (editing and saving a schedule or processing a transaction) completes successfully. Any subsequent recurring transaction, as described above fails with this error.
```
Error!

'Undefined subroutine &lsmb_legacy::edit_recurring called at bin/old-handler.pl line 169. '

dbversion: 1.5.7, company: YourCompany
```
As a workaround, the error can be cleared by logging out and back in. This error occurs on any instance of 1.5.7, including the  Demo.

**Comment by ehuelsmann** [comment]
@billott323, no need to completely log out. Workaround: click on the Recurring Transactions menu to reload the screen. That should work just as well as going through the entire logout/login cycle.
