### ISSUE TITLE
Order entry and part numbers

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2889]
1.5.6

Part numbers don't need to be numeric in the system, but the order entry screen complains if you enter a non-numeric number.

It will find it, though, but what worse is that numbers containing non-alphanumeric characters, like '-', will be found by the dropdown locator, but not accepted when updating the order.

Either accept any character everywhere in the system, or restrict what can be created.

**Comment by ehuelsmann** [comment]
I can't reproduce on the demo system. I've tried entering a sales order and a purchase order for the 'web-02' service in the demo system against the 'ABC123' customer and 'ABC' vendor respectively. Selection and updating work fine for me on demo. Could you have a go at reproducing on the demo and let me know which steps you used, if/when you succeed?

Thanks!

**Comment by kaare** [comment]
It's true; it doesn't behave like this on the demo system. I will try to update to 1.5.7 and see if that fixes the problem.

**Comment by kaare** [comment]
I updated to 1.5.7 and the problem went away.

**Comment by ehuelsmann** [comment]
Thanks for the feedback and testing!
