### ISSUE TITLE
test for file permissions and hashbangs

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2899]
we have a very small number of files that need special permissions like executable. Also very few that need a hashbang. Use a whitelist to test for those.

**Comment by jame** [comment]
This may already be known but as an example of a type of exception, of a file with a pl extension that doe not need a hashbang or its executable bit set:  the files in the tools/ directory all have hashbangs in them and a pl, sh, or psgi extension except for one, which is installer.pl.   That one has the pl extension but no hashbang and its executable bit is not set, and according to the documentation in the file itself it's supposed to be that way as it's supposed to be run by Perl at the command line.

**Comment by jame** [comment]
As of LedgerSMB v1.5.8, the file 'sql/modules/reload_modules.sh' is not set as executable but should be.  Issue also seems to be present in the master branch.

**Comment by ehuelsmann** [comment]
Apart from maintaining a clean tree, did we ever deliver the incorrect permissions? Is that what's triggering this issue? If so, what was the issue?

**Comment by sbts** [comment]
There are a variety of reasons that permissions were incorrect, including historical use of git on windows (or at least on SMB shares and VFAT/NTFS disks) where permissions were not correctly propagated back to the repo (from what I can tell)

Tools such as Lintian (used especially during debian packaging) will often complain about incorrect executable permissions, or unexpected #!'s for security purposes

In reality we should only have a very small number of executable files I'd expect

**Comment by ehuelsmann** [comment]
Instead of solving this issue, I'll wait for the lintian errors: there's only a small number of files and a small chance for error.

**Comment by sbts** [comment]
@ehuelsmann this issue was originally triggered by lintian errors reported by jame.
I believe we fixed those at the time,  but raised this issue to ensure we eventually added an appropriate test to prevent recurrence in a release set.
