### ISSUE TITLE
Provide a sysvinit init.d script for starman-ledgesmb

### ISSUE THREAD

**Issue by jame** [ledgersmb/LedgerSMB#2900]
Although Debian (and others) do now use systemd by default, it does still support sysvinit init.d scripts as well, so providing at least an example init.d sysvinit startup script for starman-ledgersmb would be quite useful.

**Comment by sbts** [comment]
I'll arrange this.
It's a trivial enough thing to add.
Not sure it will see much use these days though

**Comment by ehuelsmann** [comment]
At Efficito we use a Perl wrapper for that: Daemon::Control. It generates an `init.d` script based on parameters passed:

```perl
#!/usr/bin/perl

use warnings;
use strict;
use Daemon::Control;
use File::Path qw(make_path);

my $app_home = '/usr/local/ledgersmb';
my $program  = '/usr/bin/starman';
my $name     = 'LedgerSMB-1.4';
my $pid_dir  = '/run/starman';
my $log_dir  = '/var/log/starman/ledgersmb';
my $pid_file = $pid_dir . '/starman-ledgersmb.pid';

my $workers = 3;
my $port = 5762;

my $stderr_file = $log_dir . '/ledgersmb.err.log';
my $stdout_file = $log_dir . '/ledgersmb.out.log';

make_path($pid_dir, { chmod => 0750 })
    if ! -d $pid_dir;

make_path($log_dir, { chmod => 0750 })
    if ! -d $log_dir;

my ($unused1, $unused2, $starman_uid) = getpwnam('starman');
my ($unused3, $unused4, $starman_gid) = getgrnam('starman');

chown $starman_uid, $starman_gid, $pid_dir, $log_dir;

Daemon::Control->new({
    name        => $name,
    lsb_start   => '$apache2',
    lsb_stop    => '$apache2',
    lsb_sdesc   => $name,
    lsb_desc    => $name,

    user        => 'starman',
    group       => 'starman',

    directory   => $app_home,
    program     => "$program -E production -Ilib --preload-app tools/starman.psgi --workers $workers --listen :$port --access-log $log_dir/starman_access.log --error-log $log_dir/starman_error.log",

    pid_file    => $pid_file,
    stderr_file => $stderr_file,
    stdout_file => $stdout_file,

    fork        => 2,
})->run;
```

**Comment by sbts** [comment]
That looks to me like a good option. 
@jame if you are happy with that fine, 
Otherwise let me now and I'll submit a standard script

**Comment by jame** [comment]
@sbts It may not be used much these days but it's easy to provide an example so I think we should.  The issue causes a [Lintian error](https://lintian.debian.org/tags/init.d-script-not-included-in-package.html) during a package build and while that can be hidden if necessary for the [ledgersmb-1.5](https://github.com/ledgersmb/pkg-ledgersmb-1.5) package, it cannot really be hidden for the [ledgersmb](https://tracker.debian.org/pkg/ledgersmb) package.  Easier and better to just provide an example init script.

**Comment by jame** [comment]
@sbts @ehuelsmann  I'm not sure what a 'standard' sysv init script looks like nowadays, so I'll check to see what the output of that script looks like, compared to what I've already tried coming up  with.

**Comment by jame** [comment]
@ehuelsmann I think I can see why that script is used like you do but even with generating an init file from it, there isn't enough information to serve as an example, I don't think.
So @sbts, I think an example sysv init file with comments (including regarding environmental variables, like for the LedgerSMB config file) would be the way to go.  (Once available, I can easily patch it to adapt it to the packaging as necessary, like I already do for the systemd service file.)

**Comment by sbts** [comment]
@jame no problem. 
I'll put something together

**Comment by funkypenguin** [comment]
FYI, we'll give it some use. We're still on CentOS6, so this will be appreciated ;)

**Comment by funkypenguin** [comment]
Ended up with this, which works quite well for us:

````
#!/bin/bash
#
# starman      RHEL/CENTOS init script for Starman web server
#
# chkconfig: 345 56 50
# description: Runs the Starman web server in production environments.
#              Uses start_server superdaemon for graceful restarts and
#              runs as user/group "nobody." Expects local Perl install
#              with plenv.
#              HOME and environment setup must be customized for environment.
#              See also perldoc Starman and Server::Starter.
#              Repository: https://github.com/mla/starman-init
#
# pidfile: /var/run/starman.pid

# app settings
PATH=/usr/local/texlive/2016/bin/x86_64-linux/:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
HOME=/usr/local/ledgersmb
APP_HOME=$HOME/tools
APP=$APP_HOME/starman.psgi
APP_NAME=$(basename $(readlink -f $0))
START_SERVER=/usr/bin/start_server
STARMAN=/usr/bin/starman
PORT=5000
WORKERS=4
USER=nobody
GROUP=nobody

PID_FILE=/var/run/$APP_NAME.pid
STATUS_FILE=/var/run/$APP_NAME.status
LOCK_FILE=/var/lock/subsys/$APP_NAME
LOGDIR=/var/log/$APP_NAME

cd $HOME || exit 3

# Source function library.
. /etc/init.d/functions

# Get config.
test -f /etc/sysconfig/network && . /etc/sysconfig/network

# Check that we are root
[ `id -u` = 0 ] || { echo "must be root"; exit 1; }

# Check that networking is up.
[ "${NETWORKING}" = "yes" ] || exit 0

RETVAL=0

start(){
    echo -n $"Starting $APP_NAME: "

    mkdir -p $LOGDIR

    daemon --pidfile $PID_FILE \
      $START_SERVER \
        --interval=5 \
        --port=$PORT \
        --signal-on-hup=QUIT \
        --pid-file=$PID_FILE \
        --status-file=$STATUS_FILE \
        -- \
        $STARMAN \
          --workers $WORKERS \
          --user $USER \
          --group $GROUP \
          --error-log $LOGDIR/error.log \
          --access-log $LOGDIR/access.log \
          $APP \
          &

    RETVAL=$?
    echo
    touch $LOCK_FILE
    return $RETVAL
}

stop(){
    echo -n $"Stopping $APP_NAME: "
    killproc -p $PID_FILE $APP_NAME
    RETVAL=$?
    echo
    rm -f $LOCK_FILE
    return $RETVAL
}

graceful(){
    if [ -s $PID_FILE ]; then
      echo -n $"Gracefully restarting $APP_NAME: "
      $START_SERVER \
        --pid-file $PID_FILE \
        --status-file $STATUS_FILE \
        --restart
      RETVAL=$?
      echo
      return $RETVAL
    else
      echo $"Not running."
      start
    fi
}

restart(){
    stop
    start
}

condrestart(){
    [ -e $LOCK_FILE ] && restart
    return 0
}


# See how we were called.
case "$1" in
    start)
 start
 ;;
    stop)
 stop
 ;;
    status)
 status -p $PID_FILE $APP_NAME
 ;;
    graceful)
 graceful
 ;;
    restart)
 restart
 ;;
    condrestart)
 condrestart
 ;;
    *)
 echo $"Usage: $0 {start|stop|status|graceful|restart|condrestart|reload}"
 RETVAL=1
esac

exit $RETVAL
````

**Comment by jame** [comment]
@funkypenguin, that does look good to me (and is similar to what I found and tried to adapt) but it does appear to be somewhat RHEL/CENTOS specific.  OTOH, I also think it could be good idea to provide examples files for both Debian and RHEL/CENTOS systems.

However, something that @sbts noted in IRC about the version I'd initially tried;  "can't use --user and --group arguments to starman".  "Starman doesn't drop it's privileges early enough. That results in some of our code being run as root. Including setup of the tempdir"    So I've moved the user/group setting to the 'start-stop-daemon' (instead of 'daemon') and will be trying it that way the next time I test.

**Comment by ehuelsmann** [comment]
Note that since some time, we're not creating the temporary directory at bootup anymore, which eliminated the problems with the temporary directory ownership which relates to @sbts's warning not to start starman with its `--user` and `--group` options from `root`.
