### ISSUE TITLE
Error when printing to html

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2919]
1.5.7

Trying to print a sales order as html to screen results in a file with this error:

This page contains the following errors:
error on line 7 at column 15: AttValue: " or ' expected

Trying the same in the demo system returns nothing. In fact no option (csv, html, pdf) returns any print in the demo system.

**Comment by ehuelsmann** [comment]
Thanks for the heads up. The HTML output in the demo system has been fixed (still working on the PDF side of things).

Are you using 1.5.7 from the tarball or from Git? In case of Git, do you use compiled Dojo assets (`make dojo`)?

In all cases, did you force your browser to reload the assets by hard-reloading the page?

**Comment by kaare** [comment]
Found out the error comes from konqueror using khtml for html rendering. Probably the page isn't following html syntax but other browsers are more lax about it.

**Comment by ehuelsmann** [comment]
1.5.7 is *old*. Closing as assumed-handled. If not, please re-open.
