### ISSUE TITLE
Allow complete HTML validation

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2930]
HTML code is checked for validity to ensure quality, except when Template conditionals are used because of the difficulty to handle the conditions at test time.
We also skip menu validation because the code is generated dynamically. The upcoming switch to Dojo menus will fix that.

**Comment by ehuelsmann** [comment]
Dojo and Vue work with html fragments too. In other words, it's unlikely we will refer validate the full html.
