### ISSUE TITLE
Inventory Activity Report Not Showing Purchases

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2934]
Not sure what went wrong here but it used to (in 1.2/1.3).  This is confirmed on demo

**Comment by ehuelsmann** [comment]
I've completely rewritten the inventory adjustments & activity tracking in master/1.6; is this broken on 'master' too? If not, I propose we solve this in 1.6, because the full changes are too big to backport to 1.4/1.5.

**Comment by ehuelsmann** [comment]
This is fixed in 1.6; anyone missing this functionality should be using 1.6 (which isn't released at the time of closing this ticket, unfortunately...)
