### ISSUE TITLE
Add packager.io builds for RHEL and SLES

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2939]
This would allow us to support these platforms via native builds once again, though until we get a Real Packager(TM) we could not distribute src.rpm formatted packages,

**Comment by ehuelsmann** [comment]
@einhverfr you're aware we have absolutely perfectly great Docker packages these days? (Those have "batteries included" as well, which is what I got from the packager.io website)

**Comment by ehuelsmann** [comment]
Packager.io is based on buildpack, which doesn't support Perl (at the moment?):

![Screenshot from 2019-12-21 18-25-02](https://user-images.githubusercontent.com/2326559/71311450-4cd78400-241f-11ea-9c13-56c877f85808.png)
