### ISSUE TITLE
Need better separation of test cases from test data sets

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2943]
This makes it very hard to compose data sets in a way that allows us to meaningfully extend the database tests.  As a result I find myself putting tests where the data is rather than where we can remember where they are.

**Comment by ehuelsmann** [comment]
Solution to this issue is to use bdd scenarios which generate their own data. An example has recently been added in the form of a number of COGS testing scenarios where bdd isn't used to drive the browser, but just the pl/SQL.
