### ISSUE TITLE
investigate payment gateway integration for [authorize.net](https://authorize.net)

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2944]
John says [here](https://matrix.to/#/!qyoLumPqusaXqFJNyK:matrix.org/$14987559663036eaaLw:matrix.freelock.com) that they have a good api and support, along with easing PCI compliance in the US allowing SAQ-C level. kronos003 is definitely interested. Also John says that many other payment gateways base their api off of [authorize.net's](https://authorize.net) api

**Comment by einhverfr** [comment]
I think the immediate question is what sort of integration we need.  For payments chances are these would happen on another app I would assume?  And there is Business::OnlinePayment::AuthorizeNet.  But what about payment notifications?

**Comment by ehuelsmann** [comment]
Can someone add a use case description as per Chris's request? Itoo have a hard time imagining what would be the integration case.

**Comment by sbts** [comment]
@freelock is this still relevant today?
