### ISSUE TITLE
File::MimeInfo depends on freedesktop.org; breaks on MacOS X

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2945]
Trying to install on OS X fails because File::MimeInfo cannot be installed.  It turns out that this module depends on free desktop.org utilities in order to work and therefore tests don't pass.  For my testing system I am just forcing this and noting that file uploads won;t work. But we will see what else is broken.

It is also possible that there may be an additional dependency-related bug in File::MimeInfo.  We may want to look at moving away from this at some point in the future.

**Comment by sbts** [comment]
@einhverfr can you provide links related to the MimeInfo issue?

**Comment by einhverfr** [comment]
I can provide output from the cpan File::MimeInfo
`
Reading '/Users/christravers/.cpan/Metadata'
  Database was generated on Fri, 30 Jun 2017 08:53:59 GMT
Fetching with LWP:
http://cpan.metacpan.org/authors/01mailrc.txt.gz
Reading '/Users/christravers/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://cpan.metacpan.org/modules/02packages.details.txt.gz
Reading '/Users/christravers/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Sat, 01 Jul 2017 07:53:57 GMT
.............
  New CPAN.pm version (v2.16) available.
  [Currently running version is v2.00]
  You might want to try
    install CPAN
    reload cpan
  to both upgrade CPAN.pm and run the new version without leaving
  the current session.


...............................................................DONE
Fetching with LWP:
http://cpan.metacpan.org/modules/03modlist.data.gz
Reading '/Users/christravers/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /Users/christravers/.cpan/Metadata
Running install for module 'File::MimeInfo'
Running make for M/MI/MICHIELB/File-MimeInfo-0.28.tar.gz
Checksum for /Users/christravers/.cpan/sources/authors/id/M/MI/MICHIELB/File-MimeInfo-0.28.tar.gz ok

  CPAN.pm: Building M/MI/MICHIELB/File-MimeInfo-0.28.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for File::MimeInfo
Writing MYMETA.yml and MYMETA.json
cp lib/File/MimeInfo/Cookbook.pod blib/lib/File/MimeInfo/Cookbook.pod
cp lib/File/MimeInfo/Rox.pm blib/lib/File/MimeInfo/Rox.pm
cp lib/File/MimeInfo/Applications.pm blib/lib/File/MimeInfo/Applications.pm
cp lib/File/MimeInfo.pm blib/lib/File/MimeInfo.pm
cp lib/File/MimeInfo/Magic.pm blib/lib/File/MimeInfo/Magic.pm
cp mimeopen blib/script/mimeopen
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mimeopen
cp mimetype blib/script/mimetype
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mimetype
Manifying blib/man1/mimetype.1
Manifying blib/man1/mimeopen.1
Manifying blib/man3/File::MimeInfo::Rox.3pm
Manifying blib/man3/File::MimeInfo::Applications.3pm
Manifying blib/man3/File::MimeInfo::Magic.3pm
Manifying blib/man3/File::MimeInfo::Cookbook.3pm
Manifying blib/man3/File::MimeInfo.3pm
  MICHIELB/File-MimeInfo-0.28.tar.gz
  /usr/bin/make -- OK
'YAML' not installed, will not store persistent state
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_use_ok.t ...... 1/4 WARNING: You don't seem to have any mimeinfo.cache files.
Try running the update-desktop-database command. If you
don't have this command you should install the
desktop-file-utils package. This package is available from
http://freedesktop.org/wiki/Software/desktop-file-utils/
t/00_use_ok.t ...... ok   
t/01_normal.t ...... ok     
t/02_magic.t ....... ok     
t/03_rox.t ......... ok   
t/04_IO_objects.t .. ok   
t/05_more.t ........ 1/16 Use of uninitialized value $system in -f at /Users/christravers/.cpan/build/File-MimeInfo-0.28-cAjX_7/blib/lib/File/MimeInfo/Applications.pm line 93.
Use of uninitialized value $distro in -f at /Users/christravers/.cpan/build/File-MimeInfo-0.28-cAjX_7/blib/lib/File/MimeInfo/Applications.pm line 93.
Use of uninitialized value $system in -f at /Users/christravers/.cpan/build/File-MimeInfo-0.28-cAjX_7/blib/lib/File/MimeInfo/Applications.pm line 93.
Use of uninitialized value $distro in -f at /Users/christravers/.cpan/build/File-MimeInfo-0.28-cAjX_7/blib/lib/File/MimeInfo/Applications.pm line 93.
t/05_more.t ........ ok     
t/06_pod_ok.t ...... Can't stat bin: No such file or directory
 at /System/Library/Perl/Extras/5.18/Test/Pod.pm line 220.
t/06_pod_ok.t ...... ok   
t/07_pod_cover.t ... 1/4 WARNING: You don't seem to have any mimeinfo.cache files.
Try running the update-desktop-database command. If you
don't have this command you should install the
desktop-file-utils package. This package is available from
http://freedesktop.org/wiki/Software/desktop-file-utils/
t/07_pod_cover.t ... ok   
t/08_changes.t ..... skipped: Test::CPAN::Changes 0.18 or later required for this test
t/09_no404s.t ...... skipped: Skip $ENV{EXTENDED_TESTING} is not set
t/10filehandle.t ... WARNING: You don't seem to have a mime-info database. The
shared-mime-info package is available from http://freedesktop.org/ .
Can't locate object method "seek" via package "Path::Tiny" at /Users/christravers/.cpan/build/File-MimeInfo-0.28-cAjX_7/blib/lib/File/MimeInfo.pm line 115.
t/10filehandle.t ... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 

Test Summary Report
-------------------
t/10filehandle.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=11, Tests=85,  2 wallclock secs ( 0.08 usr  0.03 sys +  0.91 cusr  0.16 csys =  1.18 CPU)
Result: FAIL
Failed 1/11 test programs. 0/85 subtests failed.
make: *** [test_dynamic] Error 2
  MICHIELB/File-MimeInfo-0.28.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MICHIELB/File-MimeInfo-0.28.tar.gz
Running make install
  make test had returned bad status, won't install without force
`

**Comment by einhverfr** [comment]
I don't think we can assume OS X users will have Freedesktop.Org utilities installed.

**Comment by einhverfr** [comment]
but I am not sure if the seek error is related to this or due to something else.

**Comment by ehuelsmann** [comment]
Replacing File::MimeInfo with http://search.cpan.org/~markov/MIME-Types-2.17/lib/MIME/Types.pod seems like an option: the latter doesn't depend on an external list of installed libraries and/or databases.
