### ISSUE TITLE
Improve reporting by making link structure testable

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2949]
Our permalink structure has no real interface which is testable.  This means:

1.  The link structure needs to be moved into a testable library
2.  We need test cases on that.

I am happy to take on that work but would prefer to do it on a different bug report.  It should also be done on master only and this is 1.4+  so will be filing a bug report to that effect.

**Comment by ehuelsmann** [comment]
What is the use-case for the testable link structure? I mean, if the permalink does indeed work "permanently", then which problem does this enhancement solve? (I'm asking the question, because I don't see the relation to "good reporting" and "link structure".)

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
