### ISSUE TITLE
Payments Redesign

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2950]
As part of the financial rewrite we need to redesign the payments system.  Right now we have two different payment systems both with rather difficult codebases to work with.  We need better design of components, more unity and better testability.

**Comment by ehuelsmann** [comment]
I'm wondering if we shouldn't make this part of the wiki until such a time that it is actionable enough to start coding, instead of holding it here, where it won't receive any attention (too high-over)?

**Comment by sbts** [comment]
Please see my comments on #2971
They apply here as well

**Comment by ehuelsmann** [comment]
Moved to https://github.com/ledgersmb/LedgerSMB/wiki/Topic-Payments
