### ISSUE TITLE
State Machine Design

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2967]
For both transaction and batch workflows.  @ehuelsmann has done some excellent work on the wiki regarding state transitions for financial transactions, but need a design of the actual state engine itself, as well as a version limited to batch workflows like batch approval, reconciliation, and the like.

**Comment by ehuelsmann** [comment]
I've searched CPAN and http://search.cpan.org/~dwheeler/FSA-Rules-0.35/lib/FSA/Rules.pm looks interesting.

**Comment by ehuelsmann** [comment]
Moved to https://github.com/ledgersmb/LedgerSMB/wiki/Topic-State-engine
