### ISSUE TITLE
Batch/Voucher Redesign

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2968]
Batch/voucher workflow and infrastructure also needs new redesign work.

**Comment by ehuelsmann** [comment]
I'm wondering if we shouldn't make this part of the wiki until such a time that it is actionable enough to start coding, instead of holding it here, where it won't receive any attention (too high-over)?

**Comment by sbts** [comment]
Please see my comments on #2971
They apply here as well

**Comment by ehuelsmann** [comment]
Moved to https://github.com/ledgersmb/LedgerSMB/wiki/Topic-Batches
