### ISSUE TITLE
Redesign Fixed Assets

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2971]
Also part of the financial rewrite.

**Comment by ehuelsmann** [comment]
I'm wondering if we shouldn't make this part of the wiki until such a time that it is actionable enough to start coding, instead of holding it here, where it won't receive any attention (too high-over)?

**Comment by sbts** [comment]
I have to agree here.
Let's keep redesign and other long term goals as wiki and / or project notes until it's time to action on them.

Even then a generic "redesign fixed assets" doesn't really work for me.
Instead raised issues should be far more granular. 
This is where projects start to really come into the picture.
When it's time to start working on the design for this the wiki info on what's needed should be turned into specific tasks as project notes.
As it's time to action each of the notes that should be turned into a project issue with commits against a "redesign fixed assets" branch.

Once all relevant project notes are converted to issues and those issues closed the branch can be considered for merge. But not untill its well tested and an excellent level of test coverage has been implemented exercising all of the affected code and related UI

I would be very resistant to any "rewrite" associated changes being directly committed to master until a completed rewrite branch is well tested.

My reasoning here is very simple.
We at still finding fundamentally broken functionality from previous rewrites that were either not fully implemented, or sufficiently scoped.
Even worse those rewrites were never adequately tested.
Neither manually, nor via test infrastructure.

**Comment by ehuelsmann** [comment]
Moved to https://github.com/ledgersmb/LedgerSMB/wiki/Topic-Fixed-assets
