### ISSUE TITLE
Implement Tax Management Front End via Web Services

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2981]
Design is largely open and will likely need to be filled out at that point.  However for now will probably be a tabular set up similar to the current one but perhaps grouped/displayed differently.

**Comment by ehuelsmann** [comment]
@einhverfr this sounds pretty high in the sky. Can we set up a wiki page for for it (or a wiki page for all "Financial rewrite" topics together, with chapters dedicated to each topic?)
