### ISSUE TITLE
Set invoice search to default to date, descending

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2985]
It's not clear what the default sort is for an invoice search. Can it be user-configured, or default to "date descending" (show latest invoices first)?

v1.4.41

**Comment by sbts** [comment]
Traditionally it's been invoice number sort, ascending.
From memory, you can resort by clicking on the column headings.

**Comment by ehuelsmann** [comment]
Is the question sufficiently answered? If not please re-open.

**Comment by funkypenguin** [comment]
Mm.. mine is not sorting by inv date, inv number (or amount!). I agree I can click headings to sort, but that's an extra step for @Rachaelaprice and she complains about it ;)

**Comment by sbts** [comment]
@funkypenguin I'll re-open for now, could you please attach a screenshot showing the miss-orderd invoices and the setup on the search screen.
Feel free to do that from the demo system.

**Comment by ehuelsmann** [comment]
I'm afraid that there's little we can do here without the requested information.
