### ISSUE TITLE
Provide a means to set the default due date on invoices

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2986]
When you generate a new sales invoice, the due date defaults to the current date. Add a field under system -> defaults to set the default invoice term. I.e., have every invoice due (by default) 20 days after issue.

v1.4.41

**Comment by sbts** [comment]
@funkypenguin Actually we already have that functionality, except it's more capable than a simple 1 default for everyone.
The way you set it up, is to configure it for each customer account.
That allows you to have different terms for different customers, which is a very common scenario.

I'll close this issue as Won't Fix, Works for me

**Comment by funkypenguin** [comment]
Excellent solution, thank you
