### ISSUE TITLE
Invoice can't be voided, error about duplicate key, but no dup voided invoice found

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2989]
I have an invoice (6723) I created while testing on my system. I try to void it, but I get an error:
````
ERROR: duplicate key value violates unique constraint "ar_invnumber_key"
DETAIL: Key (invnumber)=(6723-VOID) already exists. at /usr/local/ledgersmb/tools/../LedgerSMB/IS.pm line 1507
````

However, when I search for invoice 6723, I only find the original invoice I tried to void (i.e., I can't find this "duplicate" 6723-VOID)

**Comment by sbts** [comment]
Hmm, more details are probably required here.
Is it possible the (voided) invoice is sitting in the approval queue?

**Comment by ehuelsmann** [comment]
@funkypenguin, did you include the "Closed" invoices in the search?

**Comment by funkypenguin** [comment]
Sorry for the delay, I just tested, and whether I include "closed" invoices or not, the 6723-VOID invoice does not appear.

**Comment by ehuelsmann** [comment]
@funkypenguin I think you might need to look under `Transaction Approval > Drafts`

**Comment by ehuelsmann** [comment]
Not sure if this has been handled or not. Given the long delay, I'm assuming it is and closing. If it's not, please reopen and post the requested details.
