### ISSUE TITLE
When editing a service, you can't change the linked accounts it points to (although there's a drop-down box)

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2990]
To test this, I logged into v1.4 demo, edited service 4011. I'm not able to change the linked accounts, although a dropdown appears in the UI. If the linked account _can't_ be changed (because there are already related transactions), then the dropdown box should not be presented to the user.

**Comment by ehuelsmann** [comment]
Verified in both 1.4 and 1.5 demos, although this *may* be a bug with the demo data, it looks like a bug in the application.

**Comment by funkypenguin** [comment]
I can confirm it's not a bug with the demo data, I see it in prod as well.

**Comment by ehuelsmann** [comment]
I'm net seeing this with 1.5 nor with master. 1.4 being EOL, I'm closing this issue.
