### ISSUE TITLE
Search for Invoices with specific Partnumber doesn't work

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#3006]
In 'Search AR Invoices' you can enter a partnumber. But it isn't included in the search. The query I get is 

SELECT * FROM "public"."report__aa_transactions"('2', NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '1', '1')

where there's no partnumber. Also, the definition of the function doesn't check the parts table at all.

**Comment by ehuelsmann** [comment]
Hi, Thanks for the report. @einhverfr found something similar in #2938 ; is this the same, or the other way around?

**Comment by kaare** [comment]
Hm, true it looks similar, but it's not really the same, I think. The problem in #2938 is in Goods.sql, this is in Report.sql. It's also similar in that the conditions are and'ed, not or'ed together, but there's no reference to the parts table on top of that.

Now, I'm not sure what the good fix is. report__aa_transactions seems to be used from several places, and is already quite huge. Adding partnumber to the parameter list, adding a subselect and turning the conditions the other way around isn't a huge job and I could probably make a PR. But is that the way it should be fixed?

**Comment by ehuelsmann** [comment]
#2926 (submitted by @einhverfr some weeks ago) seems to add an `in_partnumber` parameter to the `report__aa_transaction` stored procedure. That issue has been resolved in 1.5.9. So, this *should* be fixed in 1.5.9. Could you confirm?

**Comment by kaare** [comment]
After some sample searches, I think that the problem has been resolved. So I will confirm and close the issue.
