### ISSUE TITLE
Contact address edit, delete doesn't work

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#3009]
Clicking Edit just retusn me to the Company tab.
Clicking Delete does nothing. Stays in the Address tab, but nothing is deleted

**Comment by ehuelsmann** [comment]
Thanks for the report! However, while trying to reproduce on 1.5.9 (demo system), this works for me...

**Comment by kaare** [comment]
I can confirm that it works after having upgraded (from 1.5.7) to 1.5.9
