### ISSUE TITLE
Cannot migrate from LedgerSMB 1.2 to LedgerSMB 1.3. I need help with my database...

### ISSUE THREAD

**Issue by danieltourde** [ledgersmb/LedgerSMB#3034]
Hello,

I am in the process of updating LedgerSMB from 1.2.26 to 1.3.46 (From an old machine to a new Kubuntu 16.04.2 machine) and no matter how hard I try I do not succeed to get my database converted using the setup procedure. I end up with an empty 1.3 database.
I do not have the knowledge/time to really understand and correct the issue (I looked at the error messages, it's just beyond my limited knowledge of SQL).

I know, 1.3 is not really the latest of the latest but that's the one I got with Kubuntu 16.04 LTS. I can send the 1.2 database (nothing sensitive in it), I just need the converted 1.3.

Thanks in advance for any help.

Daniel

**Comment by sbts** [comment]
Hi @danieltourde 
could you please visit [#ledgersmb:matrix.org](https://riot.im/app/#/room/#ledgersmb:matrix.org) via Firefox or Chrome (don't use Internet Explorer)
That's our chat room and several of us are available to assist right now

**Comment by ehuelsmann** [comment]
Hi, We've since talked in the chat channel. I think this is resolved. If not, please reopen, closing for now under the assumption of it being handled.
