### ISSUE TITLE
Mailer.pm is creating messages with duplicate msgids - 1.5.10 

### ISSUE THREAD

**Issue by billott323** [ledgersmb/LedgerSMB#3041]
The Mailer.pm uses time to create the message id. 
```
 my $boundary = time;
    $boundary = "LSMB-$boundary";
    my $msg_id = "<$boundary\@$domain>";
```
Messages are being processed (or batched) so fast that "time" is not changing (or not fast enough) resulting in multiple messages with the same message id.

**Comment by jame** [comment]
The time() function is only accurate down to the second, so if multiple (batched) emails are being sent, they could easily end up with the message ID.  May need to use something like Time::HiRes in order to the get the microseconds part of the time in order to create the message ID..
