### ISSUE TITLE
Migrate "user" concept as used by SQL-Ledger

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#3042]
SQL-Ledger users do not reside in the database but in configuration files. They have always been kept oustide of the migration process, leaving to the manager to recreate them.
We should leverage the information there to offer migration.

**Comment by ehuelsmann** [comment]
I think this falls apart in 2 changes:

1. Migrate the users
2. Migrate the user's authorizations

The second part is hard. The first part should be doable.

**Comment by ylavoie** [comment]
The number of fields in the configuration files are limited and enough to provide a valid user.

For the 2nd part, we need to have a match table for privileges. The manager could then decide about the remaining few.

**Comment by ehuelsmann** [comment]
For the LedgerSMB 1.2 migration, we now migrate all users, creating their roles with expired passwords. It would be nice if the SL migration would do the same.

**Comment by ehuelsmann** [comment]
Given my last remark, I think this is no longer "needs-design",  but rather "just work"...
