### ISSUE TITLE
500 Internal server error when creating an order for a vendor from contacts

### ISSUE THREAD

**Issue by star39** [ledgersmb/LedgerSMB#3057]
I get this every time when I want to create an order to vendor from contacts.

I think the whole SQL in relation to vendor and parts is not working.

Please check the sequence and you will find out

**Comment by ehuelsmann** [comment]
@star39 thanks for the report! I did find a problem with the following workflow, on 1.5.9 (https://demo.cloud.efficito.com/erp/1.5/) - which I fixed. However, from your description, I have no idea if this is actually your problem. Can you confirm that the following steps are indeed producing the problem you're reporting? Thanks in advance!

* Log in
* Go to Contact Search
* Select Contact Type to Vendor
* Click Search
* Select one of the vendors by clicking on the vendor's name
* Click on the Account tab
* Click on the Purchase Order button

After you do, you see the following image:

![screenshot from 2017-08-15 15-09-11](https://user-images.githubusercontent.com/2326559/29317424-34f62b40-81cc-11e7-9667-5b41fe92f8a9.png)

**Comment by ehuelsmann** [comment]
As for your remark regarding vendors and parts, I take it that's a separate problem report? Could you please add a list of steps (the sequence, as you call it) here to help me reproduce and solve your problem? Thanks again!

**Comment by star39** [comment]
I think you indicate exactly what is going on. This is exactly what is
happening. I cannot find server error logs. Try to find where it is
located. Ask Chris also.

**Comment by ehuelsmann** [comment]
The fix for the `500 Internal Server Error` has been merged and will be released in 1.5.10.

@star39: As far as the comment regarding the SQL goes, is that a separate issue, or your assessment of the underlying cause? (That is: are we talking 1 or 2 problems here? If there are 2, there's more work to be done.)

**Comment by ehuelsmann** [comment]
@star39 where you need to go search for the logs depends on your setup - of which I'm blissfully unaware. From your comments, I understand you're running 1.5, but is that from the Docker images, self-installed, one of the 1.5-ledgersmb debian prerelease packages or maybe another option?

If you're using a `systemd` based setup and you're using our systemd service file, you can find the logs through `journalctl -xe`.

**Comment by ehuelsmann** [comment]
Declaring fixed in 1.5.10.
