### ISSUE TITLE
Posting Vendor Invoice Fails when using vendor-specific prices

### ISSUE THREAD

**Issue by JigmeDatse** [ledgersmb/LedgerSMB#3081]
I have been away from LSMB for a while, as I had no real billable work for a while.  While posting an invoice I get the error.

```
'99 at /home/jrasku/src/ledgersmb/LedgerSMB/tools/../old/lib/LedgerSMB/PriceMatrix.pm line 138. '
```

I am attaching the screenshots which lead to discovering this as a bug.  I was talking with @ylavoie and this seems to be a fresh new bug.  

![wordpress service](https://user-images.githubusercontent.com/66363/29148194-c379f7f8-7d20-11e7-9bf4-94c0313dcf14.png)
Service definition

![error message](https://user-images.githubusercontent.com/66363/29148195-c37d655a-7d20-11e7-8d91-71a5c8ecb59b.png)
Error message received

![vendor invoce](https://user-images.githubusercontent.com/66363/29148196-c382b10e-7d20-11e7-941a-9e8e299704d8.png)
Where I'm entering the Vendor Invoice

![vender contact](https://user-images.githubusercontent.com/66363/29148198-c3fcb01c-7d20-11e7-9cea-7dad0e23c558.png)
How the Vendor is entered

I hope this helps

**Comment by ehuelsmann** [comment]
As it turns out, this is a problem on 1.5 too.
