### ISSUE TITLE
RFC:  Gentoo overlay (and possible push to Portage)

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#3103]
I have started to work a little on Gentoo and for various reasons have abandoned my Red Hat/Fedora virtual machines.  One thing about Gentoo is that it makes it very easy to produce maintainable packages (of the Linux distributions, it has the highest barrier to install as a system and the lowest barrier to write packages for).  In fact writing packages is so easy it is often easier to write a package than install from source.  In fact it is so easy I went from "How do I install Gentoo?" to "I wrote my first package" in under a day and the only problems with my package were problems with upstream helpers.

So I have created a repo (separate) for a gentoo overlay.  It will contain ebuild files for any dependencies not in Portage along with all stable branches of LedgerSMB.

I would like this to be a general reference point for packagers (gentoo can also build rpms by the way, but I have a lot less faith in that) in terms of structure and what is possible.  Therefore I would like to:

1.  Support full installation of dependencies
2.  Support multiple side-by-side installation of LedgerSMB instances
3.  Support backproxying by url via nginx or the like to the urls.

I would like to then get this into Layman and, eventually, see what should be upstreamed into Portage.

Are there any other thoughts or ideas that we should consider for best practices here?

**Comment by einhverfr** [comment]
BTW "under a day" was mostly spent waiting for software to compile and fighting with the build system because I messed it up early.  But I hope to have a basic overlay of the dependencies completed this weekend, and start working on the LedgerSMB pieces after.

**Comment by einhverfr** [comment]
The repo in question is at ledgersmb/lsmb-overlay if anyone wants to take a look.  The initial run through dependencies, autogenerating ebuilds and reducing keywords to match convention took about half an hour.  I need to add some metadata to each dependnecy and some for the repo as a whole.  Then will be ready to start working on LedgerSMB packaging.

**Comment by einhverfr** [comment]
I have the dependencies set up there for the most part.  Maybe some more will be found as I get though it.

In the mean time, discussion will move to that repo.

**Comment by JigmeDatse** [comment]
Thank you muchly for this.
