### ISSUE TITLE
RFC:  Split off LedgerSMB::Template libraries to CPAN

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#3106]
The API here has been stable since 1.3 and seems unlikely to be subject to major changes now.  However as we move to a more service oriented architecture it is likely to be used more for document generation of reports, invoices, etc. than for the main UI.

I would like to suggest we move these off to CPAN and build a dynamic format listing function which would allow new formats for reports and invoices to be effectively pluggable (and therefore subject to development outside the normal project release cycle).

**Comment by ehuelsmann** [comment]
Well, if this concerns the LedgerSMB::Template::* modules (the so-called "formats"), then I'm afraid the "relatively stable" doesn't hold anymore: I completely refactored everything in the modules as they are on master now.

Maybe this is best discussed on the mailing list, as it allows easier exchange of messages, I think and hopefully has a broader audience.

**Comment by sbts** [comment]
I agree, this is probably best discussed on the list.
As far as it being stable, as ehuelsmann said, it's changed recently and I expect it will change even more as we develop our api infrastructure.
Reporting is likely to be a valuable implementation  of the api and can be expected to require changes to templating to take advantage of the new possibilities

**Comment by einhverfr** [comment]
I guess my thinking is change to take advantage of new possibilities makes it sound like we don't know what the single responsibility of LedgerSMB::Template should be.

**Comment by ehuelsmann** [comment]
While it may be true that the single responsibility is to be worked on, I think this is best discussed on-list.
