### ISSUE TITLE
RFC:  Proposed change to templates API

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#3108]
Right now I would like to see the template logic simplified and generalised.  The templates take on too much responsibility, being effectively an output handler in addition to a templating library. I have been thinking about this problem for a bit and have an idea on how to proceed.  Feedback is welcome.

**Template Responsibility:**

The template should be responsible *only* to render the content and provide a file mime type back with it.  This means that the output of template->render() should **always** be a two-item hash with the keys of mime-type and content.  The Template MUST NOT assume HTTP, PSGI, or any other particular input/output format.

**Handling Template Output**

The main wrapper script should be responsible for turning the template output into a CGI or PSGI output.

**Getting there**

This is a change that can be made fairly quickly by simply changing the return output of render, ignoring the no-auto-output options, and handling the result in the calling script.  Additionally the type and content can follow the existing API for now for old legacy code.

**Estimated effort to make the change**

4 hours.

**Impact on testing**

Our template handling tests may need to be rewritten a little.  Our cucumber tests should catch the rest.

**Proposed new tests**

Mock the Mailer, try to send an invoice by mailing and make sure the appropriate values get passed.

** New Testing Effort **

Another hour.

**Comment by einhverfr** [comment]
A major benefit here btw would be that it would make our workflow scripts immediately testable.

**Comment by sbts** [comment]
Hi @einhverfr,

I'm concerned that you may not be aware of the current state of the codebase.
While 1.5 would match your description and plan, master is a completely different story.

The project as a whole would not easily accept a PR to make these sorts of changes against 1.5 either as no feature changes should be made to the stable release series

**Comment by einhverfr** [comment]
@sbts 

Point though is:  there is no real way to just run a report and get the output to a template without printing the whole thing to CGI output or handling PSGI outputs myself.  Yes it can be fixed in Report.pm.  I think thats the wrong place for the fix.  Go through and trace the code if you don't believe me.  Basically I don't think we should be assuming that anything is operating in a web framework unless that is explicit and there are lots of places that this assumption is still made.

I do believe that we can move the PSGI logic in master from the Template handler to the PSGI.pm and that would fix this.

**Comment by einhverfr** [comment]
Also for 1.5 and 1.4 I think the appropriate solution would be for any third party tool to clobber the built in models where appropriate -- bad practice generally but it avoids disturbing the codebase.

**Comment by ehuelsmann** [comment]
> So when you call $report->render() it calls $template->render() which calls $template->output() because we don't set no_auto_output.

Actually, Report.pm has a `render_to_psgi()` too.

**Comment by einhverfr** [comment]
@ehuelsmann I saw that. I guess I am wondering, why the template engine needs to care whether the file is going to CGI, PSGI, a printer, or wherever.  It seems like it is a useful step forward for the framework to be sure.  But I am arguing for a strong separation of responsibilities, and equally important, a single responsibility for the template engine.

In other words, I would like to get rid of all output-specific dependencies entirely.

**Comment by einhverfr** [comment]
Also I think restricting the responsibility and functionality to a single responsibility does more to open up new possibilities than anything else we can do with the module.

**Comment by ehuelsmann** [comment]
With #3360, this goal has been achieved: there's now a `render` method on both `Report.pm` as well as `Template.pm` which renders the "evaluated template object".

Note that I'm using the evaluated template object because I don't have a good alternative API and the current state still wants a number of parameters regarding output to be passed into the template object. In a new iteration, that's to be addressed.

Closing as fixed; shortly discussed this item for backport in #ledgersmb, but it's considered too big.

**Comment by sbts** [comment]
To make it clear. This is 
- FIXED in master (1.6)
- WONTFIX 1.5 and earlier
