### ISSUE TITLE
missing units and default values in security settings

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3109]
We need to display units (days and minutes) for Password Duration and Session Timeout on the Defaults page. We should also display any default values, even if not set in the defaults table. That's probably best done by maintaining a default values module in the code instead of them being hardcoded in multiple places. I'll discuss with @ehuelsmann before implementing

**Comment by ehuelsmann** [comment]
In 1.7, the password duration has already been realized.
