### ISSUE TITLE
User Creation or Importation

### ISSUE THREAD

**Issue by ziuq** [ledgersmb/LedgerSMB#3140]
As a user with full permissions in 1.5.9.

If the 'Create new user' button is set and the user exists in another
company, Lsmb will fall back to 'Import existing user'.
No error follows but the user is not made. 
If it worked, this behavior is a questionable prediction
of intentions and could have security ramifications.  

Directly selecting 'Import existing user' also fails.

Import worked from setup.pl.

**Comment by einhverfr** [comment]
The reasoning for this is that at least a few LedgerSMB users have had holding companies, and therefore users tend to get imported a lot.  I am all for making warnings a little clearer.  But I think the idea that we should put extra steps here strikes me as helping a much smaller group of users (those with some sort of shared hosting) at the expense of a larger group (those with multiple co-owned companies).

**Comment by ziuq** [comment]
@einhverfr    I guess I was not clear:  It does not work.  If it did work it would be doing the opposite of what it says it is going to do.

I'd rather hear that I am wrong about the security issues than that the majority of users might save a
click per user.

In my case, I would like to have 1) a playground for users, 2) a trial to run in parallel, and  3) a precious target tuning toward a production launch.

**Comment by ehuelsmann** [comment]
This problem doesn't exist in 1.6.16 (just tested). Closing as 1.5 will be EOL as of Monday.
