### ISSUE TITLE
Selecting business details from list of business types, fails

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#3154]
Clicking on a specific business from the `System>Type of Business>List Businesses` fails with:
'ERROR: current transaction is aborted, commands ignored until end of transaction block: 
SELECT proname, pronargs, proargnames, string_to_array(array_to_string(proargtypes::regtype[], ' '), ' ') as argtypes FROM pg_proc JOIN pg_namespace pgn ON pgn.oid = pronamespace WHERE proname = ? AND nspname = ? at /usr/local/share/perl/5.14.2/PGObject.pm line 207. '

**Comment by ehuelsmann** [comment]
This indicates an error check is missing elsewhere: all statement handle
method calls should be checked for errors ; when they're not, the next
statement handle method call which *is* checked returns the above.

**Comment by ylavoie** [comment]
Agreed, the demo is showing that for the first item
