### ISSUE TITLE
Password displayed length

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#3155]
Masked passwords are shown with dots to mask them. The number of dots displayed should not have any link to actual password length.

**Comment by ehuelsmann** [comment]
why do you say bite-sized when this is just standard browser behaviour?

**Comment by ehuelsmann** [comment]
I would rather defer to the browsers and close this as "wontfix"...

**Comment by ehuelsmann** [comment]
Closing as WONTFIX because this is the domain of the browser showing the password with the password INPUT element.
