### ISSUE TITLE
How to produce a statement in v1.4

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#3202]
Hey guys,

Maybe a dumb question, but the manual states a key features of LedgerSMB being "Issue Invoices, Statements, Receipts, and more ".

So how do I produce a statement, which to my understanding would be a document I give to my customer indicating all their invoices and payments, with outstanding balance, over a given period?

Thanks,
David

**Comment by funkypenguin** [comment]
Hey guys,

Sorry to be a pain here, but can you please advise on how to perform this (basic) function?

Thanks,
D

**Comment by ehuelsmann** [comment]
Sorry to have missed your question. You probably want to use the Aging and/or the Outstanding reports. 
The aging report's "To" date limits transactions taken into account; meaning that all transaction up to a specific (posting) date are reported, if open.

I personally use the "Outstanding" report with an end date to specify my year-end AR and AP positions. With a start and end date, you would see all payments over a period and all (new) invoices over the same period. 

Is that what you're looking for?
