### ISSUE TITLE
Make Internal Notes scrollable

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#3203]
This is an enhancement request. I'm currently at 1.5.9

On orders, quotations, the Internal Notes keep growing as it keeps the history of emails (and probably other stuff). It's important to keep, so I don't want to prune it, but it also means that the action buttons is moving away from the order items.

So please add a scroll class to the css or sth like that.

**Comment by sbts** [comment]
Sounds like a good candidate for adding auto scroll and max height

**Comment by ehuelsmann** [comment]
Does presenting the buttons at the top and bottom like with invoices work as a solution here?

**Comment by sbts** [comment]
That would work.
Although scrollable above certain size limits would still make sense I think.
Especially regarding width.
For width we should scroll and not wrap (not sure what the current behavior is)

**Comment by ehuelsmann** [comment]
This will be addressed in 1.8.
