### ISSUE TITLE
Invoice Template selects wrong Addresses

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3222]
This isn't an issue with the template so much as the perl feeding the template. The template uses address1, address2, etc for 'TO' and shiptoaddress1, shiptoaddress2, etc for 'Ship To'. However the code incorrectly supplies the Billing Address to both. Tested on 1.5.12

**Comment by ehuelsmann** [comment]
what's unclear to me is that you're actually selecting a shipping address (or not).

**Comment by ehuelsmann** [comment]
Ping

**Comment by sbts** [comment]
@ehuelsmann well, I'm not sure how you select a shipping address for an invoice it's self.
We have a "Shipping point" field, but that appears to be free-form text as does the "Ship Via" field

From memory I tested this behaviour by adding shipping, sales, and billing addresses to a single customer.

Now It's possible that we are deliberately adding the billing address to the invoice thinking 
- "it's and invoice, so we should use the billing address"

If that's the case, how are you supposed to show the address to ship to on the invoice without manually looking it up and entering it every time

**Comment by ehuelsmann** [comment]
The workflow works as follows:

1. Create a billing and shipping address on the ECA (haven't tested on the entity)
2. Create an invoice
3. Use the "Ship to" button to allocate a shipping address
4. Print the invoice

If you don't use a separate shipping address (that is, the "Ship to" button), the billing and shipping addresses will be the same (= the billing address).
