### ISSUE TITLE
Error posting "just saved" invoice copy while voiding

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3224]
- Copy to New AP invoice,
- Copy original Invoice Number in, and append "- VOID"
- Negate all QTY's
- Hit Save

All is ok at this point.
- Hit Post

The following error is generated
> 'ERROR: null value in column "chart_id" violates not-null constraint DETAIL: Failing row contains (12, null, 0, 15/02/2017, null, f, f, null, 23, t, null, null, null, 78). CONTEXT: SQL statement "INSERT INTO acc_trans (chart_id, trans_id, approved, amount, transdate, invoice_id) SELECT p.inventory_accno_id, t_inv.trans_id, true, t_adj, t_ap.transdate, in_invoice_id FROM parts p WHERE id = t_inv.parts_id UNION SELECT p.expense_accno_id, t_inv.trans_id, true, t_adj * -1, t_ap.transdate, in_invoice_id FROM parts p WHERE id = t_inv.parts_id" PL/pgSQL function cogs__add_for_ap_line(integer) line 39 at SQL statement SQL statement "SELECT cogs__add_for_ap_line(id) FROM invoice WHERE trans_id = in_id" PL/pgSQL function draft_approve(integer) line 12 at PERFORM: SELECT * FROM "public"."draft_approve"(?) at /usr/local/share/perl/5.20.2/PGObject.pm line 360. '

**Comment by ehuelsmann** [comment]
Did the original have payments?

**Comment by sbts** [comment]
No, no payments.

This can be reproduced on demo15 as follows

- search for and open AP invoice 8789
- click "copy to new"
- enter invoice number `8789 - void`
- negate qty's
- hit save

Error is thrown

adding an "update" before save doesn't help

**Comment by ehuelsmann** [comment]
Can't reproduce on demo15 as of right now.
