### ISSUE TITLE
Attaching a file to an entity or eca causes the entity to become inaccessible

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3228]
While it's possible to successfully attach a file, doing so causes that entity to break.
The breakage prevents you from accessing the entity from Contacts -> Search
And probably from other locations as well.

The UI will report an error like....
> Not a HASH reference at /srv/ledgersmb/tools/../lib/LedgerSMB/Template/HTML.pm line 100

The error on the console will be entirely different and may look like....
>  Use of uninitialized value $value in pattern match (m//) at /usr/local/share/perl/5.20.2/PGObject/Type/ByteString.pm line 73.
 Failed to execute bin/lsmb-request.pl (): Died at /srv/ledgersmb/tools/../lib/LedgerSMB.pm line 517.

To work-around this (not really, but to make the entity work again) you need to delete the file.
- First get the entity ID.
```
psql -c "select * from entity where name ilike '%entity-name-pattern%';"
```
- get ECA id's for the entity
```
psql -c "select * from entity where name ilike '%entity-name-pattern%';"
```
- then list files attached to the entity
```
psql -c "select select id, ref_key, uploaded_at, file_name from file_entity where ref_key = $entity_id"
```
- then list files attached to the Entity Credit Account (eca)
```
psql -c "select select id, ref_key, uploaded_at, file_name from file_eca where ref_key = $eca_id"
```

- finally you can delete the undesired files from either table ( file_eca, file_entity ) with.....
```
psql -c "delete from $table_Name where id = $file_id"
```

**Comment by ehuelsmann** [comment]
Found the problem: Adding 

```
print STDERR 'this is it: ' . (ref $rawvars) . "\nrawvars: $rawvars\n\n";
```
before the offending line, the output of the offending value is:
```
lsmb    | this is it: PGObject::Type::ByteString
lsmb    | rawvars: PGObject::Type::ByteString=SCALAR(0x9833e98)
```
Meaning that we're breaking when the value we're trying to escape is a blessed scalar reference.

**Comment by freelock** [comment]
I just hit this... we store scans of hire documents on employee ECAs, and these are now inaccessible...
