### ISSUE TITLE
Cash Payment "post and print" fails

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3232]
- select one or more invoices to pay on Cash -> Payments screen
- add Memo and Source details
- Update
- Post and Print

- Result
Error message
`Can't use string ("templates") as a HASH ref while "strict refs" in use at /srv/ledgersmb/tools/../lib/LedgerSMB/Setting.pm line 69.`

**Comment by ehuelsmann** [comment]
I'm not sure how to handle this: Post and Print wants to generate 2 responses: the printed output (unless that's sent to the printer) as well as the regular "next screen" response.

**Comment by sbts** [comment]
I'd suggest the "print to screen" be executed first As a popup with the original response page being opened in the original window.

**Comment by ehuelsmann** [comment]
The error mentioned above has been fixed. However, the resulting situation isn't satisfying yet: the response gets inserted into the page, which means there's no printable document...

**Comment by ehuelsmann** [comment]
Thinking to have a button which posts the payment and retrieved the printed document on success
