### ISSUE TITLE
Viewing AR (vendor) and AP (Sales) invoices should dynamically resize Source and Memo Fields

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3234]
Currently the the gap between Payments fields dynamically resizes, where it should be the field width it's self that changes.
- Source should have a max width of at least 20em
- Memo should have unlimited max width
- Memo should be manually resizable in the vertical direction with word wrap enabled

**Comment by ehuelsmann** [comment]
Could you add a few screenshots to illustrate the current problem? That will help us understand which screens you were looking at and what you want changed there.

**Comment by ehuelsmann** [comment]
This is more energy than I think we can spare on the old code. Since we don't know what the new code's screen will look like (yet), I'm closing for now. Please re-open if the new invoice screen - once implemented - doesn't suit your expectations.
