### ISSUE TITLE
Nowhere to store a Client or Vendor URL

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3235]

**Comment by ehuelsmann** [comment]
Could you add a bit more detail as to the use-case? I think there definitely are options for contact data to be stored, including URLs, but I can't establish whether or not that suits your use-case.

**Comment by ehuelsmann** [comment]
The "definite options" referred to above, are the functionality where attaching files and links to a vendor or customer is in the Contacts screen. I'm closing for now, as this seems to be waiting for more than 2 years for feedback.

When re-opening, please do so by adding the requested feedback at the same time.
