### ISSUE TITLE
AR (Sales) Invoice Entry Notes fields need to dynamically resize their width

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3237]
This should be done with
- a 50/50 default split
- a drag bar between if possible.
- Ideally Horizontal Scrollbars should be enabled to assist editing and viewing.

A final item may be particularly difficult
- show a pair of right margin markers
  - suggested text width
  - Maximum width that can be displayed for Current Locale's default page size

**Comment by ehuelsmann** [comment]
A mock-up screenshot would help us understand what your target situation looks like.

**Comment by ehuelsmann** [comment]
This is more energy than I think we can spare on the old code. Since we don't know what the new code's screen will look like (yet), I'm closing for now. Please re-open if the new invoice screen - once implemented - doesn't suit your expectations.
