### ISSUE TITLE
template "demo with images" doesn't work well for html

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3238]
There are some missing features, values, and formatting in some of the templates.
In particular handling line breaks in blocks of text for html output, among other things.
There is also currently no way to display the configured TAX Identification number (ABN in Australia)

I've locally fixed some of these, with more fixes to come.
I'll raise a PR once I've tested across all output formats.

**Comment by ehuelsmann** [comment]
Is there even a need to have different demo sets?

**Comment by ehuelsmann** [comment]
There is little actionable here, I believe. Can you add specifics?

**Comment by sbts** [comment]
I'd completely forgotten to follow up on this.
There were quite a number of changes required to fix the templates for nice presentation. 

I'll have to go back and review. Probably do adiff between stock templates and a couple of modified setups to put a list together .

As for having 2 sets of templates with/without images, no, I don't think we need both anymore.
Especially as images can be embedded in the DB now.
I suggest we do some work on the default templates, then drop the non image version.

We also should include there LedgerSMB logo as the default image.

**Comment by ehuelsmann** [comment]
For 1.9, the demo with images set has been integrated in the main demo set. Both html and TeX sets have been cleaned up in terms of formatting. My reading of this issue is that the work is done then.
