### ISSUE TITLE
e*__location_save

### ISSUE THREAD

**Issue by ziuq** [ledgersmb/LedgerSMB#3242]
Why would a location attached to an entity not have the same address lines as one attached to a entity_credit_account?

**Comment by ehuelsmann** [comment]
it's not so much that the eca and the entity have different addresses. It's much more that two ECAs can have different addresses. E.g. when you're working for 2 different departments in the same legal entity; each of which is located in a different building and you're supposed to send your invoice to the managers of said departments.

**Comment by ehuelsmann** [comment]
I hope that's a satisfying answer to your question. I'm going to close this issue here. If you want to follow-up, better media would be on the mailing list or the chat channel, I think (because they allow for more interactive discussion back and forth).

**Comment by ziuq** [comment]
I do understand that a business may have multiple addresses for varied functions.

Why does `eca__location_save` take a `in_line_three` argument and `entity__location_save` forces an empty string instead?   Is `in_line_three` coming or going or what?

**Comment by einhverfr** [comment]
I think that's a great question.  I would be in favour of taking a line 3 in both and coalescing to an empty string on insert.

**Comment by ziuq** [comment]
Presumably, there are addresses with a  true `line_three`.   Is there a need to maintain field in displays and reports?   UI and backend consistency?   (I've not got far into the presentation side.)

**Comment by einhverfr** [comment]
I could imagine 3 lines needed for addresses, particularly if you have a c/o line.

**Comment by einhverfr** [comment]
Chances are you won't need it on a report, but for things like printing mailing labels, it would be important.

**Comment by ziuq** [comment]
I was thinking of existing user data.

**Comment by einhverfr** [comment]
I think historically this behavior has probably been in it for a long time.  The reason to break into lines is to have the option to enforce a maximum width for things like mailing labels.  Otherwise we could put the address in a single text field.

**Comment by sbts** [comment]
Actually I didn't reference that, github UI did something odd when I referenced an irc/matrix room and inserted the other most recent issue number instead

**Comment by sbts** [comment]
@einhverfr I'm wondering if your last comment is really valid these days?
We use multiline text entry boxes elsewhere, perhaps we can/should do the same for addresses and simply handle the embedded newlines correctly
