### ISSUE TITLE
adding an existing user to a new DB resets that user's password expiry

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3249]
So I created a test db yesterday
Then today when I went to raise an invoice I couldn't log in!
The cause, obviously, was the password expiry was reset by importing the user to the new db

At a minimum we should have a loud warning that this is the case.
It would be better to not touch the password nor expiry when importing a user

**Comment by sbts** [comment]
This flows over into the fact that we need to better notify the user of password expiry

**Comment by einhverfr** [comment]
That should only happen if you set a password.  I don't think you need to set a password when importing.  If you do, that's a bug.

**Comment by sbts** [comment]
@einhverfr yep, @ehuelsmann and I discussed this further in #3242 ledgersmb
Basically, the UI offers no explanation that the password will be clobbered, and allows the password to be set.
I Haven't confirmed yet, but the password may be a required field there, at least I have the impression it is.

The simple fix is probably to disable (and ignore) the password field if import is selected.
We really should be looking at also loading the user's details from existing DB's as well rather than requiring the information to be re-entered.
I'm thinking a more "procedural" workflow there would make sense.
- Click Add User (or hit that point in the new db setup
- be asked for a username with "continue" button
- cluster is checked for an existing user
  - if no existing user, ask for password and other details with "create user" button
  - if existing user
    - retrieve details
    - check that the user doesn't already exist in this DB (generate pretty error if it does and return to the start)
    - display details and prompt "import or change username"
      - if change username selected, return to the start, 
      - if import selected allow edits to details with "import user" button to complete

The same process should be used within user management in the main app.

I'd suggest the entire process be written as a small unit with a corresponding dojo widget that "pops up" in a floating div. That code can then be used in both app and setup.
