### ISSUE TITLE
Invoice entry "item number" search is foobar'd

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3266]
On the (sales) invoice entry screen the partnumber field (dropdown suffers from search issues.
- is case sensitive.
- always returns the first entry of a multiple match if a partial partnumber is entered followed by "enter key"
- Auto dropdown with filtered data is noticeably slow to display so the user may not even notice it before they press enter

To Test on demo 1.5
- new sales invoice
- pick a customer (I used Cubex)
- type `assy` hit enter
- note that there were no matches
- replace `assy` with `ASSY` hit enter
- note that `ASSY-00001` matches
- update
- for new item type `ASSY-00002` and hit enter
- note that there is such an item, but you temporarily get "no such item" before it correctly updates

- even worse , if there is ANY match, it always returns the FIRST match

However, if you type `ASSY` then wait, a filtered list will appear below the text entry box. It can take a noticeable amount of time to do so though.

Expected behavior would be to display a list of all `ASSY*` matches in a case insensitive result before allowing enter to move on to the next field.
At a minimum it should not select a default if there are multiple matches.

If it's a single match, then auto selecting that would be fine.

This causes a poor UX, and potentially makes the system unusable
It's also a regression

**Comment by ehuelsmann** [comment]
What does this block?

**Comment by sbts** [comment]
I would consider this a blocking issue as it prevents expected results from simple search terms.
consider 2 item numbers.
- Labour
- labour

With the current behavior it's not possible to enter any variation that presents a list to select from that contains both of these as the search is case sensitive and doesn't allow partial words
As this effectively "hides" items from the UI (yes even the filtered dropdown list) unless you try both lower and upper case manually, I do consider this should be blocking

**Comment by ehuelsmann** [comment]
As discussed in the chat channel, it takes a visible amount of time to show the drop-down list because the server is actively queried for the result matching the search. Avoiding that round-trip is non-trivial and needs more services and database (model) changes.

**Comment by ehuelsmann** [comment]
If we restrict the resolution of this issue to be "matches should be case insensitive", then I have a change "in the works" and we can close this issue this week.

**Comment by sbts** [comment]
That's certainly a great start and will fix the worst part of the breakage. Allowing full part discoverability to be restored. 

To partially address the second part I is need if it's possible to hook the "enter pressed" behavior and either disable it entirely or at least prevent it from selecting from the list and instead submit the partial match for the server to return a list
