### ISSUE TITLE
Default filename for saving a printed invoice needs customer name

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3268]
When "printing" an invoice the associated filename (LaTex, HTML, or other) currently follows the pattern
`invoice-$invoice_number`
it would be preferable to append a sanitized version of the entity name so it looks something like.....
`invoice-$invoice_number-joe_s_fish_chips`
where the original customer name was
`Joe's Fish & Chips`
Essentially converting any sequence of non alpha numeric chars to a single `_`

**Comment by nick-prater** [comment]
I think this is a good idea, but I'd prefer to look at this from my customers' point of view. For them, it's more useful to have my company name in the invoice filename, so it's obvious who the invoice is _from_. Perhaps it's possible to include both in the file name?

**Comment by ehuelsmann** [comment]
I'd like to solve the part of the request for the own company by advocating a configurable prefix. As for the customer, is like to propose to use the customer number instead of the name: it's meaningful and relatively short.
