### ISSUE TITLE
Purchase Orders should continue to display company (local) partnumbers

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3274]
Currently after an item is successfully added to a PO if there is a suitable vendor partnumber associated with the item the vendor partnumber is displayed instead of the local partnumber.

We should look at how we can also display the company partnumber (perhaps in the line notes field, or as a suffix or prefix to the description.
Ideally, maintain a separate field for both the vendor and local partnumbers

**Comment by ehuelsmann** [comment]
@sbts could you please add a screen recording or reproduction recipe? I don't understand what behaviour you're seeing and what it is that you're expecting.
