### ISSUE TITLE
Number handling broken on input containing thousands separator

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3282]
At least in the Cash->Receipt screen entering an overpayment amount of `4,800.00` results in a total of `4` being shown in the UI.
It appears that the thousands separator results in a truncation.
On the other hand entering `4800.00` results in the expected total.

After further testing, the transaction actually gets posted correctly, it's simply either returned to the UI incorrectly, or the UI is incorrectly displaying it

**Comment by ehuelsmann** [comment]
these totals are being generated in the payments template (`UI/payments/payment2.html`), which means number formatting isn't properly taken into account.
