### ISSUE TITLE
Activity flag

### ISSUE THREAD

**Issue by ziuq** [ledgersmb/LedgerSMB#3283]
Taking contact/search as an example.  With 5000 contacts, it may take 15 seconds for the page to display.
The problem is that there is nothing which indicates that the user is waiting for a response.  The button darkens on entry/hovering.  Upon cllicking, the button gives no visual response.  The browser's spinners and status messages are disabled.

1.5.9 and Chromium

**Comment by ehuelsmann** [comment]
On all 1.5 versions, the form is supposed to be rendered with "vagueness" until the data is returned completely from the server and the result is being rendered.
Upon investigation, the code which is there uses incorrect measures (percentages instead of fractions), making the code ineffective.
