### ISSUE TITLE
parts search page layout

### ISSUE THREAD

**Issue by rakool** [ledgersmb/LedgerSMB#3286]
This may apply to some other pages also.

The radio buttons for selecting active/onhand/short/obsolete/unused are backward.  All other buttons on the page precede their label.

Four out of four beginners comment.

**Comment by ehuelsmann** [comment]
yes, it applies to several other "report parameter" pages as well.

Question is: Do we want to have a consistent layout everywhere, meaning that we want the checkmark and/or radio selector to preceed the label everywhere? Or: does the preceding or following depend on the structure of the form? (e.g. the "Income Statement" page layout has labels following the selector; still that page doesn't seem to be as confusing as the parts search page)

**Comment by ziuq** [comment]
I'm looking a 1.5.16 now.

Contact search  is good.  The zero width dropdown  selection box is ugly.   The "Active          from" could be combined so the start date lines up with the above box.   The consistent layout helps.

AR search an AP search -- attempt to fix the date issue but dupe the "to" and "from".   It is obscure how the dates interact with the period and timeframe radio-buttons.  The single line selection sets are bad for having less \s between button-label pairs than in the button-label.

The Income Statement  looks neat for having the boxes aligned and without multiple checks or radios on a line it is clearer visually.
