### ISSUE TITLE
parts search

### ISSUE THREAD

**Issue by ziuq** [ledgersmb/LedgerSMB#3287]
The logic of the radio buttons seem poor.   Other reasonable defaults would be everything and everything but obsolete items.   But those don't seem to be achievable from the page.

**Comment by ehuelsmann** [comment]
The definition of "everything but obsolete" == "active", so it seems that part of the request is already implemented.

Is it really important to be able to search in both active (not-obsolete) *and* obsolete items in a single search? I mean, I would expect the use case for searching "obsolete" parts to be very different than being able to search "non-obsolete".

**Comment by ziuq** [comment]
I thought active was tied to the date range.   I don't have any obsolete'd parts.  Not sure how I got empty sets.

How do you assign new partnumbers without treading on old ones?!

A salesperson not finding an item, may want to re-search including everything,  e.g.  a customer is looking for a group of similar items, if one is obsolete the salesperson may want to streamline the next search..   The items might be obsolete, but further research of prior A/P info may support a seller's preliminary decision of pursuing the possible transaction.

Lsmb's meaning of obsolete seems to equate with 'discontinued' AND 'none' AND 'no-incoming'.   If that is correct, then it is just a business decision that may be reversed as situations change.

**Comment by ehuelsmann** [comment]
Obsolete is a checkmark on the part entry screen. It can have any required business definition, but has no application definition or business rules applied in LedgerSMB... I guess that means this issue can be closed. If you disagree, please re-open and provide further use cases.
