### ISSUE TITLE
More setup.pl 

### ISSUE THREAD

**Issue by rakool** [ledgersmb/LedgerSMB#3314]
More small issues with setup.pl:

I have the keys, but cannot logout to lock up when I leave.

The field hints for importing vs. creating a user could say something about Postgres databases vs. other lsmb databases.   Or the program could catch, recover,  query and move forward.

~~'No change' is pretty meaningless.~~ (duplicates #2311 )

~~Date format preference could be accommodated with a drop-down list providing a sticky preference for the site.~~

User list is slammed against the left jamb.

On all or most setup.pl pages, there is space to have help paragraphs to the right, like many SOHO routers and network interfaces.

Conversely, space could used to combine the user list and user entry pages to make entry smoother.   But
just returning to the user list from user entry should suffice.

**Comment by ehuelsmann** [comment]
> 'No change' is pretty meaningless.

Where/How do you get this output?

**Comment by ehuelsmann** [comment]
> The field hints for importing vs. creating a user could say something about Postgres databases vs. other lsmb databases. Or the program could catch, recover, query and move forward.

Sure we can handle situations differently. I'm not clear on what you think we should do to "catch and recover". Should we deny the user be created? Should we inform the admin that the user already exists? What if that happens?

**Comment by ehuelsmann** [comment]
> Date format preference could be accommodated with a drop-down list providing a sticky preference for the site.

PR #3330 merged last night might address that. Could you review please?

**Comment by ziuq** [comment]
'No change' is one of the choices:  'No Change', 'Manage Users', 'Full Permissions'.   In the context of a fresh setup that is no change from what?

**Comment by ziuq** [comment]
Creating vs. importing.   I think it is possible that someone thinks that "existing" means existing in a Lsmb database, naively missing the point and going down the wrong path.   Assuming that confusion, the error message does not seem helpful.

**Comment by ziuq** [comment]
I'll check out PR 3330.   I think Yves had strong feelings about this one.

**Comment by ylavoie** [comment]
‘No change’ in the context of a new user is an error. When editing an existing one, it is probably redundant, we could leave it as it were.

**Comment by ehuelsmann** [comment]
"No change" applies to the rights of a user being imported.

**Comment by ziuq** [comment]
Agreed, but I can select it for a new user.   

In 1.5.13, in setup,  I can repeatedly add an existing user.   I presume the existing user is over written, but don't know.

**Comment by ehuelsmann** [comment]
> In 1.5.13, in setup, I can repeatedly add an existing user. I presume the existing user is over written, but don't know.

Which steps do you go through to add the existing user? Is it to the same company? Surely that is not through the steps for company creation?

**Comment by ylavoie** [comment]
Don't we have tests to make sure that works? Does setup.feature need to be upgraded?

**Comment by ehuelsmann** [comment]
No tests and yes.

**Comment by ziuq** [comment]
//host/setup.pl,  log in as lsmb_dbadmin to same_database and add the same_user again.  It seems to be a complete no-op  but reports success.

**Comment by ehuelsmann** [comment]
Merged into #3746
