### ISSUE TITLE
Add Perl::Critic::Policy::Modules::RequireExplicitInclusion to the critic tests

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#3315]
@ziuq Could you have a look at implementing these tests? It seems we're quite sloppy at correctly `use`-ing our modules.

**Comment by ziuq** [comment]
The policy is in our perlcriticrc, changing a theme will activate it.

I can `no-critic sniff`  all of these in a somewhat reasonable time frame.  I think that is good idea, "stop the bleeding".  Will we come back to the problem to fix them?  These are the violations that I said could take a year to clean up.

If team members try fixing 10 violations each, they may each run into some of the more difficult cases.  That may give insight into what we should do.   An easy case is just tedious.
  
One thing I do recall thinking would help is a registry of all the Perl routines exposed outside of perl code.   But I'm still a beginner with Lsmb;  I have not found the interfaces between modules of code.   A module here might mean 1/20th or 1/4th of all the code.

These are fixes where just knowing the code, will help a lot.

**Comment by ehuelsmann** [comment]
As per our discussion on Matrix, there's one problem with this policy: it doesn't recognize inheritance Moose inheritance initiated through `with` or `extends`.
