### ISSUE TITLE
OH column on orders (and invoices?) not formatted according to user prefs

### ISSUE THREAD

**Issue by ziuq** [ledgersmb/LedgerSMB#3334]
The value `0.00045135172`  is displayed on Parts Search and Edit Part as `5e-05`  as a onhand value.
As a sales Order entry value it is shown as `0.000045135172`.

**Comment by ehuelsmann** [comment]
Which value would you have expected? The rounded value: `0.00` ? or the value shown on the order entry?

**Comment by ziuq** [comment]
I object to the exponential notation.

0.000045135172 is good as a fix.
 
If  it were user or company  adjustable,  I would be at four decimal places.  But that raises the issue of what is appropriate for measuring all the things a part may be;  then there are payroll time units which seem to be different regarding format.

**Comment by ehuelsmann** [comment]
How did you get yourself into this?

When I try to create a similar situation by entering fractional quantities into an invoice, the number is rounded to 5 positions (which means I'm not getting the scientific notation).

**Comment by ehuelsmann** [comment]
I've researched this subject and came to the conclusion that the problem is actually the other way around: the amounts get formatted (according to the user settings) and rounded on parts search and parts edit. The number doesn't get correctly formatted in the OH column on orders and invoices.

**Comment by ehuelsmann** [comment]
Note though that we only have generic formatting with decimals; we don't have formatting settings for parts counts where specific numbers of decimals will be produced.
