### ISSUE TITLE
Unable to add tax form (1.5.15)

### ISSUE THREAD

**Issue by kronos003** [ledgersmb/LedgerSMB#3431]
Steps to create:
Login > Tax Forms > Add Tax Form > Save

Error:
```
Action Not Defined: save at /srv/ledgersmb/tools/../bin/lsmb-request.pl line 100.

dbversion: 1.5.15, company: lsmb-sandbox
Status: 500 Internal server error (PSGI.pm run_new) 
```

Note:
It should be noted that this installation is a docker container proxied via httpd on a centos 7 host running virtualmin(webmin) with all updates installed. 

Directives on httpd:
```
<Location  /internal/lsmb/>
ProxyPass http://172.17.0.3:5762/
ProxyPassReverse /
</Location>
```

**Comment by ehuelsmann** [comment]
The cause has been established: the required `action` attribute is missing in this specific form.
