### ISSUE TITLE
Payments on invoice screen not posting with invoice (lsmb 1.5.15)

### ISSUE THREAD

**Issue by kronos003** [ledgersmb/LedgerSMB#3435]
Setup: CentOS7 with docker an Virtualmin installed (KVM VM)

`Workflow: Login > create sales order> save sales order > Logout > log in > write notes on sales order and edit qtys > save sales order > create invoice from sales order screen > fill in payments field on invoice > update invoice> post invoice > search for invoice > open invoice> payment not posted with invoice`

To get the payment noted for the invoice I need to submit payment via cash receipt. Then when I search for the invoice the payment shows. In the invoice screen it doesn't show which account the payment posted to.( but the pdf print shows it as expected)

This leads me to believe there is some brokenness in the invoices section of the AR handling code.

**Comment by kronos003** [comment]
Further testing indicates this is an issue when connecting from google chrome, but not an issue when connecting from firefox. I test this against a virgin install of chrome to rule out interference from installed plugins.

**Comment by ehuelsmann** [comment]
Only happens with chrome, not with firefox.

**Comment by kronos003** [comment]
I cant replicate in sandbox having started with a virgin chrome instance, loading all plugins one by one, until finally logging into my google account on the virgin browser, and then just using my "dirty" chrome browser that was breaking on the production server. 

At this point I suspect I haven't properly patched the production server. I'll try with 1.5.17 clean docker and see if problem persists.

**Comment by ehuelsmann** [comment]
thanks for the continued investigation. would love to hear how it is with .17.

**Comment by ehuelsmann** [comment]
My understanding is that this was not an issue (not reproducible with a clean container)
