### ISSUE TITLE
printed invoice showing twice the payment amount actually entered

### ISSUE THREAD

**Issue by kronos003** [ledgersmb/LedgerSMB#3440]
LSMB Version: 1.5.16 - docker ledgersmb:latest

I looked to see if this affects the chart of accounts, and looks like the chart of accounts shows the correct amount for the transaction. 

From my brief testing this appears to **affect ONLY  printed invoices** - PDF, Postscript, HTML. Those were the only ones I tested. 

My suspicion is you need to check the mechanism that feeds the following variables in the templates:
 "lsmb paid" and "lsmb total" 

Additionally the account selector in the payments area is still broken. The amount and destination account still posts correctly from the invoice screen, but the selector still doesn't show the account the money was posted to when you come back to the screen from an invoice search.

So whatever feeds the default position of that destination account select also needs to be looked at. 

Thinking about it, it might be a good idea to completely delete the select from posted payments(and simply give the paid account) if possible. While wiping out that particular bug, this could eliminate confusion on a bunch of levels(like giving the impression you can change what account the payment is in after you've already posted the invoice and/or payment)

**Comment by kronos003** [comment]
**UPDATE:**
seems paying via cash receipts alters things.
when paying via cash receipts, all is well.
but when noting payment directly on the invoice as it is posted - that is when the double balance issue occurs
I tested this twice with payments to 2 AR accounts to be sure.

**Comment by ehuelsmann** [comment]
Fixed in f1ccd4b
