### ISSUE TITLE
DB Backup needs proper error handling

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3441]
Currently (at least in 1.5 series) Backups can fail silently and deliver a zero size file.

One possible cause of this is a version mismatch between pg_dump and the Postgresql server

One way or another we need to handle errors in this process and
- Return a valid error message to the user
- Log a detailed error message
- NOT return any file if the dump failed

@ehuelsmann do you think we should fix this in the 1.5 series, or only before 1.6 branch

**Comment by ehuelsmann** [comment]
This problem lies currently outside our code base: PGObject::Util::DBAdmin is the module we depend upon to run commands against our databases. Fixing that would fix our issue, if it was done in a backward compatible way.

**Comment by sbts** [comment]
But I assume we can at least trap on returned file size and raise a "backup failed" error in the UK and not return the file to the user

**Comment by nick-prater** [comment]
Fixed in both master and 1.5 now that we depend on updated PGObject::Util::DBAdmin 0.120.0
