### ISSUE TITLE
Documentation: Translation into Spanish Language

### ISSUE THREAD

**Issue by michaelizer** [ledgersmb/LedgerSMB#3445]
Greetings, I would love to translate your project into Spanish so people limited by the language could join, read and use it with no problems. Let me know what do you think. 

Also, I think there's going to be needed a new branch or something.

Thanks in advance for you answer and keep up the good work!

**Comment by ehuelsmann** [comment]
Hi, We definitely need improvements to our spanish translation. You're free to choose the way you contribute your translation. You could do that in a repository which you clone from ours and submit PRs (Pull Requests) with the updated translations. With this method, you can use whatever tools you like to edit our 'po' files.
Another way to contribute your translations would be to go through Transifex (https://www.transifex.com/ledgersmb/ledgersmb/dashboard/) -- a web-based tool from which we download our latest translation-updates before every release.

If you want to get more interactive contact, feel free to join our Matrix channel through https://riot.im/app/#/room/#ledgersmb:matrix.org and we can probably help you get up and running.

Regards,

Erik.

**Comment by michaelizer** [comment]
Thank you for your time, I will start right away.

Should a create an i18n folder or not?

**Comment by ehuelsmann** [comment]
No need: there is a `locale/po/` folder with an es.po file which contains all strings (to be) translated to spanish.

Hope that helps! And thanks in advance!

**Comment by ehuelsmann** [comment]
Hi,

Is there anything more we can do to to help you get started?

Closing for now, but please reopen for more help and discussion.
