### ISSUE TITLE
bad user name and password

### ISSUE THREAD

**Issue by hermawan-fsi** [ledgersmb/LedgerSMB#3446]
When registering an issue, please take the following directions
into account to help the project best organize its work and be
efficient to help address your issues:

 * Register /exactly/ 1 problem per issue
 * Summarize the problem in the issue title
 * Mention which LedgerSMB version you're using

But first and foremost, include in your description:

 * Which steps did you execute to see the failure
 * What is the outcome of the steps that you consider faulty
 * Describe which outcome you were expecting

For more information on these three bullets, please consult
the Mozilla instructions for bug reporting:

  https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by ehuelsmann** [comment]
Please read the text in the description field and add text describing the situation and the problem. Then we can reopen the issue.

Thanks for taking the time to report!
