### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [ledgersmb/LedgerSMB#3451]
Hi, I would like to collaborate with the translations into Spanish, are they already done or is there still to be translated?

**Comment by ehuelsmann** [comment]
Hi!
Thanks for stepping up! No, the spanish translation isn't done yet. Far from, even!

Our project uses the translation interface of [Transifex](https://transifex.com). If you create an account there, log in and then browse to this url: https://www.transifex.com/ledgersmb/ledgersmb/languages/ you can click on one of the Spanish translations, you'll find a number of "Resources" (LedgerSMB-13, LedgerSMB-14, LedgerSMB-15 and LedgerSMB). Please start translating LedgerSMB-15. Matching translations will automatically be copied to the other resources.

Every time we release, we update the distributed translations from that resource into the distribution archive. So, your efforts should be reflected in the next release after you make them. Normally that would be within 3 to 6 weeks.

Recently, two other people stepped up to help with the translation: @michaelizer (in #3445) and @jossue33 (in #3448). While I haven't seen much movement in the transifex project, it could be that they're translating by other means. I would like to suggest that the three of you use devel@lists.ledgersmb.org to coordinate your efforts and prevent double work. 

Thanks again for stepping up!

Regards,

Erik.

**Comment by ehuelsmann** [comment]
Hi,

Is there anything we can do to help? I've seen one submission for the readme but don't know how to accept. Can you please indicate what you think should be the next step? Also, if you don't know, please conact us to guids you through the process...

**Comment by ehuelsmann** [comment]
Closing for now, but please reopen on further questions!
