### ISSUE TITLE
'Cannot bind a reference' when trying to upload a file to a contact.

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#3458]
Contacts - > find a contact -> Files tab -> AAttach to Entity -> Browse -> Upload

Resulting error window:

Error!

Cannot bind a reference

dbversion: 1.5.9, company: jasonic
Status: 500 Internal server error (PSGI.pm run_new) 

Server says: 

Failed to execute bin/lsmb-request.pl (): Died at ledgersmb-1.5.9/tools/../lib/LedgerSMB.pm line 517, <_GEN_300> line 500.

**Comment by ehuelsmann** [comment]
What is the version of PGObject::Type::ByteString that you have installed?

**Comment by kaare** [comment]
Den 23-02-2018 kl. 10:26 skrev Erik Huelsmann:
> What is the version of PGObject::Type::ByteString that you have installed?

$PGObject::Type::ByteString::VERSION is 1.1.2

**Comment by kaare** [comment]
Tried to upgrade to latest (1.2.0) with the same result.

**Comment by ehuelsmann** [comment]
Ok. if that doesn't work, other candidates are PGObject, PGObject::Simple and PGObject::Simple::Role. I'm sorry I'm unable to tell off-hand. However, I'm certain this doesn't occur with the latest versions of these 4 modules: the functionality works on our Docker module.

**Comment by kaare** [comment]
PGObject::Simple was the latest, but I upgraded in turn

PGObject-2.000002 (upgraded from 1.403.2)
PGObject-Simple-Role-2.000002 (upgraded from 1.12.1)

It probably worked, but now I get this error when I try to access to contact:

Error!

Not a HASH reference at ledgersmb-1.5.9/tools/../lib/LedgerSMB/Template/HTML.pm line 100.

dbversion: 1.5.9, company: jasonic
Status: 500 Internal server error (PSGI.pm run_new) 

$rawvars, which is accessed in that line, is of type PGObject::Type::ByteString when it fails.

**Comment by sbts** [comment]
@kaare unfortunately 1.5.9 has a known issue with attached files.
Please upgrade to 1.5.16 which should solve that

**Comment by kaare** [comment]
Upgraded to 1.5.17 and I can see the customer, and the uploaded files
