### ISSUE TITLE
Sequence with prefix not being savef

### ISSUE THREAD

**Issue by nicefiddler** [ledgersmb/LedgerSMB#3511]
I am using docker with latest version of lsmb and postgres. When we go to System--sequence and create a sequence for GL reference number with label, prefix and suffix and click on save, a pop-up appears with "An error occurred". Please resolve or advise.

**Comment by nicefiddler** [comment]
I am using docker with latest version of lsmb and postgres. When we go to System--sequence and create a sequence for GL reference number with label, prefix and suffix and click on save, a pop-up appears with "An error occurred". Please resolve or advise

**Comment by einhverfr** [comment]
Hi.  Thank you for your report.  I am sorry you are having issues.

Do you have any information as to PostgreSQL logs or web server logs when this happens?  Would you like help obtaining this information?

**Comment by nicefiddler** [comment]
Yes, please. How should I obtain the PostgreSQL/web-server logs? Please
guide me.

**Comment by sbts** [comment]
Hi @nicefiddler,
@ehuelsmann has already fixed this issue so we shouldnt need any logs right now.
Check his comment above, a release is likely in 2 to 3 weeks.

If you need a fix earlier and care to try patching yourself he has provided a link to the changes required

**Comment by nicefiddler** [comment]
Thanks. Actually I am sort of a newbie. I tried updating the image with
docker pull, but it didn't work.
So I downloaded the changed file and with the right permissions/ownerships
have used docker cp to put it in the right location in the container. It
worked.
However, is that the right way to do it? Is there a better way which is
recommended? Having done what I have done, will it pose problems for future
docker pull updations? Please advise.

**Comment by ehuelsmann** [comment]
Updating the image using pull didn't work because there's no new image yet(the fix isn't in any release yet).

Your solution to use Docker's cp command to insert the fixed file into the container you have now is d indeed the best available solution.

**Comment by nicefiddler** [comment]
Thanks.
