### ISSUE TITLE
Configuration options db_host, db_port, db_sslmode not respected

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#3519]
The `ledgersmb.conf` configuration file, read by `LedgerSMB::Sysconfig` supports configuration options:

* db_host
* db_port
* db_sslmode

But these are not applied when making database connections. They should be applied, or removed completely.

**Comment by ehuelsmann** [comment]
The code might have misled you: LedgerSMB::Sysconfig sets the environment variables PGHOST, PGPORT and PGSSLMODE. These will be used by libpg to set up a connection to the Pg server. As such, these values aren't directly passed to the DBI->connect call, but they *are* respected (or at least, that's my interpretation).

Now, this approach scores an A for obscurity, so, we probably want to remove the dependency on the environment variables and pass these options to DBI->connect explicitly.

**Comment by sbts** [comment]
@ehuelsmann removing the env vars isn't as easy as passing them to dbi connect .
We also have to.cover backup and restore where external tools are used.
Currently the env vars deal with those cases as well

**Comment by nick-prater** [comment]
Thanks for the feedback. Conclusion: my bug report is incorrect - db_host, db_port, db_sslmode configuration options ARE respected via environment variables. The options therefore work correctly, so I am closing this bug report.

Regarding backup and restore, we could pass db_host and db_port options to PGObject::Util::DBAdmin, but the pg_dump command it calls only accepts sslmode via an environment variable.
