### ISSUE TITLE
Configuration options for smtp authentication not respected

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#3520]
The `ledgersmb.conf` configuration file, read by `LedgerSMB::Sysconfig` supports configuration options:

* smtpauthmethod
* smtppass
* smtpuser

But these are not applied when sending e-mail. They should be applied, or removed completely.

**Comment by ehuelsmann** [comment]
I don't see that MIME::Lite supports `smtpauthmethod`. The other two options can probably be implemented through equivalent options in MIME::Lite.
