### ISSUE TITLE
1.5: Backup fails with zero byte file

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#3531]
New issue created following discussion on closed bug #2686.

@nicefiddler reports that clicking backup button from the setup.pl screen looks successful but sends a 0-byte file to download using lsmb 1.5.19 docker images.

This is a different problem to #2686, though the result is the same.

I see the same issue using ledgersmb-dev-docker docker-compose infrastructure.

I do not see the issue on my production 1.5.19 Debian Jessie machine.

**Comment by ehuelsmann** [comment]
Resolved in ca781bf.
