### ISSUE TITLE
Starman invocation path dependent

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#3532]
This was reported by Frans some time ago but I expected to quickly fix it.  I have now done some debugging and am not sure what a solution is other than perhaps to have a change of directory.

This has been reproduced on latest 1.4 and was originally reported on 1.5.  The basic problem is the same in both cases.  The problem is that the ledgersmb.conf is not found.  After some debugging the problem has been deptermined to be the fact that the current working directory is set to wherever it was before LedgerSMB was started.  This makes it needlessly hard to write init scripts etc and it makes deployments needlessly fragile.

**Comment by einhverfr** [comment]
To reproduce this simply try to start LedgerSMB from a directory other than the application one

**Comment by ehuelsmann** [comment]
You're aware there's an environment variable which can point LedgerSMB to the configuration file?

We have "init scripts" in the form of systemd config files. Those allow us to specify a working directory. Init scripts could do something similar based on a config file which they source from /etc/default/ledgersmb (debian style) or /etc/ledgersmb/... (RH style).

Do we know what other directory to use than the CWD? I mean, which directory should be the one to use if *not* the CWD?

**Comment by sbts** [comment]
Using anything other than the CWD may cause complications in other ways as well.
Can you be certain all of our dependencies will use what ever other mechanism you come up with?

Much better to follow standard practice and expect our init script (or service file etc) to ensure a rational CWD

Also, as ehuelsmann said simply setting an env car points at a ledgersmb.conf instance. 

BTW it hasn't been necessary to use a ledgersmb.conf file in 1.5 or newer in 12 months or more.
Even better if you do have a couple of settings you need to change its only necessary to put those settings in the config file, so no need for large confignfiles any more
