### ISSUE TITLE
Format Selector on Sales Order/Print button is ignored

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3563]
In 1.5.20 using the official Docker container, when viewing an individual sales order, if you set the output to "Screen" and use the "Print" button, you always get a .ps file, regardless of whether you select HTML, CSV, Postscript, or PDF.

This is not a problem for invoices -- just for Sales Orders. Have not checked purchase orders.

**Comment by ehuelsmann** [comment]
@freelock 1.5 is out of community support now; do you experience the same with 1.6 or 1.7? If not, I'd like to close this issue.

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
