### ISSUE TITLE
Quote in customer name changes to "?" in bill-to/ship-to in PDF invoices and sales orders

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3564]
We have a customer with an apostrophe in the name -- "Children's ...".

When generating either an invoice or a sales order using a LaTeX template, the ' gets turned into a ?.

**Comment by ehuelsmann** [comment]
Tested in the 1.7.13 development docker image. Works for me. Can you test more? Is this LaTeX or XeLaTeX related? What happens when you change fonts? Does it still fail in 1.7?
