### ISSUE TITLE
Invoice/Sales Order note escaping issues

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3565]
When generating a PDF or PS of a sales order or invoice, we often have paragraphs of text. We've found some escaping issues around various quotes:

' (single apostrophe) gets rendered correctly as '
" (double-quote) -- gets output as an html entity, \&quot;
curly-quotes, single or double -- get output as ?

**Comment by ehuelsmann** [comment]
Hmm. I'm finding I have no idea how to generate curly quotes on my keyboard. Can you tell me how?
