### ISSUE TITLE
AR Overpayments not shown in Cash->Reports->Receipts

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#3577]
* Enter an AR Overpayment
* Load the Cash->Reports->Receipts screen for the relevant period
* Note that the received overpayment is not shown in the Receipts report

**Comment by ehuelsmann** [comment]
Tested with payments (same code path); search has been changed to query the `payment` table instead aggregating estimated payments.
These changes fixed this problem.
