### ISSUE TITLE
journal.pm missing

### ISSUE THREAD

**Issue by msdeason** [ledgersmb/LedgerSMB#3591]
**_Unable to open script: LedgerSMB::Scripts::journal : No such file or directory: Attempt to reload LedgerSMB/Scripts/journal.pm aborted. Compilation failed in require at (eval 1061) line 1._**

occurs when choosing **Chart of Accounts** from the **General Journal** menu.
other reports work fine such as Income Statement (cash basis) and AR Outstanding.

LedgerSMB 1.5.20 on Ubuntu 16.04 (xenial)
via deb http://ppa.launchpad.net/ledgersmb/main/ubuntu xenial main

Upgraded from 1.4.34 by pg_dumpall to new lxc container then installing LedgerSMB via apt-get

**Comment by jame** [comment]
So you created the LXC container, installed Pg, imported the 1.4.34 database and then installed the ledgersmb-1.5 pkg?  Did you also install one of the web proxy pkgs?
No issue running the initial setup.pl, updating the company DB to the 1.5.20 version?

**Comment by jame** [comment]
Also;  is that the only error you received?  I ask because when I attempted to duplicate the issue, I received an error page the specifically mentioned a module that it couldn't find.  If you did see something like that as well, I'd appreciate you posting about it.

**Comment by jame** [comment]
Note that if what you are seeing is a JSON.pm related error, please explicitly install the *libjson-perl* package (if you haven't already done so) and let me know if that resolves the error.

**Comment by msdeason** [comment]
I installed the ledgersmb-apache package, which pulled in all of the appropriate web packages.  Setup.pl converted the database without error.  Most forms and pages work, only chart of accounts and GL search do not, and I pasted the entire message I received into this issue.  There was no mention of JSON.

I also untarred ledgersmb-1.5.20.tar.gz from your repository into an obscure location and compared journal.pm with /usr/share/ledgersmb-1.5.20 and they are identical.

libjson-perl was not listed by dpkg --list, so I installed it, but still receive the same message, except the eval changed to 1794

**Comment by jame** [comment]
I'll redo the testing 'xenial' LXC as well as create a new 'bionic' testing lxc, & see if I can duplicate your issue with either of those.

**Comment by jame** [comment]
The *libjson-perl* package should be kept installed, along with *libjson-xs-perl*, as they are both needed for the ledgersmb 1.5.x series releases;  I'll update the ledgersmb-1.5 package regarding that.
I created an Ubuntu *bionic* LXC container & installed the ledgersmb-1.5 v1.5.20 package to it.  Did not see the error when accessing the *General Journal|Chart of Accounts* menu that you listed but do still see one regarding JSON.pm not being located, which is resolved by installing the *libjson-perl* package.
Note that is (& has been) with a newly created company DB, not an imported & upgraded one.

**Comment by jame** [comment]
To be clear, the error I see (which is resolved by installing the *libjson-perl* package) is as follows:
> Unable to open script: LedgerSMB::Scripts::journal : No such file or directory: Can't locate
 JSON.pm in @INC (you may need to install the JSON module)

**Comment by jame** [comment]
Also;  what do you mean by " GL search" ?  The ***General Journal|Search and GL*** menu item?

**Comment by msdeason** [comment]
Yes.  **Search and GL** menu item.

I do not see JSON.pm in the message.  Screen shot attached.
![lsmb-screenshot](https://user-images.githubusercontent.com/13155320/39972345-023aa0de-56c2-11e8-8a3e-71e2a5040068.jpeg)

**Comment by ehuelsmann** [comment]
@msdeason that error can be caused after the module fails to load the first time. Please restart the ledgersmb-starman service and try again.

**Comment by msdeason** [comment]
I discovered this today shortly before reading your latest comment.  Thanks for all your help.  You may consider this issue resolved.
