### ISSUE TITLE
Reporting Feature Requests -- revenue broken down by customer information

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3675]
I'm completing a census survey, and it's asking for data I cannot easily pull up. So far:

- Total revenue for 2017 from customers outside the US
- Revenue for 2017 broken down by customer sector: private business, non-profit, federal government, local government, individuals

**Comment by ehuelsmann** [comment]
This should actually be trivial to do as customers have an associated country and a SIC code.

**Comment by ehuelsmann** [comment]
The report will be custom at this point, but those
