### ISSUE TITLE
GL journal entry DISPLAY button order varies

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3680]
Reported by cricalixwood in #ledgersmb 

I have a very minor issue. In 1.5.21 (and all previous - it just annoyed me enough today to mention it), there appears to be some sort of race condition in the GL journal entry DISPLAY. If I:
. Enter a journal, press update, press post,
. I get a new panel with buttons for 'Save as new',Schedule, New, Template in that order
.EXCEPT
. Sometimes the order is TEMPLATE then NEW. It seems to be random which way they are displayed, at least I've not discerned a pattern yet.

Not urgent, not important, but annoying.

REgards

**Comment by cricalixwood** [comment]
OS is Lubuntu, 18.04.
Browser is Firefox Quantum 60.0.1 (64-bit) (I'm sure I've seen it happen on Chromium too - I don't think it's a browser issue).

I will try to get screenshots and add them, but I don't have a test company set up at the moment, and I've done my entries for this month.

**Comment by cricalixwood** [comment]
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 62 registered patches, see perl -V for more detail)

**Comment by cricalixwood** [comment]
/home/roger/Screenshot_2018-06-10_GL3_after_post.png
/home/roger/Screenshot_2018-06-10_GL8_after_another jnl_update_post.png

**Comment by cricalixwood** [comment]
![image](https://user-images.githubusercontent.com/38114792/41201151-62560e1a-6caa-11e8-95d4-fb2b34169ee1.png)

First screen shot, after a journal.

**Comment by cricalixwood** [comment]
![image](https://user-images.githubusercontent.com/38114792/41201164-8a146e7e-6caa-11e8-9f97-c33e9637393d.png)
Second screen shot, a couple of Journals later.
