### ISSUE TITLE
Menu duplicates http requests during load

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3683]
looking at the network tab of chrome dev tools we see the following when refreshing (ctrl-r) our main app screen.
![lsmb-1 6-menu-ok](https://user-images.githubusercontent.com/11002795/41365650-8972eaa8-6f6c-11e8-8fc0-d899fc51dbad.png)

As can be seen the following are requested multiple times ....
- http://localhost:5762/js/dijit/icons/images/loadingAnimation.gif
- http://localhost:5762/js/dijit/themes/claro/images/treeExpandImages.png
- http://localhost:5762/js/dijit/nls/common.js

We should investigate if it's possible to prevent the duplicate requests.
NOTE: they should be delivered from client side cache, but that's not really the point

**Comment by ehuelsmann** [comment]
Resolved in 1.6.1
