### ISSUE TITLE
Menu is missing "home" node

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3685]
Once you have clicked on ANY menu item there is currently no way short of reloading the page to re-display the "Welcome to LedgerSMB" panel that is shown immediately after login.

**Comment by ehuelsmann** [comment]
Why is that a problem?

**Comment by ylavoie** [comment]
We *may* want to add that as an *about* item, but that's not a problem

**Comment by ehuelsmann** [comment]
ok. so, if it's not a problem, why do we want this?

**Comment by sbts** [comment]
@ehuelsmann I feel we should make it easy to return to that information as it contains the links to documentation and help channels, including the Mailing list archives, #ledgersmb etc

Perhaps we do this as a "home" entry at the top of the menu tree, or a "help" or "about" entry at the bottom.
Regardless of how we do it, the behaviour immediately after login should be to select the associated menu item which then causes the information to be displayed.
That would help with educating the user how to find it

**Comment by ehuelsmann** [comment]
But why do you want to return to that page?! I mean, it doesn't contain anything related to the actual company accounts...

**Comment by sbts** [comment]
It does provide the reference links for Chat, mailing list, and all the other links in the "Community Resources" panel

**Comment by ehuelsmann** [comment]
The work around to getting to that page is to log out and back in. The logo links to the community site (ledgersmb.org). That should help when people are not on the login page. 

Other than that, I think we already have too many top level menu nodes.
