### ISSUE TITLE
1.6.1 Menu links ignore additional clicks -- long after the first one

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3704]
I think this might be related to the recent menu rework. 

The steps that caused this:

1. Go to Cash -> Vouchers -> Receipts. 
2. Create a batch, receive payment, post approval screen, all good.
3. Try to go to Cash -> Vouchers -> Receipts again to create a new batch

Expected result: Go to the batch selection/creation screen

What actually happens: Nothing, you remain on the batch screen entry screen

Workaround: Click any other menu item. Then you can click Cash -> Vouchers -> Receipts again.

**Comment by sbts** [comment]
@freelock does this only happen with Cash -> Vouchers -> Receipts or is there an issue with other menu items as well?

**Comment by freelock** [comment]
That's the only link I've tested, and I think the only one I actually re-click as a matter of practice... in most other cases I use the back button..

**Comment by ehuelsmann** [comment]
Yes, it's broken on all links clicked more than once in succession; when a form is POSTed in between, that doesn't update the "window.location" property, which means that even in those cases the clicked link is ineffective. In 1.5, we had the same problem and introduced a "click counter" to resolve the issue. When the new menu was implemented, the "click counter"-code wasn't used to update the "window.location" (thus the returning problem)

**Comment by freelock** [comment]
hmm this is still broken in 1.6.2...

Cash -> Vouchers -> Receipts, receive some payments, post batch. Then try to get back to the create batch screen, no response.

**Comment by ehuelsmann** [comment]
@freelock this works for me. it could have been a stale cached JS asset. Could you try again, now that the asset cache should have refreshed?

**Comment by freelock** [comment]
Still a problem...
![peek 2018-07-28 08-55](https://user-images.githubusercontent.com/46937/43358309-5364b108-9244-11e8-8029-28cbb33d2987.gif)

**Comment by ehuelsmann** [comment]
This is fixed in 1.7. Not fixing in 1.6.
