### ISSUE TITLE
Add back removed functionality:  Invoice lines matching parts search

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#3752]
In 1.3 and lower one could search for invoices, sales orders, etc, that had parts and see the quantity, as well as the items, a link to the invoice etc.  This was removed (by me by accident) in 1.4 and higher.  It needs to be added back.  There is currently no other way to locate all invoices quickly that have a particular part and understand how many are sold when.  There is an inventory activity report but it is not good enough.

Technically this is a regression but we didn't notice it soon enough to tag it as such

**Comment by einhverfr** [comment]
I am tagging this as a regression because I did the code that removed the functionality and it was definitely not on purpose.

**Comment by ehuelsmann** [comment]
@einhverfr which menu option on 1.3 does this? I'd like to add it back, but it'll take me *much* less time if I know where to look (at least so I can analyse and rebuild the UI)...

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
