### ISSUE TITLE
Box to remove duplicate customers

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#3753]
Need a way to remove duplicate customers.  My thinking is:

1.  A box which indicates which customer to move things to.
2.  A button that merges results.

When the button is clicked, sales invoices, orders, etc. are moved to the referring customer (by meta_number) and the record is then deleted.  Pricematrix, customer tax, and contact/address info are all removed.  If there are no other entity credit accounts, the entity is removed.

**Comment by ehuelsmann** [comment]
Wondering how to achieve this while at the same time making sure there's no impact on issued invoices.

**Comment by ehuelsmann** [comment]
As the metanumber potentially ends up on the invoice, how are we going to solve the problem that the invoices need to remain the same? I mean, isn't it better to mark one or the other "expired" (by filling in an end date)?

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
