### ISSUE TITLE
Error deleting transaction template

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#3772]
In master or 1.6:

Transaction Templates -> Set checkbox for a row -> Click `Delete`.

An error is displayed: `ERROR: current transaction is aborted`

Further in the logs: `ERROR:  permission denied for relation journal_line CONTEXT:  SQL function "journal__delete" statement 1: SELECT * FROM "public"."journal__delete"(?) at /usr/share/perl5/PGObject.pm line 359.`

**Comment by ehuelsmann** [comment]
@nick-prater this has been resolved now, I take it???

**Comment by nick-prater** [comment]
Resolved in 1.6.4, now released
