### ISSUE TITLE
PGObject::Type::BigFloat warning

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#3781]
Not sure if it's a real issue, but I'll note it anyway.

When upgrading to 1.6.3 from 1.5.21 I used 
  cpanm --quiet --notest --with-feature=starman --installdeps .
to make sure all dependencies were met. But when starting the server, there were 5 lines of 
Use of deprecated method register_type of PGObject module at <...>/PGObject/Type/BigFloat.pm line 50.

Upgrading PGObject::Type::BigFloat with cpanm removed the warnings. Perhaps there should be a check for a minimum version there?

**Comment by ehuelsmann** [comment]
@kaare thanks for your report. The warning was harmless, but your action was exactly the right step to resolve it.
Basically, we're likely to drop support for the older version of PGObject's "register_type", but the current situation allows deployment to older distros which have older PGObject versions.

We'll increase the minimum version when we stop supporting the fallback code which generates the warning.
