### ISSUE TITLE
Symlink 'bin/diagnose' points to 'bin/diagnose.sh' file which is not present

### ISSUE THREAD

**Issue by jame** [ledgersmb/LedgerSMB#3882]
There is a symlink 'bin/diagnose' that is present in the distribution archives for the 1.6.x versions as well as being in the 'master' and '1.6' branches in the code repository;  but the file itself that the symlink points to, bin/diagnose.sh' , is not actually present in the bin/ directory.

**Comment by ehuelsmann** [comment]
But the link points to `utils/diagnose/`, not `bin/`.

**Comment by jame** [comment]
My mistake;  thank you for pointing that out.  It's a packaging issue after all;  I'll fix it at that end.
