### ISSUE TITLE
Order Entry / ship_to addresses (errors new install)

### ISSUE THREAD

**Issue by smbgoodname** [ledgersmb/LedgerSMB#3889]
Have recently installed LedgerSMB 1.6.5 to learn the system. Upgraded to 1.6.6 and the same issues are appearing.

The user has full permissions.

~~On the Order Entry -> Sales Order / Purchase Order screens. The Sales Person field value is not being saved.~~ (split out to #3910)

On the Order Entry -> Sales Order screen. When using the shipto then saving the sales order results in the following error.

' INSERT INTO new_shipto (trans_id, oe_id,location_id) VALUES ( ?, ?, ?) ERROR: permission denied for sequence new_shipto_id_seq at /ledgersmb/bin/../old/lib/LedgerSMB/OE.pm line 461. '

dbversion: 1.6.6, company: testdb

The new_shipto table has no records.

**Comment by ehuelsmann** [comment]
@smbgoodname thanks for reporting! I'll have a fix to ship with 1.6.7.

**Comment by smbgoodname** [comment]
Permission fix looks good. Should have put this in a different report but what about the Sales Person field not being saved with the Sales and Purchase orders?
