### ISSUE TITLE
Add Transaction Payment account in AP->add transaction has regressed in 1.6.6

### ISSUE THREAD

**Issue by kainz** [ledgersmb/LedgerSMB#3890]
ledgersmb#2580 is happening again in ledgersmb 1.6.6.  Change in formgen/handling at play?

**Comment by sbts** [comment]
This issue affects more than just `AP->add transaction`
I can confirm it also affects AP->Vendor Invoice "Payment account"

**Comment by ehuelsmann** [comment]
I can't see this happening in AP->add transaction. It does happen for me on the vendor invoice. Given the structure of our code base (both AR and AP transactions go through the same account selection code in aa.pl -- but vendor invoices go through ir.pl while sales invoices go through is.pl).
