### ISSUE TITLE
Dropdown Filter Select for Vendor selection in invoices BROKEN

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3896]
If `max per dropdown` is set high enough to enable dropdown lists for vendor selection you can't select any entity other than the first one.
ie: on update or save the entity ALWAYS returns to the first entry in the list.

This is confirmed on 1.6.6

**Comment by nick-prater** [comment]
Confirmed on master. This applies to Vendor Invoices, but not Sales Invoices.
