### ISSUE TITLE
add_shipto inserts multiple addresses then system randomly uses only one address

### ISSUE THREAD

**Issue by smbgoodname** [ledgersmb/LedgerSMB#3899]
Using version LedgerSMB 1.6.6

The $form->add_shipto($id, $is_oe); in old/lib/LedgerSMB/form.pm always adds a new record. This means that multiple shipto addresses can be linked to one sales order, purchase order, or transaction. When using the shipto address with oe_id the system uses the first row returned which is random because there is no "order by" on the query. old/lib/LedgerSMB/OE.pm line 594 to 626

Have a fix for the oe_id situation but not sure what is required for the trans_id situation. Do multiple shipto addresses make sense for the trans_id situation?

The add_shipto function can use a INSERT ON CONFLICT (insert or update) query to remove multiple records. It would mean a minimum PostgreSQL version of 9.5 and a unique constraint being placed on the oe_id field.

ALTER TABLE public.new_shipto ADD CONSTRAINT new_shipto_oe_id_key UNIQUE(oe_id);

The $form->add_shipto($id, $is_oe); function would be changed to the code below. Proposed function assumes uniqueness on the trans_id and oe_id.

sub add_shipto {

    my ($self, $id, $is_oe) = @_;
    if (! $self->{locationid}) {
        return;
    }
    my $idType = "";

    if ($is_oe) {
        $idType = "oe_id";
    }
    else {
        $idType = "trans_id";
    }
    my $query = "INSERT INTO new_shipto (${idType}, location_id) VALUES (?, ?)ON CONFLICT (${idType}) DO UPDATE SET location_id=EXCLUDED.location_id";
    my $sth = $self->{dbh}->prepare($query) || $self->dberror($query);

    my $rw = $sth->execute(
        $id,
        $self->{locationid}
    ) || $self->dberror($query);

    $sth->finish;
}

**Comment by ehuelsmann** [comment]
The bit that remains in this issue is the accounting side.

**Comment by ehuelsmann** [comment]
My analysis is that, yes, the schema doesn't disallow duplicate entries for AR/AP invoices using Ship To. However, I've also established that repeatedly saving an invoice doesn't add more rows to the `new_shipto` table. Obviously, if someone finds a case where that happens, I'm very much interested!

While researching the issue, I found that clicking Ship To on an invoice with selected shipping address wasn't showing the selection in the shipping page. That issue has been fixed in PR #3951.

Closing this issue now that all research has been done and all findings have been resolved. Further fixes to be released in a next 1.5 and 1.6 release.

**Comment by smbgoodname** [comment]
Previously multiple new_shipto records were created each time a AR/AP invoice that contained a shipto address was saved. Now that the system deletes and inserts a new_shipto record every time a AR/AP invoice is saved the multiple records are gone but the new_shipto primary key unnecessarily increases. It is a minor issue but it would be preferable if the system only updated fields that have changed between saves.

**Comment by ehuelsmann** [comment]
Indeed I think the solution isn't pretty. I think that if there can be only one shipto address (and there can be only one), that the current design isn't good enough. But: there's a reason why the code I edited resides in `old/`: we want to part with all of it. I'd argue that picking this little bit now to improve on that distracts from the bigger (and more important) goal to do away with all of it.
