### ISSUE TITLE
Symlink to 't/.proverc' is not present in the release archive

### ISSUE THREAD

**Issue by jame** [ledgersmb/LedgerSMB#3900]
When attempting the '_make test_' on an unarchived LedgerSMB distribution archive, it fails with errors like the following:

> Error:  Can't locate LedgerSMB/Setting.pm in @INC (you may need to install the LedgerSMB::Setting module)

I've seen that kind of issue being caused by the needed directory not in the @INC path;  in this case, '_old/lib_' and its sub-directories.  The _t/.proverc_  file does include the line "_-Iold/lib_" but the symlink that points to that file in the code respository is missing from the distribution (release) archive.

**Comment by jame** [comment]
Note that it seems that it's the '_-h_' option to the _tar_ command that can be used to save symlinks to a tar archive.

**Comment by ehuelsmann** [comment]
what if we would just leave it at what it is?

**Comment by jame** [comment]
I'm sorry but that's not clear to me.  Leave 'what' as it is? As noted, the symlink pointing to 't/.proverc' is not making it into the archive. Are you thinking that adding that '-h' option to the release archive tar command would include too many other sym links?

**Comment by ehuelsmann** [comment]
I meant to ask "what if we just don't distribute the symlink in the archive": the symlink doesn't add much value, I'd say and is more a debugging artifact than a necessary configuration item.

**Comment by ehuelsmann** [comment]
Waiting 3 months for user feedback. Closing.

Please feel free to re-open when adding the feedback requested.
