### ISSUE TITLE
Order Entry screens: the Sales Person field value is not being saved

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#3910]
Splitting out of #3889, originally filed by @smbgoodname: On the Order Entry -> Sales Order / Purchase Order screens. The Sales Person field value is not being saved.

**Comment by ehuelsmann** [comment]
Ok. I have a solution here which I'll present to the project for review. The state of the code turns out to be pretty messy, which is part of why it took me so long to figure out the right way forward.

**Comment by smbgoodname** [comment]
I took a brief look at it myself and quickly discovered that it was beyond my current abilities. Judging by the number of other bug reports submitted the next release may address a lot of issues and should be a good one.
