### ISSUE TITLE
Can't locate object method "new" via package "Template" at ...ledgersmb/bin/../lib/LedgerSMB/Template.pm line 599.

### ISSUE THREAD

**Issue by maxxatgit** [ledgersmb/LedgerSMB#4034]
I’m getting the following Template error:

Can't locate object method "new" via package "Template" at ledgersmb/bin/../lib/LedgerSMB/Template.pm line 599.

This is LedgerSMB v 1.6.10, Perl 5.24.1, CentOS 7,  Apache 2.4.

I have Template::Toolkit installed in perl/lib/site_perl/5.24.1/x86_64-linux. There is both Template.pm and a Template directory which contains Base.pm, Parser.pm and Tools.pm. Base.pm and Parser.pm both contain a method named “new”. The “new” method in Parser.pm is a public method.

If I change line 599 in LedgerSMB/Template.pm from Template->new to Template::Base->new There is no error at line 599, but at line 609 it can’t find $template -- >> process().

I've been trying to get LSMB to run on my server for a while now, and I keep getting this same error...
Please help.

**Comment by einhverfr** [comment]
Which version of Template Toolkit is installed?

**Comment by maxxatgit** [comment]
Version 2.28. It's odd though. I looked at the contents of Toolkit.pm and there was practically nothing there. Here is the code (that not commented out):
`package Template::Toolkit;

1;

__END_`

Thee isn't even a version number in there. So I reinstalled it with cpanm:
`perl/bin/cpanm --reinstall Template::Toolkit
--> Working on Template::Toolkit
Fetching http://www.cpan.org/authors/id/A/AT/ATOOMIC/Template-Toolkit-2.28.tar.gz ... OK
Configuring Template-Toolkit-2.28 ... OK
Building and testing Template-Toolkit-2.28 ... OK
Successfully installed Template-Toolkit-2.28
1 distribution installed`

And the contents of Toolkit.pm didn't change.

**Comment by maxxatgit** [comment]
FYI, I’m not using the system perl. I always use a separate installation of perl for apps (I started doing that back in the day when the system perl on CentOS was stuck at 5.08). 

This has never been a problem, I run both Foswiki and Request Tracker on that same server, with no problems. All shebang lines had to be found and changed. As an aside, there are 4 different flavors of perl shebang lines in LSMB, #!perl, #!/usr/bin/perl, #!/usr/bin/env perl and #!/usr/bin/plackup (this last flavor is in only 1 file, /bin/ledgersmb-server.psgi). I changed all of the shebang lines (except “#!/usr/bin/plackup”) to #!/opt/perl/bin/perl. The last one, I changed to #!/opt/perl/bin/plackup.

I even tried using the system perl for a bit, just in case there was some hard-coded reference to the system perl that I couldn’t find. I still got the same Template error.

It was suggested that I add the statement “use Carp::Always;” at the top of LedgerSMB::PSGI. I did that, and here is the output from that:

`Error!
Can't locate object method "new" via package "Template" at /opt/ledgersmb/bin/../lib/LedgerSMB/Template.pm line 599.
LedgerSMB::Template::_render(LedgerSMB::Template=HASH(0x514bdf0), LedgerSMB=HASH(0x9582a40), undef) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Template.pm line 625
LedgerSMB::Template::render(LedgerSMB::Template=HASH(0x514bdf0), LedgerSMB=HASH(0x9582a40)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Scripts/login.pm line 86
LedgerSMB::Scripts::login::__default(LedgerSMB=HASH(0x9582a40)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 116
LedgerSMB::PSGI::__ANON__() called at /opt/ledgersmb/bin/../lib/LedgerSMB/App_State.pm line 202
LedgerSMB::App_State::run_with_state(CODE(0x514b988), "DBH", undef, "DBName", undef, "Locale", LedgerSMB::Locale::en=HASH(0x3514880)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 128
LedgerSMB::PSGI::try {...} () called at /opt/perl/lib/site_perl/5.24.1/Try/Tiny.pm line 103
eval {...} called at /opt/perl/lib/site_perl/5.24.1/Try/Tiny.pm line 94
Try::Tiny::try(CODE(0x9582708), Try::Tiny::Catch=REF(0x9288a70)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 144
LedgerSMB::PSGI::psgi_app(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Middleware/ClearDownloadCookie.pm line 48
LedgerSMB::Middleware::ClearDownloadCookie::call(LedgerSMB::Middleware::ClearDownloadCookie=HASH(0x94a45d0), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Middleware/DisableBackButton.pm line 47
LedgerSMB::Middleware::DisableBackButton::call(LedgerSMB::Middleware::DisableBackButton=HASH(0x94a4690), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Middleware/AuthenticateSession.pm line 210
LedgerSMB::Middleware::AuthenticateSession::call(LedgerSMB::Middleware::AuthenticateSession=HASH(0x94a4750), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Middleware/Log4perl.pm line 72
LedgerSMB::Middleware::Log4perl::call(LedgerSMB::Middleware::Log4perl=HASH(0x94a4810), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Middleware/DynamicLoadWorkflow.pm line 98
LedgerSMB::Middleware::DynamicLoadWorkflow::call(LedgerSMB::Middleware::DynamicLoadWorkflow=HASH(0x94a48d0), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Middleware/AccessLog.pm line 27
Plack::Middleware::AccessLog::call(Plack::Middleware::AccessLog=HASH(0x94a49f0), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/Middleware/RequestID.pm line 52
LedgerSMB::Middleware::RequestID::call(LedgerSMB::Middleware::RequestID=HASH(0x94ae7e0), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/App/URLMap.pm line 71
Plack::App::URLMap::call(Plack::App::URLMap=HASH(0x92f3cc8), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 233
LedgerSMB::PSGI::__ANON__(HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Middleware/Conditional.pm line 16
Plack::Middleware::Conditional::call(Plack::Middleware::Conditional=HASH(0x95120a8), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/ledgersmb/lib/local/lib/perl5/Plack/Middleware/ReverseProxy.pm line 68
Plack::Middleware::ReverseProxy::call(Plack::Middleware::ReverseProxy=HASH(0x9582300), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Middleware/Conditional.pm line 16
Plack::Middleware::Conditional::call(Plack::Middleware::Conditional=HASH(0x95821c8), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Component.pm line 50
Plack::Component::__ANON__(HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Util.pm line 145
eval {...} called at /opt/perl/lib/site_perl/5.24.1/Plack/Util.pm line 145
Plack::Util::run_app(CODE(0x9582120), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Starman/Server.pm line 195
Starman::Server::dispatch_request(Starman::Server=HASH(0x1ddd0c0), HASH(0x90aa930)) called at /opt/perl/lib/site_perl/5.24.1/Starman/Server.pm line 298
Starman::Server::process_request(Starman::Server=HASH(0x1ddd0c0), Net::Server::Proto::TCP=GLOB(0x248f170)) called at /opt/perl/lib/site_perl/5.24.1/Net/Server.pm line 72
Net::Server::run_client_connection(Starman::Server=HASH(0x1ddd0c0)) called at /opt/perl/lib/site_perl/5.24.1/Net/Server/PreFork.pm line 225
eval {...} called at /opt/perl/lib/site_perl/5.24.1/Net/Server/PreFork.pm line 225
Net::Server::PreFork::run_child(Starman::Server=HASH(0x1ddd0c0)) called at /opt/perl/lib/site_perl/5.24.1/Net/Server/PreFork.pm line 183
Net::Server::PreFork::run_n_children(Starman::Server=HASH(0x1ddd0c0), 5) called at /opt/perl/lib/site_perl/5.24.1/Net/Server/PreFork.pm line 107
Net::Server::PreFork::loop(Starman::Server=HASH(0x1ddd0c0)) called at /opt/perl/lib/site_perl/5.24.1/Net/Server.pm line 58
Net::Server::run(Starman::Server=HASH(0x1ddd0c0), "port", ARRAY(0x2415da0), "host", "*", "proto", "tcp", "serialize", ...) called at /opt/perl/lib/site_perl/5.24.1/Starman/Server.pm line 106
Starman::Server::run(Starman::Server=HASH(0x1ddd0c0), CODE(0x1ddd030), HASH(0x24162f8)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Handler/Starman.pm line 25
Plack::Handler::Starman::run(Plack::Handler::Starman=HASH(0x1ddd018), CODE(0x1ddd030)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Loader/Delayed.pm line 20
Plack::Loader::Delayed::run(Plack::Loader::Delayed=HASH(0x1ba2660), Plack::Handler::Starman=HASH(0x1ddd018)) called at /opt/perl/lib/site_perl/5.24.1/Plack/Runner.pm line 277
Plack::Runner::run(Plack::Runner=HASH(0x1c4c208)) called at /opt/perl/bin/starman line 38
dbversion: , company: 1.6.10
`
I’m really hoping to get this working in my CentOS/Cpanel machine.

Thanks in advance!

**Comment by maxxatgit** [comment]
One last thing, I set the perl5lib env variable to:
Environment=PERL5LIB=/opt/ledgersmb/lib/local/lib/perl5

I could not start the ledgersmb-starman service without setting that...

**Comment by ehuelsmann** [comment]
> I have Template::Toolkit installed in perl/lib/site_perl/5.24.1/x86_64-linux. There is both Template.pm and a Template directory which contains Base.pm, Parser.pm and Tools.pm. Base.pm and Parser.pm both contain a method named “new”. The “new” method in Parser.pm is a public method.

Now that you published the fact that you're actually not using standard Perl installation *and* that you're using non-standard PERL5LIB settings, cal you please publish full paths for *all* of your installation, such as the path above? And is that full path actually in your `@INC`?

**Comment by ehuelsmann** [comment]
> Thee isn't even a version number in there. So I reinstalled it with cpanm:
perl/bin/cpanm --reinstall Template::Toolkit --> Working on Template::Toolkit Fetching http://www.cpan.org/authors/id/A/AT/ATOOMIC/Template-Toolkit-2.28.tar.gz ... OK Configuring Template-Toolkit-2.28 ... OK Building and testing Template-Toolkit-2.28 ... OK Successfully installed Template-Toolkit-2.28 1 distribution installed

Did you use a patched `cpanm` too?

**Comment by maxxatgit** [comment]
It is cpanm from the custom perl, yes. I call the cpanm binary directly: /opt/perl/bin/cpanm.

I don't think /opt/perl is in my @INC path. This is a noob question, but should the perl5lib variable point to that custom perl? I have it pointing to the modules installed in the Local::Lib directory.

I installed the dependencies with the following commands:
`cd /opt/ledgersmb
/opt/perl/bin/cpanm -l lib/local --notest --with-feature=starman --installdeps .`

The perl5lib points to that lib/local directory, which is:
/opt/ledgersmb/lib/local/lib/perl5

Sorry for the confusion...

I'll try pointing perl5lib to /opt/perl/lib/perl5 and report back.
Thanks

**Comment by ehuelsmann** [comment]
you can point to both directories, using

```
PERL5LIB=/opt/ledgersmb/lib/local/lib/perl5:/opt/perl/lib/perl5
```

that is, if `/opt/perl` isn't in your `@INC` because I would expect problems if you don't have that.

**Comment by maxxatgit** [comment]
As I was editing the PERL5LIB declaration in the starman setup, I noticed:

# In case you installed dependencies into a 'local::lib'
# make sure you set the PERL5LIB environment variable
# to the correct location by uncommenting the line below

I tried pointing it to the custom perl at /opt/perl/lib anyway, but to no avail.

How do I add /opt/perl to the INC path for the application?

Since all references to perl are pointing to /opt/perl/bin/perl, I would think that /opt/perl/bin/perl would look for any libraries or modules in /opt/perl/lib.

I don't want /opt/perl/bin/perl in the system INC path because I don't want the system to use the custom perl.

**Comment by maxxatgit** [comment]
Well... That did it! 
PERL5LIB=/opt/ledgersmb/lib/local/lib/perl5:/opt/perl/lib/perl5
made the Template error go away. I know just enough to get myself into trouble ;^)

Now I have other errors (wrong package version) that I can probably solve on my own. I REALLY appreciate the help. 

Thanks!

**Comment by ehuelsmann** [comment]
Bug in the installation environment; not in the software itself. Closing.
