### ISSUE TITLE
Restoring a backup generates an error

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4131]
While restoring a backup using
```bash
psql -h [database host] -U [database admin user] [new company name] < [company backup file]
```
the following error is reported
```plain
WARNING:  operator attribute "function" not recognized
ERROR:  operator procedure must be specified
ERROR:  operator does not exist: text public.~*~ text
```
This is caused by pgdump (which is used to generate the backup) miss-ordering the creation and use of the `~*~` function/operator

The impact is not as bad as it appears.
The database is correctly restored with the exception of the employee_search stored procedure which will be unavailable.

Until the postgres team resolve this and each LedgerSMB administrator (user) has upgraded to newer postgres tools this error can be worked around by using the following patch file.

[backup_fix.patch.txt](https://github.com/ledgersmb/LedgerSMB/files/3665197/backup_fix.patch.txt)

This issue is known to affect at least LedgerSMB 1.6.10 running on
```bash
psql --version
psql (PostgreSQL) 11.1 (Debian 11.1-1.pgdg90+1)
```

**Comment by ehuelsmann** [comment]
This is due to a mismatch in client and server versions of PostgreSQL. With matched versions (which I have locally), I'm unable to reproduce.
