### ISSUE TITLE
Developing to work on OpenBSD again.

### ISSUE THREAD

**Issue by CPBen** [ledgersmb/LedgerSMB#4186]
I am ready to work again on this. Right now I see a need to port the following perl modules first:
Test-BDD-Cucumber
Number::Range
MooX::HandlesVia
Data::Perl
Selenium::PageObject
Selenium::Remote::WDKeys
Weasel
Weasel::FindExpanders
Weasel::FindExpanders::HTML
HTML::Selector::XPath
Weasel::FindExpanders::Dojo
PGObject
PGObject::Type::ByteString
PGObject::Type::DateTime
PGObject::Type::BigFloat
PGObject::Simple
X12::Parser
Excel::Writer::XLSX
HTML::Escape
TeX::Encode
Plack::Request::WithEncoding
Plack::Builder::Conditionals
Version::Compare
Template-Plugin-Latex
Template::Latex
LaTeX::Table
MooseX::FollowPBP

Probably a few more or less. I previously did work on three of the above, but they did not make it into the ports tree. I can use that work if I still have copies of it.
OpenBSD now has an extraordinarily easy method to upgrade to the latest version of -current. "sysupgrade" followed by "pkg_add -u -Dsnap" after the reboot.
This will let me work on both amd64 and i386 at the same time.

**Comment by ehuelsmann** [comment]
Hi @CPBen, Thanks for this initiative! Beware though that each of the modules you list has dependencies, which is very likely to make this list *much* longer. Maybe you want to find someone to help you with the effort to port some of these modules for the benefit of their projects (not LedgerSMB necessarily).

**Comment by ehuelsmann** [comment]
Quick question: what is the actionable item you want to register with the project? (Issues really are for actionable items.)

**Comment by CPBen** [comment]
Actually yes. I see that there are installation instructions for 1.6. Are these instructions correct for 1.7 also? This may be relevant to developing a port to OpenBSD.

**Comment by ehuelsmann** [comment]
I'm not sure to which installation instructions you're referring for 1.6, but here's where the 1.7 instructions are: https://ledgersmb.org/content/installing-ledgersmb-17

**Comment by ehuelsmann** [comment]
Based on https://archive.ledgersmb.org/ledger-smb-devel/msg06939.html ; I'm closing this issue. @CPBen , thanks! You know where to contact us with what kind of question/action.
