### ISSUE TITLE
Installation concerns on OpenBSD due to local::lib and cpanm

### ISSUE THREAD

**Issue by CPBen** [ledgersmb/LedgerSMB#4187]
I'm now able to work again on OpenBSD, especially after receiving a donation for buying some hardware I needed for this project.

I see a big problem with creating a second Perl just for LedgerSMB.
OpenBSD almost always back ports some type of change to Perl, which would cause a need to rebuild this new version of Perl again after installation.
OpenBSD never installs packages directly from CPAN. They usually end up in the wrong places, are not tracked for removal and frequently require patches in order to work.
They would also not be tracked for security updates, which could get ugly.

How should I deal with this? Next release version will be PostgreSQL 12 or later.
Thanks.

**Comment by ehuelsmann** [comment]
@CPBen, I think the way to approach this is to create official packages for each of the modules LedgerSMB depends on. BTW, local::lib doesn't build Perl, it allows to install packages which don't overlap or pollute the system Perl. You can choose to make that incremental (i.e. only put additional packages in local::lib) or "stand alone" (i.e. put *all* packages in local::lib).
The cleanest way is probably to create an OpenBSD package for each module LedgerSMB depends on. The Debian package does that.

**Comment by ehuelsmann** [comment]
@CPBen, The issue tracker is probably not the best medium to hold this kind of discussion. I'm thinking the development mailing list is much more suited. Is using the mailing list an option for you?

**Comment by einhverfr** [comment]
Just as a note here because I think Gentoo is similar to many of the BSD ports here, I have gotten most of the packages done for Gentoo.  My work on LedgerSMB packaging stalled for a while but I expect to take it up again soon.

I would recommend looking at https://github.com/ledgersmb/lsmb-overlay as an example of what I did there and maybe it would be a better place to start?

**Comment by CPBen** [comment]
On Tue, Dec 17, 2019 at 06:02:14AM -0800, Chris Travers wrote:
> Just as a note here because I think Gentoo is similar to many of the BSD ports here, I have gotten most of the packages done for Gentoo.  My work on LedgerSMB packaging stalled for a while but I expect to take it up again soon.
> 
> I would recommend looking at https://github.com/ledgersmb/lsmb-overlay as an example of what I did there and maybe it would be a better place to start?
> 

Yes, that looks pretty much like the direction I'm headed.
Right now I'm trying to get all of the PGObject modules ported in right
now (and all their dependencies, too).

That's a method that is approved of (as in staying on one group before
moving onto another).

My work stalled for a long time too. Felt bad about it, but I even got
stuck with only remote servers for awhile, which stops most development.
OpenBSD has a fantastic tool for upgrading to the latest -current now,
which has me on fast forward.

sysupgrade
reboot (then the new kernal and userland are automatically installed)
sysmerge (which runs automatically and usually does all the new configuration changes)
pkg_add -u
reboot (maybe)
done.

I'm running all of the database tests. OpenBSD often has a few kinks
with PostgreSQL updates, so it's worth it (version 12 is causing some
hiccups, so it's not updated yet).

Best Regards,
Chris Bennett
