### ISSUE TITLE
Incorrect approved flag in acc_trans

### ISSUE THREAD

**Issue by tonka128** [ledgersmb/LedgerSMB#4208]
In 1.6.14 the `approved` column of `acc_trans` should contain the approval status of a transaction.
Unfortunately (at least for 0% tax entries) `approved` is always true, even for a saved-not-posted AP invoice

**Comment by nick-prater** [comment]
This is the same in master. The `acc_trans.approved` is true, but the encompassing `ap` record's `approved` field is false. Both tables default to `approved` being true.
