### ISSUE TITLE
Discount Tiers

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4314]
Each customer should have an associated discount tier (default retail)
Each item can then have a tier added (as if it's a customer) in the Price Matrix.
All price calculation points that currently access the price matrix should also test against the associated customer's discount tier

Tier's should be defined in preferences as
- name
- default % discount
  - if this default is changed, it should automatically update any matching percentage set for this tier on any item

Also required
- A report listing all items on any given tier
- A report listing all items on any given tier that has a non default discount (with reset to default button for each item)

**Comment by sbts** [comment]
The above is sort-of possible.

We currently have "type of business" which allows definition of discount amounts per user created type-of-business
These are defined in `System => Type of Business`
They are used by setting the `Business Type` in each customer's ECA record

We also have Price Groups which allow each item to have a discount per price group, and Customers to have a price group selected.

The only missing functionality would appear to be 
- a default discount per tier (pricegroup) that can be updated once and flow through all parts
- the associated report showing non default discount items

**Comment by ehuelsmann** [comment]
How does the price matrix factor into this?

**Comment by sbts** [comment]
A quote from my original description....
> Each item can then have a tier added (as if it's a customer) in the Price Matrix

Does that answer this?

**Comment by ehuelsmann** [comment]
I'm afraid not; amongst other things, I don't understand the "as if it's a customer". Maybe a few examples help my understanding.

Also I don't understand the relationship between the original description and the follow-up comment: which of the items of  the feature request get addressed by which of the items named in the follow-up?
