### ISSUE TITLE
More flexible discount entry

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4316]
The discount entry field for Orders and Invoices should be more flexible and allow additional types of entry.
ie: 
- percentage
- relative
- absolute

One way of doing so with minimal changes would be to implement the same scheme described in #4315

**Comment by ehuelsmann** [comment]
Why do you need absolute adjustments? There is the option of doing percentage adjustments or reentering the rate. The latter comes in handy when you want to do an absolute adjustment. Or you can enter a separate line with the discount /adjustment to list the price adjustment. That is what I use myself.
