### ISSUE TITLE
systemd Service file missing documentation key

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4347]
Lintian claims the following
> The systemd service file does not contain a Documentation key.
Documentation for systemd service files can be automatically viewed using systemctl help servicename if this field is present.
Refer to the systemd.unit(5) manual page for details.

Complying with this would seem to make sense, even if it's a one liner

**Comment by ehuelsmann** [comment]
Actually, there *is* a one-liner already there: `Description`.

`Documentation` is documented (in the `man systemd.unit`) as:

>        Documentation=
>           A space-separated list of URIs referencing documentation for this unit or its configuration. Accepted are only URIs of the
>           types "http://", "https://", "file:", "info:", "man:". For more information about the syntax of these URIs, see uri(7). The
>           URIs should be listed in order of relevance, starting with the most relevant. It is a good idea to first reference
>           documentation that explains what the unit's purpose is, followed by how it is configured, followed by any other related
>           documentation. This option may be specified more than once, in which case the specified list of URIs is merged. If the empty
>           string is assigned to this option, the list is reset and all prior assignments will have no effect.

**Comment by ehuelsmann** [comment]
I'm not planning on adding that documentation any time soon, I'm afraid.
