### ISSUE TITLE
systemd Service could benefit from some security features being enabled

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4348]
Lintian flags the fact that we are not using any systemd security features in our service file.

Looking at http://0pointer.de/public/systemd-man/systemd.exec.html there are a number of such features we may benefit from.
For example
- ReadWriteDirectories
- ReadOnlyDirectories
- InaccessibleDirectories
- PrivateTmp
- ProtectSystem
- ProtectHome
- NoNewPrivileges

The above are just a few of the more likely ones we could use, there are many others

It's worth noting that
- RuntimeDirectory
- RuntimeDirectoryMode

May both be of interest, but consideration should be given to how equivalent behaviour can be obtained if running without systemd (ie: a fallback mechanism)

**Comment by ehuelsmann** [comment]
I've contemplated this issue for a bit. I agree that these settings would absolutely make sense in a production systemd unit file. However, I also think that these settings only make sense for specific deployments, like those done by the Debian package.

I don't think we can address this in our generic systemd.unit file.
