### ISSUE TITLE
dojo dep's incorrectly declared in package.json

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4349]
Looking at UI/js-src/lsmb/package.json we declare 3 dependencies 
-    "dojo": "~1.14",
-    "dijit": "~1.14",
-    "dojox": "~1.14"

There are two problems here
- we shouldn't be using dojox (as far as @ehuelsmann and I are aware)
- The actual versions differ across our branches, but are not in sync with the versions we depend on with our git submodules config.

We need to add a test to ensure these stay in sync, and perhaps a helper script for when we need to change them to simplify life.

Any corrections here should be backported to all supported branches as soon as possible

**Comment by ehuelsmann** [comment]
Upgraded on 1.6, 1.7 and master branches.
