### ISSUE TITLE
PostgreSQL ExclusiveLock after hours of inactivity

### ISSUE THREAD

**Issue by Bobberty** [ledgersmb/LedgerSMB#4356]
When walking away from LedgerSMB with the browser open for a long term, all available Starman processes attempt a PostgreSQL ExclusiveLock on a Select.
This event happens about 3 hours after the last activity through the browser.

The test system is a stock Debian 10.  Running Lighttpd (Proxy to Starman).
Attached is a pg_stat_activity during one of these situations.

The only solution discovered is to reset starman.

[newoutput.txt](https://github.com/ledgersmb/LedgerSMB/files/4072633/newoutput.txt)

**Comment by ehuelsmann** [comment]
Diagnosing the problem, the exclusive lock hasn't been lingering for hours, but is caused by the activity that happens after the session expires.
