### ISSUE TITLE
printPayment.html not found error in Cash-->Receipt

### ISSUE THREAD

**Issue by Bobberty** [ledgersmb/LedgerSMB#4358]
When attempting to receive a payment from a customer and print a receipt, "Template error: file error - printPayment.html: not found at lib/LedgerSMB/Template.pm line 562." appears and stops the action.

![bad-print-receipt](https://user-images.githubusercontent.com/255876/72549065-00d10100-385e-11ea-9dce-5f6b22db6f1d.png)

printPayment.html is found in the /Template/(demo/xedemo/demo_with_images).
Further, it has been imported into the Template table in the database.

**Comment by ehuelsmann** [comment]
This is related to (but not quite a duplicate of) #3232 .
