### ISSUE TITLE
Suggestion: Adding a way to add/create a database once you have logged in as admin on the setup.pl

### ISSUE THREAD

**Issue by stevearbour** [ledgersmb/LedgerSMB#4408]
Suggestion: Adding a way to add/create a database once you have logged in as admin on the setup.pl because if you do not provide a database name and create at the login section of the setup.pl, a list of database is presented to you as a DBA, but you do not have a label + textbox + button to create a database from that exact location. 

A simple GET redirection would probably do, since the user already logged ?

Thank you !

**Comment by ehuelsmann** [comment]
Merged into #3746
