### ISSUE TITLE
Ordering of the Country Code list during Database creation

### ISSUE THREAD

**Issue by stevearbour** [ledgersmb/LedgerSMB#4437]
When creating a Database from setup.pl, the country code selection is not ordered alphabetically ascending, making it hard to find the country we are looking for, it seem this is a new thing in 1.7

![image](https://user-images.githubusercontent.com/4413101/74659212-eb533d80-5161-11ea-90b9-4300b7b138b3.png)

Thanks !!

**Comment by ehuelsmann** [comment]
Fixed for 1.8 in 7f3b85f2ddac5a30cde74aec696f8d698dbafe15
