### ISSUE TITLE
1.7.9 - Contacts -> Add Contact -> Vendor -> Credit Accounts -> Language Dropdown default

### ISSUE THREAD

**Issue by stevearbour** [ledgersmb/LedgerSMB#4439]
1.7.9 - Contacts -> Add Contact -> Vendor -> Credit Accounts -> Language Dropdown default

I think that the language of the current user or the company should be a default on this screen. 
IE: I choosen English, but get Arabic (Egypt) by default displayed.

![image](https://user-images.githubusercontent.com/4413101/74663146-3fadeb80-5169-11ea-8cfa-9f622f18ec5e.png)

**Comment by ehuelsmann** [comment]
the change available for 1.6 and 1.7 for this field is to make the field default to blank -- ie "no value".
