### ISSUE TITLE
1.7.9 - Quotations -> RFQ -> Vendor selection

### ISSUE THREAD

**Issue by stevearbour** [ledgersmb/LedgerSMB#4440]
Could there be an auto-complete or at least a populated drop down ?

When I do a RFQ from a Vendor screen, could the name be auto-filled to prevent typo error ?

**Comment by ehuelsmann** [comment]
The drop down functionality exists and is enabled by entering a number in the obscurely named "max per drop-down" setting on the System > Defaults screen.

As for the auto-complete functionality, this duplicates #2306 .

Thanks for taking the time to file!
