### ISSUE TITLE
1.7.9 Regression: Cannot delete individual voucher from batch

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4448]
Not sure when this started, but I know this used to work, at least in 1.5 era.

Transaction Approval -> Batches -> Receipt
Select a receipt batch
Check the box for a voucher, and click "Delete Voucher"

What happens:
Nothing. Screen refreshes, voucher is still there.

Expected:
Voucher gets deleted.

**Comment by ehuelsmann** [comment]
Probably a regression then.

**Comment by ehuelsmann** [comment]
Additionally, the "Total" label ("Source" column) isn't in the totals row, but in the last posting line instead.
