### ISSUE TITLE
1.7.9 Deleting a receipt batch takes minutes

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4449]
Not exactly sure if this is a one-off, but after being unable to delete an individual voucher, I attempted to delete the entire batch. I tried both:

Transaction Approval -> Batches -> Receipt
Click on a batch
On the batch screen, click "Delete batch"

Screen went grey. After a couple minutes of no result, I clicked away, and tried:

Transaction Approval -> Batches -> Receipt
Select the checkbox for the batch
Click "Delete batches" button

Screen again went grey, and again after a couple minutes I clicked away, opened the browser console to see if there was an error returned from the server, and tried again.

This time I saw the response was still waiting, and then it finally returned and succeeded.

**Comment by ehuelsmann** [comment]
Looking at the code of the `batch_delete()` sql function, I think this could be caused by a missing index. Could you try adding - in a test company, of course:

```sql
CREATE INDEX acc_trans_trans_id_idx ON acc_trans(trans_id);
```
?

**Comment by freelock** [comment]
Deleting goes much quicker with this index!
