### ISSUE TITLE
Regression: Reconciliation does not balance, off by 2x the difference between start and end balance

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4480]
On 1.7.9:

When reconciling an account, and the account balances, the "variance" does not reach 0, and thus the reconciliation cannot be submitted.

It is off by 2x the difference between the starting and ending balance.

This worked correctly in earlier versions of 1.7 -- I'm not sure when it stopped working correctly.

**Comment by ehuelsmann** [comment]
Confirmed fixed in 1.7.10.
