### ISSUE TITLE
1.7 Math::Bigfloat error in ar invoice handling

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#4512]
I get this box when e.g. posting a new invoice:

![image](https://user-images.githubusercontent.com/54674/76757074-3bd0b180-6787-11ea-9be5-94fd5dc35cfb.png)

But also just retrieving an already posted invoice (this is captured like that). Putting an eval round line 246 fixes the immediate issue, but I don't know the cause and consequences.
I experienced this when moving from 1.5 to 1.7.4. It's still there in 1.7.10.

**Comment by ehuelsmann** [comment]
Thanks for taking the time to report! Do you think you can capture the offending data? Maybe by forcing a stack trace to be generated? (Using Carp::Always, maybe?)

**Comment by ehuelsmann** [comment]
Please note that I need specific data as this doesn't occur with any database that I maintain myself nor in the test cases we run on each PR.
