### ISSUE TITLE
Debian installation

### ISSUE THREAD

**Issue by Timh1970** [ledgersmb/LedgerSMB#4525]
When following the instruction to install ledgersmb on debian buster after running setup.pl I am getting the following when adding a user (note the database creates ok, it just wont let me add a user so I cannot go any further)

I have tried rebuilding and reinstalling the database and creating a new database several time but to no avail.

FYI :
LedgerSMB 1.6.9 (from debian repository)
PostgreSQL 11.7 (Debian 11.7-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
(with 61 registered patches, see perl -V for more detail)

_______________________________________________________________________________

Error!

Attribute (control_code) is required at constructor LedgerSMB::Entity::Person::Employee::new (defined at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Entity/Person/Employee.pm line 189) line 49
LedgerSMB::Entity::Person::Employee::new('LedgerSMB::Entity::Person::Employee', 'login', 'lsmb_dbadmin', 'action', 'save_user', 'perms', 1, 'control_code', undef, 'country_id', 230, '_logout', undef, 'last_name', 'user', '_locale', 'LedgerSMB::Locale::en=HASH(0x5607a190cb00)', '_auth', 'LedgerSMB::Auth::DB=HASH(0x5607a18865f0)', 'VERSION', 1.6.9, 'dbh', 'DBI::db=HASH(0x5607a19b4460)', 'version', 1.6.9, 'have_latex', 1, '_create_session', undef, 'script', 'setup.pl', 'pls_import', 0, 'entity_class', 3, '_uploads', 'Hash::MultiValue=HASH(0x5607a18971e8)', 'query_string', '', '_user', 'HASH(0x5607a19286a8)', 'company', undef, 'name', 'user, test', 'password', 'secret', 'dob', 'LedgerSMB::PGDate=HASH(0x5607a19a9148)', 'dbversion', 1.6.9, 'first_name', 'test', 'database', 'lsmb_tst', '_session_id', undef, 'username', 'test', 'salutation_id', 3, '_cookies', 'HASH(0x5607a191d300)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Scripts/setup.pm line 1175
LedgerSMB::Scripts::setup::save_user('LedgerSMB=HASH(0x5607a191ccd0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 114
LedgerSMB::PSGI::__ANON__ at /usr/share/ledgersmb/bin/../lib/LedgerSMB/App_State.pm line 202
LedgerSMB::App_State::run_with_state('CODE(0x5607a5cde358)', 'DBH', undef, 'DBName', undef, 'Locale', 'LedgerSMB::Locale::en=HASH(0x5607a190cb00)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 126
LedgerSMB::PSGI::try {...} at /usr/share/perl5/Try/Tiny.pm line 102
eval {...} at /usr/share/perl5/Try/Tiny.pm line 93
Try::Tiny::try('CODE(0x5607a1917b98)', 'Try::Tiny::Catch=REF(0x5607a1868760)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 142
LedgerSMB::PSGI::psgi_app('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Middleware/ClearDownloadCookie.pm line 48
LedgerSMB::Middleware::ClearDownloadCookie::call('LedgerSMB::Middleware::ClearDownloadCookie=HASH(0x5607a5347ad8)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Middleware/DisableBackButton.pm line 47
LedgerSMB::Middleware::DisableBackButton::call('LedgerSMB::Middleware::DisableBackButton=HASH(0x5607a5347dc0)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Middleware/AuthenticateSession.pm line 210
LedgerSMB::Middleware::AuthenticateSession::call('LedgerSMB::Middleware::AuthenticateSession=HASH(0x5607a5347e80)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Middleware/Log4perl.pm line 72
LedgerSMB::Middleware::Log4perl::call('LedgerSMB::Middleware::Log4perl=HASH(0x5607a5347f40)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Middleware/DynamicLoadWorkflow.pm line 98
LedgerSMB::Middleware::DynamicLoadWorkflow::call('LedgerSMB::Middleware::DynamicLoadWorkflow=HASH(0x5607a5348000)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Middleware/AccessLog.pm line 27
Plack::Middleware::AccessLog::call('Plack::Middleware::AccessLog=HASH(0x5607a5348120)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/Middleware/RequestID.pm line 52
LedgerSMB::Middleware::RequestID::call('LedgerSMB::Middleware::RequestID=HASH(0x5607a5351430)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/App/URLMap.pm line 71
Plack::App::URLMap::call('Plack::App::URLMap=HASH(0x5607a5135560)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/ledgersmb/bin/../lib/LedgerSMB/PSGI.pm line 231
LedgerSMB::PSGI::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Middleware/Conditional.pm line 16
Plack::Middleware::Conditional::call('Plack::Middleware::Conditional=HASH(0x5607a5373a08)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Middleware/ReverseProxy.pm line 68
Plack::Middleware::ReverseProxy::call('Plack::Middleware::ReverseProxy=HASH(0x5607a53a2890)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Middleware/Conditional.pm line 16
Plack::Middleware::Conditional::call('Plack::Middleware::Conditional=HASH(0x5607a53a2818)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Plack/Util.pm line 145
eval {...} at /usr/share/perl5/Plack/Util.pm line 145
Plack::Util::run_app('CODE(0x5607a53a2608)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Starman/Server.pm line 195
Starman::Server::dispatch_request('Starman::Server=HASH(0x56079c2c5068)', 'HASH(0x5607a4e5bef0)') called at /usr/share/perl5/Starman/Server.pm line 298
Starman::Server::process_request('Starman::Server=HASH(0x56079c2c5068)', 'Net::Server::Proto::TCP=GLOB(0x5607a50d0250)') called at /usr/share/perl5/Net/Server.pm line 72
Net::Server::run_client_connection('Starman::Server=HASH(0x56079c2c5068)') called at /usr/share/perl5/Net/Server/PreFork.pm line 225
eval {...} at /usr/share/perl5/Net/Server/PreFork.pm line 225
Net::Server::PreFork::run_child('Starman::Server=HASH(0x56079c2c5068)') called at /usr/share/perl5/Net/Server/PreFork.pm line 183
Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x56079c2c5068)', 5) called at /usr/share/perl5/Net/Server/PreFork.pm line 107
Net::Server::PreFork::loop('Starman::Server=HASH(0x56079c2c5068)') called at /usr/share/perl5/Net/Server.pm line 58
Net::Server::run('Starman::Server=HASH(0x56079c2c5068)', 'port', 'ARRAY(0x56079c943ed8)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 125, 'group', '134 134', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1) called at /usr/share/perl5/Starman/Server.pm line 106
Starman::Server::run('Starman::Server=HASH(0x56079c2c5068)', 'CODE(0x56079c2c4fc0)', 'HASH(0x56079c2c51d0)') called at /usr/share/perl5/Plack/Handler/Starman.pm line 25
Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x56079c2c4fa8)', 'CODE(0x56079c2c4fc0)') called at /usr/share/perl5/Plack/Loader/Delayed.pm line 20
Plack::Loader::Delayed::run('Plack::Loader::Delayed=HASH(0x56079c1bcf58)', 'Plack::Handler::Starman=HASH(0x56079c2c4fa8)') called at /usr/share/perl5/Plack/Runner.pm line 277
Plack::Runner::run('Plack::Runner=HASH(0x56079c07e4a0)') called at /usr/bin/starman line 38

dbversion: , company: 1.6.9

**Comment by ehuelsmann** [comment]
Hi,

Thanks for taking the time to report this issue. It's a tremendously ugly error; if you want to be able to proceed, please fill any number into 'employee number' (other than 0).

Leaving this open to be resolved in a patch release.

Erik.
