### ISSUE TITLE
1.7: Price groups not working correctly

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4542]
On version 1.7.11, Pricegroups are no longer overriding the product price.

1. Create price group
2. Tag ECA with pricegroup
3. Add pricegroup with price to a part (leave customer info blank)
4. Create sales order for customer and add part

^^^ Here I expect to see the price for the pricegroup, but instead I'm getting the main price of the part.

If it makes any difference, in the actual scenario, the pricegroup price is higher than the base price on the product.

**Comment by ehuelsmann** [comment]
@freelock it works for me. I went through these steps on a new company:

* Add Contact
* Name: XYZ ; Country: Aland Islands
* Save
* [Credit account page] Description: XYZ
* Save New
* Create pricegroup G1 (through Goods & Services)
* Add part; Sell price: 30, List price: 30
* Save
* Pricematrix row: Pricegroup: G1, price: 25, minimum quantity: 1
* Save
* Contacts > Search
* Open Customer XYZ
* Credit Account page: Select pricegroup G1
* Save Changes
* Sales invoice: Customer: XYZ
* Update
* Line 1: P1
* Update
--> Price shown: 25 (= pricegroup price)

(Discard entered data, continue in next step:)
* Sales order: Customer: XYZ
* Update
* Line 1: P1
* Update
--> Price shown: 25 (= pricegroup price)

(Discard entered data, continue in next step:)
* Goods & Services > Search
* Open P1 screen
* Change Pricegroup price from 25 to 35
* Save

* Sales invoice: Customer: XYZ
* Update
* Line 1: P1
* Update
--> Price shown: 35 (= pricegroup price)

(Discard entered data, continue in next step:)
* Sales order: Customer: XYZ
* Update
* Line 1: P1
* Update
--> Price shown: 35 (= pricegroup price)

Could you provide me with a set where things aren't working?

Note that if I don't set the minimum amount value, I'm getting an error.
