### ISSUE TITLE
1.7 regression: Payments get null transdates when received/paid using voucher batches

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4587]
In 1.7, when using payment or receipt vouchers, the transdate does not get set, even after the batch is posted.

This results in payment transactions not showing on the reconciliation screens, or in cash reports. When you view a transaction (e.g. an invoice) you do see the payment line entered, but the date column is empty.

Steps to reproduce:
1. Create some invoices
2. Go to Cash -> Vouchers -> Receipts, and create a payment batch with a payment date.
3. In the batch screen, receive payments and post.

At this point, the payment lines appear on the invoice but without a transdate. After going to Transaction Approval -> Batches and approving the batch, these transactions do not appear when reconciling the cash account you received into, and they do not show up on the cash receipts reports.

The same issue happens with Cash -> Vouchers -> Payments (against AP transactions).

This started in 1.7.

This query sets the missing data (but does not correct the underlying cause):

```
UPDATE acc_trans SET transdate = default_date
  FROM batch
  WHERE batch.id = voucher.batch_id
  AND voucher.id = acc_trans.voucher_id
  AND acc_trans.transdate IS NULL
```

**Comment by ehuelsmann** [comment]
Fixed in ecbfc4d
