### ISSUE TITLE
AR Search for Employee shows all Employees

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4604]
AR => Search
- Select Employee to report on
- enable "show Sales Person" checkbox

Result shows all sales for all employees and sales persons.

Expected result is to only show sales where the employee that entered the sales matches the selected employee

This can probably be best solved by adding live filters UI side for Sales Person and Employee when those fields are displayed

**Comment by sbts** [comment]
Ideally, regardless of how this is fixed, it should be possible to search on both Sales Person and Employee

**Comment by ehuelsmann** [comment]
@sbts if this is a regression, could you say which version is the last known-working version?
