### ISSUE TITLE
AR Document Sales Person has no specific default

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4621]
For any AR Document such as
- Sales Invoice
- Sales Quote

The Sales Person drop-down default to the first alphabetical person (or is it the lowest numbered ID in the list).

This breaks all standard workflows as it should default to the logged in Person if they are a Sales Person
If the Logged In Person is NOT a Sales Person, the default should be `blank` with mandatory selection required on update/save

**Comment by ehuelsmann** [comment]
This title suggests there is a default. That's not the case: there simply is a drop down with values. No defaults.

**Comment by sbts** [comment]
That is true, I'll change the title to reflect that it needs a default

**Comment by ehuelsmann** [comment]
This issue is fixed in the soonish to be released 1.8 version.
