### ISSUE TITLE
feature: Select All checkbox when approve Transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#4637]
When approving transactions, need to select one by one, this take much time if we have hundreds unapproved transactions. So it will be better, we can select all at once

![image](https://user-images.githubusercontent.com/31498748/82721023-53746b00-9cdf-11ea-9ada-4621b22140bc.png)

**Comment by ehuelsmann** [comment]
Apparently, we have wanted this for quite some time already. It's a duplicate of #1601
