### ISSUE TITLE
Add a link in the UI to the latest changelog 

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4649]
Somewhere on the "info" screen shown on successful login we should add a prominent link to the changelog.

This can be done reasonably easily by pointing at one of
- https://github.com/ledgersmb/LedgerSMB/blob/master/Changelog (to include all changelog entries, including for future stable release)
- https://github.com/ledgersmb/LedgerSMB/blob/1.7/Changelog  (for the 1.7 series)

Use of information from
- https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#section-links 

Should allow us to add section links (a TOC) to the top of the Changelog file making navigation to individual versions easier for the user. 

The viewing experience for the user can be further enhanced by renaming
`Changelog` to `Changelog.md` so that github renders the content as markdown automatically

Adding this may assist users to decide if they want to immediately upgrade, or defer until the next release.

This should probably be done in the 1.7 series so it's available to users considering upgrading to 1.8 when that's released later this year

**Comment by ehuelsmann** [comment]
But... Our changelog really isn't md.

**Comment by sbts** [comment]
True, it's not currently real markdown, but it is close.
To the point that making it markdown would have little impact on the way it appears in a raw form, but would significantly improve readability when viewed via a markdown engine

**Comment by ehuelsmann** [comment]
It's rather unclear how to implement this request: Where do we point these links on master, so that the only step required on a release is to replace the links?!

**Comment by ehuelsmann** [comment]
My point on the previous post is that we already have a tremendous list of documents which need to be (manually) adjusted when a new release branch is being created. I'm very much against creating more manual steps in the process to create a new release branch.
