### ISSUE TITLE
Credit Invoice with Inventory breaks COGs unless created as a VOID

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4669]
Credit Invoice with Inventory MUST only be created by voiding an invoice with the Void button.
Failing to do this will (ie: manually creating a Credit Invoice) will cause a $0 cogs amount to be recorded against any inventory items instead of the COGs amount used in the original invoice.

Use of a credit invoice to purchase goods from a customer can't work for this reason.
Instead the customer should be set up as a Vendor, and a Vendor invoice used.

For the record, a Sales Invoice with negative QTY for an invoice Item will also cause this issue.

I propose we prevent saving and posting (with an informative error) any Sales or Credit Invoice that contains inventory items that is not linked to a suitable Sales Invoice for the negative items.
Allowing this when there is a linked sales invoice would need to be handled with care to ensure consistency.
For now it's probably best to ONLY allow it if the Credit Invoice has been created as a VOID invoice using the VOID button

**Comment by ehuelsmann** [comment]
As discussed, testing worked for me on 1.8. please test that it works for you too, or which exact scenario doesn't.

**Comment by tonka128** [comment]
Tested and confirmed as now working correctly. the "negative" invoice will reverse the COGS for the last set of transactions to match.
Have tested this in a sandbox with a similar set of invoices to the set that flagged the issue originally and its now all performing as expected.

**Comment by ehuelsmann** [comment]
Thanks for confirming! I'll close the issue as fixed in 1.7.15 now then.
