### ISSUE TITLE
Cash->Vouchers->Reverse Payment trips "strict refs" check

### ISSUE THREAD

**Issue by tonka128** [ledgersmb/LedgerSMB#4721]
when going to reverse an overpayment, the software trips over strict ref checking

error:
Can't use string ("LedgerSMB::DBObject::Payment") as a HASH ref while "strict refs" in use at /usr/local/share/perl/5.24.1/PGObject/Simple.pm line 178.

v1.7.15

**Comment by ehuelsmann** [comment]
I ran this locally on my development installation; running these steps -- but can't reproduce with 1.7, 1.8 or 1.9/master:

1. Create a new company based on the US CoA
2. Create a user `test` with `Full permissions`
3. Log in
4. Create a new vendor (`ABC` / eca: `ABC`)
5. Create a new AP transaction against `ABC` & Post
6. Pay the transaction through the payment interface
7. Reverse the transaction through the Cash > Vouchers > Reverse Payment  menu-item

None of the above versions produce this error. 

@sbts, could you narrow this problem down a bit more?
