### ISSUE TITLE
Improve CONTRIBUTING / getting started experience & documentation

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#4751]
As per @gwhitney's experience, we want to help people (instead of discouraging them!), by getting better documentation in place to help them get started & contributing. These steps are minimally necessary to address the "getting started" experience:

* [ ] Create a "Getting started (without Docker)" document as per https://github.com/ledgersmb/LedgerSMB/issues/4655#issuecomment-647317453
* [x] Add now-required `--preload-app` to the various startup scripts as per https://github.com/ledgersmb/LedgerSMB/issues/4655#issuecomment-647899756
* [ ] Add documentation on what it means to run "with configuration" or "without configuration" and why one would be preferrable over the other
* [ ] Add documentation of the Docker-based code/test/debug/commit cycle

@gwhitney, please don't hesitate to add items to this issue when you come up with ideas that would have lowered your barrier of entry.

**Comment by gwhitney** [comment]
The only related suggestion I have to this at the moment is that in the docker for development document, if there were a brief overview of the code - test - debug - commit cycle in the Docker approach to development, it might have eased my adoption of that path (now that docker deployment itself has been considerably smoothed). Not that I'm at all unsatisfied with the "manual" approach I've now gotten to, just it might be helpful to others getting started with using Docker to develop this project.

**Comment by neilt** [comment]
Add new section in the README at https://github.com/ledgersmb/ledgersmb-dev-docker/pull/50 to address this issue.
