### ISSUE TITLE
1.7.17: something weird with Voucher Payment numbering

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#4780]
![Screenshot from 2020-07-03 22-55-06](https://user-images.githubusercontent.com/2326559/86497051-5489c500-bd80-11ea-9d93-250ed7e4ab95.png)

**Comment by aungzwin10** [comment]
Initial Numbering is correct. See below.

![image](https://user-images.githubusercontent.com/31498748/91156884-a7318e80-e6ea-11ea-9f3b-996efe74a2b8.png)

But after selecting vendors and update numbering wrong.

![image](https://user-images.githubusercontent.com/31498748/91157232-10190680-e6eb-11ea-8297-c30df7201a9d.png)

**Comment by ehuelsmann** [comment]
@aungzwin10 do you happen to be able to determine which version is the first one to show this weird behaviour?

**Comment by aungzwin10** [comment]
I can't tell exactly, I just notice a few days ago.

**Comment by ehuelsmann** [comment]
The problem is this line: https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/Scripts/payment.pm#L647 which ignores the text in the source number.

The original numbers originate from https://github.com/ledgersmb/LedgerSMB/blob/master/old/lib/LedgerSMB/DBObject/Payment.pm#L506-L519 which violates at least 2 layers of separation of concerns by inspecting the value of 'action' from the "caller". It also generates a source number for each account instead of only for the checked ones (but not on update, because that skips generating the numbers).

**Comment by ehuelsmann** [comment]
Backported to 1.7.19.
