### ISSUE TITLE
1.8 Cannot sort AR -> Search results

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4872]
I opened a reconciliation, had a note about an unapproved transaction before the closing date, followed the link to find an unapproved invoice..

So I opened another window, did an AR -> Search, entered the customer name, set the search to "All" "All" for include in report (open/closed, approved/unapproved). Got a list of invoices, but not in any easily understandable order -- all the dates were scrambled. (This should be ordered by date by default, wouldn't you think?)

But the big issue: I clicked on the date header and instead of getting a sorted list of results, I got a completely blank list. Sorting appears to break the search result.

**Comment by ehuelsmann** [comment]
As discussed on the Matrix channel, neither @ylavoie nor @ehuelsmann could reproduce the issue. We need more guidance on how to reproduce.

**Comment by freelock** [comment]
Ok. This is really weird. It's now working when I put in a search term that pulls up multiple customers, but not when it's specific enough to load only a single customer.

I searched for several different customers, and it seems to fail for each one that is the only one in the result set. It usually (but not always) succeeds when there are multiple customers.

Video recording available here for the next 3 days: https://cloud.freelock.com/s/2xCFbEpXq76TitZ

**Comment by freelock** [comment]
This is also happening in 1.7.20. Not sure when it last worked.
