### ISSUE TITLE
1.8 Cannot print Check Vouchers

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4873]
1. Go to Cash -> Vouchers -> Payments
2. Select vouchers to pay, and click Update
3. Click "Print". Nothing happens.

In browser console log, there's an Ajax request that returns a 500 error with this message:

```
Error!

Can't call method "to_output" on an undefined value at lib/LedgerSMB/Scripts/payment.pm line 462.

dbversion: 1.8.0-dev, company: freelockco
```

... this is using LSMB using a stock Dockerfile, modified from master to set the version to 1.8.

**Comment by ehuelsmann** [comment]
@freelock could you provide me with a series of exact steps? I executed these steps and didn't see the problem pop up:

1. create a new contact
2. create a new vendor
3. create a new AP transaction against the vendor (single line, 1 amount)
4. save & post the transaction
5. go to Cash > Vouchers > Payments
6. Select a batch date (2020-08-01) & Continue
7. Enter a Start (cheque number) (my data: 1) & Continue
8. Check the row for the new vendor
9. Click Update
10. Click Print

(I'm running the above on the ledgersmb-dev-docker image.)

I *am* running into problems, but not any problems that indicate failure to prepare or evaluate the template. I'll fix the problem that I do see, but I'll need more specific instructions to reproduce your specific issue.
