### ISSUE TITLE
Exchange rate with comma as thousands separator calculates incorrectly

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#4879]
Please see below image
![image](https://user-images.githubusercontent.com/31498748/91036265-092bbe80-e62d-11ea-9bb7-3a5f8817f9a1.png)

**Comment by ehuelsmann** [comment]
just to clarify: is the "comma" your thousand separator? (1 USD is 1300 MMK?)

Also, what happens when you enter "1300" instead of "1,300" in the box?

**Comment by aungzwin10** [comment]
Yes 1 USD is 1300 MMK. I use Number format "1,000.00" in the user preference. I enter "1300" but when update, it automatically change to "1,300". It work with Number format "1000.00".

**Comment by ehuelsmann** [comment]
Ok. So the exchangerate *does* multiply, but the format is the problem. Let me change the problem description.
