### ISSUE TITLE
No header tag in the AR/AP transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#4890]
From Cash > Payment or Cash > Receipt, when I clicked on the Invoice Number link, it open in new browser tab and no CSS was apply to that page. No header tag in the code. Doesn't show any error on the browser console.

![image](https://user-images.githubusercontent.com/31498748/91515974-64510000-e910-11ea-9dec-7765b4a25802.png)

![image](https://user-images.githubusercontent.com/31498748/91516132-b6922100-e910-11ea-92d5-2f7dc891edc4.png)

![image](https://user-images.githubusercontent.com/31498748/91516209-e2150b80-e910-11ea-99aa-22fe9e9b2387.png)

![image](https://user-images.githubusercontent.com/31498748/91516228-ec370a00-e910-11ea-8544-c9549ec6280a.png)

**Comment by ehuelsmann** [comment]
The fact that the HTML and HEAD tags are missing is by design. The bug here is that the base link is missing.
