### ISSUE TITLE
1.7 & 1.8 minor issue: After batch approval, user is returned to list of all batches

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#4971]
Go to Transaction Approval -> Batches -> Unapproved (Search).

You get a list of unapproved batches (in my case, both receipt and payment batches).

Click on a batch, and view its details.

From the detail screen, approve or delete the batch.

The action succeeds, and then it takes a while to generate a full list of batches, which now includes all approved batches instead of just unapproved.

Minor usability issue, not a high priority.

**Comment by ehuelsmann** [comment]
I've seen this too, but can't reproduce it with a single unapproved batch. Apparently, I need more data to reproduce.

**Comment by freelock** [comment]
This is also happening in 1.7.
