### ISSUE TITLE
Add suggest password and show password to new user screen

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#5031]
On the "New User" and "Update Password" screens etc we should have provision to
- suggest a new password
  (as long as a suitable library, or system tool such as `pwgen` is available)
- show the newly entered password on request
  (but only until it is saved. ie: you don't want to expose already set passwords.)

There are many examples of websites and applications that do both of the above.
If there is a decent JS lib we can use for password suggestion then that's a good starting point and likely trivial to implement.
However, it may not offer the flexibility a server side library/binary could in terms of security, ability to filter out unwanted strings, etc.
Downside to server side generation is the required round trip to the server, and the need to consider some form of security (eg: ssl) end to end on that request. (LSMB it's self doesn't use ssl, instead it relies on a reverse proxy such as NGINX to provide SSL support. So an analysis of the threat level for the "proxy to lsmb" segment of the connection will be required.)

**Comment by ehuelsmann** [comment]
Firefox will suggest a new password itself. Can we do better than that?!

**Comment by ylavoie** [comment]
So will Chrome.
