### ISSUE TITLE
Entity Type should not be able to be changed after creation

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#5032]
Currently it is possible to change the type of an entity after it has been created.
This should not normally be possible as it can introduce issues behind the scenes.

For example, changing a "robot"  entity to an "employee" causes issues with control codes, and may cause other problems with the basic setup of the entity.

**Comment by ehuelsmann** [comment]
Actually, that drop down should be irrelevant: the "accounts" are the rules an entity assumed. That check box is only informational. In that sense, removal has been planned as it mostly serves to confuse
