### ISSUE TITLE
1.8: Cannot search GL report

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5151]
![image](https://user-images.githubusercontent.com/31498748/94637228-09d70500-02fd-11eb-8352-675528678e3d.png)

**Comment by ehuelsmann** [comment]
Which field did you fill in the search criteria screen?

**Comment by aungzwin10** [comment]
I didn't fill anything. General Journal > Search, then click directly on 'Continue' without filtering anything. This is work in previous version.

**Comment by aungzwin10** [comment]
Issue is okay now. I don't know why the error come out. I removed my copy of git repo and clone the new one, after clone, do cpanm, make step and then rebuild the database from setup. I may have conflict between my fork and lsmb repo while I merge the lsmb repo to my fork.
