### ISSUE TITLE
Cannot post recurring transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5152]
![image](https://user-images.githubusercontent.com/31498748/94637425-8833a700-02fd-11eb-9c17-585c2d2ec7c7.png)

![image](https://user-images.githubusercontent.com/31498748/94637432-8e298800-02fd-11eb-9c00-9e47bd136e2d.png)

![image](https://user-images.githubusercontent.com/31498748/94637439-92ee3c00-02fd-11eb-94d9-e200fa25f3b2.png)

**Comment by ehuelsmann** [comment]
Regressed from 1.7
