### ISSUE TITLE
1.8 regression: Sales Order -> Sales Invoice uses order date

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#5175]
Just got a report from my AR person that when shipping a new sales invoice from a sales order, it picks up the date on the sales order and inserts it into the invoice -- and he's having to go in and change that to the current date. It should empty out the invoice date field and set it to the current date when saved.

**Comment by ehuelsmann** [comment]
Yup. Have that reproduced. Looking into it deeper.
