### ISSUE TITLE
Unbalance disposal transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5180]
According to our chat, we have unbalance transaction when we do disposal for the asset.
There should be another account transaction with the amount 350,000, which is the actual sale amount of asset.

![image](https://user-images.githubusercontent.com/31498748/96574418-6ffbea00-12f5-11eb-98f4-38011d052b2f.png)

**Comment by aungzwin10** [comment]
System let the user to dispose already disposed item. I think when we dispose the item, it should not appear in the Asset Disposal Report again.

**Comment by ehuelsmann** [comment]
The problem here seems to be `asset_report__disposal_gl` (full disposal), which doesn't account for the sales amount to be inserted into an `acc_trans` line of itself.

**Comment by ehuelsmann** [comment]
The work-around here is to add the missing cash line to the transaction before posting it; after loading it through `Transaction approval > Drafts`.

**Comment by ehuelsmann** [comment]
> System let the user to dispose already disposed item. I think when we dispose the item, it should not appear in the Asset Disposal Report again.

Yes. But that's a different issue than this one. It deserves its own issue. Also, what happens after an asset has been completely written off? I guess it still needs disposal? If that's the case, then running an Asset Disposal/ Abandonment report would be the way forward to remove written-off assets from the asset inventory too and your point becomes even more important.
