### ISSUE TITLE
Field at Fixed Asset Class Search is not usable

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5182]
![image](https://user-images.githubusercontent.com/31498748/96575719-244a4000-12f7-11eb-82d6-c84559650561.png)

**Comment by ehuelsmann** [comment]
It's meant to filter the the asset classes by the `asset_dep_method.unit_label` value used by the class. I'm not sure what its value is in practice. I can't imagine it to be very practical. I'd like to remove the filter until someone complains, really (KISS - Keep It Simple, Seriously).
