### ISSUE TITLE
Purchase Order automatically sets to close once "Vendor Invoice" button is clicked.

### ISSUE THREAD

**Issue by Bobberty** [ledgersmb/LedgerSMB#5187]
Tested with LSMB 1.8.6

1)  Setup a vendor
2)  Create a Part
3)  Setup a Purchase Order for the part from the Vendor.
4)  Save the Purchase Order
5)  Click on the "Vendor Invoice"  <--  Users are great for clicking on buttons just to see what would happen.
6)  * Do Not Save/Post the invoice * -- User made a mistake.
7) select Order Entry --> Reports -->Purchase Orders
8) Key in select search criteria
9) Not finding the purchase order  <--  User needs to make a modification to the Purchase Order

The user would never realize that the Purchase Order was closed due to the "Vendor Invoice" button click.

An assumption that the purchase order is still open would be supported by the Search Purchase Orders having a default of "Open". 

If the Purchase Order is set to Closed, the user may believe that a Vendor Invoice has been created.

**Comment by ehuelsmann** [comment]
It would be possible to implement this request with elaborate use of Workflow and an invoice workflow observer to close the order when the invoice gets posted

**Comment by ehuelsmann** [comment]
@Bobberty in your view, should the order be closed when the invoice is saved, or when the invoice is posted?
