### ISSUE TITLE
Blank Payment Type in Payments

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5191]
Cash > Vouchers > Payments, create payment in next screen what is the purpose of Payment type? Payment Type is empty. Do I need to set anything?

![image](https://user-images.githubusercontent.com/31498748/97153830-82689e80-17a1-11eb-9472-2845d53c21a7.png)

**Comment by ehuelsmann** [comment]
@aungzwin10 I'm not sure what it does or that it has been consistently been propagated through the UI. To unclutter the UI, I'm going to hide the field. I don't think there's a way to set the values for the drop-down in the configuration screen(s). Once we come up with a good use for the field (it's undocumented now), it's easy to add it back.
