### ISSUE TITLE
Need explanation on Vendor History and Customer History

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5194]
AR > Reports > Customer History
AP > Reports > Vendor History
Although I payed with multiple combinations of the search filter, no record coming out in the report.
Is that a bug or Do I need to aware anything before generating report?

**Comment by ehuelsmann** [comment]
The documentation of this reportis available in section 9.7.2 of https://github.com/ledgersmb/LedgerSMB/blob/master/doc/LedgerSMB-manual.pdf

To be honest, i have no more documentation and no more historic experience to make any more of it.

 The underlying query is here: https://github.com/ledgersmb/LedgerSMB/blob/1ef66d05256072c588cae4ed49276db5ad87b983/sql/modules/Company.sql#L103
A contribution towards describing what it does as documentation of the function would be highly appreciated!

**Comment by aungzwin10** [comment]
The SQL function return results, the perl doesn't show that in the UI. Could you please check?

**Comment by ehuelsmann** [comment]
@aungzwin10 as mentioned in #4361 , I *am* seeing results (with my development branch, which is equivalent to master for this purpose).

**Comment by ehuelsmann** [comment]
Transferred to the LedgerSMB book repository.
