### ISSUE TITLE
1.8 Accounting issue

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#5201]
Hit a very strange issue where the "acc_trans" amounts do not match the amounts on an invoice.

I'm not exactly sure how this happened, but the result in this case was a debit from the wrong revenue account.

My AR person created an invoice for a client with 4 line items, 3 non-taxable and 1 taxable. The taxable item was the last line.

At some point I'm wondering if he adjusted the amount on one of them and then posted (the client wanted us to bill one of the items to a different credit account). Or maybe he tried to partially void it? Not sure the exact steps but what happened was bad...

He then voided the entire invoice, and created a new one.

Original invoice: 7724 , trans_id 33228
Voided invoice: 7724-void, trans_id 33229
New invoice: 7725, trans_id 33230

The total of all 3 - 7724, 7724-void and 7725 is $1236.00. However, 7724 and 7724-void have a line in the acc_trans table showing $1592 going into/out of the AR account.

For 7724, the $356 difference was added to the first line item, but for 7724-void, the difference was added to the last line item.

This resulted in a $356 debit from the wrong revenue account (which is what I'm using to complete a sales tax and busines and occupation tax report -- the taxable account has a different B&O rate than the non-taxable account, and I need to declare that income as "foreign exchange" because this client is not subject to sales tax in my jurisdiction).

My guess is that my AR guy originally had posted a $1592 invoice, then attempted to adjust it to the correct $1236 amount, but he didn't think it worked. But it actually updated the invoice amounts, and not the AR amount, and some check forcing the transaction to balance applied the difference to a line item in a way that it's not visible on the invoice. He then voided the invoice, which made a reversing transaction, and this time it applied the out of balance amount to a different line item.

**Comment by ehuelsmann** [comment]
@freelock, do you have any hints on how to reproduce? I don't have any idea how you got into this situation and for me to fix it, I'll need to know how to get into this situation, so I can determine how to prevent that.
