### ISSUE TITLE
Unable to delete unapproved AP invoice

### ISSUE THREAD

**Issue by thedoctor0124** [ledgersmb/LedgerSMB#5207]
I accidentaly created a duplicate transaction on AP and when I tried to delete it in drafts I got this error:

https://drive.google.com/file/d/15J9_zCV16zVxmsF0--g-y6czBZWF5hbd/view?usp=sharing

**Comment by ehuelsmann** [comment]
The problem here is that a payment has been entered with the invoice and that the payment record isn't being deleted with the invoice (but still references it)
