### ISSUE TITLE
AP Aging doesn't appear in menu

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5213]
I have full permission but I don't see AP Aging in menu.

https://github.com/ledgersmb/LedgerSMB/blob/a3922866edddc72193a298d695ccdc040191fe52/sql/Pg-database.sql#L2687

I think above lines is the AP again item in menu node table.
But in my DB, the id 27 is Files. Check the image below.
![image](https://user-images.githubusercontent.com/31498748/98800581-fdd37c80-243e-11eb-92b0-9cbd4ba0ee49.png)

**Comment by ehuelsmann** [comment]
`AP Aging` isn't in the database after it finishes upgrading to `master`.

**Comment by ehuelsmann** [comment]
(more research to come)
