### ISSUE TITLE
Unable to open "New Window" in Safari

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5288]
In Safari browser, "Credentials invalid or session expired" page open when "New Window" is opened from the menu and all session are expired and need to log in again.

But doing manual
 1. Open new empty tab
 2. Paste the URL https://<server>/erp.pl?action=root
Open the page correctly and both pages work.

**Comment by ehuelsmann** [comment]
I don't have access to a Safari browser; definitely in need of help here.

**Comment by aungzwin10** [comment]
Please feel free to tell me how can I help.

**Comment by ehuelsmann** [comment]
@aungzwin10 you could research (or ask Apple) why the authentication data is lost ; when you're being handed a work-around (by Apple or elsewhere), please test and PR. I have no means to do this test...
