### ISSUE TITLE
1.7 and 1.8 templates add a spurious gutter column to main table

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#5298]
This gutter column can cause Off-by-One column issues once the templates are processed.

**The following is from a [#ledgersmb](https://matrix.to/#/!qyoLumPqusaXqFJNyK:matrix.org/$1609747391488505ZUxWv:matrix.org?via=matrix.org&via=matrix.freelock.com&via=t2bot.io) discussion

> **[dcg]**
If you take a look at....
- https://github.com/ledgersmb/LedgerSMB/blob/1.7.25/templates/demo/letterhead.html
- https://github.com/ledgersmb/LedgerSMB/commit/2814c8d7eddfe659d26fd10bcb2179bb39737779#diff-becfc0e6e93f814b7c02a6b4f07e63124efd17897c7c9b26618d93550130b786
￼
> Line 2 of letterhead is....
```html
<td width=10>&nbsp;</td>
```

> **[ehuelsmann]**
yes

> **[dcg]**
In invoice.html the end result is adding
```html
<td> </td>
```
> to every toplevel `<tr>`
￼
> In the commit I linked to, all of the <td> </td> lines were removed from purchase_order.html
This broke printing of the PO (the header and PO were in different table columns)
as far as I can tell, the only reason that empty column exists in leterhead.html is to forma gutter (margin) to the left of the document

> If that is the case, I would strongly recommend we remove it from all html templates
￼If the gutter is really desired, then we should simply add a left margin to the outer table

> **[ehuelsmann]**
that's indeed the purpose of the original use of it indeed.
I did a lot of clean up on the HTML documents, I think post-1.8. maybe this has been resolved too.

> **[dcg]**
It's still present in 1.8
￼It's also present in 1.9
ehuelsmann: so, at the moment, we need to do one of the followning....
- revert the commit to purchase_order.html
- remove the gutter column from all other templates

> I think the correct solution would be "remove from other templates"

> **[ehuelsmann]
Agreed. We need to remove everywhere.

**Comment by ehuelsmann** [comment]
@sbts I don't understand. This commit was added after testing templates with Andrew (on your request). What happened in the mean time to make us want to revert the commit on all branches?
I mean: I cleaned up the templates on the master branch, but I'm pretty sure most of that work wasn't backported.

**Comment by ehuelsmann** [comment]
The fix for this change can't be back-ported due to extensive merge conflicts.
