### ISSUE TITLE
Upgrade to 1.8 and login credentials don't work

### ISSUE THREAD

**Issue by mplubratt** [ledgersmb/LedgerSMB#5370]
Hello.

I'm running LedgerSMB using the docker containers from Docker Hub with a Ubuntu server as the Docker host and PostgreSQL server (12.6).  I was running 1.6.29 and decided to upgrade to 1.8.10.  I backed up my database and started the 1.8.10 Docker image using the same options as my successfully running 1.6.29 image.  When I went to the setup.pl script to do the database migration, I received a "Access denied (500): Bad username/password" error.  This also happens using the login.pl script.  I tried to backtrack and upgrade from 1.6.29 to 1.7.26.  That worked as expected.  Then I thought I'd try the upgrade from 1.7.26 to 1.8.10; but again, I got the same error.

I've looked through the 1.8 upgrade guide and it looks like drop-in upgrades should work.  Am I missing a docker run option?  Or, a database user tweak that used to work but doesn't now?

Thank you,
Mark

**Comment by ylavoie** [comment]
Most likely a browser cookie problem, login changed in 1.8.
1- Use setup and set/reset your user password on 1.8
2- Make sure that your browser cookies are cleared for Ledgersmb

**Comment by mplubratt** [comment]
I cleared the cookies and restarted my browser and it works.  Thank you!
