### ISSUE TITLE
1.8.12: Migration from 1.3 missing some fields

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#5417]
I'm working on a more extensive analysis, but the following fields have been identified to be missing:

* [x] ap.crdate
* ~~[ ] ap.is_return~~
* [x] ar.crdate

**Comment by vwren** [comment]
Looking at the 1.3 schema, there does not appear to be a column for ap.is_return, so it seems reasonable that it would be populated with a default value.

> # select is_return from lsmb13.ap;
> ERROR:  column "is_return" does not exist

in the 1.5 schema, ar also has an 'is_return' column, but again, I can't find that column in the 1.3 schema.

**Comment by ehuelsmann** [comment]
`is_return` has been added in 1.4, so that can't be migrated.
