### ISSUE TITLE
Transaction disappeared when saving AR/AP transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5452]
The transactions are disappeared when saving AR/AP transaction. This is urgent and need to fix ASAP.
You can view screen recording at below link

https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/mXGmczkiZCJMkpRwksbAWwhz

**Comment by ehuelsmann** [comment]
I've found the reason, but not the cause:

When you remove the "AP_overpayment" checkmark from these accounts, it starts working.

**Comment by ehuelsmann** [comment]
The cause has been identified to be https://github.com/ledgersmb/LedgerSMB/blob/d87c4f8/old/lib/LedgerSMB/Form.pm#L1954-L1969

This bit of code precludes AP accounts used in the account dropdown for transactions to be marked with anything but "AP_amount" flags (account links).

**Comment by ehuelsmann** [comment]
I'm not sure what the next step should be here.

**Comment by ehuelsmann** [comment]
Can we close this?
