### ISSUE TITLE
Selected value of AR/AP account dropdown is not retained at update

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5453]
In AR/AP > Add Transaction,

The value selected for AR/AP account dropdown is not retained at update. See image below

I selected 2100 but when I update, it reverted back to first account

<img width="1155" alt="Screen Shot 2021-05-24 at 7 35 11 PM" src="https://user-images.githubusercontent.com/31498748/119352026-2c23f580-bcc7-11eb-944c-a57af0443153.png">

<img width="892" alt="Screen Shot 2021-05-24 at 7 37 52 PM" src="https://user-images.githubusercontent.com/31498748/119352318-8ae96f00-bcc7-11eb-8a7f-1f95d51b5720.png">

**Comment by ehuelsmann** [comment]
does this also happen on invoices?

**Comment by aungzwin10** [comment]
Yes, it doesn't retain in invoices too
