### ISSUE TITLE
Receivable/Payable line at AR/AP Transaction doesn't show the correct total of transactions

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5528]
Receivable/Payable line at AR/AP Transaction doesn't show the correct total of transactions
But it show Receivable/Payable line which match with receipt/payment.
Also, Receivable/Payable line indicate (-) when we look back the transaction.

1. AR > Add Transaction, Choose a customer
2. Add two transaction lines, one with 5,000 and another with 70,000, you can choose the account as you want.
3. Save and Post
4. Cash > Receipt, Choose customer
5. Receipt 100,000 for that transaction, then Save
6. AR > Search, Search for that transaction and you will see.

Same step can be applied for AP transaction

<img width="1232" alt="Screen Shot 2021-06-08 at 1 51 26 PM" src="https://user-images.githubusercontent.com/31498748/121154873-52bc6180-c86d-11eb-8f9d-3db6eebf1240.png">

**Comment by aungzwin10** [comment]
The query doesn't select correct matching receivable/payable line, it takes value of receivable which match with receipt/payment line. So, what if we reset the $form->{invtotal} to zero and calculate by adding all the line?
This approach is used in Add(new) transaction. See https://github.com/ledgersmb/LedgerSMB/blob/0b61e14a4a2be91195405cb6208722dbd595a170/old/bin/aa.pl#L1214-L1218

My idea is adding following block of code before this. https://github.com/ledgersmb/LedgerSMB/blob/0b61e14a4a2be91195405cb6208722dbd595a170/old/bin/aa.pl#L782
```
    $form->{invtotal} = 0;
    for ( 1 .. $form->{rowcount} ) {
        if ( defined $form->{"amount_$_"} ) {
            $form->{invtotal} += $form->{"amount_$_"};
        }
    }
```

By doing this, it probably fulfills 3 requirements. 
1. Current issue solved.
2. Receivable/Payable Line indicates (-) sign.
3. Because of total is calculated on the fly, the user can get the correct total when he/she update the transaction in save_draft state. Currently what happened when user change amount or add another new line and click 'Update', is, the total doesn't change until user click 'Save Draft'.

@ehuelsmann How do you think? If the approach is okay, I will PR.

**Comment by ehuelsmann** [comment]
@aungzwin10 I'd prefer to fix the problem of the not-changing total when editing a saved transaction as a separate problem. (Could you please create a separate issue for that? I'd be happy to solved it.)

The solution from #5545 uses the fact that all journal lines - except the opening journal line - will be associated with payments. By excluding the payments-related lines, the transaction-total-posting journal line is the only one remaining.
