### ISSUE TITLE
Empty lines at AR/AP Transaction generate double lines only when saving as draft

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5529]
In the System > Defaults, Minimum Empty line is set to 1. It only generates 1 extra line at each update and save. But when saved as draft it generate double amount of empty lines. Also tested by setting Minimum Empty line as blank(0).
Please see the screen recording video.

Version is 1.8.14

https://user-images.githubusercontent.com/31498748/121300179-81454580-c91c-11eb-9cbe-4d814e5c61d2.mov

**Comment by ehuelsmann** [comment]
Thanks for filing! This problem has existed for quite a while (long before 1.8); I *think* I have solved it for 1.9. Please test that, if you have time.

**Comment by aungzwin10** [comment]
It is still happening in 1.9. Please see the screen recording

https://user-images.githubusercontent.com/31498748/121470848-c634af00-c9e4-11eb-84f5-84f454a59f71.mov
