### ISSUE TITLE
Error on Save Draft of AP > Vendor Invoice

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5532]
The following error occur in Save Draft of AP > Vendor Invoice.

`'ERROR: update or delete on table "transactions" violates foreign key constraint "invoice_trans_id_fkey" on table "invoice" DETAIL: Key (id)=(28) is still referenced from table "invoice". CONTEXT: SQL statement "DELETE FROM transactions WHERE id = old.id" PL/pgSQL function track_global_sequence() line 18 at SQL statement SQL statement "DELETE FROM ap WHERE id = in_id AND approved IS FALSE" PL/pgSQL function draft_delete(integer) line 27 at SQL statement: SELECT * FROM "public"."draft_delete"(?) at /usr/local/share/perl/5.26.1/PGObject.pm line 362. '`

<img width="1192" alt="Screen Shot 2021-06-10 at 10 06 28 AM" src="https://user-images.githubusercontent.com/31498748/121460765-887b5a80-c9d3-11eb-954d-c00547366c22.png">

**Comment by ehuelsmann** [comment]
@aungzwin10 I'm assuming this is 1.8, correct?

**Comment by aungzwin10** [comment]
Yes, it is 1.8, I will add 1.9 in the title if the issue is for 1.9

**Comment by ehuelsmann** [comment]
I expect this to be present in 1.9 too.

**Comment by aungzwin10** [comment]
I haven't test it yet, but it might present in 1.9 too

**Comment by ehuelsmann** [comment]
I think the first time you save, that succeeds, but this error shows on subsequent attempts to save the invoice.

**Comment by aungzwin10** [comment]
Yes, the first time save is worked as expected. This error shows on submitting "Save draft"
