### ISSUE TITLE
Vendor/Customer select dropdown at  AR/AP Transaction and Invoice show all entity type

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5534]
<img width="309" alt="Screen Shot 2021-06-10 at 12 12 57 PM" src="https://user-images.githubusercontent.com/31498748/121471284-6a1e5a80-c9e5-11eb-8161-ad8f2d11f95d.png">
<img width="299" alt="Screen Shot 2021-06-10 at 12 12 45 PM" src="https://user-images.githubusercontent.com/31498748/121471292-6ee30e80-c9e5-11eb-9970-28b278a3eadd.png">

**Comment by ehuelsmann** [comment]
This is a problem of 1.8 too (and I'm assuming 1.7 too)
