### ISSUE TITLE
AR/AP total not changing when editing a saved transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5554]
@aungzwin10 create a new issue according to @ehuelsmann comment

I'd prefer to fix the problem of the not-changing total when editing a saved transaction as a separate problem. (Could you please create a separate issue for that? I'd be happy to solved it.)

**Comment by ehuelsmann** [comment]
For 1.8, this is a known issue. It's fixed in 1.9. It's very hard to fix this in 1.8; instead, people who suffer from this problems, should probably upgrade to 1.9.
