### ISSUE TITLE
Default AR/AP set on credit account doesn't automatically select in AR/AP dropdown of Transaction and Invoice 

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5573]
If I remember correctly, before 1.8, when user choose Vendor/Customer for Transaction or Invoice, the AR/AP dropdown automatically selects the default one for that vendor/customer which is set when creating Credit Account.

Yes I hit 'Enter Key' after vendor/customer select in master/1.9. In 1.8, user have to hit 'Enter key' or 'Update' after typing vendor/customer.

See screenshot below.

<img width="927" alt="Screen Shot 2021-06-15 at 10 18 14 AM" src="https://user-images.githubusercontent.com/31498748/121990473-db825280-cdc3-11eb-9d7b-afe620ecb0a2.png">

<img width="569" alt="Screen Shot 2021-06-15 at 10 28 14 AM" src="https://user-images.githubusercontent.com/31498748/121990794-66634d00-cdc4-11eb-85d8-e04945608781.png">

**Comment by ehuelsmann** [comment]
@aungzwin10 I'm puzzled, because I've searched the 1.7 sources in `old/` (which is where both transactions and invoices come from), yet I can't find the field name which stores this information (`ar_ap_account_id`) anywhere in the sources on that branch.

**Comment by aungzwin10** [comment]
I don't remember exactly which was the last version, but I am sure that the AR/AP account is selected to the one that user set default in credit account.

**Comment by ehuelsmann** [comment]
I'm actually unable to reproduce this with 1.7.31-dev (current branch head): creating 7 AR accounts and a single customer, it's not selecting the default AR account. (Not on transactions *and* not on invoices...)

So this is not a regression, but it's pretty useless that it's not working because otherwise: why even allow this default to be set??
