### ISSUE TITLE
Unicode character are not correctly showed in Journal Entry

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5583]
In other screen such as AR/AP transaction and Payment, unicode character are correctly saved and rendered

See below for journal entry
<img width="679" alt="Screen Shot 2021-06-18 at 4 15 43 PM" src="https://user-images.githubusercontent.com/31498748/122542241-7abb7a00-d050-11eb-9fda-c0870f2b084b.png">

**Comment by ehuelsmann** [comment]
Actually, it's everywhere in the journal entry screen. The difference between the other screens and the journal entry screen, is that the journal entry screen is rendered by Template Toolkit whereas all the others directly render from the source code.

**Comment by ehuelsmann** [comment]
Does this happen on 1.8 and 1.7 too? The line that I need to change on 1.9/master exists exactly the same way on 1.8 and 1.7.

**Comment by ehuelsmann** [comment]
Interesting. This does not seem to happen on 1.8.

**Comment by aungzwin10** [comment]
The screenshot is using 1.8.15

**Comment by ehuelsmann** [comment]
Oh! I actually tested with 1.7! It's not happening on 1.7.
