### ISSUE TITLE
design chart of accounts account entry/edit interface

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#559]
The reason for this is that we cannot support cash flow statements without some additional categorization of accounts.  To do this, I expect to add a subclassification for cash flow statement section.

Additionally, this is one of our composite interfaces, and therefore this seems to be a good time to bring it to dancer, add appropriate web services, etc.  Currency and Exchangerate handling will follow shortly afterwards.

I would also like to conbsider generalizing headings off to allow heading classification (a system similar to reporting units) but this may not happen with this revision.  The idea is that way an account could be attached to several different heading trees (one for managmenet accounting, one for financial accounting etc).

URL proposals (... referring to the lsmb root url):

```
  - .../accounts/ coa (get)
  - .../accounts.(html|json|xml|csv) (get/post)
  - .../accounts/:accno.(html|json|xml) (get/put)
```

The current dropdowns that use accounts would have to be moved to thie above url system

**Comment by ehuelsmann** [comment]
Hi Chris,

Could you explain what you think it is that we require for cash reporting that's needing configury from accounts? All I can think of is that we need more info on posting level, that's why I'm asking.

Regards,


Erik.

**Comment by ehuelsmann** [comment]
Chris and I discussed cash reports some time ago. There's more to cash reports than just account classifications, because in some cases the type of transaction ("balance movement") determines the "cash movement" classification. This is especially true for the gain(loss) upon asset disposal.

**Comment by einhverfr** [comment]
tagging as maor enhancement because we know the requirements well but this is an architecture shift for this component.

**Comment by einhverfr** [comment]
I think we need a report redesign ticket too per @ehuelsmann's comment above.

My initial thinking is that what we need on the *account* side is a mapping to sections of reports.
I think what we need on the *report* side is a handling of the additional pieces.  The journal structure needs to be sufficient to provide the report what it needs in this regard also.

**Comment by einhverfr** [comment]
https://github.com/ledgersmb/LedgerSMB/wiki/Topic-COA

**Comment by einhverfr** [comment]
appropriate tickets created for implementation.  Closing.
