### ISSUE TITLE
rewrite of currency and exchangerates

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#560]
After the accounts, plan on refactoring currency and exchangerate handling.  The plan is to have a buy/sell system which can be better constrained than what we have now and useful for individual transactions as we move into the financial rewrite.

The initial phase would be backwards-compatible largely with previous implementations. 

New tables:
- currency 
  - symbol
  - allowed_variance
  - default

Would have a dojo form for adding currencies in a tabular manner, orderd by symbol

Eschangerate would have an fkey on symbol.

New urls:

.../currency/$symbol/ get: report of currency
 .../currency/$symbol/ put/post, update currency
 ..,/currency/$symbol.json/xml get pr put currency 
 .../currency/$symbol/$bysell/$date get|post|put a new exchangerate (html/http form)
  .../currency/$symbol/$bysell/$date.json|xml get|post|put

**Comment by ehuelsmann** [comment]
Feature has been started (in a variant of the above) on my 1.4-mc branch.
