### ISSUE TITLE
Financial rewrite:  Journal and Ledger Design

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#562]
Planning the following regarding the journal design and rewrite:

Database tables:
- journal (stores journal identifiers, not journal entries, i.e, general journal, sales journal etc).
- journal_entry (stores journal entry data)
- journal_line (stores journal entry line items)

URL namespaces:
- .../journal/general/entry/new/ (get a form for a new entry)
- .../journal/general/entry/:id (show an entry by id, as a report)
- .../journal/general/entry/:id.{html/json/xml/csv/pdf} (show entry with format shown)
- .../ledger/general/:accno[.ext]?date_from=...&date_to=... General ledger for account
- .../journal/search/... (current gl/search report)

**Comment by ehuelsmann** [comment]
Moved to https://github.com/ledgersmb/LedgerSMB/wiki/Topic-Journals
