### ISSUE TITLE
Sales/Purchase Journal (Rewrite with financial rewrite)

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#564]
This will not occur before the gl rewrite.  New tables will include eca_journal_entry which will connect entity_credit_account to journal_entry

New procedures will include:
- eca_journal_entry__get(id int) which will get the appicable sales/purchase entry)
- eca_je_save(self eca_je) will save the eca journal entry (eca_je is the new type)

URLs:
- .../journal/(sales|purchase)/new get|put|post, getting the new form or posting/putting it.
- .../journal(sales|purchase)/id.fmt (fmt being html, xml, or csv), get to retrieve, post to approbve
- .../journal/(sales|purchase)/(search|outstanding|aging) for relevant reports, get only

**Comment by ehuelsmann** [comment]
Moved here: https://github.com/ledgersmb/LedgerSMB/wiki/Topic-Sales-purchase
