### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [ledgersmb/LedgerSMB#5738]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ehuelsmann** [comment]
Hi!

There's a security issue report form at the project's domain (https://ledgersmb.org/contact/security_report); if that doesn't work for you, you can send mail to the address mentioned in my profile (as the lead maintainer).

Thank you for filing your issue!

Regards,

Erik.

**Comment by zidingz** [comment]
Hey @ehuelsmann, not myself personally, but open source security researchers on our platform huntr.dev.

Our sole aim is to find your preferred contacted method for receiving security reports, so by no means is a security.md mandatory! 

I appreciate your response, and will send over the reports to you by email within the hour.
