### ISSUE TITLE
Unable to uncheck the 'Recon' checkbox in Account

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5955]
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/SAgPkpqHzbPALFBbiXkifJYd

**Comment by ehuelsmann** [comment]
Ok. In order to understand the use case, it's important to know why you want to remove it: e.g. are there reconciliations on the account already? If so, what is the reason you want to remove it?
