### ISSUE TITLE
Vendor/Customer at AR/AP are not rendered as dropdown in 1.9

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5956]
Upgrade from 1.8 to 1.9, Vendor/Customer selection are not rendered as dropdown.
It is rendered as dropdown only for new db creation on 1.9.

**Comment by ehuelsmann** [comment]
Could you check the setting for "max per dropdown" in System > Defaults?

New companies get created with a setting of "9999" to enable the drop-down. Your migrated company is older and likely shows no value or "0". The setting exists to prevent companies with 100.000 clients downloading the full set of clients on every invoice/transaction update.

**Comment by aungzwin10** [comment]
Great, the issue solved with setting `9999` to "Max per dropdown". IMO, it is better if the update version change  "Max per dropdown" value.
