### ISSUE TITLE
URGENT: Payment Lines are not correctly showed

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5985]
This happened for all versions, master, 1.9, 1.8

<img width="1190" alt="Screen Shot 2021-09-15 at 5 01 17 PM" src="https://user-images.githubusercontent.com/31498748/133418274-caebbc5b-21ab-40cc-8346-4f22ecabc915.png">

<img width="1184" alt="Screen Shot 2021-09-15 at 5 00 43 PM" src="https://user-images.githubusercontent.com/31498748/133417694-aea197c4-03f6-4ce6-8fdd-3d0e5f2a5136.png">

**Comment by ehuelsmann** [comment]
@aungzwin10 thanks for the report! I've tried to reproduce, but I wasn't able to. Could you post one of your screen recordings so I can see which steps you go through to trigger this condition?

**Comment by aungzwin10** [comment]
@ehuelsmann Thanks for the check. I have local fix for generating extra double number of empty payment lines on Save. That fix trigger this condition. So I reverted back this changes and it is work now. But the doubling extra payment lines issue is unsolved. I will create a new issue for that.
