### ISSUE TITLE
Doubling extra empty payment lines

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5989]
Payment lines at AR/AP Transaction and Invoice are generated double number of empty lines on the `Save [Draft]`. It is okay on the `Update`

**Comment by ehuelsmann** [comment]
This is fixed in 8cc0ed56376aee3abf376f8528f5bc73b7a3b64e for 1.9 and master.

**Comment by aungzwin10** [comment]
The commit you mention fixed for the transaction lines.
The current issue is with lines under  **Payments** heading. Could you please recheck it?

**Comment by ehuelsmann** [comment]
Sorry about that. Reopening to be able to close later when I have a solution.
