### ISSUE TITLE
AR/AP Transactions and Invoices cannot save again after attaching files

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6018]
The transactions is saved as draft, not posted yet, and attach the files. Then save the transaction again. Following error occurs.

```
'ERROR: update or delete on table "transactions" violates foreign key constraint "file_transaction_ref_key_fkey" on table "file_transaction" DETAIL: Key (id)=(13) is still referenced from table "file_transaction". CONTEXT: SQL statement "DELETE FROM transactions WHERE id = old.id" PL/pgSQL function track_global_sequence() line 18 at SQL statement SQL statement "DELETE FROM ap WHERE id = in_id AND approved IS FALSE" PL/pgSQL function draft_delete(integer) line 31 at SQL statement: SELECT * FROM "public"."draft_delete"(?) at /usr/share/perl5/PGObject.pm line 362. '

dbversion: 1.10.0-dev, company: test
```

**Comment by ehuelsmann** [comment]
The same applies to GL transactions.

**Comment by ehuelsmann** [comment]
I have to think longer about this regression (which is actually not really a regression: before this release, "re-saving" a transaction was simply not practical).

**Comment by aungzwin10** [comment]
Please feel free to ask if you have any concern.

**Comment by ehuelsmann** [comment]
The problem with this issue is that saving a draft invoice/transaction causes it to be deleted from the database (and thus loosing the reference for the file to be attached to) only to create a completely new invoice/transaction in the database immediately after.

It's very much possible we can only solve this issue when we're on a new code base for invoices and transactions.

**Comment by ehuelsmann** [comment]
In `old/lib/LedgerSMB/AA.pm`, this is the section which causes this problem:

https://github.com/ledgersmb/LedgerSMB/blob/0a5675adfa81eba841eb511be4d8e18812d79fb1/old/lib/LedgerSMB/AA.pm#L282-L316

And while it may be possible to remove the "delete" operation for non-batch-related transactions, `voucher__delete` deletes the `transactions` line too (which means changes in the code can only be partially solved in the existing code).

**Comment by ehuelsmann** [comment]
The work-around here, since you *can* attach after posting a transaction, is to wait for the transaction to be posted (at which point there's no need to saving it again) and attach after it's posted.
