### ISSUE TITLE
No total due on AR Aging report

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#6053]
Perhaps this is something that just needs to be added to the template, but when I print an aging report, I get columns for 0, 30, 60, 90 days aged, totals for each time period, but no grand total. 

This is different than the aging screen itself.

Is there a variable we can add to the template to print the total amount due?

**Comment by ehuelsmann** [comment]
The variable to use should be `total` (instead of `c30`, `c60`, `c90`).

**Comment by ehuelsmann** [comment]
@freelock confirmed this works on the chat channel.
