### ISSUE TITLE
Payment form does not allow expense account entry

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6059]
Step to reproduce:

1. Create a new vendor in Contacts -> Add Contact.  Verify that class is marked 'Vendor'
2. Go to 'Credit Accounts' tab.
3. Fill in 'Pay To', 'Description', 'Payment Terms', and 'Starting Date'.
4. Save
5. Go to Cash -> Payment.
6. Enter vendor name from above.
7. Click 'Continue'.
8. In 'Item 1' the 'Account' column has a pull down, but does not have any entries.

I would have expected a list of G/L expense accounts.

Branch: 1.9
Commit: c7e99971412ec470b247d5e5d0f71665a8bb41ac

The problem is present with both:
G/L: US GeneralHierarchical.xml
G/L: US General.xml

**Comment by neilt** [comment]
Note that the same issue occurs when trying to receive cash from a customer using Cash -> Receipt.

The account column has no pull down. I would expect to get a list of income accounts. 

 Let me know if you want me to separate this into a separate issue.

**Comment by ehuelsmann** [comment]
This was replied to by chat on how this can be achieved. Can this be closed?

**Comment by neilt** [comment]
I do not think an unworkable empty dropdown is good UI practice.  It should contain something like "Not Applicable", "Not Available", "Select x to see options", etc.   Something to give the user an idea of what is happening.

I've not verified that the following works, but I am fine for closing this issue right now.

For the history, this was the chat response, unfortunately, I did not capture the author.

> I use AP transactions for this kind of thing -- create a vendor, create an AP transaction with the amount drawing from whatever account is appropriate (commissions, expense, etc)
once you have an open ap transaction, you can go to Cash -> Vouchers -> Payments, and create a new batch with the date to go on the check. On the next screen, pick your checking account and the next check number to print. Then you can select vendors with open transactions (or vendor invoices if you purchase items for inventory) and click "Print" to generate a PDF you can then print.

Here is the graphic I posted in the chat

<img width="1101" alt="Screen Shot 2021-09-29 at 12 27 42 PM" src="https://user-images.githubusercontent.com/1809796/136032987-61b9672c-58b4-4981-bed0-3a628d45867a.png">
.

**Comment by ehuelsmann** [comment]
I agree that an empty drop-down is a bad experience.

Taking a step back, the screen needs redesign in general: the impression it makes on you is that you'll be offered expense and income accounts. The section here is, however, meant to enter overpayments or excess payments from customers, with or without payment of invoices.
