### ISSUE TITLE
Password still expired after 24 hours although user change from Preferences > Password

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6067]
Before 1.9, the password expiry time is set 24 hours only if admin reset password from `setup.pl`. And if user change password from `Preferences > Password` the expiry time is set to a year, right?
1.9 behavior is not same as before. Password expired after 24 hours although user change from `Preferences > Password`.
<img width="343" alt="Screen Shot 2021-09-30 at 9 51 26 AM" src="https://user-images.githubusercontent.com/31498748/135380763-3ea2bf8a-019c-4a91-86b0-dc2f85c25921.png">

**Comment by neilt** [comment]
I set the password duration in System->Defaults to 365, but still get the expiration notice shown above.

I also tried logging out and back in and the notice still shows.  The data is correct in the database for key `password_duration`.
