### ISSUE TITLE
Discount created on sales order gets duplicated on generated invoice

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#6125]
Sales order discount is applied to price when creating invoice, making the discount double when you create the invoice. Not sure if these are the exact steps, but my AR guy did something along these lines:

-    Added a 5% discount to 2 line items on a sales order.
-    Created an invoice from the sales order, expecting the same view as in the sales order (line item price, 5% discount visible)
-    Instead, the line item price had been lowered by 5%, and 5% was also carried over to the discount field and applied again.

**Comment by ehuelsmann** [comment]
The cause is this code which overwrites the "sellprice" field: https://github.com/ledgersmb/LedgerSMB/blob/79f165201c206264bd5ff21c9ad5ba5db9a2e0c9/old/lib/LedgerSMB/IS.pm#L891-L893

The solution is to reload the invoice after it's been written to disk (posted).
