### ISSUE TITLE
GL import batch menu is not available

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6248]
According to the code, GL has two import type, gl and gl_multi(batch). Although I have full permission, menu show only one ,`Import`. Please see the screenshot.
<img width="212" alt="Screen Shot 2021-12-06 at 11 34 59 AM" src="https://user-images.githubusercontent.com/31498748/144790291-37d0b0e0-c31b-4cf5-b2b0-3e6120353831.png">

Step to reproduce
1. Create a new company from setup,pl
2. Check the menu

My finding
According to the `sql/changes/1.8` GL Import batch menu is inserted. However, I think the entry to `menu_acl` is not inserted correctly.
https://github.com/ledgersmb/LedgerSMB/blob/f91e0fa0b24c40dd9b59b71de6adae635b9eeb36/sql/changes/1.8/add-gl-batch-import-menu.sql#L30-L38

All branch master/1.9/1.8

**Comment by ehuelsmann** [comment]
I think Yves is correct in his assessment that the Roles.sql module should be extended to add the ACL, instead of setting up the ACL in this file.
