### ISSUE TITLE
UX improvement for CSV import screen

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6264]
CSV Import/Import Batch screen need UX improvement.
Although screen contains 4 visible fields and 1 button, it will be better for the user if we provide more information.
<img width="592" alt="Screen Shot 2021-12-08 at 1 34 20 PM" src="https://user-images.githubusercontent.com/31498748/145163670-cd460afe-b7e0-4c21-b214-90d92edea0cb.png">
This screen use to import the following process.
```
gl             
gl_multi       
ar_multi       
ap_multi       
chart          
gifi           
sic            
timecard       
inventory      
inventory_ulti
parts          
services       
overhead
```

As you can see the same screen is used to import a lot of different process, and  it doesn't show the `title` and information such as how user should import or prepare file. The user cannot easily understand what he should do next.
Also all 4 visible fields are mandatory in some case and the code doesn't check for existence of these value. So the error message is not easily understandable by the user.

That's why I want to propose a solution which can improve UX. 
<img width="1198" alt="Screen Shot 2021-12-08 at 1 45 18 PM" src="https://user-images.githubusercontent.com/31498748/145164964-c38c04b0-fd0f-4b06-9a81-3853127b1d8a.png">

Above is AP > Import Batch. I add `title` as `AP Transaction Batch Import` and some help information.
Although we provide example csv upload file in the code under `/doc` folder, in real life, normal user cannot access server and file system except sys-admin. User have no idea what is the format or what type of file he should use to import. So under the `title`, I add some sample information for normal user.

Then I add `required` for the field so that form cannot submit till the `required` fields are not fill.

<img width="1209" alt="Screen Shot 2021-12-08 at 1 48 39 PM" src="https://user-images.githubusercontent.com/31498748/145165380-d7a5def9-201e-466b-9035-752ee23f90bb.png">

**Comment by ehuelsmann** [comment]
Closed by #6279
