### ISSUE TITLE
Printable language options show a list of country instead of actual language

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6267]
Transaction Approval > Batches > Batch Details

<img width="1194" alt="Screen Shot 2021-12-09 at 2 39 52 PM" src="https://user-images.githubusercontent.com/31498748/145358997-5b802c22-5875-4dcd-b36c-2a0b3ac521ce.png">

**Comment by aungzwin10** [comment]
@ehuelsmann 
As you suggest in here https://github.com/ledgersmb/LedgerSMB/pull/6270#discussion_r767288230
`LedgerSMB::I18N::location_list_country_localized` returns a list of country too.

What this issue mention is that, the drop down should be a list of `Language`, not a list of `Country`.
Please reference the print language in AR/AP Transaction and Invoice screen.
<img width="223" alt="Screen Shot 2021-12-17 at 10 36 04 AM" src="https://user-images.githubusercontent.com/31498748/146487815-b7d40722-d880-4b84-9e9d-8986ab260214.png">

I think the logic is that user want to print it in `English` language format or `Dutch` language format. not in `United State` format or `Netherlands` format.

**Comment by ehuelsmann** [comment]
This is a 7-year old bug that was introduced right off the beginning. Interesting find! ( See https://github.com/ledgersmb/LedgerSMB/blame/be6b031f89d572dc90db8a0185eca0223f047ab0/lib/LedgerSMB/Report/Unapproved/Batch_Detail.pm#L239 )
