### ISSUE TITLE
Error when posting an invoice from a sales order

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#6280]
In LedgerSMB 1.9.4, getting an error when creating an invoice by shipping a line item on a sales order.

It sounds like first got an error on a null transdate (but you can see in the screenshot that all 3 dates have a value):

![2021-12-16_15-31](https://user-images.githubusercontent.com/46937/146464515-8975be59-ffb7-412f-87ef-343f74ac56e3.png)

... then later attempts had a couple other errors:
![image(2)](https://user-images.githubusercontent.com/46937/146464561-2b5c19c6-74da-412e-b4b9-e727ce76eb35.png)

![image(3)](https://user-images.githubusercontent.com/46937/146464578-06336745-bcef-456b-8f8b-215c46e7adf9.png)

I found two unapproved copies of this invoice with the Due date not set. Was able to successfully update the note, manually set the due date and save -- and then post it -- but it sounds like others had lots of trouble getting an invoice successfully posted.

**Comment by ehuelsmann** [comment]
@freelock, would you be able to test https://github.com/ledgersmb/LedgerSMB/commit/50fa2a4a26283d9f504c9c24288a7e00c47a303d ? I think that closes it.

**Comment by ehuelsmann** [comment]
The reason I didn't mark this as "solved" is because I only could reproduce the `duedate =''` issue. The other issue I couldn't reproduce. With the changes to get a due date calculated as part of the initial conversion of the invoice, I'm able to post the invoice without further issue.

**Comment by ehuelsmann** [comment]
Closing after all. Please re-open if not fixed.
