### ISSUE TITLE
Bug on Payment/Receipt Reversal

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6340]
When doing payment/receipt reversal, following error occurred.

```
ERROR: new row for relation "acc_trans" violates check constraint "transdate_nullity"
DETAIL: Failing row contains (3332, 223, null, null, f, null, null, t, null, null, 203, 14775, -10000.00, -10000.00, MMK).
CONTEXT: SQL statement "WITH new_entries AS (
INSERT INTO acc_trans (trans_id, chart_id, transdate, source,
cleared, memo, invoice_id, approved, cleared_on,
reconciled_on, amount_bc, amount_tc, curr,
voucher_id)
SELECT trans_id, chart_id, in_payment_date, source,
false, memo, null, coalesce(in_approved, true), null,
null, -1 * amount_bc, -1 * amount_tc, curr,
(select id from voucher v
where a.trans_id = v.trans_id
and v.batch_id = in_batch_id) as voucher_id
FROM acc_trans a
WHERE exists (select 1 from payment_links pl
where pl.payment_id = in_payment_id
and a.entry_id = pl.entry_id)
RETURNING entry_id
)
INSERT INTO payment_links (payment_id, entry_id)
SELECT t_payment_id, entry_id
FROM new_entries"
PL/pgSQL function payment__reverse(integer,date,boolean,integer) line 34 at SQL statement:
SELECT *
FROM "public"."payment__reverse"(?, ?, ?, ?) at /usr/local/share/perl/5.30.0/PGObject.pm line 362.
```

Moreover, there is no place to clearly look at which payment are reversed. And, reversal line can also reverse which is not expected.

**Comment by ehuelsmann** [comment]
@aungzwin10 I'm not able to reproduce this with single payments and reversal on 1.10 (tested with AR as well as AP). The steps I went through are:

1. Create a customer or vendor
2. Create an invoice or transaction for that customer or vendor
3. Post the invoice
4. Go to Cash / Receipts or Cash / Payments
5. Enter a 1.00 payment/receipt, use 2022-01-01 as the date and Post
6. Go to Cash / Vouchers / Reverse Payments (or Receipts)
7. Select 2022-01-01 as the batch date and Continue
8. Select the payment which was entered and Post
9. Go to Transaction Approval > Batch
10. Select the payment/receipt reversal batch
11. Click Post

All of the above went fine. Is there something specific to the payment you're trying to reverse? Maybe it's a batch, it's foreign currency, something else?

**Comment by aungzwin10** [comment]
@ehuelsmann Now I am able to reverse the payment. I know what I was wrong. Thank you very much for your time.

I'd like to know about the following things

1. Why the exchange rate input field is exist without actually using it?
<img width="291" alt="Screen Shot 2022-01-17 at 8 02 09 PM" src="https://user-images.githubusercontent.com/31498748/149778177-3d9e70fd-5a7d-4193-8d6b-0ca52b32314a.png">

2. Why system allow reversed payment line to be reversed again?
e.g.  payment id `12` reverse the `11` and user can reverse `12` again. IMO, system shouldn't allow this. How do you think?

**Comment by ehuelsmann** [comment]
> Why the exchange rate input field is exist without actually using it?

Good find. I think this is a remnant of when our application supported only a single exchange rate per day. It makes sense to remove this field for all reversal batches.

**Comment by ehuelsmann** [comment]
> Why system allow reversed payment line to be reversed again?

The system does not have the concept (internally) of reversed versus reversing transactions. I have long wanted to add this concept, but haven't had the time to do so yet.
