### ISSUE TITLE
Contact > Search and AR/AP Transaction  taking too long to load

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6344]
In my db, I have 2,000+ entity and 88,000+ entity_credit_account(the reason why there are a lot of eca is because of a weird workflow we are using, we need to split multiple eca for each entity).

Because of a big number, loading the contact took too long(3mins +) to load the all those 88,000. And AR/AP Transaction also delay because of these ECA

**Comment by ehuelsmann** [comment]
Can you add a list of steps to get to these bad timings , for both cases ?

**Comment by aungzwin10** [comment]
@ehuelsmann For the Contact > Search, you might generate dummy data about 2,000 entity and 40 Credit Account link to each entity. Then you can view the list using Contact > Search, click `Search` without any filters.

For AR/AP Transaction, because of too many records, vendor selection drop-down is very slowed on first load and subsequent update/Save. IMO, it will be better if vendor selection list load in background using JS and API.

Also with normal input text, following vendor selection screen is delayed a bit. After vendor selected, subsequent update/save has no issue.
<img width="1196" alt="Screen Shot 2022-01-10 at 10 51 27 AM" src="https://user-images.githubusercontent.com/31498748/148718414-04603498-f84c-4552-8ba9-7479ee4b32c6.png">

**Comment by ehuelsmann** [comment]
@aungzwin10 which browser are you using? If this is Chrome, it could be that 1.10.8 and 1.9.22 fix part of this issue.
