### ISSUE TITLE
Trans line do not retained on AR/AP Transaction Vendor Update

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6357]
Trans lines are not retained if it through vendor selection screen. I hope, the following video help to describe the issues.

https://user-images.githubusercontent.com/31498748/148713457-637050e1-5e52-4d22-8750-1ee3681fa208.mov

https://user-images.githubusercontent.com/31498748/148713482-0491a7ec-6927-487e-aac8-3a2e7e11d2aa.mov

NOTE: In my use-case, I cannot use vendor selection dropdown in AR/AP because of 88,000+ records.

**Comment by ehuelsmann** [comment]
If I'm correct, the workaround here is to click Update between filling out the customer/vendor and the rest of the form, right?
