### ISSUE TITLE
Unclear logic on Cash > Payment/Receipt Filter

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6358]
What is the purpose of `Date from` and `Date to` field?
<img width="837" alt="Screen Shot 2022-01-12 at 1 05 32 PM" src="https://user-images.githubusercontent.com/31498748/149076682-a196b683-e9e4-4bb7-8dd3-fb2a68b6fa1c.png">

From a normal user perspective, `Date from` and `Date to` is to filter the open invoices with the `Transaction/Invoice Date` within specified date range, right?

After spending some time on the code, I found that `Date from` and `Date to` is used to filter the inactive entity credit account also. Please see https://github.com/ledgersmb/LedgerSMB/blob/889f69d3780ec8cb0ee314f9b0b6c38f8b59ca7d/sql/modules/Payment.sql#L35-L56
Because of the way the code is, as a user, this looks weird and cannot easily understand why it cannot filter with the date range.

In my opinion, this is not a correct logic/usage to determine active or inactive of Credit account. (Currently, I have no idea what will be the correct logic)

Following are the step to reproduce the issue

1. Create two Vendors - "Vendor 1 and Vendor 2" (either person or company is okay)
2. Create Credit Account on each vendor
- "Vendor 1" with blank(empty) `Start Date` and `End Date` (Meaning this credit account is always active, no?)
- "Vendor 2" with `Start Date = 2021-01-01` and `End Date = 2022-12-31` (Meaning this credit account is active since previous year till end of this year, right?)
3. Add AR/AP Transaction for both Vendors by using `AR/AP > Add Transaction` with `Invoice Date = 2022-01-02`
4. Add another AR/AP Transaction for both Vendors by using `AR/AP > Add Transaction` with `Invoice Date = TODAY`
5. Go to `Cash > Payment`, enter 
`Vendor Name = Vendor 1`,
`Date from = 2022-01-01`,
`Date to = 2022-01-03`
And click `Continue`
 -- According to the filter above, transaction created on Step 3 should come out since "Vendor 1" is active, right?
6. Go to `Cash > Payment`, enter 
`Vendor Name = Vendor 1`
And click `Continue`
-- Both transactions created on Step 3 and 4  come out correctly.
7.  You can repeat Step 5 and 6 for "Vendor 2" also.

NOTE: I notice that the check is wrong(see below). But issue is not just because of it.
https://github.com/ledgersmb/LedgerSMB/blob/889f69d3780ec8cb0ee314f9b0b6c38f8b59ca7d/sql/modules/Payment.sql#L52-L55

**Comment by ehuelsmann** [comment]
> From a normal user perspective, Date from and Date to is to filter the open invoices with the Transaction/Invoice Date within specified date range, right?

Agreed. That's what you'd expect as a user when presented with that input screen.

> After spending some time on the code, I found that Date from and Date to is used to filter the inactive entity credit account also.

What the input screen doesn't say - but what it really *does* - is that it asks for __entity__ selection criteria, not __invoice__ selection criteria. So your remark that it filters inactive credit accounts *as well* is not correct, because that's *the only* thing those dates do. (Aside from those semantics: you're right that this is not clear from the input screen!)

Once the list of active entity credit accounts has been determined, *all* open invoices associated with those accounts are shown.

**Comment by aungzwin10** [comment]
> it asks for entity selection criteria, not invoice selection criteria

I think date from and date to is also used for invoice selection according to the following function,
https://github.com/ledgersmb/LedgerSMB/blob/889f69d3780ec8cb0ee314f9b0b6c38f8b59ca7d/sql/modules/Payment.sql#L187

**Comment by ehuelsmann** [comment]
> I think date from and date to is also used for invoice selection according to the following function,

True, however, I thought that parameter isn't linked to anything in the UI. However, the template `payments/payment1_5.html` passes the value on to the next stage of the selection. You're right it uses the same date input for two separate things.

So: is your proposal to add a second set of dates?
