### ISSUE TITLE
Deleting the batch payment/receipt wipe all lines from `payment_links` table

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6368]
Deleting the batch payment/receipt or payment/receipt reversal using Transaction Approval > Batches, delete all lines from `payment_links` table.

Step to reproduce

1. Create Batch payment
2. Go to Transaction Approval > Batches
3. Select the batch and click `Delete`
4. Check the payment_links

**Comment by aungzwin10** [comment]
I suspect the following lines because, most of the time, `voucher_id` column is null.
https://github.com/ledgersmb/LedgerSMB/blob/4ed2b079c183315fc4f84c25016807c208c7e07f/sql/modules/Voucher.sql#L467-L471

**Comment by ehuelsmann** [comment]
You're correct about those lines. The reason is that there is no relationship between the outer delete and the subquery.
