### ISSUE TITLE
Filter by multiple account on general ledger report

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6394]
Currently General Ledger Report(General Journal > Search) can filter with only one account.
I'd like to filter using more than one account.(something like multi-select)

<img width="625" alt="Screen Shot 2022-02-03 at 11 16 22 AM" src="https://user-images.githubusercontent.com/31498748/152282745-3d96fa65-a85e-4d66-af3d-29211f1842c9.png">

**Comment by ehuelsmann** [comment]
What's your use-case? I mean does this request come from your desire to export loads of data?
