### ISSUE TITLE
Trial Balance and PNL/BS/GL report are mismatched

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6402]
**Trial Balance Report**
<img width="1211" alt="Screen Shot 2022-02-10 at 1 29 19 PM" src="https://user-images.githubusercontent.com/31498748/153355754-d0b5a5b6-4ff0-4d65-9988-441b81ddc0c5.png">

**General Journal > Chart of Accounts**
<img width="898" alt="Screen Shot 2022-02-10 at 1 28 19 PM" src="https://user-images.githubusercontent.com/31498748/153355743-b377df54-00b4-41b1-a1b7-00b37b2bfaae.png">

**Last line of running balance(ending balance) from General Ledger Report(General Journal > Search)**
<img width="237" alt="Screen Shot 2022-02-10 at 1 29 40 PM" src="https://user-images.githubusercontent.com/31498748/153355757-626d4d7e-b333-4776-ad18-de3523c9a455.png">

**Amount from PNL/BS report**
<img width="580" alt="Screen Shot 2022-02-10 at 1 30 29 PM" src="https://user-images.githubusercontent.com/31498748/153355759-ea3b0a04-9d4e-49e9-9284-74555891f2d7.png">

According to the above comparison, Trail balance (Debit, Credit, Closing Balance) totals are more than the actual amount. And Trial balance is mismatched with other reports. GL, PNL/BS are correct.

**Comment by ehuelsmann** [comment]
Having looked at the code, I know *why* they're different; just no idea what would be a good way to resolve it. As to the reason:

The balance sheet and PNL *include* year-end transactions whereas the trial balance excludes all year-end transactions.

**Comment by aungzwin10** [comment]
FYI, I've never done the year-end process to that db. So the yearend table and account check point table is empty.

**Comment by aungzwin10** [comment]
<img width="551" alt="Screen Shot 2022-03-09 at 1 45 26 PM" src="https://user-images.githubusercontent.com/31498748/157391553-e2685c54-9c77-4742-9ef2-3c78ae403b94.png">
<img width="1198" alt="Screen Shot 2022-03-09 at 1 48 46 PM" src="https://user-images.githubusercontent.com/31498748/157391895-029e4936-89b5-44cd-86e5-d7876dc00f3b.png">
<img width="710" alt="Screen Shot 2022-03-09 at 1 53 33 PM" src="https://user-images.githubusercontent.com/31498748/157392484-928a88fc-80da-475e-9ad8-ffb636127621.png">
