### ISSUE TITLE
SysVInit script for debian/ubuntu host servers

### ISSUE THREAD

**Issue by hesco** [ledgersmb/LedgerSMB#6455]
As a systems administrator responsible for installing LedgerSMB on an ubuntu or debian server, I want a version of a SysVInit script suitable for my OS available in the code base, so I do not have to craft one on my own.

**Comment by hesco** [comment]
Ready for a code review:  

https://github.com/hesco/LedgerSMB/blob/feature_request/issue_6455--sysvinit-script-for-debian/doc/conf/sysvinit/starman.debian 

I found a template for this purpose, reviewed that code and found it suitable for this purpose, then edited three lines, mostly drawn from the rh-centos version, reviewing the error logs and getting one question answered by @ehuelsmann in the chat.  

At this point the failures seem related to a missing configuration file, and I am turning my attention in that direction.  After I get this successfully sustaining the service with a working configuration, I will offer a pull request.

**Comment by ehuelsmann** [comment]
@hesco the script looks good! I've taken the liberty to create a pull request and merge that into the master branch.

**Comment by ehuelsmann** [comment]
Please let me know if you object, then I'll reverse.

**Comment by hesco** [comment]
No problem, I have left a handful of loose threads hanging out there as
I try to complete a happy path deployment.  I am still struggling with
(have been distracted by other priorities from focusing on) configuring
an apache2 proxy that works.  But that init script has seen sufficient 
tests already that I am fairly confident in it by now.  My starman
workers have been running now (with no load) for five days in my
development environment.  If I run into any additional issues once I
see the service in a remote browser, I will send through another pull
request to patch what I have offered so far.  

-- Hugh Esco 
912-571-1833 (cell, sms) 

On Sat, 26 Mar 2022 13:17:28 -0700
Erik Huelsmann ***@***.***> wrote:

> @hesco the script looks good! I've taken the liberty to create a pull request and merge that into the master branch.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/ledgersmb/LedgerSMB/issues/6455#issuecomment-1079767606
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>


-- 
Hugh Esco ***@***.***>
