### ISSUE TITLE
Excel Export: write large data into XLSX file

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6483]
### Version

Latest released version

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

I am facing memory run out problem and starman unexpectedly stop when exporting large data to excel.
According to the cpan documentation, Excel::Writer::XLSX is slow when writing a large data.
https://metacpan.org/pod/Excel::Writer::XLSX#SPEED-AND-MEMORY-USAGE

Excel can write only `1,048,576` rows in a sheet. So one other problem is: when the data rows from db exceed the excel row limit, it stops writing the exceed row.
https://metacpan.org/pod/Excel::Writer::XLSX#LIMITATIONS

### What should have happened?

- [x] Use `$workbook->set_optimization();` as documentation stated?

- [ ] Need to write the data in a new sheet if the row count 1 million.

I found an example of how to use Excel::Writer::XLSX to write large data in XLSX file. Please see the link below
https://github.com/AarthiRT/Excel_Writer_XLSX/blob/master/Write_largeData_XLSX.pl

**Comment by ehuelsmann** [comment]
@aungzwin10, I'll agree to the first action. But it sounds like the user is doing something (outside the application) which the application should be doing when you're exporting more than 1 million rows to Excel. Maybe it's better to discuss what is the use-case that's not serviced well enough?

**Comment by ehuelsmann** [comment]
There were other attempts to reduce memory use when generating output to file. However, none of those seemed to truly lower memory use enough to stop the OOM killer from killing the template-expanding process. Don't know what more to do here...
