### ISSUE TITLE
Partial disposal create a new fixed asset with the disposed percent

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6491]
### Version

1.9.12

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Partial disposal of the asset create a new asset with the disposed percentage.

### What should have happened?

 It should create the asset with the remaining percentage.

let's take a look at simple example
Fixed asset purchase value is 50 USD.
if partially disposed by 10%, the disposed amount will be 5 USD.
Then the new asset should create with remaining 90%, the amount of 45 USD?

**Comment by ehuelsmann** [comment]
Yes, the new asset should be created with the remaining amount. Not the disposed amount.

**Comment by ehuelsmann** [comment]
To be honest, i think there are more problems with partial disposal: i think it will not register the depreciation before the creation of the copied asset correctly, meaning that the depreciation will be posted a second time during the first depreciation run.
