### ISSUE TITLE
Year-closing complains about unapproved transactions, but none visible in UI

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#652]
Going through my database, I found why: There's a transaction which has status "approved" 'f':

```
select * from ap where transdate <= '2015-12-31'::date and not approved;
```

Returns:

```
 id  | invnumber | transdate  | entity_id | taxincluded | amount | netamount | paid | datepaid |  duedate   | invoice | ordnumber | curr | notes | person_id | till | quonumber | intnotes | department_id | shipvia | language_code | ponumber | shippingpoint | on_hold | approved | reverse | terms | description | force_closed | entity_credit_account |   crdate
-----+-----------+------------+-----------+-------------+--------+-----------+------+----------+------------+---------+-----------+------+-------+-----------+------+-----------+----------+---------------+---------+---------------+----------+---------------+---------+----------+---------+-------+-------------+--------------+-----------------------+------------
  66 | 6         | 2013-08-28 |           | f           |  83.57 |     69.07 | 0.00 |          | 2013-08-28 | f       |           | EUR  |       |         1 |      |           |          |             0 |         |               |          |               | f       | f        | f       |     0 |             |              |                    14 | 2013-08-28
```
Then, going to the vouchers table, it turns out the transaction is associated with a voucher:

```
select * from voucher where trans_id=66;
```

Returns:

```
 trans_id | batch_id | id | batch_class
----------+----------+----+-------------
       66 |       18 | 14 |           4
```

And then in the last step, it turns out that the batch is of class 4 as suggested by the previous result, and the batch is approved too:

```
select * from batch where id = 18;
```

returns:

```
 id | batch_class_id | control_code | description | default_date | approved_on | approved_by | created_by | locked_by | created_on
----+----------------+--------------+-------------+--------------+-------------+-------------+------------+-----------+------------
 18 |              4 | B-11150      | B-11150     | 2013-08-28   | 2013-10-06  |           1 |          1 |       380 | 2013-10-06
```

However, looking at the function [batch_post()](https://github.com/ledgersmb/LedgerSMB/blob/master/sql/modules/Voucher.sql#L373-405), the function doesn't update the AR/AP/GL tables for this type of batch.

How this transaction got into this type of batch, I have no idea.

**Comment by einhverfr** [comment]
I have no idea how this could have happened but it is another reason why payments need to be first class transactions long-run.

Here's the situation:

The AR record is a draft, not a voucher (you should look there as well).  If it isn't showing up there, that is a bug.

The voucher is for the payment against the ar record.

So if there are two possible bugs here:
1)  If you could pay an unapproved transaction with a payment, that is a bug (as appears to have happened here)
2)  If the transaction is not showing up under drafts, there is a bug there.

However, without current information I don't see how to track down either.

**Comment by einhverfr** [comment]
hmmm as I think about it, there is probably the second issue, so will solve that.

**Comment by einhverfr** [comment]
Looking at the code, this is not so trivial to make more robust.  I will close it for now but if you can track down a ccase where you can pay an unapproved transaction with the batch payment interface, we need to fix that.
