### ISSUE TITLE
Net Book Value Remaining Life for Whole Month Straight Line Method Calculation Wrong

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6563]
### Version

1.9.14

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Fixed Assets > Assets > Reports > Net book Value

Below screenshot is the net book value report.
The remaining life still remain as 59 although it is depreciated for a year. it should be 48 in months(4 years)
NOTE: the amount calculated amount and net book value are correctly calculated here.
<img width="1188" alt="Screen Shot 2022-05-31 at 10 53 59 AM" src="https://user-images.githubusercontent.com/31498748/171092437-6976536a-383c-4d1b-b2eb-c4d08f9566ef.png">

The asset item is setup as follow, `Usable life` is 60 months(5 years)
<img width="958" alt="Screen Shot 2022-05-31 at 11 18 47 AM" src="https://user-images.githubusercontent.com/31498748/171095628-16c3955a-019b-495e-8b18-38d87ac17845.png">

### What should have happened?

The net book value show the remaining life in the uniform unit(in years) only or if it need to show in the method default unit,
remaining life calculation need to be adjust for the "months" unit item.

https://github.com/ledgersmb/LedgerSMB/blob/afa30186ebe0e0eb486a8ed5ccd830fc274281fc/sql/modules/Assets.sql#L663-L666

**Comment by ehuelsmann** [comment]
The accounting values are correct; just not the values shown in the display.
