### ISSUE TITLE
Postgres 14 compatibility

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#6801]
### Version

1.10 but applies to 1.9 too.

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Fix usage of array handling building functions for migration of Accounts and Invoices,
Postgres 14 changed the data types of build-in array functions, namely `array_append` and `array_cat`

### What should have happened?

No errors in migration and invoices reporting

**Comment by ehuelsmann** [comment]
How does this problem show? I've been testing with Pg 14 for months now but didn't see any errors like that except the ones I fixed some time ago

**Comment by ylavoie** [comment]
Backups from Postgres versions before 14 were imposing types on `array_append` and `array_cat`. Restoring will produce errors of no consequence when trying to fix functions that are not existing in PG14.

**Comment by ylavoie** [comment]
No backup done before PG14 can be restored because of that change.

**Comment by ehuelsmann** [comment]
> No backup done before PG14 can be restored because of that change.

That's only true for backups made ook versions of LedgerSMB that were not Pg14 compatible.  We have Pg 14 compatible versions for 1.7 and up. What more should we do to close this issue?
