### ISSUE TITLE
1.10 - Manual Sales Tax cannot be added

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#6812]
### Version

1.10-beta3

### What browsers are you seeing the problem on?

Firefox

### What happened?

When adding an invoice for a taxable customer and part, when you click "Manual" to enter a tax amount and details manually, nothing happens.

### What should have happened?

A mini form should open allowing you to specify tax rate, basis, total, and source for the invoice.

**Comment by ehuelsmann** [comment]
Related to #6791

**Comment by ehuelsmann** [comment]
@freelock did you hit "Update" between selecting "Manual" and expecting the detail-entry to pop up?

**Comment by freelock** [comment]
Hitting update does make the detail entry show up...

**Comment by ehuelsmann** [comment]
I'm afraid that's the type of interaction we get from our server-rendered UI... :-(
