### ISSUE TITLE
Lack of configure/make/make install makes packaging harder than it should be

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#6877]
### Version

1.9 and 1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Normally packaging software on Gentoo and many other distributions takes advantage of automation already present in standard toolchains.  The lack of such a toolchain in LedgerSMB makes packaging a lot harder.   I have not worked with Debian or RedHat packages recently enough to check this but I would expect this would make packaigng easier for these formats too.

The toolchain should not be responsible for dependencies, but should install the software with a default configuration to a specified destination directory, and set up relevant service or openrc files etc.

I recognize this effort is probably not a high priority here so I am assigning it to myself.  However, I would like this to have an issue to gather feedback on build systems.  I know that the standard (autotools/make) could be used here, but PostgreSQL is moving to Meson and I would like to evaluate that as well before making a decision.  

### What should have happened?

Packaging should be able to take advantage of existing installation logic, rather than having to reinvent large portions fo reverything whether done in Docker, ebuild, rpm, or debian packages.

## Options under consideration

- autoconf/make/makeinstall
- meson
- cpanification

## autoconf/make/make install

the major advantage here is that it is widely supported by just about every packaging system out there, and there are common expectations regarding how it performs.  The disadvantage is that getting much of this right for a basic install  and package building framework may take some time.  It is also complex to work with in places.

## meson

Meson is a modern build system with support for many languages already built in.  Perl is not on that list but the overall structure provides what would be needed.

## cpanification 

This option has the advantage of being very well supported by all systems that expect to use Perl anywhere on the system.  On the other hand, it is intended to be used to manage Perl enfironments, not whole applications which may be run in parallel via different versions.  For this reason I am not necessarily inclined to use this.

**Comment by ehuelsmann** [comment]
I'm not sure this makes sense for our project: the number of dependencies is very high (also due to JavaScript). Compiling the dependencies into runnable target is part of the release process and CI, taken off of the user's hands deliberately die to complexity.

Also, the project never decided or even supported running in a way where different parts are installed base on the Unix filesystem standard (meaning that Ui/ should be installed somewhere different from lib/ and old/lib gets installed in the same directory as lib/)...

**Comment by ehuelsmann** [comment]
I guess my question is: which problem did you run into concretely? And could the project have made any decisions to make your work as a packager easier, concretely?
