### ISSUE TITLE
AP/AR Vouchers mishandles UTF8 characters

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#6894]
### Version

master but applies to lower versions too

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

![Screenshot_20221022_213441](https://user-images.githubusercontent.com/1445864/197369020-fe640ee0-8d98-4bce-8fcd-9036224beb80.png)

### What should have happened?

Adding a transaction through `AP/AR Transaction` works properly.
Caliing the same action through `AP/AR Voucher ­­> AP/AR Transaction` doesn't display accented characters properly.

**Comment by ehuelsmann** [comment]
@ylavoie does it matter it this is on the initial presentation of the screen or later ones?

**Comment by ylavoie** [comment]
Selecting a Customer/Vendor and clicking `Update` shows the proper characters.
