### ISSUE TITLE
AP/AR items in vouchers cannot be saved multiple times

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#6895]
### Version

Master but applies to lower versions too

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Adding a new AP/AR Transaction, filling data and clicking `Save` multiple time results in failure with `'ERROR: Invalid transaction id 6 CONTEXTE : PL/pgSQL function draft_delete(integer) line 38 at RAISE: SELECT * FROM "xyz"."draft_delete"(?) at /usr/local/share/perl/5.32.1/PGObject.pm line 382. '`

Editing an already saved Transaction and trying to Save will give the same result.

### What should have happened?

One should be allowed to Save multiple times or Save an edited version of a previous one.

**Comment by ehuelsmann** [comment]
Does not apply to transactions alone. Problem includes invoices too.
