### ISSUE TITLE
Loading... pop up stays visible forever, unless selected.

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6906]
### Version

SMB 1.11.0-dev

### What browsers are you seeing the problem on?

Firefox

### What happened?

When I go into the Order Entry -> Sales Order, or Quotation -> Quotation views I get a "Loading ..." pop up that never goes away. In this example the pop ups are visible from both navigations.

<img width="743" alt="Screen Shot 2022-10-27 at 7 32 08 AM" src="https://user-images.githubusercontent.com/1809796/198285530-ffe94438-18ff-440e-9796-9e525ebd2df2.png">

Both will go away when clicking on them, but they do not go away on their own.

There is no database activity while these are shown.

### What should have happened?

When loading is complete, the pop up should have gone away by automatically.

**Comment by ehuelsmann** [comment]
@neilt thanks for this report! did you try rebuilding the javascript library? I'm not running into this problem on 1.11.0-dev as of yesterday.

**Comment by neilt** [comment]
master as of 2d8fa393979be61f9e7a659dec740d8a4a72dbd9
Closed browser, did `make js`, logged back in, and still have problem.  Is there something else I need to do?
Order Entry -> Sales Order.
