### ISSUE TITLE
Mixed Widgets on Order Entry -> Sales Order

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6911]
### Version

LedgerSMB 1.11.0-dev, master as of 2d8fa393979be61f9e7a659dec740d8a4a72dbd9

### What browsers are you seeing the problem on?

Firefox

### What happened?

Order Entry -> Sales Order has mixed widgets on the screen.  `System Defaults` has the `Tundra` widget themes selected. 

See Example below where the `Group` widget is different between item 1 and item 2, and also the `Customer`, `Cost Code` and `Project` widgets are different between item 2 and item 3.  Once the widgets change style they seem to stay that way further down the page.

The `Update` and `Save` buttons do not appear to work. Neither updates the `Extended Price`.

<img width="1960" alt="Screen Shot 2022-10-28 at 9 13 52 AM" src="https://user-images.githubusercontent.com/1809796/198638643-14fb0586-183e-4a60-8352-b667144bea55.png">

### What should have happened?

All widgets should be the same.

**Comment by ehuelsmann** [comment]
I think this has to do with "Reporting Units", but wasn't able to reproduce myself. Can you post a screenshot of the page showing under "System > Reporting Units" ?

**Comment by neilt** [comment]
<img width="955" alt="Screen Shot 2022-10-28 at 1 12 38 PM" src="https://user-images.githubusercontent.com/1809796/198704505-76d87abe-4591-470e-b9cb-520f7542c661.png">

**Comment by neilt** [comment]
This issue uses the Demo15 data loaded into pg14.5.
