### ISSUE TITLE
LSMB 1.10.5 Postgres 15.1 Cannot change password.

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6978]
### Version

1.10.5, pg 15.1.

### What browsers are you seeing the problem on?

Firefox

### What happened?

Preferences won't let me change the password.

1. Create new docker install of LedgerSMB using the attached compose file.
[docker-compose.yml.zip](https://github.com/ledgersmb/LedgerSMB/files/10180495/docker-compose.yml.zip)

2. Use setup.pl to initialize a database.
3. Login using login.pl
4. Change defaults to allow 389 day password duration.
5. Change defaults to allow 2 days session timeout.
6. Save defaults
7. Goto Preferences -> password
8. Start entering password.
9. Get red line with no error text and no errors in lsmb log.
<img width="584" alt="RedBar" src="https://user-images.githubusercontent.com/1809796/206310402-57ba49a6-db53-4a98-bc16-d6e93786d1fd.png">

10. Finish entering old and new passwords, which are the same.
11. Hit 'change password' button.
12. Get the following error in lamb logs.

```
2022/12/07 22:16:22 Can't locate object method "error" via package "LedgerSMB::DBObject::User" at old/lib/LedgerSMB/DBObject/User.pm line 71.\n
Req:C851D20E767C11ED9C52BF0BCD85045E ::ffff:172.16.1.10 - - [07/Dec/2022:22:16:22 +0000] "POST /user.pl HTTP/1.1" 500 260 "http://172.16.1.222:49762/erp.pl?action=root" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
```
14. Not able to change the password to get the new duration and timeout active.
15. The following error shows:

<img width="621" alt="ErrorChangingPassword" src="https://user-images.githubusercontent.com/1809796/206311544-c2bc8bd5-79c2-40b2-ac06-337e72c4e30e.png">

### What should have happened?

Password should have changed.

**Comment by neilt** [comment]
No errors were shown in the Postgres logs.

**Comment by neilt** [comment]
I don't think this is related but when I logged in the following appeared in the lsmb logs:

```
Req:25F7F746767111ED9C52BF0BCD85045E ::ffff:172.16.1.10 - - [07/Dec/2022:20:53:05 +0000] "POST /login.pl?action=authenticate&company=pci2022 HTTP/1.1" 200 35 "http://172.16.1.222:49762/login.pl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
Use of uninitialized value in string ne at /usr/share/perl5/Starman/Server.pm
	line 304, <$io> line 1 (#1)
Use of uninitialized value in string ne at /usr/share/perl5/Starman/Server.pm
	line 347, <$io> line 1 (#1)
```

**Comment by christian-eriksson** [comment]
I noticed this problem as well when experimenting with the docker images. The server responds with status `500` and the following error: 

> Error!
>
>Can't locate object method "error" via package "LedgerSMB::DBObject::User" at old/lib/LedgerSMB/DBObject/User.pm line 71.

I did a `git bisect` search and found that `f7e7c5f6e9d85a9d637e05f9b4d789841b5450fe is the first bad commit`.  These were the changed files:

```
    Migrate the database parameters to dependency injection

 doc/conf/ledgersmb.yaml                          |  3 +
 lib/LedgerSMB.pm                                 |  2 +-
 lib/LedgerSMB/Database/Factory.pm                | 70 ++++++++++++++++++++++++
 lib/LedgerSMB/Database/Upgrade.pm                |  2 +-
 lib/LedgerSMB/Middleware/Authenticate/Company.pm | 10 +---
 lib/LedgerSMB/PSGI.pm                            |  8 +--
 lib/LedgerSMB/Scripts/setup.pm                   | 13 ++---
 lib/LedgerSMB/Sysconfig.pm                       | 38 +++++--------
 t/01-load.t                                      |  3 +-
 9 files changed, 101 insertions(+), 48 deletions(-)
 create mode 100644 lib/LedgerSMB/Database/Factory.pm
```
Unfortunately I don't see the referenced file in the list. However, I'm not a Perl developer so I'm not sure what to look for, but maybe it'll be of some help :)

**Comment by christian-eriksson** [comment]
Not a problem I figured I'd try to help out if I could. I'll try to detail what I did (not sure how detailed you want/need it so I'll try to be thorough):

1. Used trail and error to figure out that the issue was somewhere between version `1.10.0` and `1.9.19`, to have a starting point for the search.
   - I used the official `docker-compose.yml` from:
        ```shell
        wget https://raw.githubusercontent.com/ledgersmb/ledgersmb-docker/1.10/docker-compose.yml
        ```
   - and only changed the image version for `lsmb` between `1.10.5`, `1.10.4`, ..., `1.9.19`:
        ```yaml
         lsmb:
            depends_on:
              - postgres
            image: ghcr.io/ledgersmb/ledgersmb:<SELECTED_VERSION>
        ```
2. Clone the LedgerSMB repo to `~/temp/LedgerSMB`
3. Clone the docker repo to `~/temp/ledgersmb-docker` 
   - As I have no idea how to setup a perl dev environment, I had to run it through docker :see_no_evil:
   - I had tag 1.10 checked out for the full search
   - pointed the `docker-compose.yml` file to the local `Dockerfile`, with the following changes:
        ```diff
        diff --git a/docker-compose.yml b/docker-compose.yml
        index aee9a20..df37c6d 100644
        --- a/docker-compose.yml
        +++ b/docker-compose.yml
        @@ -31,7 +31,10 @@ services:
           lsmb:
             depends_on:
               - postgres
        -    image: ghcr.io/ledgersmb/ledgersmb:1.10
        +    image: chris-test/ledgersmb:latest
        +    build:
        +      context: ./
        +      dockerfile: Dockerfile
             networks:
               - internal
               - default
        ```
    - pointed the local `Dockerfile` to use a locally built tar file:
        ```diff
        diff --git a/Dockerfile b/Dockerfile
        index ce1c1be..ebe5e61 100644
        --- a/Dockerfile
        +++ b/Dockerfile
        @@ -16,8 +16,9 @@ RUN set -x ; \
           DEBIAN_FRONTEND="noninteractive" apt-get -y install dh-make-perl libmodule-cpanfile-perl git wget && \
           apt-file update
        
        +COPY ledgersmb.tar.gz /tmp/ledgersmb-$LSMB_VERSION.tar.gz
        +
         RUN set -x ; \
        -  wget --quiet -O /tmp/ledgersmb-$LSMB_VERSION.tar.gz "$ARTIFACT_LOCATION" && \
           tar -xzf /tmp/ledgersmb-$LSMB_VERSION.tar.gz --directory /srv && \
           rm -f /tmp/ledgersmb-$LSMB_VERSION.tar.gz && \
           cd /srv/ledgersmb && \
        @@ -90,9 +91,11 @@ RUN set -x ; \
           (wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -) && \
           DEBIAN_FRONTEND="noninteractive" apt-get -y update && \
           DEBIAN_FRONTEND="noninteractive" apt-get -y install postgresql-client && \
        -  DEBIAN_FRONTEND="noninteractive" apt-get -q -y install git cpanminus make gcc libperl-dev && \
        -  wget --quiet -O /tmp/ledgersmb-$LSMB_VERSION.tar.gz "$ARTIFACT_LOCATION" && \
        -  tar -xzf /tmp/ledgersmb-$LSMB_VERSION.tar.gz --directory /srv && \
        +  DEBIAN_FRONTEND="noninteractive" apt-get -q -y install git cpanminus make gcc libperl-dev
        +
        +COPY ledgersmb.tar.gz /tmp/ledgersmb-$LSMB_VERSION.tar.gz
        +
        +RUN  tar -xzf /tmp/ledgersmb-$LSMB_VERSION.tar.gz --directory /srv && \
           rm -f /tmp/ledgersmb-$LSMB_VERSION.tar.gz && \
           cpanm --notest \
             --with-feature=starman \
        ```
4. Create `run.sh` in `~/temp/ledgersmb-docker`, to reset and start the application with the latest build:
    ```shell
    #!/usr/bin/sh
    set -e
    
    docker compose down -v --remove-orphans #RESETS YOUR DATABASE, BE CAREFUL
    [ -f ledgersmb.tar.gz ] && rm ledgersmb.tar.gz
    cp ~/temp/LedgerSMB/.dist/ledgersmb.tar.gz ./
    POSTGRES_PASSWORD=admin docker compose up --build
    ```
5. Create `build.sh` in `~/temp/LedgerSMB`
    ```shell
    #!/usr/bin/sh
    set -e

    current_dir=$(pwd)
    script_dir=$(dirname $(realpath $0))
    [ -d $script_dir/node_modules ] && rm -rf $script_dir/node_modules
    [ -d $script_dir/.dist ] && rm -rf $script_dir/.dist
    sed -i s%DIST_DIR=/tmp%DIST_DIR=$script_dir/.dist% $script_dir/Makefile
    sed -i s%ledgersmb-\$\(DIST_VER\).tar.gz%ledgersmb.tar.gz% $script_dir/Makefile
    make dist
    ```
6. Started the `git bisect` in `~/temp/LedgerSMB` with:
    ```shell
    git checkout 1.10.0
    git bisect start
    git bisect bad
    git checkout 1.9.19
    git bisect good
    ```
7. For each cycle I:
    1. With two terminals, run `./build.sh` in  `~/temp/LedgerSMB` in one and `./run.sh` in `~/temp/ledgersmb-docker` in the other.
    2. run the setup at `http://localhost:5762/setup.pl`, using:
        ```yaml
        DB admin login: postgres
        Password: admin
        Database: test
        ```
       The rest of the settings where:
        ```yaml
        Country: Sweden
        Chart of account: General
        Template: demo
        Username: admin
        Password: admin
        Assign Permissions: Full permissions
        # Dummy values for the rest
        ```
    3. go to the login screen by clicking "Start using LedgerSMB"
    4. login to `test` with `admin:admin`
    5. Navigate to preferences and try to change password from `admin` to `test`
    6. Restore the changes that the build script does in `~/temp/LedgerSMB` with `git restore .` 
    7. If I got the error in `7.v.` mark the commit with `git bisect bad` otherwise mark it with `git bisect good`
    8. Repeat from `7.i.`
8. sometimes I had to do small fixes to get the project to build but it was mostly (i think only) either of the following:
    - `npm install --save-dev @babel/core`
    - `sed -i s%docs/database%doc/database%g Makefile`

I think that was it, feel free to ask if there seems to be something missing :)
