### ISSUE TITLE
UI Oddity, Pop Up Calendar has `M12` instead of December.

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#7005]
### Version

LSMB 1.10.6

### What browsers are you seeing the problem on?

Safari (MacOS X)

### What happened?

Try to create a Cash -> Vouchers -> Payments batch and get M12 where the month should be. See the following:

<img width="659" alt="Screen Shot 2022-12-12 at 10 02 17 AM" src="https://user-images.githubusercontent.com/1809796/207094484-20b3e326-bbde-41da-9384-786ad6c103e7.png">

### What should have happened?

Should have seen 'December' in the calendar.

**Comment by ehuelsmann** [comment]
Do you have any specific date settings either on the OS or in the preferences of the application?

**Comment by neilt** [comment]
<img width="570" alt="Screen Shot 2022-12-23 at 7 09 46 AM" src="https://user-images.githubusercontent.com/1809796/209341666-707f0d02-d630-4c76-90eb-28efd9550095.png">

**Comment by neilt** [comment]
Don't recall setting any date formats.  The server time zone is set to US CST but no format changes. The server is Ubuntu 22.04.1 LTS, newly installed in the last few weeks.

**Comment by ehuelsmann** [comment]
The reproduction recipe is as follows:

1. Create a new company with a new user
2. Go to preferences and set the printer to Screen, the language to "American English" and the number format to "1,000.00".
3. **Refresh the page using F5**
4. Go to *any* page with a date entry box and you'll see "M12" for December

**Comment by ehuelsmann** [comment]
The source of the "M**" values is "gregorian.js" in `dojo/cldr/nls/`. The `en` variant has the complete names of the months.

`dojoConfig.locale` gets initialized to `en_US`; I believe that this should have been `en-us` from Dojo's docs, but changing the value to 'en-us' doesn't resolve this problem. By the way, please note that Dojo *has* an "en" locale, but *does not* have an "en-us" locale, which leads me to believe it fails to load the "en" locale when it fails to find the "en-us" locale...

**Comment by neilt** [comment]
> I'm thinking this has to be a "won't fix". @ylavoie what do you think?

Then is there something I can do to make it work correctly?

**Comment by ehuelsmann** [comment]
> Then is there something I can do to make it work correctly?

I'm not sure: this problem seems to come from Dojo. We need to figure out if we need to submit a fix to Dojo, or that we can simply fork a specific Dojo class in order to work around it. It's a JavaScript library thing. Not our code base (which is why I was copying in Yves; he's been great with figuring out these JS dependencies!)

**Comment by aungzwin10** [comment]
> Then is there something I can do to make it work correctly?

@neilt for the  time being, you can change the language to "English" in the Preferences to show the full name of month.
This is the only way to make it work, I think.
<img width="395" alt="Screenshot 2023-01-27 at 11 52 36 AM" src="https://user-images.githubusercontent.com/31498748/215015425-e6f807e7-50ca-45a7-a405-07d1990e3d9e.png">

**Comment by neilt** [comment]
@aungzwin10 Yes that worked after I logged out, closed the browser window and logged back it.

Thanks.

**Comment by ehuelsmann** [comment]
Issue filed upstream.
