### ISSUE TITLE
Add created documents to the browser's back-button history

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#706]

**Comment by ehuelsmann** [comment]
My thoughts currently are that the solution here lies in http://dojotoolkit.org/documentation/tutorials/1.10/hash/index.html

**Comment by ehuelsmann** [comment]
The 'GET' half of this issue has been addressed. The part that needs design is the "POST" part.

My current thoughts: any page update that doesn't create a new entity doesn't need to be saved in the browser's history (i.e. "isn't a rewind point"). Ideally, when a POST request creates a new entity ("Save" or "Save as"), the back button history should point to the created entity (and not the intermediate state that was last presented in the browser).

One option would be to make "entity creating POST requests" return a "201 Created"+Location response instead of a "200 Ok". POST requests can then be added to the history if (and only if) the response is a 201+Location; the hash added to the browser history will be the relative URL provided in the Location header.

**Comment by ehuelsmann** [comment]
Moving this from 'blocking' to 'enhancement' because the posted documents aren't in the browser history in 1.4 either.

**Comment by freelock** [comment]
+1 POST/PUT/other non-GET requests should not be in browser history, should redirect to GET. Even in the "normal" CGI this is an improvement, avoid messages about "do you want to repost form contents" which really break normal browser history too.

**Comment by ehuelsmann** [comment]
@freelock We probably agree here, but the problem that I'm looking at is that the response to the POST request *doesn't* contain the POST-created document, but a different document entirely; this may be a search result, customer screen or other callback.

It's not clear to me that e.g. the ```303 See Other``` response would be allowed to redirect to an *unrelated* resource.

**Comment by freelock** [comment]
Well, I think it depends upon the nature of the POST request. If it's POSTing a new data object, then I think the response should redirect to a GET of that newly created object. But if it's more of an RPC-type of call, then the redirect result may vary depending on what is appropriate (but should be well-documented).

Cheers,
John
