### ISSUE TITLE
UX Improvement - `Logging in...` text cover by `Login` button

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#7109]
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

The text `Logging in...` in the Login page cover by the `Login` button as shown below.
<img width="918" alt="overflow" src="https://user-images.githubusercontent.com/31498748/214479082-42e2b536-2ca7-4d47-95d0-cf03cb95d933.png">

### What should have happened?

It should not cover each other for better UX.

**Comment by ehuelsmann** [comment]
Agreed with the general statement (that it shouldn't overlap). However, I'm not seeing this behaviour: locally, my version number does not wrap, which doesn't push the section with the input fields and the button down over the "Logging in..." text.

**Comment by aungzwin10** [comment]
The master branch doesn't wrap the version number. But the 1.10 branch did. Could you please test by running `make dojo` on the 1.10 branch?

I am tested  with 3 browsers: Chrome, Firefox and Safari. All behave the same on 1.10

**Comment by ehuelsmann** [comment]
On FF on linux (Ubuntu), it looks like this on my system:

![2023-01-26_08-43](https://user-images.githubusercontent.com/2326559/214782306-4493edde-5d55-4cd6-8317-e548d9631a42.png)

**Comment by ehuelsmann** [comment]
Really wondering what could be the difference here and how we can find out.

Looking at the text though, it's especially the "-dev" suffix which causes this. On a normal deployment, this won't happen. So it's mostly a development system problem. (Which I'd rate as much less bad than on an official release)

**Comment by ehuelsmann** [comment]
Solved by the new login UI.
