### ISSUE TITLE
Labels and Inputs are mismatched in Contact > Addresses

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#7110]
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Because of moving to grid system from table layout, the label and input are not matching. As shown below.
<img width="676" alt="Screenshot 2023-01-25 at 10 54 15 AM" src="https://user-images.githubusercontent.com/31498748/214479543-6996e0ea-9b8f-4ab2-948c-15a8a70f87d7.png">

### What should have happened?

It should be like below.
<img width="268" alt="Screenshot 2023-01-25 at 10 59 32 AM" src="https://user-images.githubusercontent.com/31498748/214480179-3ecabd05-eb2a-4272-8f46-e227c5d016c0.png">

**Comment by ehuelsmann** [comment]
This works for me. I think we should revert, because before, this merge it looked like:

**Comment by aungzwin10** [comment]
@ehuelsmann Sorry for the alignment. I didn't notice about it when I was working on.
The reason why it works for you is that, you have credit account(s) for that entity.
The screenshot I took is in the state entity doesn't have credit account(s). So the issue happened only when entity doesn't have any credit account(s).

I will PR the changes.

**Comment by ehuelsmann** [comment]
Ok. Yes, thanks for the explanation.

Now fixed in #7125.
