### ISSUE TITLE
Address line 3 for entity doesn't save

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#7127]
Why the `entity__location_save` function doesn't accept line_three while the internal function `_entity_location_save` accept?
https://github.com/ledgersmb/LedgerSMB/blob/73a89dcff86345db8d0ca342306d5a4ea8f6c313/sql/modules/Company.sql#L1161-L1174
https://github.com/ledgersmb/LedgerSMB/blob/73a89dcff86345db8d0ca342306d5a4ea8f6c313/sql/modules/Company.sql#L1184-L1215

Saving address line 3 with empty string is intended?

**Comment by ehuelsmann** [comment]
> Saving address line 3 with empty string is intended?

No, imo that's a bug.
