### ISSUE TITLE
Mark input mandatory for import screen(all types)

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#7159]
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Import can be saved without any inputs.
<img width="1440" alt="Screenshot 2023-01-31 at 2 42 34 PM" src="https://user-images.githubusercontent.com/31498748/215703293-36120eb0-21ce-48e0-bd43-de3b2261ae92.png">

### What should have happened?

Save should not submit if transaction fields are empty.

**Comment by aungzwin10** [comment]
@ehuelsmann
https://github.com/ledgersmb/LedgerSMB/blob/1d89e77c51e8edd800a049c03a9409b22624df89/UI/src/components/ImportCSV-Base.vue#L20-L36
Although fields are marked as required, the `Save` button still continue the action. I believe, the `required` has no affect on the custom click action.

**Comment by ehuelsmann** [comment]
The problem here is that in regular Dojo, on submit(), the dijit/form/Form's `validate()` method is called and - when not successfull - submission is blocked. Here, this method isn't called.

**Comment by ehuelsmann** [comment]
The question here though is if we shouldn't be using one or more state machines to drive the UI state.

**Comment by ehuelsmann** [comment]
We should probably look at #7199 for an example on how to deal with required values and other validations to solve this issue.
