### ISSUE TITLE
Error message is ugly in Vue Import screen

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#7161]
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

<img width="1203" alt="Screenshot 2023-01-31 at 2 57 58 PM" src="https://user-images.githubusercontent.com/31498748/215707914-7ba439bd-f56a-46c0-bf59-7561f57733a4.png">
The error message in Vue import screen is displaying with HTML tag.

### What should have happened?

It should show only error message without HTML or show with dialog box like  1.9 version does.

**Comment by ehuelsmann** [comment]
What should happen here is that the return value of the error is encapsulated in a json blob instead of an html document; the latter is injected directly in the upload page.
