### ISSUE TITLE
Javascript are not working when loading the same page more than one time

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#7162]
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

When user load the same page more than one time, javascript are not working anymore. This happened only for server side rendering page.
Please take a look at below screen recording.
https://user-images.githubusercontent.com/31498748/215709540-dd2f884e-eac8-44a8-a38b-ce1126b1f496.mov

Step to reproduce
1. Click on Contact > Search menu.
2. Date picker/Drop down/Button are working.
3. Click the same menu again(Contact > Search).
4. Date picker/drop down/button are not working anymore.
5. Click another menu(e.g. Contact > Add Contact). all js are work again.

PS. Some time CSS are also lost.

Please see screen recording  below.
https://user-images.githubusercontent.com/31498748/215711294-1b65ee23-4e7d-44ea-8f2b-bef062d6d0ac.mov

### What should have happened?

it should not happen.

**Comment by ehuelsmann** [comment]
Yes. Thuis issue in 1.10 is known to me. I tried to do something about it in 1.11/master. I don't think I succeeded completely yet.....

**Comment by ehuelsmann** [comment]
Solved for 1.11
