### ISSUE TITLE
Installation: Not possible to run db tests with remote database

### ISSUE THREAD

**Issue by GoodMirek** [ledgersmb/LedgerSMB#726]
While installing LedgerSMB-1.4 with remote database, it is not possible to run tests against that database, even though remote database connection is properly configured in ledgersmb.conf.
It always tries to connect to localhost.

**Comment by einhverfr** [comment]
Thanks!  I will be looking into this today.  The issue sounds like the psql tests are connecting to localhost.  Note you can run the sql/modules/test/*.sql scripts (do not run Base.sql though!) direcltly tin psql for a nice test report.  Thats not perfect but it is a workaround.

**Comment by einhverfr** [comment]
Ok, it looks like the configuration is not being pulled properly from the config file.  I hope to have a fix in for this today.

**Comment by GoodMirek** [comment]
Thanks for the answers! I have found another workaround. I set PGHOST and PGPORT environment variables.
Being inspired by travis-ci job I ran from bash:
PGHOST=ledgerdb.blabla.us-east-1.rds.amazonaws.com PGPORT=5432 PGUSER=postgres PGPASSWORD=password LSMB_TEST_DB=1 LSMB_NEW_DB=lsmb15installtest make test

It seems different tests are using different authentication methods, what makes proper setup a bit tricky. I found the whole installation process quite difficult, with many steps missing from any documentation. I will do my best to contribute in order to improve.

**Comment by ehuelsmann** [comment]
By the sound of it, we need to lay out some clear ideas of what we want from our test suite.

**Comment by einhverfr** [comment]
Minor enhancement (doable in a stable branch) because it doesn't stability issues.

**Comment by einhverfr** [comment]
Based on recent progress on the BDD test enhancements, it looks like this is pretty clearly resolved in master.  I think corner cases in this area should get their own reports now.
