### ISSUE TITLE
Enhancement: Auto generated documentation

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#7293]
Most of my internal projects end up generating a pdf overview document.  One of the things that I am not really fond of is documentation  duplication.  You know something is documented in a UI field, in a database column, table, or function comment, in a source file, in a help file, and also in the pdf. The text really says the same thing but appears in multiple places.

The obvious problem with this is that the documentation is always out of sync.  Nobody goes around to all of these places to make sure it is in sync.

I was wondering if the project would accept the following changes to LSMB and LSMB Book:

1. Move the current LSMB Book into the main LSMB repository. An old version is already there. I don’t really understand the separate repository.

2.  A new perl script that is able to retrieve selective table, function, and column comments from a running database and create a series of tex files.  During retrieval, the comments would be modified to add tex stuff like index, glossary, etc. No latex need be in the database comments.

3. If enabled, then when the LSMB server starts for the first time on a new version the server would, in a background thread, use the script described above to extract the current stuff from the database into tex files, then generate a new pdf.  The enabling is required because you may not want to run the doc generation when running tests.  This would probably be a shell script and there are multiple ways it could be run.

4. The LSMB Book main tex files would selectively include the generated tex files were needed to reduce duplication. Information in the LSMB Book, where accurate, might be moved into appropriate comments in the database (without any latex markup).

In my projects I also scan all of the source code files for embedded documentation that should be included in the pdf.  Oddly, enough I use a perl script. It scans all source code files for the text between `*latex` and `latex*` in the files native block comments.  This way programmer only comments destined for the pdf are included.  

While the text can be latex format, in most cases I use plain text, not latex.  This means developers do not have to understand latex to keep the comments up to date. As with database comment scanning any needed latex commands are added and saved in a unique tex file and this tex file is then added as an include to the book.

Obviously the change would not happen overnight, but would put in place consistent infrastructure for project documentation at the source.

Any thoughts?

**Comment by ehuelsmann** [comment]
Hi!

Let me start by completely agreeing that duplicate documentation is horrendous. As for the separate book repository and the manual in the main repository: these don't share a common ancestry. The book in the separate repository was drafted from scratch without looking much at what was written in the book in the main repo. Reason is that there were already big differences between the then-current code base and the in-repo book/manual, which is why I decided to start from a clean slate. The main reason to have the book in a separate repo is because that way, the book can have its own maintenance and release timelines -- much like Debian prefers the code for packages to be outside of the source repositories.

I appreciate your goals with the generated documentation have a different purpose, but: did you notice that there's a lot of generated documentation already? See:

1. https://docs.ledgersmb.org/perl-api/
2. https://docs.ledgersmb.org/openapi/
3. https://docs.ledgersmb.org/database-schema/ (accidentally left empty; I'll be uploading in a sec)

So: I like the idea of reducing documentation duplication. I think we should get a long way on developer documentation, too. However, I have no clear understanding of how we should create documentation users would be looking for ("how do I 'undo' this invoice?") in the source code we currently have at hand. How do you deal with that in your projects?

Regards,

Erik.

**Comment by neilt** [comment]
All good points.

1. None of what I am talking about overlaps with your 3 numbered examples.  Your examples are complete documents that are way too detailed for a user, when the user wants to know specific information.
2. Picking up documentation from the database for a pdf is really limited to having a clear understanding of the meaning of database columns and less so about functions and tables.  If a column appears essentially directly in the UI, then the description of what that column means and how it is used can be documented in the column comments.  It is about presenting a narrow focus for easy understanding by the reader.
3. For example, in the AR table the `intnotes` column has the comment, "These notes are not displayed when the invoice is printed or emailed and may be updated without reposting hte invocie."  Ignoring the spelling errors, this is information that could be valuable in a user focused Book pdf.  Maybe it goes on the page in the pdf showing the new AR entry? Why would I write the same sentence in the PDF when I could retrieve it from the database column comment?  Then if a developer decides that, for example, some other restriction applies, then they update the comment and bingo, it appears automatically in the appropriate place or places in the documentation.  
4. So this is really about linking the book to the database **where appropriate**. Then moving comments from the book pdf to the database if appropriate or just using what is in the database.  
5. In addition to the above, during the extract the script might recognize automatically that 'invoice' and 'notes' are key words and automatically add `\index{notes}` or `\index{invoice} to the tex file without any interactions from anyone. I don't think we would add ' invocie' to the index. :-) In my own stuff I usually add a latex footnote describing where the paragraph came from.  Something like \footnote{From ar.intnotes column comment.}
6. Regarding "how do I 'undo' this invoice?".  The basic structure of the PDF would remain the same. There may or may not be any relevant information in the database about this action so it would all be in the pdf as it is or should be now.  Now there might be, for example, a `pgsql` undo function with a comment.  That comment may or may not contain any information that is valuable to in the PDF describing limitations of the 'undo'.  If applicable then it would be pulled into the documentation instead of duplicated.
7.  Here is an example that appears directly in code from my BBQ Sheriff iPhone app:
```
/*latex TieBreakCoinTossRule.generated.tex
\item \textbf{Coin Toss}

 This rule group controls step 4 of the tie break process and determines how coin toss is handled.
 If used, the coin toss is the last process used to break a tie.  The options are to either use a coin toss or not.

 In order to handle the coin toss and make the coin toss repeatable between recalculations of the scores,
 the random order is determined when the team score (total score for a team in a single BBQ Category or Grand Champion)
 is first created using a unique cryptographically secure random number between 1 and  2,147,483,647.

 This unique random number is stored in the database but is not visible except in import/export data and exists regardless of the \ref{RuleGroup:08} setting.

 Rule ID:
 \begin{enumerate}[label={\arabic*.}, start=0]

 \item Use Coin Toss -- The saved random number will be used as the final tie break to determine the winner.
 Reporting will show Coin Toss as the method used to break the tie.  \workingnotes{Working.}

 The highest unique random number is the winner in a tie. \workingnotes{Working.}

\item Ignore Coin Toss -- The saved random number is used to rank tied scores in the database and in exports.  \workingnotes{Working.}

If any teams are still tied after all tie break processes have been applied then only the highest (closer to zero)
 rank is displayed in reports for all teams in the tied group. Ranks that would normally be shown for the rest of the group are skipped. \workingnotes{Working.}

 The tied teams are listed in tie break random number descending. \workingnotes{Working.}

Even though the teams are in order of the tie break sequence number descending they have the same rank and therefore since no tie was broken will not show Coin Toss as breaking the tie.  \workingnotes{Working.}
\end{enumerate}
latex*/
```
8. Here is another example from the same code file:
```
    /*latex TieBreakCoinTossRG.generated.tex
     \item \label{RuleGroup:08} \textbf{Tie Break Step 4 -- Check Coin Toss}

     This rule group controls step 4 of the tie break process and determine how coin toss is handled as the final tie break check.

     Rule ID:
     \begin{enumerate}[label={\arabic*.}, start=0]
     \item Ignore -- Coin toss check is NOT used in tie break calculations.  \workingnotes{Working.}
     \item Use -- Coin toss check is used in tie break calculations.  \workingnotes{Working.}
     \end{enumerate}

     latex*/
```
9. So you can see that these examples contain latex, but any developer could update them without any detailed understanding of latex.  In these examples, the file name appears after the `*latex` and on the same line. This file then is included into the book.tex file.
10. I am ambivalent about about which repository the book resides in. If it is not in the same repository, then a manual step will be required to extract the data and move it to the book repository.  Much the same way you do for the numbered examples  above.
11. I have not looked through the perl code yet, but I'll bet that their text exists that would help in different parts of the book pdf.
12. What I am talking about does not include gathering all comments. It includes putting comments in the correct place either in source code files, help files, or database comments so that the information is sourced in one place.

**Comment by neilt** [comment]
From Erik: How about using  https://docs.ledgersmb.org/openapi/1.10.0/LedgerSMB-api.html.  Download the json file.

**Comment by ehuelsmann** [comment]
> 4\. So this is really about linking the book to the database **where appropriate**. Then moving comments from the book pdf to the database if appropriate or just using what is in the database.

The defined application roles would be a great place to start doing this: they currently don't have documentation, but it does make sense to start changing that.

**Comment by neilt** [comment]
> > 4. So this is really about linking the book to the database **where appropriate**. Then moving comments from the book pdf to the database if appropriate or just using what is in the database.
> 
> The defined application roles would be a great place to start doing this: they currently don't have documentation, but it does make sense to start changing that.

Some issues that I an considering:

* Application roles is probably a great place to start.   Since the book will not be integrated into the LSMB repository, then the Book repository has to have a way to access the LSMB repository.  I am not sure how to do that?  In addition, where is the canonical location for the documentation in the LSMB. This probably needs a discussion about documentation strategy all of its own.
* For any screen grabs we need decent test data.  Decent meaning more that a couple of companies, contacts, etc. that are random.  I am unclear about the source of that data, but am currently creating it as part of learning how the database works. That is different than the 'Jack' data.
* For the screen grabs, I am looking into writing some code similar to the test code that runs against an active server from the book repository.  That way the book code drives the process.  

So for example, the code `grab_screens.pl` would:
1. load a configuration file that contains URLs for the screens wanted, screen size, cropping info, etc.
2. sign into an LSMB instance (which has been pre-populated with approved test data)
3. navigate to each screen wanted and take screen grab (WWW::Selenium)

It seems this technology already exists in the test infrastructure, but I think it would work better driven from the book side for a number of reasons.  The most important is that testing and book would be separated. Meaning that test changes would not mess with the book and vice versa.  

Also important is that the screen grab names could be better.

This approach also will also set the stage for videos, which will require different automation and probably different outcomes than the existing tests.

**Comment by ehuelsmann** [comment]
> * Application roles is probably a great place to start.   Since the book will not be integrated into the LSMB repository, then the Book repository has to have a way to access the LSMB repository.  I am not sure how to do that?  In addition, where is the canonical location for the documentation in the LSMB. This probably needs a discussion about documentation strategy all of its own.

This is now done.

**Comment by neilt** [comment]
Both of the major items are complete (roles and screenshots).
