### ISSUE TITLE
Possible patch required for IR.pm

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#732]
John writes in IRC that he has this patch applied to IR.pm in his local install.

line 1456, changed to:
+                WHERE eca.id = ? and coalesce(e2l.location_class, el.location_class) = 1|;

Impact to be investigated.

**Comment by ehuelsmann** [comment]
@freelock A few rows up (lines 1440 through 1444) show:

````sql
             LEFT JOIN eca_to_location e2l ON eca.id = e2l.credit_id
                                     and e2l.location_class = 1
             LEFT JOIN entity_to_location el ON eca.entity_id = el.entity_id
                                     and el.location_class = 1
````

I'd expect those to have the same effect. Could you test removing your change? I don't think it's required (anymore?).

**Comment by freelock** [comment]
Ok, will try that out...

**Comment by freelock** [comment]
Have been running without this patch for a month, not finding anything missing...

Closing...
