### ISSUE TITLE
Templates loaded with ledgersmb-admin template load-all are wonky?

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#7378]
Loaded templates into master 459bebc15 using:
```
docker exec -u root ldmaster_lsmb perl -Ilib bin/ledgersmb-admin template load-all postgres@postgres/jack templates/demo
```

1. Create new Sales Order, Save, and Post
2. Search for Sales Order
3. Select Sales Order
4. Click Print
5. Get Error, see below
6. Works fine when database is initialized with UI, so while I think it might be template related since the error is in `Template.pm` it might be related to how I manually initialized the database, not using the UI.  In addition, other templates like Reports -> Balance Sheet seem to work.

```
'Can't call method "can" on an undefined value at /srv/ledgersmb/lib/LedgerSMB/Template.pm line 494. '
```

https://github.com/ledgersmb/LedgerSMB/blob/459bebc153fcfbc84380ff7db35d515feea3305c/lib/LedgerSMB/Template.pm#L488-L494

<img width="1233" alt="Screenshot 2023-04-30 at 11 33 05 AM" src="https://user-images.githubusercontent.com/1809796/235364840-5a907a78-98a5-4cae-a895-fd5adfb63121.png">

<img width="678" alt="Screenshot 2023-04-30 at 11 31 07 AM" src="https://user-images.githubusercontent.com/1809796/235364854-4a67c588-275c-4e87-8541-3f27ff3edd71.png">

**Comment by ehuelsmann** [comment]
I'm getting this error even when using templates loaded through setup.pl.
