### ISSUE TITLE
Module LedgerSMB::X12::EDI894 depends on non-existing X12::Parser

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#738]
Module is now blacklisted in module load tests.

**Comment by einhverfr** [comment]
Yeah parser is optional and I wanted to make sure since it is rarely needed
that our tests ran without it.

**Comment by ehuelsmann** [comment]
Ok. I'm adding a conditional test for it right now, so blacklisting isn't
necessary anymore. (Now it would be nice to have a system somewhere
actually run the load tests with X12::Parser installed of course, but the
same goes for the other optionals...)
