### ISSUE TITLE
Invoice template "contact" and "shiptocontact" fields cannot be set

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#7452]
### Version

1.10.17

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

My invoice.tex template has two variables: "contact" and "shiptocontact". These are empty for all of our entities/credit accounts.

I have a new client that wants their contact name on the invoice as a requirement for their new AP system.

I don't see anywhere in the Contacts to add this name that ends up populating this field -- am I missing something?

I have added their name on the "Contact Info" tab, as a description on their billing email:
![image](https://github.com/ledgersmb/LedgerSMB/assets/46937/4814f96d-6640-4bd7-9e57-38c6051eb64e)

... I don't see a contact name in the drop down or any other place to put the actual contact name. The ECA name is also needed, in our case...

### What should have happened?

Maybe additional field(s) in the contact info section?

"Attention:"
"Shipping Attention:"

**Comment by ehuelsmann** [comment]
The data you describe - if registered on the credit account - is shown in the Ship To screen. I'm however unable to assess where the data is getting saved for use in the invoice (if at all).

**Comment by ehuelsmann** [comment]
Note: the contacts on the *entity* aren't shown in the shipto screen.

**Comment by ehuelsmann** [comment]
@freelock I think this is the cause:

https://github.com/ledgersmb/LedgerSMB/blob/bccf63299e1658f84e4ca7b0d0741bcc0ee749ab/old/lib/LedgerSMB/IS.pm#L655-L656

**Comment by ehuelsmann** [comment]
@freelock where would you expect the `contact` value to be taken from? From the phone number's `description`? From the E-mail's `description`? From a new value to be introduced (that is, a contact name with a new value and description)?
