### ISSUE TITLE
Tests for PR #767

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#768]
In PR #767 I fixed two joins. Apparently, we don't have tests for the sprocs I fixed; this issue exists to correct that situation.

**Comment by einhverfr** [comment]
Bumping to 1.5 for the following reason:

As long as we are willing to drop support for PostgreSQL 9.1 we can do better than adding tests here. We can switch these to SQL language stored procedures which will do parse testing on load, so our db tests will fail if joins are against columns that don't exist anymore.

**Comment by einhverfr** [comment]
closing since we have moved most of these to plain sql so we should avoid most of these problems.
