### ISSUE TITLE
Calling General Ledger->Chart of Accounts in PDF format fails to render the Credits and Debits

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#7739]
### Version

1.10.25

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Calling General Ledger->Chart of Accounts in PDF format fails to render the Credits and Debits.  Calling for CSV format presents the values as shown on the relevant screen.

### What should have happened?

The "number" columns should have rendered.

**Comment by howardlowndes** [comment]
This problem also occurs in  _**Reports->Trial Balance**._ for the :End Balance column
