### ISSUE TITLE
Balance sheet in 1.4 lacks feature present in 1.3: in-/exclude account headings

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#774]
In 1.3 the balance sheet report has more options and selections than in 1.4; notably:

* The ability to report on GIFI
* The ability to in-/exclude account numbers
* The ability to in-/exclude (account) headings

**Comment by einhverfr** [comment]
we should add tickets for each of these.

**Comment by ehuelsmann** [comment]
Actually, with 1.4.17, we can declare the first two fixed.

I'll change the title appropriately.

**Comment by einhverfr** [comment]
For account numbers and headings, what is the use case there?

**Comment by einhverfr** [comment]
hmmm I know the use cases :-P  Setting milestone to 1.4

**Comment by einhverfr** [comment]
hmmm I think in 1.3 we added this for a user who only uses this for trial balances.  So I am not actually sure this is used by anyone.  For income statements and trial balances, such an option makes sense, but I am not sure it does for balance sheets.  I think we should close this and add the feature only if someone complains.
