### ISSUE TITLE
Add more columns in General Ledger->Chart of Accounts display

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#7740]
In General Ledger->Chart of Accounts display would it be possible to add columns for:
Account type
Contra
Recon
Tax
Summary Account.
This would ensure that all relevant fields are available in the display and the anticipated column widths would not be excessive. Some displays could be achieved by imaginative use of font colour (red for Contra??, underscore for Tax??) in the same way that bold font is used to highlight Headings.

**Comment by ehuelsmann** [comment]
The value for Summary account is implicit in the Links field: the AR, AP and IC values indicate the account is a summary account. The extra columns take a lot of extra space on the page. I'm thinking the current balance amounts should then go, because that is what the trial balance is for.

**Comment by howardlowndes** [comment]
In essence this is #7931 which I raised the other day. I agree about removing the CR and DR columns if that provides the space needed. I've not had the opportunity to try, but do those account values sum back to their corresponding headings values?

**Comment by ehuelsmann** [comment]
From #7931:

1. A system option to abandon the listing of GIFI for those countries who do not use it, or if there are no entries in that field. It's a waste of space if not used.
2. Include in the CoA listing flags for additional items - Account Type, Contra, Reconciliation, Tax, Obsolete, Negative Balance Heading.
3. Tier the presentation of the Description field in the CoA to reflect the structure of the CoA. This could possibly be achieved by means of CSS.
