### ISSUE TITLE
Clarification of various trial balance parts

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#775]
Notably, there are 3 trial balance stored processes, of which only one seems to be used:

* trial_balance__generate (used)
* trial_balance_get (unused?)
* report__trial_balance (unused?)

To support trial_balance_get, there are a number of (seemingly unused) trial balance tables:

* trial_balance
* trial_balance__account_to_report
* trial_balance__heading_to_report

The last table (trial_balance__yearend_types) seems to be used in a dropdown on PNL and Balancesheet filters.

**Comment by einhverfr** [comment]
Yes, these need cleanup.  You are, I think, correct as to what is used or not.

The get was to get options for running a trial balance, but it was abandoned when we switched to links at the bottom of the page.
