### ISSUE TITLE
Reversing a GL transaction does not show 'POST' button

### ISSUE THREAD

**Issue by cricalixwood** [ledgersmb/LedgerSMB#7778]
### Version

1.11.4

### What browsers are you seeing the problem on?

Firefox

### What happened?

Run trial balance, select any account, then any GL transaction. Select 'Reverse'. UI only provides an 'UPDATE' button, no option to 'POST'.

### What should have happened?

Should have been able to POST.

**Comment by ehuelsmann** [comment]
@cricalixwood hi. this works for me. could it be that your original transaction is in a closed period? Or maybe that for some reason there is no value in the "date" field?

**Comment by cricalixwood** [comment]
Ok, I think this is still not quite right. It seems to work as intended if I enter a new transaction (under 1.11.5) and then reverse it. But today when i tried to reverse a transaction from August - definitely not closed - it behaved as i described previously. The transaction is marked as 'Status reversed', there is no change to the account total, and the only button available when I clicked reverse, was Update. So maybe new transactions are setting a status or a field which is not set on old transactions...possibly needs to be set during Upgrades?

**Comment by ehuelsmann** [comment]
This *does* seem to work for me, on my production database. Are there more details you can provide? Can you query the database? If so, could you find out what the value of the "workflow_id" field is in the table "transactions", for the GL transaction you're trying to reverse? You can find the value for "transactions.id" in the URL when you open the transaction in the "id" parameter (`&id=1234`).

**Comment by ehuelsmann** [comment]
Removing bug tag because I can't reproduce

**Comment by cricalixwood** [comment]
Agreed.

⁣Get BlueMail for Android ​

**Comment by neilt** [comment]
Closed, not reproducible.
