### ISSUE TITLE
Balance sheet no longer reports 'Current Earnings'

### ISSUE THREAD

**Issue by cricalixwood** [ledgersmb/LedgerSMB#7785]
### Version

1.11.4

### What browsers are you seeing the problem on?

Firefox

### What happened?

Upgraded database from 1.10.25 to 1.11.4. No transactions entered.  Template for Balance Sheet not changed for this database. (I had changed it for other companies). Balance sheet on 1.10.25 shows 'Current earnings' under Equity, so Total Equity plus Total Liabilities = Total Assets. On 1.11.4 the balance sheet numbers all agree, except that the Current Earnings line is missing, so the Balance Sheet does not balance. 

### What should have happened?

I am expecting to see a line for Current Earnings, as in 1.10.25

**Comment by cricalixwood** [comment]
Just upgraded 1.11.4 to 1.11.5. Issue remains.

**Comment by ehuelsmann** [comment]
Thanks for testing! I think I identified the problem and am working on a fix for 1.11.6

**Comment by cricalixwood** [comment]
Great! Thank you.

Roger 

⁣Get BlueMail for Android ​
