### ISSUE TITLE
Phase out 'chart' view

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#780]
The 'chart' view is a mix of accounts and headings, which is a union of the ```account``` and ```account_heading``` tables -- it used to be a table of its own though.

The separation in accounts and headings has been created explicitly to support code to use e.g. account heading trees. The 'chart' view, being legacy, should be phased out.

**Comment by einhverfr** [comment]
I doubt we can remove the final references for 1.5, so reassinging to 1.6.

**Comment by einhverfr** [comment]
Pending merge
