### ISSUE TITLE
Clarification of set functions versus record functions

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#781]
There are loads of inconsistencies in our code base regarding returning a set of a single record versus returning just a record. E.g.

```sql
CREATE OR REPLACE FUNCTION account_heading_get (in_id int) RETURNS chart
```
versus

```sql
CREATE OR REPLACE FUNCTION account_get (in_id int) RETURNS setof chart
```

**Comment by einhverfr** [comment]
I think we should adopt a rule that we always return record unless we need to return a set.

account_get looks like it is in error in this case.  It can be changed easily enough and from an API sense it makes very little difference (the only difference is that you cannot `select account_get(123)` but you can `select account_heading_get(123)`  You can select * from both however.

**Comment by einhverfr** [comment]
THis could be cleaned up in 1.4

**Comment by einhverfr** [comment]
I am going to try to fix this for beta 2.  For something like this, better sooner than later.
