### ISSUE TITLE
users@lists.ledgersmb.org is down

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7810]
### Version

Not a version issue

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

As per the heading. Bounce error message is:
`Message not delivered
Your message couldn't be delivered to users@lists.ledgersmb.org because the remote server is misconfigured. See the technical details below for more information.`

`The response from the remote server was:
554 5.7.1 <[users@lists.ledgersmb.org](mailto:users@lists.ledgersmb.org)>: Relay access denied`

### What should have happened?

Investigation and rectification

**Comment by neilt** [comment]
Confirmed. 

The server is up at http://lists.ledgersmb.org/hyperkitty/list/users@lists.ledgersmb.org/ but not accepting emails.

**Comment by freelock** [comment]
Hi, 

Thanks for reporting! Please try again, I think I found and fixed the problem.

Cheers,
John

**Comment by ehuelsmann** [comment]
This should be fixed now.
