### ISSUE TITLE
Unable to delete a part

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7811]
### Version

1.11.4

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Trying to delete a part via Goods & Services->Search->[select part to delete]->Delete throws the following error:

`Error!
'DELETE FROM translation WHERE trans_id = ? ERROR: permission denied for table translation at old/lib/LedgerSMB/IC.pm line 905. '

dbversion: 1.11.4, company: PlayAMS`

### What should have happened?

The part should be deletable. Translations are not being used.

**Comment by neilt** [comment]
Confirmed as of master e6bcd81b204e92be5fef7ac2740cbe0436d9a04e.

Steps to reproduce:
1. Create a new clean database
2. Create a new part
3. Exit new part screen
4. Search for part and select it
5. Click "Delete'
