### ISSUE TITLE
Unable to delete an account

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7812]
### Version

1.11.4

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Trying to delete an account item that was previously an Inventory summary account (but is no longer) throws the following error.

`23503: ERROR: update or delete on table "account" violates foreign key constraint "parts_inventory_accno_id_fkey" on table "parts"
DETAIL: Key (id)=(22) is still referenced from table "parts".
CONTEXT: SQL statement "DELETE FROM account WHERE id = in_id"
PL/pgSQL function account__delete(integer) line 17 at SQL statement

dbversion: 1.11.4, company: PlayAMS`

### What should have happened?

This is probably as a result of the error reported in #7811 not allowing a part to be deleted

**Comment by ehuelsmann** [comment]
Hmm. What you're also saying here is that the "can I delete this account" check forgets to check some of the foreign keys. If the account is used in a part, it shouldn't be offering to delete the account.

Thanks for reporting!

**Comment by howardlowndes** [comment]
What you say is reasonable but my problem stemmed from not being able to
delete the part because of a different problem (was that #7811?).

**Comment by ehuelsmann** [comment]
That's correct: you couldn't delete the part and the part was using the account. So: the `[delete]` link on the account should not have been offered. #7811 is about being able to delete the account (which fails). I'm looking into that.

When #7811 is fixed (and your setup updated) *and* you delete the part, then you should be able successfully to remove the account.

**Comment by ehuelsmann** [comment]
@howardlowndes 1.11.6 was released earlier today, with this fix included.
