### ISSUE TITLE
Selected paper size does not lock in

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7817]
### Version

1.11.4

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Setting System->Defaults->Default Paper Size to anything other than Letter does not lock the size to the selected setting but it reverts to Letter

### What should have happened?

This may be associated with locale problems referenced in earlier recent issues

**Comment by ehuelsmann** [comment]
That's correct. This was fixed with the 1.11.5 release.
