### ISSUE TITLE
CoA output formatting errors

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7818]
### Version

1.11.4

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Calling for the CoA to be displayed in various formats has differing errors.
PDF - no values are displayed (all account values are currently zero so this may not be a valid error)
CSV - renders correctly
ODS, XLS, XLSX - all render only the page title and the company name, no other detail. Presentation is via Libreoffice

### What should have happened?

Needs resolution

**Comment by neilt** [comment]
master as of e6bcd81b204e92be5fef7ac2740cbe0436d9a04e

PDF - Not able to confirm, seems to work fine here. Please update to at least 11.5
ODS, XLS, XLSX - Not able to confirm. Note that the CoA is on a 2nd tab labeled "Chart of Accounts"

**Comment by howardlowndes** [comment]
I'm not too sure of the process here. Do I just downloaded the tarball,
unpack it over the earlier version then run Upgrade as Admin in setup.pl?

**Comment by ehuelsmann** [comment]
Assuming that's how you installed in the first place, then, yes. that's the way to go. (I usually create a copy of the directory tree before going there, so I have a way to restore.

**Comment by howardlowndes** [comment]
I've actually got the code in /opt/1.11.4 and have that directory soft
linked to /opt/ledgersmb which is where the application is called from.
That way I will extract the new tarball into /opt/1.11.5 , relink to there,
and run setup.pl in /opt/ledgersmb, thus retaining /opt/1.11.4 as a
fallback.
