### ISSUE TITLE
Cosmetic correction in General_Ledger_Report_.pdf

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7834]
### Version

1.11.6

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

In the subject PDF report the column titles "Vendor/Customer" and "Description" overlap
[General_Ledger_Report_-.pdf](https://github.com/ledgersmb/LedgerSMB/files/13691360/General_Ledger_Report_-.pdf)

### What should have happened?

Picky

**Comment by neilt** [comment]
Confirmed. The column title "Vendor/Customer" should be made into 2 lines like the column title "Account Number"

**Comment by neilt** [comment]
Fixed by #7846
