### ISSUE TITLE
Partsgroup vs Pricegroup, and other matters

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7843]
### Version

1.11.6

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

All of the following are under the top level menu item **Goods and Services**:

~~Item **Pricegroups** allows the user to add a description of a **pricegroup**;~~ [Responded to in [a comment below](https://github.com/ledgersmb/LedgerSMB/issues/7843#issuecomment-1858792059)]

~~Under **Search** there is a checkable item Part Group;~~ [Responded to in [a comment below](https://github.com/ledgersmb/LedgerSMB/issues/7843#issuecomment-1858827475)]

~~Under **Search Groups** there is the option to select **Partsgroups**;~~ [Responded to in [a comment below](https://github.com/ledgersmb/LedgerSMB/issues/7843#issuecomment-1858828187)]

~~Under **Add Group** it expects an existing **Parent**;~~ [Responded to in [a comment below](https://github.com/ledgersmb/LedgerSMB/issues/7843#issuecomment-1858826306)]

~~Under **Add Part**, **Add Service**, **Add Assembly**, **Add Overhead**, there is no ability to connect to a partgroup or a pricegroup;~~ [Responded to in [a comment below](https://github.com/ledgersmb/LedgerSMB/issues/7843#issuecomment-1858792059)]

~~Under **Search** some of the reportable items are pre-checked and some are not. There appears to be no way in which the items checked can be "locked in" from one **Search** to the next.~~ [Responded to in [one of the comments below](https://github.com/ledgersmb/LedgerSMB/issues/7843#issuecomment-1858788788)]

~~Also the **No.** check box does nothing.~~ [Split out into #7845]

### What should have happened?

Multiple issues requiring clarification or resolution.

**Comment by howardlowndes** [comment]
Additionaly, the item order in the **Goods & Services** -> **Search** appears to be in a random order with parts and services intermixed if not explicitly selected, and even if they are so selected.

**Comment by ehuelsmann** [comment]
I hope you don't mind me editing the report directly, because that helps to split out in a way that I can best explain the various parts of it.

**Comment by ehuelsmann** [comment]
> Under **Search** some of the reportable items are pre-checked and some are not. There appears to be no way in which the items checked can be "locked in" from one **Search** to the next.

That's correct. This is tracked in #5719.

**Comment by ehuelsmann** [comment]
> Under **Add Part**, **Add Service**, **Add Assembly**, **Add Overhead**, there is no ability to connect to a partgroup or a pricegroup

Adding parts to a parts group is covered in the book at https://book.ledgersmb.org/1.10/full-book/#Ch7.S3

Price groups aren't covered in the book yet, but can be used to a#ign a part price per group in the lower half of the part screen.

**Comment by howardlowndes** [comment]
Go for it. You would know better than I hope much you can merge issues
together or how much they need to be separated.

**Comment by ehuelsmann** [comment]
> Under **Add Group** it expects an existing **Parent**;

This is a misconception: *if* there are other parts groups, one of them can be used as a parent. Or did your report mean to say that leaving the Parent field empty leads to an error? (Because with 1.11.6, this isn't the case for me.

**Comment by ehuelsmann** [comment]
> Under **Search** there is a checkable item Part Group;

Correct. It's in the section "Include in report", which is what it does for me: checking that column shows a Partsgroup column for parts which have one set.

**Comment by ehuelsmann** [comment]
> Under **Search Groups** there is the option to select **Partsgroups**;

Correct. It selects all parts in the parts group and its "child parts groups".

**Comment by ehuelsmann** [comment]
I hope this clarifies your points?

**Comment by howardlowndes** [comment]
I didn't try any input. I find the nomenclature confusing as to whether
there is supposed to be one or two groupings.

**Comment by ehuelsmann** [comment]
> whether there is supposed to be one or two groupings.

Yes. I can imagine. There are two:

 * Price groups
 * Part groups

We're looking at changing the menu to clarify *and* to change the screens to reduce the number of required menu-items.

**Comment by howardlowndes** [comment]
I can see where price groups would apply especially for volume sales discounts.
Refer to issue #7848 for a different problem concerning the input of parts groups.

**Comment by ehuelsmann** [comment]
Thanks for your reports and questions! They help fix bug and unclarity in the application as well as trigger expansion of the documentation in the book.

The references issue send like a bug indeed. Thanks agaun!

**Comment by howardlowndes** [comment]
I was wondering whether my issues were becoming a PITA which is why I try
to be as forensic as I can in the reporting 😎🇦🇺

**Comment by neilt** [comment]
> I was wondering whether my issues were becoming a PITA which is why I try to be as forensic as I can in the reporting 😎🇦🇺

Reporting issues is not a PITA, we welcome all issues and questions big and small.  LedgerSMB is undergoing a lot of development right now, especially migrating the UI to new infrastructure and it is good to have knowledge of all issues.
