### ISSUE TITLE
login.pl incorrectly reports version database schema mismatches (if at all)

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#785]
Under Starman, 1.5.0-dev reports an ```500 ISE``` in the HTTP status, with the real error in the body.

Before we release, we should invent our own HTTP error (possibly HTTP status) which we can detect to be a schema mismatch error.

**Comment by freelock** [comment]
Hi,

I think 500 is ok for a schema mismatch, though 520 looks ok too... in general I think if the server needs attention we should return something 5xx, but if there's a data issue or client request issue, 4xx. 

A schema issue definitely sounds like a server-side problem... so I would think 5xx is appropriate.
