### ISSUE TITLE
Error when creating an invoice from a sales order

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#7884]
### Version

1.11.6

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Ok we've hit a new issue:
![image](https://github.com/ledgersmb/LedgerSMB/assets/46937/5f5a9e6d-5f48-475c-bdcc-3d2ece26efba)

1.     Create a sales order with some items on it, and save it
2.     Add qty to the "ship" field, and click "Sales Invoice"
3.     We're getting this error, instead of it creating a new invoice/subtracting from the sales order.

The dates are set to today, which is not in a closed period

### What should have happened?

No error, invoice created, sales order items selected to ship removed from sales order leaving unshipped items open.

**Comment by ehuelsmann** [comment]
Duplicates #7855 (Fixed, to be released)
