### ISSUE TITLE
Unable to upload CSV CoA

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7910]
### Version

1.11.7

### What browsers are you seeing the problem on?

Other

### What happened?

Browser is Chromium
Attempting to upload a CSV CoA formatted IAW doc/csv-import/README.md and doc/csv-import/example-coa-upload.csv
File CoA.csv attached
[CoA.csv](https://github.com/ledgersmb/LedgerSMB/files/13852372/CoA.csv)
Error message on screen is uncopyable - it disappears on movement of the screen cursor, but refers to a malformed array literal ... must start with "{" or dimension information. The line it appears to be objecting to is either line 5, 35, or 45 in the attached file "...ss Transaction" but it refers to line 3 and the referred text that follows doesn't match any of those input lines

### What should have happened?

It should have imported a CoA defined IAW the documentation

**Comment by ehuelsmann** [comment]
With the logging level set to INFO, I see this in the logs:

```plain
2024/01/07 09:16:21 Use of uninitialized value $settings{"link"} in split at /srv/ledgersmb/lib/LedgerSMB/Scripts/import_csv.pm line 374.\n
2024/01/07 09:16:21 Use of uninitialized value $settings{"heading"} in hash element at /srv/ledgersmb/lib/LedgerSMB/Scripts/import_csv.pm line 379.\n
2024/01/07 09:16:21 Saving heading 0 (BALANCE SHEET)
2024/01/07 09:16:21 Use of uninitialized value $settings{"link"} in split at /srv/ledgersmb/lib/LedgerSMB/Scripts/import_csv.pm line 374.\n
2024/01/07 09:16:21 Saving heading 0.1 (ASSETS)
2024/01/07 09:16:21 Use of uninitialized value $settings{"link"} in split at /srv/ledgersmb/lib/LedgerSMB/Scripts/import_csv.pm line 374.\n
2024/01/07 09:16:21 Saving heading 0.1.10 (HUME BANK)
2024/01/07 09:16:21 Saving account 0.1.10.10 (Business Transaction)
2024/01/07 09:16:21 Server response: 500
2024/01/07 09:16:21 Rolling back current db transaction
Req:6C509E4CAD3D11EEBA11A8125A7BD962 172.30.0.4 - - [07/Jan/2024:09:16:21 +0000] "POST /import_csv.pl HTTP/1.0" 500 410 "http://172.30.0.4/erp.pl?__action=root" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
172.30.0.4 - - [07/Jan/2024:09:16:21 +0000] "POST /import_csv.pl HTTP/1.0" 500 410 "http://172.30.0.4/erp.pl?__action=root" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

Which suggests that the last account to be processed (or being processed) was "Business Transaction" which would explain the "...ss Transaction" part in the error message on-screen.

Regardless: fixes on their way.

**Comment by howardlowndes** [comment]
... And the rollback explains the lack of any accounts.
