### ISSUE TITLE
Automatic validation of correct operation of menu links

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#797]
Develop a series of tests which opens all pages available from the menu and verify that none of the pages return an error. (Requires minimal configuration -- e.g. currencies.)

**Comment by einhverfr** [comment]
Now that sauce is set up, should be doable for 1.5

**Comment by ehuelsmann** [comment]
Although this isn't entirely complete, a very long list of menu items is being checked. Forwarding the remaining items to 1.5 somewhere during the release cycle, these can be added.

@sbts maybe this is a good place to start getting to know and extending our test suite?

**Comment by einhverfr** [comment]
as I understand it, this is not really a goal as such anymore, and we are instead working on (IMHO) a better goal of solid bdd tests for all topical workflows.  If this is premature feel free to re-open with a note, but in the interest of ticket cleanup, I am going to close this one for now.
