### ISSUE TITLE
Date format for new user creation is confusing

### ISSUE THREAD

**Issue by lifeboy** [ledgersmb/LedgerSMB#7983]
### Version

1.11.8

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

When a new user is created using setup.pl and create new user, the data format in the empty date field shows "dd/mm/yyyy".  However, entering a date in that format results in an error.  

### What should have happened?

The format of that date shown should match the format that the date must be entered in.

When one uses the dropdown date widget and selects a date from there, it adds a date on "yyyy-mm-dd" format, which works (even if one edits the actual date in that format).   

Either the form field should display the correct format or the acceptible format should be adjusted.

**Comment by ehuelsmann** [comment]
Thanks for reporting! However, I'm unable to reproduce: my input asks for `m/d/yyyy`, not `dd/mm/yyyy`. So that's a major difference, but selecting a date in that format correctly gets me the user I need/want.

Is there anything you're able to share about your environment? What's the default language preference you're using for browsing your web pages? Mine is `en_US`.

**Comment by lifeboy** [comment]
I have in the meantime decided to do a re-installation.  I'll update this
ticket if the same problem is still there after that.

**Comment by lifeboy** [comment]
I have installed using docket-compose now and since South Africa is not on
the list of countries, I selected EN-GB.

My OS timezone is:

# date
Mon Feb 26 06:56:46 PM SAST 2024

that's UTC+2, but I don't think that makes a difference.

Here's what my create user screen looks like.

[image: Capture.PNG]

However, as can be seen by the red exclamation mark, the date format not
understood.

regards

Roland

**Comment by lifeboy** [comment]
The only format that is accepted is:  yyyy-mm-dd

yyyy/mm/dd is not acceptable even though the original suggestion uses / as
separator.

**Comment by ehuelsmann** [comment]
> Here's what my create user screen looks like. [image: Capture.PNG]

Unfortunately, your image didn't get copied into the site. Could you try again? Thanks in advance!

**Comment by lifeboy** [comment]
> > Here's what my create user screen looks like. [image: Capture.PNG]
> 
> Unfortunately, your image didn't get copied into the site. Could you try again? Thanks in advance!

![Capture](https://github.com/ledgersmb/LedgerSMB/assets/4822951/9711afd6-dcdf-43dd-84e4-90594c1a09c8)

**Comment by lifeboy** [comment]
> > I have installed using docket-compose now and since South Africa is not on the list of countries, I selected EN-GB.
> 
> Just to be sure: you selected that in your browser's settings, not in "setup.pl", correct?

I selected UK in setup.pl.
![image](https://github.com/ledgersmb/LedgerSMB/assets/4822951/27cde478-f8d9-4893-905a-9eb59402411e)

**Comment by ehuelsmann** [comment]
Thank you for getting back with the screenshots and steps to create the problem.

The step where you select `en_GB` is about selecting a chat of Accounts (the set of general ledger accounts and their settings), not a language selection.

The language selection I was referring to, is the setting you have in your browser. https://www.pcmag.com/how-to/how-to-change-your-default-language-in-google-chrome describes how to select it change language settings in chrome. Other broeders have similar ways to change preferences.

What I meant to ask is: what is the preferences confused in your browser? With that I can hopefully reproduce your report.

**Comment by lifeboy** [comment]
Hi Erik,
I use Brave and Firefox in general.  The screenshots were taken from
Brave.  There my language settings are:

1. English (United Kingdom)
This language is used when translating pages
2. English (United States)
3. English
I tested this in Firefox with English (GB) as language selection and it
works fine.  I don't have Chrome installed on my machine.

Also, selecting a date with the date-dialogue popup actually fills in a
yyyy-mm-dd formatted date, so it's literally only the template format
that's displayed by default in the add user form that doesn't match the
required format.

**Comment by ehuelsmann** [comment]
Thanks! That helped me find (and fix) the issue!
