### ISSUE TITLE
CRITICAL ERROR - Bad request: CSRF token failure

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#8004]
### Version

1.11.9

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

I have installed 1.11.9
I have run Rebuild/Upgrade from setup.pl and am able to access existing databases without error
I logged back into setup.pl and attempted to create a fresh database from the login screen and received this error

> Bad request: CSRF token failure

The new database was not created.
![20240208_10h52m17s_grim](https://github.com/ledgersmb/LedgerSMB/assets/52798206/670f24be-33a2-4997-b152-b7b0ec429c96)
![20240208_10h52m25s_grim](https://github.com/ledgersmb/LedgerSMB/assets/52798206/53a61a48-8960-4133-9684-86e5d96cc056)

### What should have happened?

I should not have received the error message.
I should have been able to create a new database.

**Comment by howardlowndes** [comment]
I was able to revert to 1.11.8 and was able to create a new database ans to import a CoA.csv

**Comment by ehuelsmann** [comment]
This issue has a workaround: instead of clicking "Create", click "Login" and the app will ask you to create the database since it doesn't exist yet.
