### ISSUE TITLE
Not all pdf/csv/html templates in <root>/templates/<template-set>/

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#811]
The templates used to download PNL and Balance Sheet reports from the system are not included in the templates directory, but instead are in the directories with files for definition of system UI: UI/Reports.

(Please add others as you encounter them)

**Comment by einhverfr** [comment]
For PNL and balance sheet, the problem is that our reporting structure puts everything in the same place.

I am wondering if we should have the reporting structure try to look up the table in the db first, allowing for all reports to run off custom templates
