### ISSUE TITLE
More preferences (preference country)

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#815]
As per Rob Ransbottom's suggestion on the mailing list:

``` plain
It would be good to have a default country for forms per user preference.
```

Note that the United States is all the way down on most drop-downs to understand the importance of his request.

**Comment by einhverfr** [comment]
What other preferences do we need?

**Comment by einhverfr** [comment]
From discussion, default printer, default format, and default attachment for dropdown

**Comment by einhverfr** [comment]
See also https://sourceforge.net/p/ledger-smb/feature-requests/310/

**Comment by pbolger** [comment]
It'd also be good to be able to limit the visible countries in the country dropdowns. Many users won't ever select Afghanistan (for example) so having to go past it on the list is an unecessary distraction.

**Comment by ehuelsmann** [comment]
@pbolger I was going to react that you can reduce the list from the ````System```` menu, but as it turns out I'm mixing Country listing with Languages listing. The latter allows removal.

**Comment by ehuelsmann** [comment]
@ylavoie I guess the enhancement we were talking about today (reduction of the number of countries) has an issue filed already.

**Comment by ehuelsmann** [comment]
User-level preferences should be made more flexible before we can implement this one => depends #776
