### ISSUE TITLE
creating two near-identical ARs (or APs) confuses system so that sometimes they are combined into one, potentially breaking double-entry

### ISSUE THREAD

**Issue by brush** [ledgersmb/LedgerSMB#8151]
### Version

1.10.34

### What browsers are you seeing the problem on?

Firefox

### What happened?

still can't reliably reproduce from scratch, may be partially contingent on old transactions from 1.4-1.10 upgrade, however this at least is a problem:

* create AR/AP
* post it
* copy invoice number
* create new AR/AP with same invoice number, but add a space
* these invoices will be spliced together

in some cases, the splicing together leaves an extra AR or AP line, resulting in the payments being out of balance with the total, but the AR/AP still balancing, resulting in `select sum(amount_bc) from acc_trans;` being nonzero.

### What should have happened?

not this. :)

**Comment by brush** [comment]
(or maybe it's not exactly the above, it's hard to create from scratch, but somehow something like this happened multiple times in my data.)

**Comment by brush** [comment]
workaround: find the extra AP or AR summary line, and delete it.

**Comment by neilt** [comment]
We need to be able to recreate this problem is order to figure it out.  Please post two screen grabs showing the data for the two AR or AP entries that get confused.  This has never happened to me or the other developers so It is kind of hard to troubleshoot without more concrete examples.
