### ISSUE TITLE
Create automatic posting of LSMB release announcement to Facebook

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#8189]
Need help creating a procedure for automatically posting LSMB release announcements to Facebook.

**Comment by ehuelsmann** [comment]
Note that we have release notification infrastructure at https://github.com/ledgersmb/ledgersmb-release-tools/tree/master/notify ; extending it is one of the ways this issue could be solved.

**Comment by ehuelsmann** [comment]
Posted to Facebook that our releases will be announced elsewhere. No further announcements on Facebook (community too small).
