### ISSUE TITLE
Create automatic posting of LSMB release announcement to LinkedIn

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#8190]
Need help creating a procedure for automatically posting LSMB release announcements to LinkedIn.

**Comment by ehuelsmann** [comment]
Note that we have release notification infrastructure at https://github.com/ledgersmb/ledgersmb-release-tools/tree/master/notify ; extending it is one of the ways this issue could be solved.

**Comment by ehuelsmann** [comment]
We abandoned the idea of putting to the LinkedIn groep.
