### ISSUE TITLE
Expense Reporting Undocumented

### ISSUE THREAD

**Issue by snunez1** [ledgersmb/LedgerSMB#8267]
### Version

N/A

### What browsers are you seeing the problem on?

Firefox

### What happened?

Looking through the documentation, there appears to be no way to account for employee expenses incurred on business travel, e.g. airfare, taxi, hotels, meals, etc.

### What should have happened?

Documentation should describe the expense reimbursement process.  See [documentation for Flecta expenses](https://doc.flectrahq.com/2.0/applications/finance/expenses.html) for an example of how this might work.

**Comment by neilt** [comment]
Currently there is no specific expense tracking functionality that I know if.

The way I do this now is to create an AP to the employee and apply each expense to a GL account.

This functionality could be added if you were willing to sponsor the development or assist in providing code for the functionality.

**Comment by snunez1** [comment]
Thanks for the suggestion.  Unfortunately I have neither money to sponsor the development nor time to learn PERL.  I was hoping this was common enough that the functionality already existed.

**Comment by neilt** [comment]
> Thanks for the suggestion. Unfortunately I have neither money to sponsor the development nor time to learn PERL. I was hoping this was common enough that the functionality already existed.

This functionality is definitly common and desired, but currently we are resource limited. 

Of course, we also wish that was not the case.

Thank you for considering LSMB.

**Comment by neilt** [comment]
Closing this since there is nothing to document. Leaving #8266 open for future reference.
