### ISSUE TITLE
Quotes not editable after saving

### ISSUE THREAD

**Issue by Alt-Tech-Au** [ledgersmb/LedgerSMB#8346]
### Version

1.11.14

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

After clicking save on a new quote you used to be able to edit them, after the upgrade to 1.11.14 all fields are greyed out and read only.

Intermittent issue affecting about 30% of our quotes.

Have tested in multiple browsers.

Check the workflow in postgres and confirmed an affected quote is in the SAVED state

### What should have happened?

we would expect to be able to edit all of the fields after saving.

**Comment by ehuelsmann** [comment]
I tried to reproduce, but didn't see this problem. Maybe because it's intermittent. Can you provide more information? Does it happen to specific customers? Does it happen with orders as well as quotes? Does the number of rows matter? Did you send the quote by mail or print it?

**Comment by ehuelsmann** [comment]
Using real world data, I was able to identify the problem. Fix forthcoming.
