### ISSUE TITLE
sql function report__balance_sheet doesn't use account check points

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#835]
This is not a bug or error.

Performance would benefit from having this change in place.

**Comment by einhverfr** [comment]
Adding to 1.5 milestone since 1.4 will soon be oldstable

**Comment by einhverfr** [comment]
I think this could be moved to 1.5 general if we can first come up with a good data set for testing balance sheet corner cases via the stored procedures.

**Comment by einhverfr** [comment]
otherwise I think we need to do it in 1.6

**Comment by ehuelsmann** [comment]
This function completely duplicates the trial balance function with the notable difference that the latter does use the account checkpoints.

**Comment by ehuelsmann** [comment]
Instead of enhancement, this function needs to be cleaned up.
