### ISSUE TITLE
Replacement for TT2

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#836]
TT2 (or: Template Toolkit version 2) doesn't allow methods to be called on anything that isn't a report variable.

However, with our move to Moose, that's exactly the style that's being endorsed by the fact that attribute accesses are in effect function calls. E.g.

```
  FOR row IN report.rheads.sort_axis()
```

doesn't work because rheads is an attribute on the 'report' object, which returns an object itself and the "sort_axis()" function can't be called on the second level object.

**Comment by einhverfr** [comment]
Ok so this is mostly an issue with reports, correct?  Everything else needs to go through services and dojo, right?

I am wondering if we want to instead slice the report before handing it to TT in this case.

**Comment by einhverfr** [comment]
I am closing this for now for a simple reason, namely that we've changed direction and are less likely to actually end up using server-side templating in the future for most new things.

So I think this is obsolete given our efforts to move to a service oriented interface

For these issues, we are may use client-side rendering and templating for example.
