### ISSUE TITLE
Customer Lookup Fails with Error

### ISSUE THREAD

**Issue by dme1sc** [ledgersmb/LedgerSMB#8364]
### Version

1.11.15

### What browsers are you seeing the problem on?

Firefox

### What happened?

I am testing LSMB 1.11.15 docker.  I have logged in, built a customer, assigned a control code. I then tried to add an AR transaction by adding the customer name (also tried the control code), hit enter, and get an error of customer not on file:
'Customer not on file! at /srv/ledgersmb/bin/../old/bin/arap.pl line 146. '.  
![lsmb1](https://github.com/user-attachments/assets/cb5b76ca-e713-4505-aa9b-1f10e137bd37)
![lsmb2](https://github.com/user-attachments/assets/571f7280-ab11-41aa-b584-0fdd5a7ed43a)

### What should have happened?

expected my customer to be selected after typing in the name and clicking Enter.

**Comment by tonka128** [comment]
You need to add a credit account to the customer file
at the moment they are a contact, but there is nowhere to save a transaction to
![image](https://github.com/user-attachments/assets/795e6339-0ef8-4399-9748-a255278e85fb)

**Comment by dme1sc** [comment]
Ok, that worked. Thanks.
