### ISSUE TITLE
Docker setup not setting correct port for database server

### ISSUE THREAD

**Issue by walidmujahid** [ledgersmb/LedgerSMB#8399]
### Version

1.11.17

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

On my local machine, I ran:` docker run -p 5762:5762 -e POSTGRES_HOST=ledgersmb-do-user-66666666-0.k.db.ondigitalocean.com -e POSTGRES_PORT=25060 ledgersmb/ledgersmb:latest`

Then I navigated to setup.pl and the browser loaded to: `http://localhost:5762/setup.pl#/`

I put in the credentials and database to my managed database on Digitalocean. Then I hit login.

After 5 minutes, I got the following error:
```
Error!
Could not connect to database: connection to server at "ledgersmb-do-user-66666666-0.k.db.ondigitalocean.com" (111.11.11.11), port 5432 failed: Connection timed out
Is the server running on that host and accepting TCP/IP connections? at lib/LedgerSMB/Scripts/setup.pm line 267.

dbversion: 1.11.17, company:
```

Here's the docker logs:
```
--------- LEDGERSMB CONFIGURATION:  ledgersmb.conf
paths:
  $class: Beam::Wire
  config:
    UI: ./UI/
    UI_cache: lsmb_templates/

db:
  $class: LedgerSMB::Database::Factory
  connect_data:
    host: ledgersmb-do-user-66666666-0.k.db.ondigitalocean.com
    port: 25060

mail:
  transport:
    $class: LedgerSMB::Mailer::TransportSMTP
    tls: 

miscellaneous:
  $class: Beam::Wire
  config:
    proxy_ip: 172.17.0.1/12

ui:
  class: LedgerSMB::Template::UI
  method: new_UI
  lifecycle: eager
  args:
    cache:
      $ref: paths/UI_cache
    root:
      $ref: paths/UI
--------- LEDGERSMB CONFIGURATION --- END
2024/09/13-15:42:49 Starman::Server (type Net::Server::PreFork) starting! pid(1)
Binding to TCP port 5762 on host 0.0.0.0 with IPv4
Setting gid to "33 33 33"
Req:E087743471E611EF829493EE39560C07 172.17.0.1 - - [13/Sep/2024:15:43:09 +0000] "GET /setup.pl HTTP/1.1" 200 4806 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
Req:F912A3F271E611EF974B93EE39560C07 172.17.0.1 - - [13/Sep/2024:15:43:50 +0000] "GET /setup.pl?action=authenticate&company=postgres HTTP/1.1" 401 29 "http://localhost:5762/setup.pl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
Req:F91CE34E71E611EF974B93EE39560C07 172.17.0.1 - - [13/Sep/2024:15:43:50 +0000] "GET /setup.pl?action=authenticate&company=postgres HTTP/1.1" 200 7 "http://localhost:5762/setup.pl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
2024/09/13 15:48:12 Could not connect to database: connection to server at "lledgersmb-do-user-66666666-0.k.db.ondigitalocean.com" (111.11.11.11), port 5432 failed: Connection timed out\n	Is the server running on that host and accepting TCP/IP connections? at lib/LedgerSMB/Scripts/setup.pm line 267.\n
Req:F921365671E611EF974B93EE39560C07 172.17.0.1 - - [13/Sep/2024:15:48:12 +0000] "GET /setup.pl?action=login&database=defaultdb&csrf_token=%5ES7.Net%60FuEDQ%5El8x!%26%5Bq8n HTTP/1.1" 500 400 "http://localhost:5762/setup.pl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
```

### What should have happened?

It seems that it was still using port 5432 when I assumed it would have used the port I gave through the env variable., which was: 25060 

EDIT:
What I'm trying to accomplish here is having ledgersmb connect to the managed database server I have on digitalocean, which is why I tried setting `POSTGRES_HOST` and `POSTGRES_PORT`.

**Comment by ehuelsmann** [comment]
Hi! Thanks for the report!

I see there's confusion here: the container does not itself contain a PostgreSQL server. The POSTGRES_PORT variable helps the container find the PostgreSQL server, which is especially useful when the PostgreSQL server is started on a different port (e.g. which happens on Debian when multiple clusters and/or versions are installed).

I'd love to clarify descriptions to make clear that this is what is going on. Do you have a suggestion for a piece of text that wouldn't have confused you?

Regards, Erik.

**Comment by walidmujahid** [comment]
@ehuelsmann I am aware that the container itself does not contain a postgres server. I am trying to set it to the managed database server I have on digitalocean, which is why I tried setting the `POSTGRES_HOST` and `POSTGRES_PORT` environment variables. Did I go about doing that the wrong way?

**Comment by ehuelsmann** [comment]
Ah. See the problem in the logs now. Missed that when I answered the first
time. I'll have a look to see what's going on.

**Comment by ehuelsmann** [comment]
@walidmujahid, the problem turns out to be in one of our dependencies. The fix has been uploaded to CPAN. The new dependency will be in the 1.11.18 release, or, if you build a copy of the containers yourself, in any container you build an hour or two from now.

**Comment by walidmujahid** [comment]
@ehuelsmann Thank you very much.
