### ISSUE TITLE
Feature suggestion -- An sqlite version?

### ISSUE THREAD

**Issue by fadi123go** [ledgersmb/LedgerSMB#8412]
### Version

None

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Non technical  freelance accountants may find trouble installing and configuring servers . 

### What should have happened?

Why don't you create an sqlite based severless version aimed at freelancers and beginners who just want to try and learn your app. I believe there are tools that may help turn a web app into a desktop like app such as neutralino and tauri.

**Comment by ehuelsmann** [comment]
> Why don't you create an sqlite based severless version aimed at freelancers and beginners who just want to try and learn your app.

You probably don't mean it this way, but the wording above comes across pretty demanding ("Why don't you..." reads to me as "You really need to..."). I'll respond on the assumption that that isn't what you meant.

The answer is simple. The main reasons are:

* Nobody is stepping up to do the work
* The SQLite database model is significantly different from PostgreSQL that it would mean a reimplementation of the application; e.g.:
  * The database server does many extra user access rights checks
  * Most of the (quite significant) database stored procedures would need to be reimplemented (including views, triggers and authorization model)

The solution for non-technical freelance accountants would be to ask for some help of a knowledgeable LedgerSMB consultant. Setting and maintenance of a server doesn't need to cost more than a few hundred dollar per year.

**Comment by neilt** [comment]
> Non technical freelance accountants may find trouble installing and configuring servers .

Yes, I agree. The instructions we provide, the last time I checked, were available, but a bit lacking about setting up a fully secure WAN based setup.  With that said, most of our customers are not doing a WAN based setup without technical help. With the ever changing world of WAN security and the many options, this is probably best.

Internal LAN and single computer setups are very easy and we provide full instructions. Improvement suggestions are welcome.
 
> Why don't you create an sqlite based severless version aimed at freelancers and beginners who just want to try and learn your app. I believe there are tools that may help turn a web app into a desktop like app such as neutralino and tauri.

In addition to @ehuelsmann 's response above, I would add that right now, and in a simplistic view, changes require UI code and database code.  It we added another database, that would mean changes would require UI code, Postgres database code, and SQLite code.   This makes every change require, in a simplistic view, 50% more effort, especially when you consider testing and documentation.   And yes, having programed both databases, they are not that similar, especially in the areas of optimizations and quirks.  We don't have these resources for functionality that might only be used for learning.

Applications that support both, do so by limiting the database to common functionality and low performance.  This also causes increased development and support costs.  Based on the recommendations of neutralino and tauri it seems you have a web development background and maybe are familiar with the use of ORMs.  ORMs are not databases and present their own problems which web developers spend a lot of time working around.

As a project we have chosen not to go the ORM route.  There are many JS/ORM accounting systems that you might want to research.

**Comment by fadi123go** [comment]
I was just suggesting an idea and I did not know how demanding it would be. Apologies for that. May I present  another idea  then. Would you consider offering a cloud service ? It would cost you but you may be able to make  money out of it , which may help sponsor the project . A lot of freelancers, SMBs and startups may be willing to pay for it instead of paying  for  servers and server administrators . And I am sure that many of the issues reported to you are to do with trying to install it locally.

**Comment by neilt** [comment]
> I was just suggesting an idea and I did not know how demanding it would be. Apologies for that. May I present another idea then. Would you consider offering a cloud service ? It would cost you but you may be able to make money out of it , which may help sponsor the project . A lot of freelancers, SMBs and startups may be willing to pay for it instead of paying for servers and server administrators . And I am sure that many of the issues reported to you are to do with trying to install it locally.

No apology needed.

Try https://efficito.com.

**Comment by fadi123go** [comment]
Thanks.

**Comment by ehuelsmann** [comment]
@fadi123go, the efficito.com site has a bug when submitting support requests. It's easiest to mail info@efficito.com.
