### ISSUE TITLE
Duplicate code to set connection DateStyle

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#842]
There are two places in our code base which set the database connection's DateStyle:

* [LedgerSMB.pm](https://github.com/ledgersmb/LedgerSMB/blob/master/LedgerSMB.pm#L297)
* [LedgerSMB/DBH.pm](https://github.com/ledgersmb/LedgerSMB/blob/master/LedgerSMB/DBH.pm#L78)

Each uses its own list of date styles (not the same) and neither compensates for what happens when the list doesn't contain the entry defined for the current user.

**Comment by ehuelsmann** [comment]
Added @einhverfr to answer the question on what the right list is.

**Comment by einhverfr** [comment]
And one is executed after the other too.....
