### ISSUE TITLE
1.10 EOL

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#8444]
* [x] Add ` (End of Life)` to the 'Changelog for X.YY Series' entry in Changelog
* [x] Remove the release branch from `renovate.json` in the root of the master branch 
* [x] Remove the transifex resource (`LedgerSMB-XX`) for the EOL-ed branch
* [x] Update the supported items page: https://ledgersmb.org/faq/which-versions-do-you-support
* [x] Update Docker image README.md
  * [x] Docker README listing available tags (on all branches!)
* [x] Update [list of supported Perl versions](https://ledgersmb.org/faq/which-versions-perl-does-ledgersmb-support)
* [x] Update [list of supported PostgreSQL versions](https://ledgersmb.org/faq/installation/what-versions-postgresql-does-ledgersmb-support)
* [x] Mark ledgersmb.org items linked to the specific version number as obsolete  
      unless they're relevant for more recent versions too
* [x] Update the "Current Versions" section on the ledgersmb.org front page
* [x] Send EOL notice to the mailing list, using the following mail template:

----

To all users of LedgerSMB 1.10, this is a notice that the community support for 1.10 has expired on October 8th. As of 2024-10-08, there will be no more releases for 1.10, which has had 38 patch releases over its 2-year period of community support.

Users running versions older than 1.11 are encouraged to upgrade to 1.11 which will receive community support until 2025-10-03. If the remaining period of community support is too short on 1.11, please note that we're currently working toward a 1.12 release which is expected to appear over the coming weeks. 1.12 will - like its predecessors 1.10 and 1.11 - receive 2 years of community support.

If it is not possible to upgrade to 1.11 or 1.12, please note that although community support has expired, commercial support may be available for these older versions from vendors. Please consult the Commercial Support page on the LedgerSMB project webpage (https://ledgersmb.org/content/commercial-support).

----

**Comment by neilt** [comment]
This does not seem like the correct text for 1.10 EOL.  Shouldn't the version numbers be 1.10 and 1.11 instead of 1.9 and 1.10 respectively?

**Comment by ehuelsmann** [comment]
Text updated. Thanks for verifying!
