### ISSUE TITLE
Visual Anomaly Blue Bar title background

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#8506]
Normally the blue bar in the ui looks something like:

<img width="794" alt="Screenshot 2024-11-19 at 11 38 50 AM" src="https://github.com/user-attachments/assets/9fd1d459-9ce1-40bf-8116-4401744fa569">

Notice the blue bar behind "Add Assets". It is wide and is the page title background.

Now look at Fixed Assets -> Assets -> Search Assets looks like this:

<img width="539" alt="Screenshot 2024-11-19 at 11 40 10 AM" src="https://github.com/user-attachments/assets/cfa491f1-5beb-4d36-865d-bc648f78672c">

The same blue bar anomaly (thin blue line) is visible at:
* [x] Fixed Assets -> Assets -> Search Assets
* [x] Fixed Assets -> Assets -> import
* [x] Budgets -> Add Budget
* [x] System -> Reporting Units

LSMB 1.12 branch as of cb45e7e783052896a31c34dd2503218958652591

**Comment by ehuelsmann** [comment]
Changed the numbers of the pages to checkboxes in order to be able to monitor completion.
