### ISSUE TITLE
Fixed Assets -> Assets -> Import field definitions missing 

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#8507]
Normaly, the import views show the expected import format.  For example:

<img width="436" alt="Screenshot 2024-11-19 at 11 59 34 AM" src="https://github.com/user-attachments/assets/a36ca722-3a4b-494a-b1a5-1592b478be91">

However for Fixed Assets -> Assets -> Import, no expected format is provided. See:

<img width="485" alt="Screenshot 2024-11-19 at 12 03 14 PM" src="https://github.com/user-attachments/assets/9502da11-e82e-43b2-9130-55dede0945d0">

**Comment by ehuelsmann** [comment]
Nice find. I think this is not a regression in 1.12, but a bug that's been in the system all along. Thanks for reporting!
