### ISSUE TITLE
Enhance DateTextBox with serializer

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#853]
As described in:

http://dojotoolkit.org/reference-guide/1.10/dijit/form/DateTextBox.html

our DateTextBox should have both a serializer _and_ a postMixInProperties. Currently, we only have the latter.

**Comment by einhverfr** [comment]
Seems appropriate to resolve within the 1.5 release cycle at this point.

**Comment by einhverfr** [comment]
We should have this cleaned up by rc2 to allow plenty of time for testing.

**Comment by einhverfr** [comment]
If this doesn't make rc2, I would vote to push for 1.6

**Comment by ehuelsmann** [comment]
Pushing for 1.6 then, because RC2 is not going to have things with impact of this size.

**Comment by ehuelsmann** [comment]
Ran an initial test with this patch:

```
diff --git a/UI/js-src/lsmb/DateTextBox.js b/UI/js-src/lsmb/DateTextBox.js
index 3c4c6cb..8f437c7 100644
--- a/UI/js-src/lsmb/DateTextBox.js
+++ b/UI/js-src/lsmb/DateTextBox.js
@@ -44,6 +44,19 @@ define([
                 }
                 return locale.parse(value,
                                     { datePattern: "yyyy-MM-dd", selector: "date" });
+            },
+            serialize: function(value, options) {
+                var pad = function(val) {
+                    var r = String(val);
+                    if (r.length === 1) {
+                        r = '0' + r;
+                    }
+                    return r;
+                };
+
+                return value.getUTCFullYear()
+                    + '-' + pad( value.getUTCMonth() + 1)
+                    + '-' + pad( value.getUTCDate() );
             }
         });
     }
```

The result is that I get hiddens encoded with the user's preference (olddate=27/7/2017) and input fields encoded with the 'serializer format' (ISO): 2017-07-27

**Comment by ehuelsmann** [comment]
Resolution: can't be made to work without major impact. Must be part of the UI rewrite which converts our code base to services.
