### ISSUE TITLE
Add "Draft" as a state to search AR/AP transactions

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#855]
Currently, "Open" and "Closed" are states that can be searched for. It would be practical to have a "Draft" state to search for too, in order to be able to de-duplicate drafts.

**Comment by einhverfr** [comment]
Recommend make this "unapproved" so it includes vouchers too (and that would make it easier to implement)

**Comment by einhverfr** [comment]
Since this is potentially workflow changing, I will take on doing this for rc2
