### ISSUE TITLE
Translation of table content (meta/master data)

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#859]
Many, many tables hold values with descriptions that will eventually be inserted in some dropdown somewhere in the application (in its UI or (printed) output).

However, only a limited number of tables (e.g. accounts and headings) have associated translation tables.

The thing that needs design here is: do we want to introduce translation tables for each and every table which has a description in it? Or should we introduce a different structure??

**Comment by freelock** [comment]
Would a simple string replacement functionality work for us, or are there strings that get used in different contexts that need different translations?

e.g. Drupal has a t() function you use to wrap all strings that end up in code, and whenever it's called it simply returns the translation for that string. The translation interface keeps track of all t() calls that have been made without a corresponding translation, and provides a searchable list of them so it's easy to complete...

**Comment by einhverfr** [comment]
I think for areas with largely static content we should translate like we do the menu (and add helper scripts to extract strings for the .pot).

For areas with more dynamic content we need to add the tables.

**Comment by ehuelsmann** [comment]
@einhverfr I think John means to say that the static content can be translated in-app if add missing translations to a table of strings to be translated and offer that to our users. Then they can translate the app without the need to understand *.po/*.pot files.

Also, my personal thinking would be that if we allowed dumping the content of that table, we as a project could benefit hugely from this new functionality, because people could mail /send us the content translations and we could include them (after review).

**Comment by ehuelsmann** [comment]
I think John's point is that in Drupal, the user can create translations
for things that are normally found in the .po file, but are not there for
his/her translation. Then Drupal makes that string available in the
database for immediate translation and use by that user.

Now, I do see a great benefit for this:

1. The user is able to enhance his own instance with translations without
the need to understand the complexities of gettext's PO format
2. We get a much more accessible translation interface (and thus chances
for translation)
3. If we provide functionality to submit translations back to the project,
we even might tap into much bigger translation potential

I think it's worth trying.

**Comment by einhverfr** [comment]
I think for 1.5, we should try to catalog the tables we are looking at and get the messages into the PO.  We need these anyway.

I think if we go this route, it would be good to *also* give a PO export option for translated data so that users can more easily share translations and contribute them back.

**Comment by ehuelsmann** [comment]
The solution we ended up implementing (in Dec 2015 and deployed as of 1.5) is to scan the database files for translatable strings. These strings are added to our translation lexicons. This system has worked great for us so far and as such I think this issue can be closed. The question about letting users add translations for their systems is an entirely different one and beyond the scope of this issue as far as I'm concerned.
