### ISSUE TITLE
permission denied while saving an asset in fixed assets

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#878]
With a user with full rights:

ERROR:  permission denied for relation asset_ite
m
CONTEXT:  SQL statement "UPDATE asset_item
        SET asset_class_id = in_asset_class,
                description = in_description,
                tag = in_tag,
                purchase_date = in_purchase_date,
                purchase_value = in_purchase_value,
                usable_life = in_usable_life,
                location_id = in_warehouse_id,
                department_id = in_department_id,
                invoice_id = in_invoice_id,
                salvage_value = in_salvage_value,
                asset_account_id = in_asset_account_id,
                exp_account_id = in_exp_account_id,
                start_depreciation =
                         coalesce(in_start_depreciation, in_purchase_date),
                dep_account_id = in_dep_account_id
        WHERE id = in_id"
PL/pgSQL function asset__save(integer,integer,text,text,date,numeric,numeric,numeric,date,integer,integer,integer,integer,integer,integer) line 4 at SQL statement

**Comment by ehuelsmann** [comment]
Same problem for asset_note.

**Comment by einhverfr** [comment]
yep, will fix for 1.4.18

**Comment by einhverfr** [comment]
#899 now fixes this as well
