### ISSUE TITLE
Depreciation report false net book value reported

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#879]
From my tests, I see NBV returned "0" while there are no depreciations:
![image](https://cloud.githubusercontent.com/assets/2326559/10278016/6b3d529e-6b5a-11e5-8dc9-ecda94c60e3b.png)

**Comment by einhverfr** [comment]
ick, probably affects 1.3 too....  Will get this fixed today

**Comment by einhverfr** [comment]
will be ready o merge following the 1.4.17 release

**Comment by einhverfr** [comment]
PR #899  fixes this

**Comment by ehuelsmann** [comment]
PR merged, closing as fixed.
