### ISSUE TITLE
Remove mostly useless 'lsmb_roles' table

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#881]
The ```lsmb_roles``` table is being created in the Pg-database.sql schema creation file and then later used (filled) in modules/admin.sql. However, as far as I can tell, **nothing actually uses** the recorded information...

**Comment by einhverfr** [comment]
This table used to be used for UI stuff.  That may have been removed.

The reason it used to be used there is that we couldn't use system functions for the checkboxes.  It looks like pulling the data from the table has been removed however.  Let's delete the table for 1.5
