### ISSUE TITLE
When importing a user in setup.pl, allow for "no role changes"

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#883]
This is particularly interesting in case users are being imported into a company which has ```role_prefix``` set to that and the user has been defined in the other company with the correct access rights already.

**Comment by einhverfr** [comment]
I am not sure what you mean.  If you just import the user in that case, it should just work.  If not, we have a problem and a bug report.  Is this working?  If not what happens when you import the user?

**Comment by ehuelsmann** [comment]
@einhverfr our current code allows importing existing users with one of two role-sets:

* Manage users
* Full permissions

However, in this case, I don't want either: I simply want to use the existing GRANTs which have been applied in another company with the same ```role_prefix```

**Comment by einhverfr** [comment]
ah ok gotcha.  Will fix for 1.4.18

**Comment by einhverfr** [comment]
I think you can import from the main UI without setting roles though, just not in setup.pl
