### ISSUE TITLE
Need better pricematrix for vendors

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#903]
![kijeloles_077](https://cloud.githubusercontent.com/assets/341143/10558022/870aa312-74c1-11e5-8018-e45984303272.jpg)
![kijeloles_078](https://cloud.githubusercontent.com/assets/341143/10558023/870b31d8-74c1-11e5-8577-829f012062b1.jpg)

Initial ticket filed by @pongraczi on SF:

How to reproduce:
- Edit a part
- Pick up a vendor, by entering a name and Update the form
- Only choose a currency for this Vendor, left empty: sku, lead time, price
- This state: screenshot 1.
- Save it: screenshot 2.

In fact, no vendor line saved into partsnumber.
![kijeloles_075](https://cloud.githubusercontent.com/assets/341143/10558005/fbd057ce-74c0-11e5-8763-2aa3bf649c1d.jpg)
![kijeloles_076](https://cloud.githubusercontent.com/assets/341143/10558006/fbd3dcc8-74c0-11e5-9824-0fcfdeda1597.jpg)

https://sourceforge.net/p/ledger-smb/bugs/1029/

**Comment by einhverfr** [comment]
I filled up parts (products) with vendor, prices etc. Check screenshot 77.
Vendor's pricelist (78) has missing values.

Would be nice to have:
- list price entered for vendor from the part (aka from partsvendor table) in its currency (in this case USD)
- last purchase price if it has invoice. The amount in USD or local currency? Exchange rate?

I think it is question of the design, I guess the last purchase price calculated in local currency, while the partsvendor table has vendor's currency. In the example HUF vs. USD.

**Comment by ehuelsmann** [comment]
Due to the text above ("It's a matter of design"?) --> Adding the "needs-design" label.

**Comment by ehuelsmann** [comment]
The pricematrix is a mechanism to store prices. When you don't enter a price, nothing gets saved. I say this works as it should.
