### ISSUE TITLE
Need better dojo delivery system

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#904]
We need a better approach to including dojo.  We don't want to keep this in the repo anymore.

See https://sourceforge.net/p/ledger-smb/bugs/1182/ for past issues with the current approach

**Comment by freelock** [comment]
From chat, the proposed steps for this:

> I would say what needs to happen would be this:

1. create a layer build file, instructions for using it, and establish a build target location
2. Create a config option to allow switching dojo source path between source and build location, and adapt templates to use it
3. Add build to git
4. Create instructions for doing a build, and commit
5. Remove dojo sources
6. Add dojo sources as submodules
7. Create script to assist with doing a dojo build

Any comment on this approach? I can probably create a PR to do this in the next week.

Something we can get in for 1.5?

**Comment by sbts** [comment]
If einhverfr and ehuelsmann agree I think this should be done.
It has the potential for significant User Perceived speed improvements due to reduced server requests, and reduced bytes to be downloaded for each request.

The only negative is the need for a couple of extra steps if the dojo src needs to be modified.
A minor tradeoff that can be mitigated with a couple of helper scripts.

**Comment by sbts** [comment]
From IRC discussion, there is history of dojo minor releases significantly changing what I would call function prototypes (ie: the way arguments are passed) and other things.

In light of the potential stability issues this would cause, I think staying with it included in our tree (in some form) makes sense. Hence I disagree with using distro provided packages as was suggested in the sourceforge bug 1182

I think we should REQUIRE that our in-tree version be used

**Comment by jame** [comment]
On Tuesday, December 29, 2015 08:24:27 PM David wrote:
> From IRC discussion, there is history of dojo minor releases significantly
> changing what I would call function prototypes (ie: the way arguments are
> passed) and other things.

  And is there some reason that we need to update what we're writing against  to such "dojo minor releases" ?


> ... Hence I disagree with using distro provided packages as was suggested in
> the sourceforge bug 1182
> 
> I think we should REQUIRE that our in-tree version be used

   And I think that's a bad idea since it would preclude uploading to Debian (and therefore Ubuntu, etc) because embedded libraries are not allowed.  (Section 4.13 of Debian Policy.)

   And note that I have not yet seen any issues using the Debian packages, at least so far, although I'll admit that the testing I do with it is not that extensive...  (Install the package (which does not contain the dojo libraries) I'm testing on the whichever container I'm using to test, log in and try creating or updating a company db and perhaps a user, then log in and check a few menu items.)

  And speaking of which, do we have any testing of the dojo usage yet?

**Comment by einhverfr** [comment]
I am totally in favor of this.

On Thu, Dec 31, 2015 at 6:55 PM, Robert James Clay <notifications@github.com
> wrote:

> On Tuesday, December 29, 2015 08:24:27 PM David wrote:
>
> From IRC discussion, there is history of dojo minor releases significantly
> changing what I would call function prototypes (ie: the way arguments are
> passed) and other things.
>
> And is there some reason that we need to update what we're writing against
> to such "dojo minor releases" ?
>
> ... Hence I disagree with using distro provided packages as was suggested
> in
> the sourceforge bug 1182
>
> I think we should REQUIRE that our in-tree version be used
>
> And I think that's a bad idea since it would preclude uploading to Debian
> (and therefore Ubuntu, etc) because embedded libraries are not allowed.
> (Section 4.13 of Debian Policy.)
>
> And note that I have not yet seen any issues using the Debian packages, at
> least so far, although I'll admit that the testing I do with it is not that
> extensive... (Install the package (which does not contain the dojo
> libraries) I'm testing on the whichever container I'm using to test, log in
> and try creating or updating a company db and perhaps a user, then log in
> and check a few menu items.)
>
> And speaking of which, do we have any testing of the dojo usage yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ledgersmb/LedgerSMB/issues/904#issuecomment-168229070>
> .
>



-- 
Best Wishes,
Chris Travers

Efficito:  Hosted Accounting and ERP.  Robust and Flexible.  No vendor
lock-in.
http://www.efficito.com/learn_more

**Comment by einhverfr** [comment]
n favorof the submodules etc.

I am also in favor of being able to use OS distributions of Dojo within
reason.

On Thu, Dec 31, 2015 at 8:12 PM, Chris Travers <chris.travers@gmail.com>
wrote:

> I am totally in favor of this.
>
> On Thu, Dec 31, 2015 at 6:55 PM, Robert James Clay <
> notifications@github.com> wrote:
>
>> On Tuesday, December 29, 2015 08:24:27 PM David wrote:
>>
>> From IRC discussion, there is history of dojo minor releases significantly
>> changing what I would call function prototypes (ie: the way arguments are
>> passed) and other things.
>>
>> And is there some reason that we need to update what we're writing
>> against to such "dojo minor releases" ?
>>
>> ... Hence I disagree with using distro provided packages as was suggested
>> in
>> the sourceforge bug 1182
>>
>> I think we should REQUIRE that our in-tree version be used
>>
>> And I think that's a bad idea since it would preclude uploading to Debian
>> (and therefore Ubuntu, etc) because embedded libraries are not allowed.
>> (Section 4.13 of Debian Policy.)
>>
>> And note that I have not yet seen any issues using the Debian packages,
>> at least so far, although I'll admit that the testing I do with it is not
>> that extensive... (Install the package (which does not contain the dojo
>> libraries) I'm testing on the whichever container I'm using to test, log in
>> and try creating or updating a company db and perhaps a user, then log in
>> and check a few menu items.)
>>
>> And speaking of which, do we have any testing of the dojo usage yet?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ledgersmb/LedgerSMB/issues/904#issuecomment-168229070>
>> .
>>
>
>
>
> --
> Best Wishes,
> Chris Travers
>
> Efficito:  Hosted Accounting and ERP.  Robust and Flexible.  No vendor
> lock-in.
> http://www.efficito.com/learn_more
>



-- 
Best Wishes,
Chris Travers

Efficito:  Hosted Accounting and ERP.  Robust and Flexible.  No vendor
lock-in.
http://www.efficito.com/learn_more
