### ISSUE TITLE
Move fixed asset reports to new report structures

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#911]
Currently the fixed asset reports use the older dynatable structure.  This means less functionality and more code.  We should move these to the reports structure instead.

**Comment by einhverfr** [comment]
We have 4 reports here.

1. Depreciation
2.  Disposal
3.  Asset report search/approval
4.  NBV

**Comment by ehuelsmann** [comment]
@einhverfr put this in 1.4 because it has some real usability annoyances for 1.4.x; however, no urgent need to do this by 1.4.29; putting in 1.4 (general) instead.

**Comment by einhverfr** [comment]
this should be done for rc2 for testing reasons.  And because they look ugly on the old framework.

**Comment by einhverfr** [comment]
Depreciation and disposal are the only two reports to migrate left.

**Comment by einhverfr** [comment]
Minor enhancement, no major workflow implications.
