### ISSUE TITLE
Set defaults for dates where appropriate

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#914]
see https://sourceforge.net/p/ledger-smb/bugs/1305/ for older discussion

We should allow dates to be set by default in some areas.  For example:
1.  For batches, current date
2.  For payments/receipts, current date
3.  For sales invoices, current date

Any others?  Needs discussion and design before doing much.

**Comment by einhverfr** [comment]
See also https://sourceforge.net/p/ledger-smb/feature-requests/137/

**Comment by einhverfr** [comment]
Potentially workflow changing, needs to go through beta and rc process

**Comment by ehuelsmann** [comment]
For (sales) invoices, the default date is already the current date.

**Comment by ehuelsmann** [comment]
Single payments get the current date as well.

**Comment by ehuelsmann** [comment]
With the original discussion missing, I think this issue is sufficiently addressed. (Meaning that I'd like to concentrate on larger issues for now.)
