### ISSUE TITLE
After session experation the browser's auth dialog doesn't work

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#918]
After the session is expired, the auth popup keeps popping up, even when I know for sure I'm entering the correct credentials.

The only way to get back into the system is through login.pl

**Comment by einhverfr** [comment]
hmmm I can't repro.  It now seems to work for me.

As I recall, I fixed something in this corner some time ago.  Can you reproduce, for example by deleting sessions from the db?  Is this on Windows/Chrome?

**Comment by einhverfr** [comment]
I am going to close this for now.  If you can reproduce, please re-open and post db logs from the attempt to log in again.
