### ISSUE TITLE
Need default for precision (and maybe general system of setting defaults?)

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#926]
Previous discussion at https://sourceforge.net/p/ledger-smb/bugs/1318/

My thinking is we need a few other things here to make it work.  Do we want this one to be special cased?  Or do we want a default to be stored in the row as well?

**Comment by ehuelsmann** [comment]
@einhverfr with the original request gone, could you add a bit more context? What's the actual request here?

**Comment by ehuelsmann** [comment]
Closing: more than 90 days without user response. Feel free to reopen with your comments.
