### ISSUE TITLE
New <invoice|order|...> buttons in ECA screen should populate eca in target screen

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#932]
Previous discussion at https://sourceforge.net/p/ledger-smb/bugs/1320/

It would make the UI nicer to have the popups which define new customers (and later parts/services) populate appropriate fields.

**Comment by ehuelsmann** [comment]
Proposed approach here is to create a dino button which when clicked does not submit the form, but instead loads a specific page into the maindiv.
