### ISSUE TITLE
Cannot save company/eca

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#936]
In 1.5, saving a company/eca seems to do nothing

**Comment by freelock** [comment]
I think this is currently broken in 1.4, too -- at least there, it no longer auto-generates the vendor number, supplying one allows you to save.

**Comment by einhverfr** [comment]
I think with 1.4 there is the issue that you have to click the generate control code button.  With 1.5 that button works but then no other buttons work.  A person however can be saved.

I suspect the problem has to do with dojo and id fields.

**Comment by einhverfr** [comment]
The problem appears to be that after submission a form's buttons no longer work, so probably a dojo issue.

**Comment by einhverfr** [comment]
In 1.5, the specifc problem here is that the handling of submit values is broken by the return of the generate contro code button.  This does not seem to be the same as errors breaking form submission
