### ISSUE TITLE
1.4 regression: vendor number not automatically added when blank, on a new vendor ECA

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#947]
reported by @freelock  as a comment to #936 

"I think this is currently broken in 1.4, too -- at least there, it no longer auto-generates the vendor number, supplying one allows you to save."

**Comment by freelock** [comment]
To be clear, I wasn't referring to entity control codes -- that has always been a manual step.

The issue I was commenting on is the "vendor number" for an ECA -- this used to get autogenerated if saved when blank -- sometime in the past release or two this broke and now needs to get explicitly set when saving an ECA. (We've hit it on vendor number, I don't think we've hit it on customer number).

**Comment by einhverfr** [comment]
I am still getting added vendor numbers.  Is it possible you are missing a value in your defaults somewhere?  Please check your system/defaults screen for missing values.

I am going to fix this regarding entity control codes however because the addition of required fields makes this process a little harder.

**Comment by einhverfr** [comment]
We did previoushly have entity control codes added at least in 1.3 if blank and will restore that.

**Comment by einhverfr** [comment]
I have confirmed vendor numbers are added on demo  Closing works for me, for now, but adding automatic handling of entity credit acounts.
