### ISSUE TITLE
Preference change (to format or language) requires a reload to take effect

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#950]
More discussion at https://sourceforge.net/p/ledger-smb/bugs/1376/

the question is whether we want to fix this by documenting it or by trying to engineer a fix at present.

I am thinking documentation is best right now because the problem and solution will change as we go to a more service-oriented interface.

**Comment by einhverfr** [comment]
What about just reloading this page after preferences are saved?

**Comment by ehuelsmann** [comment]
reloading the page is one option,
the other could be to change the stylesheet (I'd expect?) and changing the content of `lsmbConfig` which is consulted on widget construction, meaning that any newly instantiated input widgets will use the new format preferences.

**Comment by ehuelsmann** [comment]
@einhverfr should we simply implement the page refresh now and file "the rest" of the ticket (the needs-design part) for "sometime during 1.5"

**Comment by ehuelsmann** [comment]
Anything that needs design can't be in RC2

**Comment by ehuelsmann** [comment]
It's a general problem with preferences wrt how Dojo is supposed to work.

**Comment by ehuelsmann** [comment]
@ylavoie , you implemented reloading the page. Not quite what I had in mind when I filed this issue, but effective. Didn't this solve the full scope of this issue?!
