### ISSUE TITLE
Directory structure cleanup

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#951]
We should move our project to conform to existing standards, such as moving things to bin, lib, etc.

**Comment by einhverfr** [comment]
I also think this will help streamline installation.

**Comment by ehuelsmann** [comment]
With 1.5, we now have lib/ being the LedgerSMB libraries; we have bin/ being the old code dispatch; we have UI/ as the docroot. I'm considering that "enough" for now. Closing under that consideration. Please re-open if you disagree.
