### ISSUE TITLE
Show a dashboard in the main div at application startup

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#959]
Items to be shown in the dashboard should be role-dependent, but could include:
- AR/AP Aging
- Pending drafts
- Pending batches
- Partially shipped orders
- Open orders/quotations

Imagining something like "top 10 (longest over due, longest open,...)" or summary by state, or others.

**Comment by sbts** [comment]
Maybe also some simple metrics like.
    
      Count of AR Invoices / Orders raised this day/week/month (for
        the entity and for the logged in user)
      # Unshipped AR Invoices / Orders this day/week/month (for the
        entity and for the logged in user)
      # Unpaid AR Invoices this day/week/month (for the entity and
        for the logged in user)
      probably others along the same vein
    
    I know there is some overlap with what Erik has suggested, I'm
      thinking simple numbers in either Pi/Fuel Gauge or Bar graph form
      that can be used to give a feel for performance of eg: a sales
      rep, against the company as a whole.
    
    
    On 27/10/15 03:20, Erik Huelsmann
      wrote:
    
    
      Items to be shown in the dashboard should be role-dependent,
        but could include:
      
        AR/AP Aging
        Pending drafts
        Pending batches
        Partially shipped orders
        Open orders/quotations
      
      Imagining something like "top 10 (longest over due, longest
        open,...)" or summary by state, or others.
      —
        Reply to this email directly or view
          it on GitHub.
