### ISSUE TITLE
1.4 regression: cash payments no longer print unpaid invoices, partial payments, and get reset

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#961]
When using cash -> vouchers -> payments, if there are several open invoices to pay, you can enter a partial payment amount(s) for multiple invoices, and the total entered gets printed on the check.

This still works fine.

However, in a recent update in 1.4, the list of open invoices on the voucher no longer shows any unpaid invoices -- the list only shows the total paid for both "Amount Due" and "Applied", and does not show any invoices with unpaid amounts.

Also, after using the server printing option, invoices that were marked with a "0" balance have gotten reset to their full amount, which could easily lead to mistakenly posting a payment that has not actually been made.

**Comment by freelock** [comment]
Hi, Chris,

It looks like this got committed to master, but not 1.4? I'm still seeing the issue...

Cheers,
John

**Comment by einhverfr** [comment]
Yes was closed when committed to master.  PR is awaiting 1.4.18's release and will be in 1.4.19.

If you want to test, merge my 1.4.19-fixes branch.

**Comment by einhverfr** [comment]
PR971, one sec and will get the commit for you

**Comment by einhverfr** [comment]
Commit is here if you want to merge:
https://github.com/einhverfr/LedgerSMB/commit/60cca06e185686d134be99ca52240a08e85f723f

**Comment by einhverfr** [comment]
BTW, expect these to be merged to 1.4 main tomorrow after the 1.4.18 release.
