### ISSUE TITLE
edit/update on saved transaction clobbers changed data

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#975]
https://sourceforge.net/p/ledger-smb/bugs/1356/

**Comment by ehuelsmann** [comment]
Using this workflow:

    Open an existing AP transaction
    Copy to new.
    Transaction is copied, invoice # and payment lines cleared.
    Update date, add a payment line with an incorrect payment account specified, and Save.
    (need to add another payment line...) Click update and a new payment line appears
    Add another payment line, notice that first payment account is wrong. Fix account, and Update.

Result: Saved payment line is restored on next screen.

This issue caught me a couple times while trying to reconcile books, doing data entry on past transactions.

"Save Draft" works correctly, and stores the new payment account info, but "Update" changes back what you just changed, with no warning.

**Comment by ehuelsmann** [comment]
@einhverfr I don't think this can be solved in old code. Basically, the code assumes that a transaction is either posted (and thus "constant") or it's being newly created. The condition by which this is determined, is the existence of an "id" field being present. There's no real "state" tracking. However, saved transactions *have* an 'id' field, but are not posted yet....

This looks like a requirement for "new code" instead.

**Comment by ehuelsmann** [comment]
I doubt this is a bug:accounting. I think it's a bug:old-code. Moving to 1.4.24 pending discussion.

**Comment by ehuelsmann** [comment]
Like #994, this is a problem in the design of draft transactions. The system assumes that transactions which have an 'id' field are posted/frozen. Saved transactions want to be edited, but can't because they have an 'id' field, and hence are considered frozen.

**Comment by einhverfr** [comment]
recommend for 1.6 getting rid of the payment field in drafts and vouchers and making the list read-only for posted transactions.
