### ISSUE TITLE
duplicate line in order entry in 1.4.10.1, but not in 1.4.6

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#976]
https://sourceforge.net/p/ledger-smb/bugs/1335/

**Comment by ehuelsmann** [comment]
Yep. This is definitely caused by the changes for the 'min_empty' lines. Taking, unbreaking normal behaviour. Not sure if I can completely "unbreak" the new behaviour, but since that's what was added and caused this breakage, I'll prefer that.
