### ISSUE TITLE
Reconciliation does not add new transactions

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#979]
https://sourceforge.net/p/ledger-smb/bugs/1354/

**Comment by ehuelsmann** [comment]
Do we have a reproduction recipe?

**Comment by freelock** [comment]
Copied from SF (trying to work through reconciliations again, this is still a problem):

This is a regression from 1.3 -- this behavior works as expected in 1.3, but not in 1.4.

1. Create a reconciliation (Cash -> Reconciliation)
2. Mark some transactions complete.
3. In another window, add some new transactions (e.g. transactions that are needed to complete reconciling) and make sure they are posted.
4. On reconciliation screen, click "Update".

Result: no change to entries available

In 1.3, this would result in the new transactions becoming visible on the transaction list, allowing you to complete the reconciliation.

In 1.4, nothing seems to trigger this desired behavior -- Save is broken, re-opening a report does not regenerate the transaction list. The only solution is to generate an entirely new reconciliation, which makes this process extremely annoying.
