### ISSUE TITLE
SF#1377 the "Batch lock" functionality is *really*, really broken...

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#992]
Reported by John Locke on the developers mailing list:

Another really broken workflow -- the "Batch lock" functionality causes more harm than it helps. Once you've printed any checks or received any payments through Cash -> Vouchers -> Receipts/Payments, you cannot add anything further to that batch, regardless of whether you go to the transaction approval screen or not. Each batch is a single pass -- and it breaks at the worst possible time. E.g., open a "daily check printing batch", print a few checks. Re-open batch to do some more, enter check numbers, print, get to the approval page, and save. Error! Batch is locked. Uh, oh, you already put the checks in envelopes, now what checks did I print? I need to go back and create a whole new batch, find the starting check number, remember exactly which checks I printed, and save again.

https://sourceforge.net/p/ledger-smb/bugs/1377/

**Comment by freelock** [comment]
Does not quite work. When attempting to post to a previously open batch, getting this error:

42703:ERROR: column users.user_id does not exist
LINE 4: AND users.user_id = SESSION_USER ^ QUERY: SELECT * FROM session JOIN users ON (session.users_id = users.id) WHERE id = t_batch.locked_by AND users.user_id = SESSION_USER CONTEXT: PL/pgSQL function "payment_bulk_post" line 26 at PERFORM at LedgerSMB.pm line 770.

**Comment by einhverfr** [comment]
fix to merged today.  Please double check it.

**Comment by einhverfr** [comment]
merged, please double check

**Comment by craigwebster** [comment]
As per 1.4.23 this or closely related issues are still breaking batch workflow.

On 1.4.22 demo, to reproduce:

AR->Voucher->AR Voucher

Create a batch and an entry.

Go do something else, especially approving transactions, but at least sometimes other things as well.

Go back to voucher entry, add to batch, it'll break with "batch locked".

Go to Transaction Approval->Batches and try to unlock the batch, to no avail.

Also seems to happen in AP and Cash batches.

**Comment by einhverfr** [comment]
I have been unable to reproduce a programming problem here.  Note that when you search for batches it locks all that it finds.  So I am fixing by adding a note that these are locked in the UI
