### ISSUE TITLE
SF#1384 No "save" button for non-posted transactions

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#994]
See https://sourceforge.net/p/ledger-smb/bugs/1384/

This affects sales invoices but not AR transactions if memory serves me.

**Comment by ehuelsmann** [comment]
Heavy workflow problem, but does not result in incorrect accounting. Not a 'bug:accounting' --> reclassifying.

**Comment by ehuelsmann** [comment]
Git branch 1.4/be56030e42

    Create new AP transaction: AP › Add Transaction
    Save. (Twice. See #1383.)
    Locate via Transaction Approval › Drafts
    Open new tx

=> There is an 'Update' button (which recalculates form), but no 'Save' button (see image ap-edit-tx-no-save.png)

**Comment by ehuelsmann** [comment]
Like #975, this is a design problem with old code. (Or probably with LedgerSMB in general; I've not seen any workflow designs written down anywhere so far.)

Based on my findings so far, moving to 1.6, which can address this at the earliest (with 1.5 being feature complete, there's no way we can get shocking changes in).

**Comment by einhverfr** [comment]
turned out to be a bug, in that we were checking for roles that didn't exist.  Pending PR #2063

**Comment by einhverfr** [comment]
backport to 1.4 will look just a little different, but will backport.

**Comment by einhverfr** [comment]
The problem was in ar/ap transactions and gl because a role name changed and we didn't catch it.

**Comment by einhverfr** [comment]
last worked in 1.3
