### ISSUE TITLE
SF#1398  1.4.13 Quotations->Reports->Quotations Field "Contact" field empty after 1st print

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#997]
In 1.4.13 Quotations->Reports->Quotations Field

Once the quotation is loaded for the first time to the screen for printing, it displays the name of the contact person in the specified field. After loading it the second and following times this field is always empty. Tested this several times.

https://sourceforge.net/p/ledger-smb/bugs/1398/

**Comment by ehuelsmann** [comment]
I'm not sure what to make of this bug. Can someone add an exact reproduction recipe for me?

**Comment by ehuelsmann** [comment]
As there is no "Contact" field either on the search page nor on the quotation page for any of the quotations I tried on demo/1.4.41, closing.
