### ISSUE TITLE
#1402 quotations->quotation no "back" button on add service/product mask 

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#998]
In 1.4.15 ->Quotations->Quotation
when directed to the add new product/service mask a "continue" button is offered, but no "back" button. In case you where directed to the mask by mistake, because, for example, you entered the item nr and description for a new item at the same time, you lost your quotation and can start from zero, unless it was saved.

**Comment by einhverfr** [comment]
https://sourceforge.net/p/ledger-smb/bugs/1402/

**Comment by einhverfr** [comment]
I think this can be done with 1.4, working with the rowcount parameter.

**Comment by einhverfr** [comment]
This causes workflow regressions and so despite other problems suggesting noting it as a minor enhancement for a stable branch

**Comment by ehuelsmann** [comment]
I don't think there's an "Add part" link anywhere in the quotation anymore: we're using dropdown selectors with only existing parts/services right now.
