### ISSUE TITLE
SF#1403 quotations -> quotation -> update accepts duplicate quotation nr 

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#999]
https://sourceforge.net/p/ledger-smb/bugs/1403/

in 1.4.15

quotations->quotation

duplicate quotation numbers are accepted via the update button. error message displayed only when quotation is saved.

Note this cannot be fixed without rewriting order entry so moving to 2.0

**Comment by ehuelsmann** [comment]
works as designed.
